### ISSUE TITLE
'datetime' error when using a year search filter

### ISSUE THREAD

**Issue by wildsavage** [Kometa-Team/Kometa#10]
I get the following error when trying to use the year search function with plex_search

| Unknown Error: name 'datetime' is not defined 

[2021-02-10 03:27:07,391] [util.py:575]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 572, in update_libraries
                                                                 |     elif method_name in ["year", "year.not"]:                           methods.append(("plex_search", [[(method_name, util.get_year_list(collections[c][m], method_name))]]))
                                                                 |   File "/modules/util.py", line 491, in get_year_list
                                                                 |     current_year = datetime.datetime.now().year
                                                                 | NameError: name 'datetime' is not defined
                                                                 | 
[2021-02-10 03:27:07,391] [config.py:1029]            [ERROR]    | Unknown Error: name 'datetime' is not defined

**Comment by meisnate12** [comment]
added a fix in the develop branch it will be in the next release
