### ISSUE TITLE
Inconsistent result with title search

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#100]
The new title search is very useful, but I have found some quirks when searching for multiple titles. In one case I had this search: `title: Black Sabbath, Ozzy Osbourne`. There are two movies in my library that fit this, `Inside Black Sabbath` and `Ozzy Osbourne: 30 years after the blizzard`. At first, only the Black Sabbath one got added to the collection. I then changed the order to `Ozzy Osbourne, Black Sabbath`, and then both movies got added. 

A second example was for my Beatles collection. It searches for `title: Beatles, John Lennon, George Harrison`. The movies fitting the description are `Imagine: John Lennon` and `George Harrison: Living in the Material World`. In this case I have not been able to get the George Harrison movie into the collection, even if I switched around the search strings. 

I have not had any problems when searching for a single movie. If I make a collection and only search for `George Harrison` it will be added to the collection.

**Comment by meisnate12** [comment]
it just uses the default plex search to get those results you can do multiple searches by doing
```yaml
title:
  - Black Sabbath
  - Ozzy Osbourne
```

**Comment by Alaksin** [comment]
If I use the list it doesnt work. Looks like the array needs to be dereferenced
```
title:
  - Black Sabbath
  - Ozzy Osbourne

| Processing Plex Search: title(['Ozzy Osbourne', 'Black Sabbath'])                                  |
| No items found to add to this collection                                                           |
|                                          
```
If I do it comma separated it works:

```
| Processing Plex Search: title(Ozzy Osbourne, Black Sabbath)                                        |
| Black Sabbath Collection | + | Inside Black Sabbath: A Critical Review 1970-1992                   |
| Black Sabbath Collection | + | Ozzy Osbourne: Thirty Years After The Blizzard                      |
| 2 Movies Processed                                                                                 |
```


There is something strange with the order of the strings:
```
THIS ORDER WORKS
| Processing Plex Search: title(George Harrison, Beatles, John Lennon)                               |
| The Beatles Collection | + | George Harrison: Living in the Material World                         |
| The Beatles Collection | = | Imagine: John Lennon                                                  |
| 2 Movies Processed

NOT THIS ONE
| Processing Plex Search: title(Beatles, John Lennon, George Harrison)                               |
| The Beatles Collection | + | Imagine: John Lennon                                                  |
| 1 Movie Processed                
```

**Comment by meisnate12** [comment]
Comma separated doesn't actually separate that attribute so you're just searching the whole string in plex at once

**Comment by Alaksin** [comment]
That doesn't make much sense, if I searched for the whole string then I would get zero results. I tried doing these searches inside Plex, with `Black Sabbath, Ozzy Osbourne`. This will change into `|Black Sabbath| or |Ozzy Osbourne|` once I hit Apply, but the search misses the Ozzy movie. If I instead search with `Black Sabbath` and `Ozzy Osbourne` as separate tags before applying, I get the correct result. So there seems to be something strange inside Plex when searching with comma. 

However, adding the title search with list in the script does not work:
```
title:
  - Black Sabbath
  - Ozzy Osbourne

| Processing Plex Search: title(['Ozzy Osbourne', 'Black Sabbath'])                                  |
| No items found to add to this collection                                                           |
|                                          
```

**Comment by meisnate12** [comment]
how its searching it is up to the plexapi all I'm doing is sending the one string and any other search terms. I just pushed an update so it should supports lists now and do multiple searches one with each term. To be honest I do not know how that search actually works.

**Comment by Alaksin** [comment]
Yes, I understand that, and as I said it seems like Plex itself has some problems with searching. I will have to figure out how to use it so it works for me. Thanks for the list fix

**Comment by meisnate12** [comment]
no problem let me know if there's anything I can do to make this better!
