### ISSUE TITLE
[Feature]: Add ability to search playlists

### ISSUE THREAD

**Issue by hbooo** [Kometa-Team/Kometa#1001]
### Is your feature request related to a problem? Please elaborate.

I'm using https://github.com/rnagabhyrava/plex-playlist-sync to sync playlists from deezer and spotify and I would love to merge some of them into a new one.

Plex doesn't allow to make smart playlists based on another playlists but maybe something is possible using PMM?

### Describe the solution you'd like

The scenario I was thinking about is:

PMM searchs for playlists with name that contains xxx, add a collection tag for all files in this playlist
Then creates a smart playlist based on the collection tag.

### Additional Information

Created after the discussion there https://discord.com/channels/822460010649878528/1009816724004151346

**Comment by meisnate12** [comment]
i need to just add spotify to pmm and this isnt needed
