### ISSUE TITLE
Issues with first setup

### ISSUE THREAD

**Issue by Kazz3r24** [Kometa-Team/Kometa#1005]
### Is your feature request related to a problem? Please elaborate.

I just want to literally tag cover posters with HDR or DV, but am having trouble getting things set up. <-- Edited from original

Is it at all possible to run this without collections? As it is I'm currently forced to have "IMDB-Top-250" because I had to have a collection. Unless I'm misreading the error that pops up when I try to run without a collection attribute.

### Describe the solution you'd like

Allow me to simply do quality/resolution overlays without needing collections.

**Comment by Kazz3r24** [comment]
Decided this wasn't the way I wanted to go.

**Comment by chazlarson** [comment]
collections are not a requirement.  If you want to run just overlays that's absolutely possible.

**Comment by Kazz3r24** [comment]
I figured that out afterwards, that's why I closed this request - I just didn't elaborate further.

I may come back and visit this again later, but for the time being, the amount of time it'll take me to set this up the way I want will take more time than I'm willing to commit at the moment.

**Comment by chazlarson** [comment]
OK, the default overlay setup is pretty quick and easy; if you have some requirement beyond that there might be a quick way to do it.  Perhaps ask in the discord [or here] and someone can offer that simple method if there is one.

If this is the requirement:
> I just want to literally tag cover posters with HDR or DV

The setup should take just a few minutes, unless you've got something unusual beyond that going on.

**Comment by Kazz3r24** [comment]
Essentially yes, I'm looking to have 4K, DV, HDR, Atmos, Special Editions.

The feature request came from when I would try to run the script, it would throw an error stating that without a collection 
 or metadata section added it wouldn't run. When I did add a collection, it would run but only put an overlay on a couple movies that were in the top 250 list, It would state that there was no overlay that matched the name of any of the resolutions I had in my yml file. I tried looking through some of the configs in the other repo but none were really what I was looking for without too much modification.

I could have reached out for help, but chose to close the request and spend my evening watching Plex instead of tinkering with it lol.

I'll pop in the Discord this week if I'm feeling ambitious, unless there is a really quick way to get what I'm looking for?

**Comment by chazlarson** [comment]
Make sure you are using the latest PMM, then for each library, enter this in your `config.yml`:
```
libraries:
  LIBRARY NAME HERE:
    metadata_path:
    overlay_path:
    - remove_overlays: false
    - git: PMM/overlays/audio_codec
    - git: PMM/overlays/resolution
    - git: PMM/overlays/special_release
```
I *think* Atmos and the like is covered by 'audio_codec'.

**Comment by Kazz3r24** [comment]
Thank you for taking the time to do this for me, it's much appreciated. 

I was definitely overcomplicating it!

**Comment by Kazz3r24** [comment]
Thank you again for the config above, I'm watching it go in cli now and appears to be only adding the overlays I wanted.

**Comment by chazlarson** [comment]
Excellent; glad to hear.
