### ISSUE TITLE
Mapping issues

### ISSUE THREAD

**Issue by djf73267** [Kometa-Team/Kometa#101]
I tried mapping my library with the HAMA for the anime Dr. Stone which caused an issue with resulting in this line of code when running. I already tried switching to MAL agent for this anime and successfully mapped the rest but I was wondering what the error code means.

Edit: The issue only occurred with this single anime. Both HAMA and MAL agent worked fine with the rest. 
> |================================================================================= =================|
|                                      Mapping My Anime Library                                      |
|====================================================================================================|
|                                                                                                    |
| Mapping Show Library: My Anime                                                                     |
| Cache | + | com.plexapp.agents.hama://anidb-14491?lang=en  | 86031  | None       | 355774 | 14491 | None  | Dr. Stone |
| Traceback (most recent call last):                                                                 |
|   File "plex_meta_manager.py", line 84, in start
|     config.update_libraries(test, collections)                                                                 
|   File "D:\Users\DJF\Downloads\Plex-Meta-Manager-develop\Plex-Meta-Manager-develop\modules\config.py", line 398, in update_libraries
|     movie_map, show_map = self.map_guids(library)
|   File "D:\Users\DJF\Downloads\Plex-Meta-Manager-develop\Plex-Meta-Manager-develop\modules\config.py", line 654, in map_guids
|     id_type, main_id = self.get_id(item, library, length)
|   File "D:\Users\DJF\Downloads\Plex-Meta-Manager-develop\Plex-Meta-Manager-develop\modules\config.py", line 802, in get_id
|     self.Cache.update_guid("movie" if library.is_movie else "show", item.guid, tmdb_id, imdb_id, tvdb_id, anidb_id, mal_id, expired)
|   File "D:\Users\DJF\Downloads\Plex-Meta-Manager-develop\Plex-Meta-Manager-develop\modules\cache.py", line 140, in update_guid
|     cursor.execute(
| sqlite3.InterfaceError: Error binding parameter 1 - probably unsupported type.
| 
| Error binding parameter 1 - probably unsupported type.
|====================================================================================================|
|                                            Finished Run                                            |
|                                         Run Time: 0:01:08                                          |
|====================================================================================================|

**Comment by meisnate12** [comment]
Thanks for the report! i think i figured out the issue and have pushed an update to devlop

**Comment by djf73267** [comment]
Yep, that fixed it. Thanks!

**Comment by meisnate12** [comment]
glad it worked let me know if you find any more!

PS leaving this open until the fix is in master
