### ISSUE TITLE
Unraid Docker could not download icon pmm.png

### ISSUE THREAD

**Issue by jakabo27** [Kometa-Team/Kometa#1013]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

UnRaid Docker GUI can't download the  icon - each time loading the docker page it says 
_"Plex-Meta-Manager: Could not download icon https://metamanager.wiki/en/latest/_static/pmm.png"._  
The icon file appears to have been moved from that page.  

### Logs

https://gist.github.com/jakabo27/a8a9bfd2e70d01716ab8767450ca35be

**Comment by nwithan8** [comment]
That line of code does not exist in v1.17.3. How did you install this template? I am working on an official Unraid template as we speak.

**Comment by jakabo27** [comment]
From searching "plex meta manager" on Unraid's community apps, I installed the one from Roland's Repository.  
Docker hub:  https://hub.docker.com/r/meisnate12/plex-meta-manager/

![image](https://user-images.githubusercontent.com/29758597/188284336-251f042f-b047-4a62-b860-57c792d825ea.png)

**Comment by curious44** [comment]
Just incase anyone runs into this.  I also was seeing this using unraid official docker.  If you edit docker and click advanced view there is a field called "ICON URL:"  This must have been pointing to that URL at some point.  I just updated mine to below.

https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/docs/_static/favicon.png
