### ISSUE TITLE
[Feature]: Support adding shows/miniseries from Letterboxd lists

### ISSUE THREAD

**Issue by axsuul** [Kometa-Team/Kometa#1015]
### Is your feature request related to a problem? Please elaborate.

Shows/miniseries within Letterboxd lists are ignored but should be supported. For example, this list should be supported: https://letterboxd.com/slinkyman/list/letterboxds-top-100-highest-rated-narrative

### Describe the solution you'd like

After looking through the codebase, I don't think https://github.com/meisnate12/Plex-Meta-Manager/pull/102 applies anymore since each Letterboxd item is crawled individually anyways (if I'm not mistaken) and the TMDB id can be retrieved. For example, from [Chernobyl](https://letterboxd.com/film/chernobyl/) the TMDB id can be parsed from

```html
<a href="https://www.themoviedb.org/tv/87108/" class="micro-button track-event" data-track-action="TMDb">TMDb</a>
```

So it seems like shows/miniseries should now be able to be properly handled since with the TMDB ids we can get TVDB ids. The only caveat is I believe PMM assumes all TMDB ids added to the Letterboxd cache are movies so there willl need to be a way to address this.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/support-adding-showsminiseries-from-letterboxd-lists)
