### ISSUE TITLE
[Feature]: restrict collections to specific users

### ISSUE THREAD

**Issue by G4Zz0L1** [Kometa-Team/Kometa#1021]
### Is your feature request related to a problem? Please elaborate.

Hi, I'd like to ask if it will be possible to implement something similar to the playlist's "sync_to_users" but for collections.

### Describe the solution you'd like

A parameter just like "sync_to_users" on the playlists but for collections.

**Comment by meisnate12** [comment]
So that's just not how collections work in plex. This is kinda possible but it takes some setup basically you have to add a label to the collection and then when you manage your users you can set allowed labels for certain people.

**Comment by G4Zz0L1** [comment]
It requires a plex pass to manage that with labels? So, it's not possible to automate it with PMM?

**Comment by YozoraXCII** [comment]
The usage of labels does not require a Plex Pass, you just cant see them in the UI as they as visibly hidden, but still usable via the API which is what PMM does.

**Comment by G4Zz0L1** [comment]
But in that way I can't use PMM to associate users to labels. It's possible to manage that with the config files, maybe?

**Comment by chazlarson** [comment]
Not possible in PMM, at this time, anyway.
