### ISSUE TITLE
[Feature]: Docker Compose Health Check

### ISSUE THREAD

**Issue by antwanchild** [Kometa-Team/Kometa#1031]
### Is your feature request related to a problem? Please elaborate.

I would like to see if there is a way to implement some kind of health check when running Plex Meta Manager? Whether that's built into the Docker File, os if there is something I could run as a health check in my yaml file.

### Describe the solution you'd like

Solution would be a health check

**Comment by mnkhouri** [comment]
In case anyone else is looking for something similar, this is what I'm doing in my docker-compose:

```
        healthcheck:
            test: "! grep -E '(Error|Critical) Summary' -A 20 /config/logs/meta.log"
```

If there's any "error" or "critical" messages in the latest logfile, the healthcheck will fail. Obviously this might need an update if the format of the logfile changes, but I'm finding it's working quite well for me.

**Comment by antwanchild** [comment]
Critical could just represent a bug in the code. So restarting wont fix it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
