### ISSUE TITLE
[Feature]: Add support for Editions in Plex Builder

### ISSUE THREAD

**Issue by robertheath** [Kometa-Team/Kometa#1034]
### Is your feature request related to a problem? Please elaborate.

Plex recently added support for mutliple editions of the same movie, i.e. 2D and 3D. I would like to be able to use the Plex Builder to select all movies of a specific edition, i.e. 3D, so that I can apply a specific overlay to those movies.

### Describe the solution you'd like

Add support for the Edition filter to the Plex Builder. Documentation on the new Editions feature is here https://support.plex.tv/articles/multiple-editions/.

**Comment by rclark213** [comment]
I think editions will need to be addressed somehow, given that a single movie can now have multiple editions in Plex, and thus when attempting to update the metadata of a film, there will be uncertainty in which edition to update. I'm guessing it'll be a big headache at first, but could be pretty powerful eventually.

**Comment by meisnate12** [comment]
this has been added in nightly
