### ISSUE TITLE
[Feature]: Using template variables inside regex patterns

### ISSUE THREAD

**Issue by vpatel9202** [Kometa-Team/Kometa#1039]
### Is your feature request related to a problem? Please elaborate.

I have some libraries with non standard content, like lectures and sports. I've been using my directory structure as a way to organize this stuff since there's no real way for Plex to get metadata aside from me manually tagging everything. For example, one of my lecture series' may be in `Lectures > Medicine > Cardiology > Pathology` and the only real way for me to find something specific is to navigate to it using the folder view on whatever Plex client I'm using. 

I'd like to use PMM instead, but since I have it organized by directories, I would need to use a Plex builder with a `filepath.regex` filter:

```
collections:
  ECG Lectures:
    plex_all: true
    filter:
      filepath.regex: \/data\/Other\/Lectures\/Medicine\/Cardiology\/ECGs\/*
```

This works well, but it can get cumbersome without a template, especially when I start adding other filters to it.

### Describe the solution you'd like

Ideally, I'd like to be able to use a template to auto-generate the regex patterns. As far as I can tell, you can't inject a template variable into the regex pattern currently so I can't use templates at all for this purpose. If it would be feasible, this is how I imagine the metadata yml would be structured:

```
templates:
  Subject:
    plex_all: true
    filter:
      filepath.regex: \/data\/Other\/Lectures\/<<subject>>\/.+

collections:
  ECG Lectures:
    template: { name: Subject, subject: "((ECGs|Cardiology)|Cardiology\/ECGs)" }
```

This is probably an overly simplistic demonstration of the use case but it would make PMM a lot more extensible for non standard libraries, especially when combined with the conditionals and optionals.

**Comment by meisnate12** [comment]
have you tried this it should absolutly be possible

**Comment by vpatel9202** [comment]
It does actually work, I'm not sure what I was doing incorrectly before but I tried it again and it worked...
