### ISSUE TITLE
[Docs]: cna not can

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#1054]
### What is the improvement or update to the Wiki you wish to see?

A small typo to be fixed.
<img width="897" alt="cna" src="https://user-images.githubusercontent.com/96403800/192057945-05945cab-90e3-43e4-aed0-9f73d4197ce7.png">

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/search.html?q=cna&check_keywords=yes&area=default

**Comment by chazlarson** [comment]
This has been fixed in nightly.
