### ISSUE TITLE
[Bug]: Plex - Setting container serialization range to [0, 0] (total=-1) - after running PMM

### ISSUE THREAD

**Issue by Ricas13** [Kometa-Team/Kometa#1055]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

Running PMM. Tried the normal local installation and currently running it on docker.

The Plex installation is a fully fresh new one. No watched history, no users added. Just libraries scanned.

The collections are created based on the PMM master config: https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/PMM

After running the script in one library, plex starts fixing the database related to the collections. The bigger the library, the longer this process takes and it stalls plex. Impossible to play or browse media until the fix ups are done. This can take long hours.

All plex servers I owned display the same behaviour after the script. They run the latest docker version [plexinc/pms-docker].

See the plex logs attached please.

### Relevant Collection/Overlay/Playlist Definition

```yml
Running the master PMM config: https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/PMM
```

### Logs

https://gist.github.com/Ricas13/c0c5347b6e798588bd2998384d608126

**Comment by Ricas13** [comment]
I've added another log to the gist. 

The log message is now different (no longer says DatabaseFixUps. But it's still doing something similar. Whilst this, the server is still pretty much unresponsive. 

https://gist.githubusercontent.com/Ricas13/c0c5347b6e798588bd2998384d608126/raw/d253373c61247a73fb342736611f41148ced3a2e/Plex%2520log%25202

**Comment by wesholley** [comment]
I'm having what looks like this same issue. Plex Scanner hangs and keeps adding these entries to the log:

Oct 06, 2022 13:50:05.093 [0x7f0da2f23b00] DEBUG - Request: [xxx.xx.xx.16:50141 (Subnet)] GET /library/sections/9/all?type=8&sort=titleSort&includeCollections=1&includeExternalMedia=1 (8 live) #251 TLS Page 0-289 GZIP Signed-in Token (Redacted-Username) (Chrome)

Oct 06, 2022 13:50:05.094 [0x7f0da2f23b00] DEBUG - [Req#251] Setting container serialization range to [0, 289] (total=-1)

Oct 06, 2022 13:50:05.129 [0x7f0da2f23b00] DEBUG - [Req#251] It took 40.000000 ms to retrieve 290 items.

Oct 06, 2022 13:50:05.132 [0x7f0da2f23b00] DEBUG - [Req#251] Setting container serialization range to [0, 289] (total=487)

Oct 06, 2022 13:50:05.340 [0x7f0da5ed2b00] DEBUG - Completed: [xxx.xx.xx.16:50141] 200 GET /library/sections/9/all?type=8&sort=titleSort&includeCollections=1&includeExternalMedia=1 (8 live) TLS GZIP Page 0-289 247ms 491054 bytes (pipelined: 3)

**Comment by Ricas13** [comment]
I know, I ended up isolating it - running a plex instance with no one in it and restoring a database pre-PMM. It has been doing this fixups for 2 weeks. Completely impossible to use plex in this scenario. Bear in mind that my library is really big, but it shouldn't need to do this I would imagine.

Now it's doing this:
```
Oct 08, 2022 12:11:42.638 [0x7f687acb2b00] DEBUG - PlayQueue: Converted 'server://6e4b2afc1bafd40f5919548190479b13effb886a/com.plexapp.plugins.library/library/sections/1/all?type=1&sort=originallyAvailableAt%3Adesc&push=1&subtitleLanguage=ta&pop=1' to 'library://x/directory/%2Flibrary%2Fsections%2F1%2Fall%3Ftype%3D1%26sort%3DoriginallyAvailableAt%253Adesc%26push%3D1%26subtitleLanguage%3Dta%26pop%3D1'
Oct 08, 2022 12:11:42.638 [0x7f687acb2b00] DEBUG - Setting container serialization range to [0, 0] (total=-1)
Oct 08, 2022 12:11:43.030 [0x7f687acb2b00] DEBUG - PlayQueue: Converted 'server://6e4b2afc1bafd40f5919548190479b13effb886a/com.plexapp.plugins.library/library/sections/1/all?type=1&sort=originallyAvailableAt%3Adesc&push=1&subtitleLanguage=te&pop=1' to 'library://x/directory/%2Flibrary%2Fsections%2F1%2Fall%3Ftype%3D1%26sort%3DoriginallyAvailableAt%253Adesc%26push%3D1%26subtitleLanguage%3Dte%26pop%3D1'
Oct 08, 2022 12:11:43.030 [0x7f687acb2b00] DEBUG - Setting container serialization range to [0, 0] (total=-1)
Oct 08, 2022 12:11:43.366 [0x7f687acb2b00] DEBUG - PlayQueue: Converted 'server://6e4b2afc1bafd40f5919548190479b13effb886a/com.plexapp.plugins.library/library/sections/1/all?type=1&sort=originallyAvailableAt%3Adesc&push=1&subtitleLanguage=fil&pop=1' to 'library://x/directory/%2Flibrary%2Fsections%2F1%2Fall%3Ftype%3D1%26sort%3DoriginallyAvailableAt%253Adesc%26push%3D1%26subtitleLanguage%3Dfil%26pop%3D1'
Oct 08, 2022 12:11:43.366 [0x7f687acb2b00] DEBUG - Setting container serialization range to [0, 0] (total=-1)
Oct 08, 2022 12:11:43.395 [0x7f686e495b00] WARN - [Req#2c67aeb] Waited one whole second for a busy database.
Oct 08, 2022 12:11:43.458 [0x7f687b8d8b00] WARN - [Req#2c6795d] Waited one whole second for a busy database.
Oct 08, 2022 12:11:43.699 [0x7f687acb2b00] DEBUG - PlayQueue: Converted 'server://6e4b2afc1bafd40f5919548190479b13effb886a/com.plexapp.plugins.library/library/sections/1/all?type=1&sort=originallyAvailableAt%3Adesc&push=1&subtitleLanguage=sr&pop=1' to 'library://x/directory/%2Flibrary%2Fsections%2F1%2Fall%3Ftype%3D1%26sort%3DoriginallyAvailableAt%253Adesc%26push%3D1%26subtitleLanguage%3Dsr%26pop%3D1'
Oct 08, 2022 12:11:43.700 [0x7f687acb2b00] DEBUG - Setting container serialization range to [0, 0] (total=-1)
```


No longer the DatabaseFixUps, but it's refreshing the same episodes multiple times. My alerts window is continuouly listing the metadata updates - and the same Season appears multiple times during the day - almost kinda in a loop.

**Comment by sysmoon14** [comment]
Is there any resolution to this? I'm starting to see the same problem

**Comment by wesholley** [comment]
I never heard from Plex on this, so I decided to just let it run basically overnight and after a day or so it seemed to sort itself out. I haven't seen it happen again so far (~1 year now).

**Comment by shades6057** [comment]
I'm seeing the same thing, I too have a relatively large library. I've stopped it and tried a couple thing to no avail.  It's on my test server so I guess I'll just let it run like wesholly stated and see what transpires.

**Comment by chazlarson** [comment]
I have run PMM many times against absurdly huge libraries and have never seen this.  PMM is communicating with Plex via the standard Plex API that all its own clients use; it's not doing anything to the database directly, so it seems very unlikely that there's anything PMM is doing specifically to trigger this.

Note that I am not denying that anyone's seeing this issue, just noting that PMM's not doing anything behind Plex's back.
