### ISSUE TITLE
[Feature]:  Make use of requests-cache to cached request responses for a certain duration

### ISSUE THREAD

**Issue by Drapersniper** [Kometa-Team/Kometa#1056]
### Is your feature request related to a problem? Please elaborate.

This should significantly improve the performance of resumed runs.

For obvious reasons, the cache shouldn't be permanent - but 12-24h should allow a reasonable cache time.

### Describe the solution you'd like

Should be as simple as 
https://github.com/meisnate12/Plex-Meta-Manager/blob/bf4b11c689d24b98108cf6bf51304c15b0240c80/plex_meta_manager.py#L4
```py
# Add this to line 4 of plex_meta_manager.py 
from  requests_cache import install_cache
install_cache(
    '/config/http_cache',
    expire_after=timedelta(days=1),  # Otherwise expire responses after one day
    allowable_methods=['GET', 'POST'],  # Cache POST requests to avoid sending the same data twice
    allowable_codes=[200],
    match_headers=True,
)

```

### Additional Information

The cache can be fine-tuned more by skipping specific sites, arg, the usage above is just a very simple way to make it applicate to the whole runtime.

**Comment by meisnate12** [comment]
this caused issues when we tried to add it and decide to remove it again
