### ISSUE TITLE
Request: Support ENV Vars

### ISSUE THREAD

**Issue by dcplaya** [Kometa-Team/Kometa#107]
It would be nice if, instead of having to  modify the command the docker runs, you could just specify ENV vars for things like config path location, run time, ect.

I am putting this in a K8s cluster and it just requires less work to specify ENVs instead of override the run command.

**Comment by meisnate12** [comment]
ok can you test the Environmental variables have been added to develop. They are `PMM_DEBUG`, `PMM_TEST`, `PMM_RUN`, `PMM_COLLECTIONS`, `PMM_TIME`, `PMM_DIVIDER`, `PMM_WIDTH`, and `PMM_CONFIG`

**Comment by dcplaya** [comment]
Sorry it took so long for me to check this. But it works (obviously, since you pushed to main 😆)!!

Thank you!
It lets me not override your base docker command now.
For the curious, the kubernetes file is [here](https://github.com/dcplaya/home-cluster/blob/main/cluster/media/Plex%20Meta%20Manager/plex-meta-manager.yaml)

**Comment by Data-Monkey** [comment]
I get this error when using the PMM_WIDTH ENV in the docker version:
File "//plex_meta_manager.py", line 72, in <module>
if screen_width < 90 or screen_width > 300:
TypeError: '<' not supported between instances of 'str' and 'int'

I tried to fix the code, but it gets reset on every restart.

edit: raised a new bug, hope that makes it easier #435
