### ISSUE TITLE
1.5.0 Debug Errors in Log

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#108]
I'm seeing a few random errors in my logs after 1.5.0 that I didn't notice before the upgrade.

[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6142198/meta.log)

Log is also dramatically smaller. It was 4.8mb last Wed, Thu, Fri, Sat, Sun (yesterday 3am) and today it's 90kb.

**Comment by meisnate12** [comment]
these errors are being caused by the program timing out while trying to connect to plex

**Comment by Tharic99** [comment]
Perfect, thanks. I bumped my timeout up from the 60 default to 120.
