### ISSUE TITLE
1.5.0 Docker Requirements error

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#109]
The docker file for 1.5.0 updated overnight and when running the script manually in the container, it kicks the following errors

```
plex_meta_manager.py: line 1: import: command not found
plex_meta_manager.py: line 2: from: command not found
plex_meta_manager.py: line 3: try:: command not found
plex_meta_manager.py: line 4: import: command not found
plex_meta_manager.py: line 5: from: command not found
plex_meta_manager.py: line 6: from: command not found
plex_meta_manager.py: line 7: except: command not found
plex_meta_manager.py: line 8: syntax error near unexpected token `"Error: Requirements are not installed"'
plex_meta_manager.py: line 8: `    print("Error: Requirements are not installed")'
```

I saw in the 1.5.0 update notes that the PlexAPI has been updated to 4.4.1, but is it updated in the docker file?

**Comment by meisnate12** [comment]
this ones really odd to me because the new docker container is working fine for me. What are you running docker on? have you tried completely removing the image and re pulling it from docker hub

**Comment by Tharic99** [comment]
Unraid 6.9.1

I've forced an update on it twice. I know it's running 1.5.0 though. Doing a cat on plex_meta_manager.py I can see the 1.5.0 version in the file.

![Selection_072](https://user-images.githubusercontent.com/39832147/111199066-9cf7b480-8596-11eb-9424-6289b94670b4.png)

**Comment by meisnate12** [comment]
i pushed a change to the develop branch can you see if that helped any?

**Comment by Tharic99** [comment]
that fixed it. Thanks!

**Comment by meisnate12** [comment]
whats really weird is i took out something I added in 1.4.0 not 1.5.0. Did you use 1.4.0 and have it work?

**Comment by Tharic99** [comment]
I realized what I did wrong... I was using "bash" instead of "python" to run the `plex_meta_manager.py`... Ooph.. 

Sorry for the trouble on this one!
