### ISSUE TITLE
[Feature]: TheTVDB Alternate Order

### ISSUE THREAD

**Issue by PilaScat** [Kometa-Team/Kometa#1102]
### Is your feature request related to a problem? Please elaborate.

Shows like Money Heist are a pain in Plex due to the custom Netflix order

### Describe the solution you'd like

Add the custom metadata episode ordering tvdb_alternate

### Additional Information

![image](https://user-images.githubusercontent.com/12989749/194715309-5364b968-452e-46e2-8243-762679ceedd5.png)
Now is missing

**Comment by meisnate12** [comment]
this just emulates the `Episode Ordering` Advance Option all im doing is changing that value. If the Plex Metadata Agent is amended to allow for custom episode ordering ill happily add it in as an option, but this isnt something that pmm can do you need a custom Metadata Agent or change the Plex one for this to work

![image](https://user-images.githubusercontent.com/1631064/196333188-4bf7a256-73b0-41b8-b36d-9b0e47d9a668.png)

**Comment by jardim01** [comment]
Hi! This is now supported by Plex (https://forums.plex.tv/t/tvdb-alternate-orders/882249), any plans on adding the extra options @meisnate12?
