### ISSUE TITLE
[Feature]: visible library order

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#1105]
### Is your feature request related to a problem? Please elaborate.

thanks to visible_shared and visible_home, we can display collections on the home page.
but we can't order the libraries by preference. if libraries are to be left as is, no problem, we can order them in plex library manager, but when we have schedules collections (for holidays :-) )we can't display then on top :-/
it would be a nice feature.
thanks

### Describe the solution you'd like

have a visible_order function :-)

**Comment by meisnate12** [comment]
requested here https://features.metamanager.wiki/features/p/manage-home-screen-hubs
