### ISSUE TITLE
[Feature]: Upgrade Python from 3.10 to 3.11

### ISSUE THREAD

**Issue by darthShadow** [Kometa-Team/Kometa#1138]
### Is your feature request related to a problem? Please elaborate.

Nothing as such but python 3.11 has significiant speed-ups in general and also provides better tracebacks.

From the release notes at https://www.python.org/downloads/release/python-3110/:

```
The Faster CPython Project is already yielding some exciting results. Python 3.11 is up to 10-60% faster than Python 3.10. On average, we measured a 1.22x speedup on the standard benchmark suite.
```

### Describe the solution you'd like

Migrate the docker image from 3.10 to 3.11.

**Comment by darthShadow** [comment]
I could submit the PR for the dockerfile change, but I am not sure of what else needs to be tested so I have left it alone for now.

**Comment by chazlarson** [comment]
PMM requires LXML, which is apparently hobbled by build issues under 3.11 at the moment.

**Comment by chazlarson** [comment]
Saw the same thing when 3.10 first released.

**Comment by darthShadow** [comment]
Looks like the lxml wheels are available now for 3.11: https://github.com/lxml/lxml/releases/tag/lxml-4.9.1

The release date seems old but perhaps the wheels were added recently.

Installing on Ubuntu 18.04 seems to be working fine now with the wheel:

```
darthshadow@server:~$ pip3 install --force-reinstall lxml==4.9.1
Collecting lxml==4.9.1
  Using cached lxml-4.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.0 MB)
Installing collected packages: lxml
  Attempting uninstall: lxml
    Found existing installation: lxml 4.9.1
    Uninstalling lxml-4.9.1:
      Successfully uninstalled lxml-4.9.1
Successfully installed lxml-4.9.1
```

**Comment by meisnate12** [comment]
https://bugs.launchpad.net/lxml/+bug/1977998

Im going to wait on 3.11 untill the next lxml version is released

**Comment by meisnate12** [comment]
added
