### ISSUE TITLE
[Bug]: my anime list seasonal anime returning currently airing (not just seasonal). 

### ISSUE THREAD

**Issue by MattSidney** [Kometa-Team/Kometa#1153]
### Version Number

na 

### What branch are you on?

master

### Describe the Bug

My Anime List _season pull all currently airing anime rather than just the seasonal anime which is presented here: https://myanimelist.net/anime/season

### Relevant Collection/Overlay/Playlist Definition

```yml
PMM/chart/myanimelist.yml
```

### Logs

na

**Comment by MattSidney** [comment]
created a scrappy PR here: https://github.com/meisnate12/Plex-Meta-Manager/pull/1152

**Comment by meisnate12** [comment]
this isnt actually a bug the list is showing the correct items you just want it filtered more im closing this as its a FR not a bug
