### ISSUE TITLE
ValueError When Attempting to Add Prerolls

### ISSUE THREAD

**Issue by OcifferAction** [Kometa-Team/Kometa#1182]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

Receiving an error when attempting to use preroll feature. Error states ValueError: not enough values to unpack (expected 2, got 1). Attached Movies.yml in txt file. Full error below.
[Movies.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/10016239/Movies.txt)

### Logs

https://gist.github.com/OcifferAction/01957279ea76c36744125210fce03abc

**Comment by chazlarson** [comment]
I'm curious why the preroll value is two of the same path, with the first `/` doubled in each:
```
    server_preroll: //media/preroll/Thanksgiving.mp4;//media/preroll/Thanksgiving.mp4
```
If you make that a single copy without the doubled slash, does that affect the error?  Perhaps something about that is throwing off a parser.

**Comment by OcifferAction** [comment]
I've played around with the paths a little. First only having server_preroll: /media/preroll/Thanksgiving.mp4

Once I received the error I added an additional /media/preroll/Thanksgiving.mp4 after the ;

Once I received the error again I tried using the double slashes as in the example from a previous issue on the topic. [https://github.com/meisnate12/Plex-Meta-Manager/issues/486](url)

**Comment by meisnate12** [comment]
so this is an error coming from the plex api all pmm is doing is looking at your plex settings and the plexapi is throwing the above error

**Comment by OcifferAction** [comment]
You're correct, I see that now in the logs. File "/usr/lib/python3.10/site-packages/plexapi/server.py" It looks like I'm getting the same error in Rollarr.

I've created a Plex Community Forum post [https://forums.plex.tv/t/api-issue-with-prerolls/818766](url)

**Comment by meisnate12** [comment]
If you can go into the plex UI and add the value there it's not an issue with the api itself. It would be an issue with the python module for the api https://github.com/pkkid/python-plexapi

I believe it is an issue with the module as that error is a python error

**Comment by OcifferAction** [comment]
Created a issue ticket with Plex-API. Creator has reviewed and made changes to code to resolve the error. [https://github.com/pkkid/python-plexapi/pull/1057](url)
