### ISSUE TITLE
[Defaults]: Audio/Subtitle Languages

### ISSUE THREAD

**Issue by turkeyphant** [Kometa-Team/Kometa#1186]
### Link to File

pmm: languages

### Version Number

1.18.0-develop25 (Docker)

### What branch are you on?

nightly

### Describe the Bug

Several issues and errors regarding this.

1. https://metamanager.wiki/en/latest/defaults/overlays/languages.html has the wrong ISO country code for S
2. It seems odd and arbitrary to make all but six languages `false` by default. Under what circumstances would a user want to see that the video contains Portuguese audio but not Swedish audio? The only way to fix this is to manually add something like the following:
```- pmm: languages
        template_variables:
          use_ko: true # Korean
          use_zh: true # Chinese
          use_da: true # Danish
          use_ru: true # Russian
          use_it: true # Italian
          use_hi: true # Hindi
          use_te: true # Telugu
          use_fa: true # Farsi
          use_th: true # Thai
          use_nl: true # Dutch
          use_no: true # Norwegian
          use_is: true # Icelandic
          use_sv: true # Swedish
          use_tr: true # Turkish
          use_pl: true # Polish
          use_cs: true # Czech
          use_uk: true # Ukrainian
          use_hu: true # Hungarian
          use_ar: true # Arabic
          use_bg: true # Bulgarian
          use_bn: true # Bengali
          use_bs: true # Bosnian
          use_ca: true # Catalan
          use_cy: true # Welsh
          use_el: true # Greek
          use_et: true # Estonian
          use_eu: true # Basque
          use_fi: true # Finnish
          use_fl: true # Filipino
          use_gl: true # Galician
          use_he: true # Hebrew
          use_hr: true # Croatian
          use_id: true # Indonesian
          use_ka: true # Georgian
          use_kk: true # Kazakh
          use_kn: true # Kannada
          use_la: true # Latin
          use_lt: true # Lithuanian
          use_lv: true # Latvian
          use_mk: true # Macedonian
          use_ml: true # Malayalam
          use_mr: true # Marathi
          use_ms: true # Malay
          use_nb: true # Norwegian Nokmåuse
          use_nn: true # Norwegian Nynorsk
          use_pa: true # Punjabi
          use_ro: true # Romanian
          use_sk: true # Slovak
          use_si: true # Slovenian
          use_sq: true # Albanian
          use_sr: true # Serbian
          use_sw: true # Swahili
          use_ta: true # Tamil
          use_ur: true # Urdu
```

3. I don't get why there are two types of Norwegian listed but not many other languages like Armenian. Why are not all ISO-639 available?
4. Persian comes up as Farsi even though there's no Persian in the documentation.

**Comment by meisnate12** [comment]
1. i think we fixed this in nightly
2. we didnt want to overwhelm people with them all being true off bat so thats why theres only 6 
you can also just make a list of those you want to use under the `languages` template variable 
3. we started with a list of country flags and are trying to match them with languages some get left out some we may not have had flags for im happy to add any if you can tell me its code and what flag it should have
4. is the pesian language not farsi?

**Comment by gitthangbaby** [comment]
2) Can this infromation be added to [wiki](https://metamanager.wiki/en/latest/defaults/overlays/languages.html#supported-audio-subtitle-language-flags) and example? We should enable all languages - weight is already there to apply, This 6 language supreme pack doesn't make sense, quite opposite is preferred - disable the most frequent languages and show unique language labels.

**Comment by meisnate12** [comment]
its already been added its just only on the nightly wiki as that feature is only in nightly

**Comment by jordiortizdomenech** [comment]
May I suggest changing the country flag for catalan and use Andorra (ad) instead of Spain (es)? 
The reason is that catalan is the official language in Andorra, and it is the only country with catalan as main/single official language.
