### ISSUE TITLE
[Defaults]: Franchise TV ignores collection_section

### ISSUE THREAD

**Issue by alejakun** [Kometa-Team/Kometa#1187]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/show/franchise.yml

### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

Ran the defaults metadata-files + overlays for both Movies and TV libraries. The only significant change from the example configuration is the order of the processing of the files and change in the `collection_section` attribute to the `template_variables` for most collections:

```
    - pmm: franchise
      template_variables:
        collection_section: "09"
```

After the collections are run the name for the Star Wars collection (the only one in my library) is the following: `Star Wars` instead of the usual default naming convention: `!16_Politics Shows` for example

**Comment by meisnate12** [comment]
can you try nightly and see if your issue is fixed

**Comment by curious44** [comment]
This is also happening for Movies.  I tried Nightly with no change. I also tried to change sort title and doesn't reflect template variable.

    - pmm: franchise
      template_variables:
        collection_section: 04
        minimum_items: 3
        sort_title: "!04_<<collection_name>>"

**Comment by alejakun** [comment]
Hi,

Just tested for this, seems to happen the same in both Movies and Shows (as indicated by @curious44). For example for TV shows I'm seeing:

![image](https://user-images.githubusercontent.com/72576153/210867579-0b673cc6-ad04-461d-99a7-62d65a1a2430.png)

For Movies:

![image](https://user-images.githubusercontent.com/72576153/210867701-68e14414-a4c1-4c8f-8052-66e13513a21d.png)

Tested this with the most current PMM version with the following command: `docker run -it --env-file "$PWD/.env" -v "$PWD/plex-meta-manager/config:/config:rw" --name pmm --network=traefik meisnate12/plex-meta-manager:nightly --run-libraries "TV,Movies"` for reference the log shows `Version: 1.18.2-develop4 (Docker)`.

**Comment by meisnate12** [comment]
this should be fixed in nightly

**Comment by alejakun** [comment]
Verified in nightly!!

Thanks for the fix!
