### ISSUE TITLE
[Defaults]: Request to add more TV Networks

### ISSUE THREAD

**Issue by alejakun** [Kometa-Team/Kometa#1188]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/show/network.yml

### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

Not really a bug, a request to add more TV Networks:

Adult Swim
Apple TV+
Hulu
Paramount+
Peacock
STAR+
SyFy

**Comment by chazlarson** [comment]
That file is no longer used as a default by PMM, so the quickest way to do this will be to make a copy of it and customize it to suit.

**Comment by alejakun** [comment]
I was thinking that was the one used by PMM Defaults, which is the one instead?

**Comment by chazlarson** [comment]
In version 1.18, the defaults are in the app repo [so they're in the docker container if you're using docker]
https://github.com/meisnate12/Plex-Meta-Manager/tree/master/defaults
They're documented here:
https://metamanager.wiki/en/latest/defaults/guide.html

Prior to that, the defaults were taken from the config repo:
https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/PMM

Prior to that, the meisnate12 files form the configs repo were used as examples and "defaults" in the wiki:
https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/meisnate12

**Comment by alejakun** [comment]
Please correct me if I'm wrong but I believe the file I made reference is actually part of the app repo (it comes from Plex-Meta-Manager, not Plex-Meta-Manager-Configs).

Given that it is from the app repo I still don't know how to make the required changed for the request to work, I'll try to see if I can identify how I can achieve this and report back.

**Comment by chazlarson** [comment]
Oh, you’re right.  I misread the URL.  Apologies.

**Comment by alejakun** [comment]
No worries, actually your pointing to the documentation after a few reads and re-reads (my fault I believe, not the documentation), I believe I've found the solution which I believe lies in using the template parameters `append_include` and `append_addons`. I'm testing this and will report back.

Best regards.

**Comment by alejakun** [comment]
I was correct, this is the right way to handle this case, I'm sorry for the unnecessary issue, just for reference this is how my config file ended up looking like:

```
    - pmm: network                                  # ABC, CBC, NBC, FOX, etc.
      template_variables:
        collection_section: "13"
        append_include:
          - Adult Swim
          - Apple TV+
          - Hulu
          - Paramount+
          - Peacock
          - STAR+
          - SyFy
        append_addons:
          Adult Swim:
            - Adult Swim
          Apple TV+:
            - Apple TV+
          Hulu:
            - Hulu
          Paramount+:
            - Paramount+
          Peacock:
            - Peacock
          STAR+:
            - STAR+
          SyFy:
            - SyFy
```
