### ISSUE TITLE
pmm: ratings - two ratings (top/center) - ratings/images stacked

### ISSUE THREAD

**Issue by CaptainPimpJr** [Kometa-Team/Kometa#1195]
### Version Number

1.18

### What branch are you on?

master

### Describe the Bug

using `-pmm: ratings` (overlay_level: episode)

selecting just two ratings for overlay, selecting: 
`vertical_position: top`, 
`horizontal_position: center`, 
`alignment: horizontal` 

leads to stacking ratings / images:
log:
`Conditional: rating1_horizontal_offset Condition 1 Failed: rating_alignment "horizontal" is not "vertical" Condition 2 Failed: rating2 "audience" is not "none" Condition 3 Failed: rating2 "audience" is not "none" Conditional Variable: rating1_horizontal_offset is "-<<ch2_offset>>"`

and

`Conditional: rating2_horizontal_offset Condition 1 Failed: rating_alignment "horizontal" is not "vertical" Condition 2 Failed: rating1 "critic" is not "none" Condition 3 Failed: rating1 "critic" is not "none" Conditional Variable: rating2_horizontal_offset is "-<<ch2_offset>>"`

line 240 needs to end with:
`value: +<<ch2_offset>>` or `value: <<ch2_offset>>`
instead of:
`value: -<<ch2_offset>>`

or more detailed rating1_horizontal_offset leads to line 164 which is exactly the same as rating2_horizontal_offset ending in line 240. 

It looks like this:
<img width="109" alt="Bildschirmfoto 2022-11-17 um 21 56 19" src="https://user-images.githubusercontent.com/80001972/203856124-ccdf0dac-ec05-4f77-9612-ced0c8d8eccb.png">

### Logs

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/overlays/ratings.yml

**Comment by meisnate12** [comment]
fixed in nightly thanks for letting me know

**Comment by CaptainPimpJr** [comment]
You are very welcome - I appreciate your work and efforts.
