### ISSUE TITLE
Tagline error

### ISSUE THREAD

**Issue by djf73267** [Kometa-Team/Kometa#120]
I'm having trouble with a tagline error on the latest version for the master branch whenever I try to change metadata for shows end up failing to get an update through. 
> |                                                                                                    |
| Updating Show: Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2...                            |
| Traceback (most recent call last):                                                                 |
|   File "plex_meta_manager.py", line 84, in start                                                   |
|     config.update_libraries(test, collections)                                                     |
|   File "D:\Users\DFun\Downloads\Plex-Meta-Manager-master\Plex-Meta-Manager-master\modules\config.py", line 401, in update_libraries |
|     try:                        library.update_metadata(self.TMDb, test)                           |
|   File "D:\Users\DFun\Downloads\Plex-Meta-Manager-master\Plex-Meta-Manager-master\modules\plex.py", line 298, in update_metadata |
|     add_edit("tagline", item.tagline, self.metadata[m], value=tagline)                             |
|   File "C:\Users\DFun\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\plexapi\base.py", line 389, in __getattribute__ |
|     value = super(PlexPartialObject, self).__getattribute__(attr)                                  |
| AttributeError: 'Show' object has no attribute 'tagline'                                           |
|                                                                                                    |
| 'Show' object has no attribute 'tagline'

**Comment by meisnate12** [comment]
did you install requirements again after you upgraded to 1.5.0?

**Comment by djf73267** [comment]
You are right however after updating the requirements again I get this when running

> |                                                                                                    |
| Updating Show: Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2...                            |
| Show: Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2 Details Update Not Needed              |
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "plex_meta_manager.py", line 84, in start                                                   |
|     config.update_libraries(test, collections)                                                     |
|   File "D:\Users\Darren\Downloads\Plex-Meta-Manager-master\Plex-Meta-Manager-master\modules\config.py", line 401, in update_libraries |
|     try:                        library.update_metadata(self.TMDb, test)                           |
|   File "D:\Users\Darren\Downloads\Plex-Meta-Manager-master\Plex-Meta-Manager-master\modules\plex.py", line 400, in update_metadata |
|     output = match.group(0)[1:].split("E" if "E" in m.group(0) else "e")                           |
| AttributeError: 'str' object has no attribute 'group'                                              |
|                                                                                                    |
| 'str' object has no attribute 'group'                                                              |
|

**Comment by meisnate12** [comment]
can you post your metadata setup for `Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2` and the metadata entry that immediately follows it

**Comment by djf73267** [comment]
The metadata entries following Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2 do not get fulfilled
>"Re:Zero kara Hajimeru Isekai Seikatsu Season 2 Part 2":
    episodes:
      S01E01:
        rating: "7.5"
  "Sword Art Online: Alicization - War of Underworld (2020)":
    rating: "7.4"
  "Tate no Yuusha no Nariagari":
    rating: "8.0"
  "Tensei Shitara Slime Datta Ken Season 2":
     rating: "8.0"

**Comment by meisnate12** [comment]
ok can you test in develop i think I fixed it

**Comment by djf73267** [comment]
Yep just tested it and all the entries processed normally. Thank you!

**Comment by meisnate12** [comment]
no problem glad i could fix it
