### ISSUE TITLE
[Defaults]: ratings not accepting <directional>_align: 

### ISSUE THREAD

**Issue by Davst** [Kometa-Team/Kometa#1202]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/overlays/ratings.yml

### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

To standardize ratings with the other default scripts and provide a more cohesive expected behavior, positioning of ratings should use the template_variables `horizontal_align` and `vertical_align` instead of the _position versions that it currently accepts.

Currently the documentation on this subject is also inconclusive listing both <direction>_align and <direction>_position

**Comment by meisnate12** [comment]
ratings is special and has some predetermined locations if you need to use a custom location youre going to have to make the overlay file for that yourself i dont have any intention  of changing this
