### ISSUE TITLE
Overlay label not applied consistenly

### ISSUE THREAD

**Issue by G4Zz0L1** [Kometa-Team/Kometa#1204]
### Version Number

1.18.0-develop41

### What branch are you on?

nightly

### Describe the Bug

I've found out that the label `Overlay` doesn't get applied on some items (always the sames on every run) even if the logs doesn't show errors or anything useful.
This causes the overlays to get reapplied everytime (with strange behaviours like multiple layers on a poster or, if moved, multiple overlays with a single default overlay file) and to not be deleted with `remove_overlays`.
I don't know what to test to prove this, but everytime I have to reset every library and the process is long, so if anyone has something specific to check, I'll be appy to test and report.
The logs doesn't show anything, the overlays are applied as normal (and multiple times), and the issue is only on the plex label side.
This issue recaps some tests and thoughts: https://github.com/meisnate12/Plex-Meta-Manager/issues/1191

### Logs

The logs are fine, nothing useful there.

**Comment by meisnate12** [comment]
can you plex dance on of the items thats its failing with and see if that fixes the issue

**Comment by G4Zz0L1** [comment]
That doesn't do anything, the same items as before have the same issues (the operations I usually do are listed here https://github.com/meisnate12/Plex-Meta-Manager/issues/1191#issuecomment-1325705068).
I don't imply that a PMM issue, it may be on the plex side, it's just I don't know how to test it to check where the issue lies.

**Comment by meisnate12** [comment]
when you did the plex dance  did you also empty trash and clean bundles while the item wasnt in your library? sometimes even when items are removed their metadata isnt deleted so when you add them back its using the old data (data that i think is bad and causing the errors). And yea PMM is just telling plex to add this label and sometimes plex just doesnt want to. The usual solution is clearing out the metadata with a plex dance.

**Comment by G4Zz0L1** [comment]
Sadly that doesn't work.
Even with the step as you describe, the same items as before doesn't get the labels.
The script that I use for cleaning the assets (https://github.com/bullmoose20/Plex-Stuff/blob/main/plex-bloat-fix.py) does exactly that.
The steps I do to remove the overlays are the following:
- moving everything out of the library
- clearing pmm backup folders
- clearing plex metadata with the script (with empty trash, clean bundles and optimize db)
 - moving the files back in the library, as a clean start
 
 If you have something I can try to narrow it down, let me know, I can test it.
Thanks a lot for following on this, maybe with your expertise I can solve this.

**Comment by G4Zz0L1** [comment]
It seems that I've finally solved this overlay problem.
I've deleted the `$PLEX_HOME/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db` file and recreated the libraries from scratch.
Now it seems to work correctly and apply the labels on everything.
We'll never know if the fault was in the PMM side or Plex one, and it was an extreme solution, but it works.

**Comment by meisnate12** [comment]
seems like a corrupt database on the plex side i dont think that would have been PMM's fault as everything it does to Plex is through standard api actions just automated but good to know that there is at least a fix
