### ISSUE TITLE
PMM always stops before completing

### ISSUE THREAD

**Issue by ShanaryS** [Kometa-Team/Kometa#1210]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

I don't know what else I can say, but PMM never works for me, it can never finish. It seems to be some connection in a python script timing out but I don't know. The only thing I'm doing is applying the default overlays, nothing fancy. It also was like this in the previous version, which I managed to have completed once but I don't know.

In this case it slows to a crawl near the end then just stops.

### Logs

https://gist.github.com/ShanaryS/41d1174c233633e1cf8a30b87a3a58ef

**Comment by chazlarson** [comment]
You're applying a lot of overlays, which involves a lot of processing.  When PMM grinds to a halt as opposed to failing with an error, that's generally a sign that it's fighting resource constraints.  I've seen this when dynamic collections consume a lot of RAM.

My first suggestion would be to make test runs applying just a few overlays, then add a couple with each run to determine if there's a point at which this issue appears.  You can use that information to perhaps tune *how* the overlays are being applied or make decisions about which ones your setup will reasonably support.

It could be that either the system running PMM or the system running Plex are resource-constrained.  It could be that you're running PMM while Plex is busy doing other things.  It could be that the Plex DB has some issues.

There are lots of possibilities.

**Comment by ShanaryS** [comment]
So the connection timing out seems to be docker being dumb. It just randomly decides that nothing can connect to my containers.

But aside from that, it seems limiting the number of overlays help. I'll just create multiple config files for multiple containers and schedule the overlays at different times.

**Comment by chazlarson** [comment]
That's not going to work as you hope, assuming you're talking about splitting up overlays for a single library across runs.  Overlays are all-or-nothing, you can't run different overlays on the same library in different runs and have them all get applied.  Each run will replace the overlays from the previous run.

**Comment by ShanaryS** [comment]
I thought that's what reapply_overlays was for? Either way it seems like I should be able to get most of them. I really only wanted a few but thought I could just add the rest.

Strange because I have 32gb of ram and a 7700k. I should not be resource limited.

**Comment by chazlarson** [comment]
"reapply_overlays" tells PMM to reapply the overlays even if it doesn't think it needs to.  Every overlay run starts [at least attempts to] from the non-overlaid original poster.

You *could* force PMM to behave like this by messing around behind the scenes, but that becomes messy quickly.

**Comment by ShanaryS** [comment]
Reducing the number of overlays works. Removing just pmm: resolution was enough to have it work.
