### ISSUE TITLE
[Bug]:  

### ISSUE THREAD

**Issue by BamaSlymm** [Kometa-Team/Kometa#1211]
### Version Number

1.18.0-develop47

### What branch are you on?

master

### Describe the Bug

I'm trying to start the .py script for the meta manager but everytime I run the command I get this error:
     File "plex_meta_manager.py", line 75
         run_arg + " ".join([f'"{s}"' of "" in s else s for s om sys.argv[:]])
                                              ^
SyntaxError: invalid syntax

### Logs

https://gist.github.com/BamaSlymm/5f3b503f957c95b86828d4ca43774081

**Comment by chazlarson** [comment]
How are you running the script?  What's the specific command?  Also, what does `python --version` show?

**Comment by chazlarson** [comment]
I strongly suspect you're running it under Python 2, which is not going to work.  The script requires Python 3.7 or higher.

```
% python --version
Python 2.7.18
% python plex_meta_manager.py
  File "plex_meta_manager.py", line 74
    run_arg = " ".join([f'"{s}"' if " " in s else s for s in sys.argv[:]])
                               ^
SyntaxError: invalid syntax
```
Where if I switch to Python3:
```
% python --version
Python 3.10.8
% python plex_meta_manager.py
| Current Time: 17:13 | 11 Hours and 47 Minutes until the next run at 05:00 | Runs: 05:00
```

**Comment by BamaSlymm** [comment]
Ran it under Python 3 and got this:

Traceback (most recent call last):
  File "plex_meta_manager.py", line 125, in <module>
    from modules.builder import CollectionBuilder
  File "/mnt/3rd/Plex-Meta-Manager/modules/builder.py", line 3, in <module>
    from modules import anidb, anilist, flixpatrol, icheckmovies, imdb,
letterboxd, mal, plex, radarr, reciperr, sonarr, tautulli, tmdb, trakt,
tvdb, mdblist, util
  File "/mnt/3rd/Plex-Meta-Manager/modules/plex.py", line 11, in <module>
    from plexapi.library import Role, FilterChoice
ImportError: cannot import name 'Role' from 'plexapi.library'
(/usr/local/lib/python3.8/dist

**Comment by chazlarson** [comment]
That seems like you haven't installed the requirements, or they're out of date.

**Comment by BamaSlymm** [comment]
And I thought I did because its run before. I'll try to reinstall
everything. Thank you.

**Comment by chazlarson** [comment]
When you installed them before, was it in a virtual environment [as the walkthrough does]?  If so make sure that virtual environment has been activated.
