### ISSUE TITLE
Only rating#: audience works for tv shows and anime. Critic and user does not show up regardless of source

### ISSUE THREAD

**Issue by ShanaryS** [Kometa-Team/Kometa#1212]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

On movies they all show up, but with anime movies, anime series, and tv shows, only the source with rating#: auidience will be overlayed.

### Relevant Collection/Overlay/Playlist Definition

pmm: rating

### Logs

https://gist.github.com/ShanaryS/8467f18f2bf1e6ff358ee95679fcb7c4

**Comment by ShanaryS** [comment]
Just did more testing and mal is working, all rating providers do. However they all ONLY work as rating#: audience. critic and user does not show up for anime. Both anime movies and anime series. It also doesn't show up for tv shows.

Only movies seem to support all three rating#?

Edit:
I noticed a second rating shows up for regular show, but that is in the imdb top250. So that may have something to do with it.

**Comment by meisnate12** [comment]
youre not actually telling pmm to pull in any ratings. Youre just telling it to overlay with a specific logo from a specific plex attribute. You need to run the corresponding library operations to actually update those ratings to have values [Wiki Page](https://metamanager.wiki/en/latest/config/operations.html#mass-rating-update)
