### ISSUE TITLE
Why today i always error with Time Out When Processing Rating

### ISSUE THREAD

**Issue by art1469** [Kometa-Team/Kometa#1216]
### Version Number

1.18 docker

### What branch are you on?

nightly

### Describe the Bug

I have to try many many time but i cannot complete Can u help me?

I try with Unraid and Ubuntu but they error both.

Traceback (most recent call last): |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 449, in _make_request |
| six.raise_from(e, None) |
| File "", line 3, in raise_from |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 444, in _make_request |
| httplib_response = conn.getresponse() |
| File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse |
| response.begin() |
| File "/usr/local/lib/python3.10/http/client.py", line 318, in begin |
| version, status, reason = self._read_status() |
| File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status |
| line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") |
| File "/usr/local/lib/python3.10/socket.py", line 705, in readinto |
| return self._sock.recv_into(b) |
| TimeoutError: timed out |
| |
| During handling of the above exception, another exception occurred: |
| |
| Traceback (most recent call last): |
| File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 48 9, in send |
| resp = conn.urlopen( |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 787, in urlopen |
| retries = retries.increment( |
| File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 5 50, in increment |
| raise six.reraise(type(error), error, _stacktrace) |
| File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise |
| raise value |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 703, in urlopen |
| httplib_response = self._make_request( |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 451, in _make_request |
| self._raise_timeout(err=e, url=url, timeout_value=read_timeout) |
| File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", li ne 340, in _raise_timeout |
| raise ReadTimeoutError( |
| urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(redacted): Read timed out. (read timeout=60) |
| |
| During handling of the above exception, another exception occurred: |
| |
| Traceback (most recent call last): |
| File "//plex_meta_manager.py", line 552, in run_libraries |
| run_operations_and_overlays() |
| File "//plex_meta_manager.py", line 515, in run_operations_and_overlays |
| library_status[library.name]["Library Operations"] = library.Operations.ru n_operations() |
| File "/modules/operations.py", line 457, in run_operations |
| item.saveEdits() |
| File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 612, in saveEdits |
| return self.reload() |
| File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 367, in reload |
| return self._reload(key=key, **kwargs) |
| File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 376, in _reload |
| data = self._server.query(key) |
| File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 697, in query |
| response = method(url, headers=headers, timeout=timeout, **kwargs) |
| File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 60 0, in get |
| return self.request("GET", url, **kwargs) |
| File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 58 7, in request |
| resp = self.send(prep, **send_kwargs) |
| File "//plex_meta_manager.py", line 142, in new_send |
| return old_send(*send_args, **kwargs) |
| File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 70 1, in send |
| r = adapter.send(request, **kwargs) |
| File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 57 8, in send |
| raise ReadTimeout(e, request=request) |
| requests.exceptions.ReadTimeout: HTTPConnectionPool(redacted): Read timed out. (read timeout=60) |
| |
| HTTPConnectionPool(redacted): Read timed out. (read timeout=60)

### Logs

https://gist.github.com/art1469/0836984af6102508e2ac8c9d4c5fe7fc

**Comment by meisnate12** [comment]
increase you timeout in your config to greater then 60 pmm is asking plex to do something and plex is just taking its time nothing pmm can do but wait longer

**Comment by art1469** [comment]
Thx.
