### ISSUE TITLE
4:3 thumbnails get stretched when overlays applied

### ISSUE THREAD

**Issue by andres-asm** [Kometa-Team/Kometa#1232]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

I have been noticing some of my thumbs (I generate thumbs with a script) are stretched now since using PMM
![image](https://user-images.githubusercontent.com/1721040/208001543-00953fdf-699b-4215-9e6c-00e0bc22e323.png)

Plex does an aspect ration style crop, but PMM seems to just stretch it to 16:9 and apply the overlays

Original thumb example for reference ![image](https://user-images.githubusercontent.com/1721040/208001732-bb913652-2eae-47bf-9bca-f9ad819228b8.png)

### Logs

NA

**Comment by meisnate12** [comment]
not really a bug but more of just how pmm is programmed you can open a Feature Request to get this added
