### ISSUE TITLE
Webhooks for deletion of collections is not working

### ISSUE THREAD

**Issue by tssgery** [Kometa-Team/Kometa#1247]
### Version Number

1.18.1-develop4

### What branch are you on?

develop

### Describe the Bug

I've configured PMM to send webhooks to a service that just dumps the payloads. I see all of the webhook information documented at https://metamanager.wiki/en/latest/config/webhooks.html but I never receive webhook calls when PMM deletes channels ( I never receive a change notification with deleted=True although I do see PMM deleted the channels). I am testing with the holiday collection configuration at `https://raw.githubusercontent.com/tssgery/plex-posters/main/config/movies/holiday.yml`

I should also add that I don't see the delete of collections going to notifiarr either. Maybe I am wrong in thinking that a webhook will be sent if a collection is deleted

### Logs

https://gist.github.com/tssgery/59a2075922fbdc5939f785f0c23bc072

**Comment by tssgery** [comment]
I see that the webhook for deletions is added in https://github.com/meisnate12/Plex-Meta-Manager/commit/f2efa8cfd7e290151977f65f27c244817f3d83e0, but I do not see the name of the collection being deleted, only the server_name, library_name, and a message

**Comment by meisnate12** [comment]
the name is in the message

**Comment by tssgery** [comment]
I tried to test this out but get an exception when processing deleted collections. I attempted to send notifications via notifiarr. I've attached the meta.log, the exception looks like:

> [2022-12-29 15:27:22,429] [builder.py:233]            [INFO]     |============================ Validating Thanksgiving Movies Attributes =============================|
> [2022-12-29 15:27:22,590] [builder.py:473]            [DEBUG]    |                                                                                                    |
> [2022-12-29 15:27:22,590] [builder.py:474]            [DEBUG]    | Validating Method: smart_label                                                                     |
> [2022-12-29 15:27:22,590] [builder.py:479]            [DEBUG]    | Value: title.asc                                                                                   |
> [2022-12-29 15:27:22,595] [builder.py:500]            [DEBUG]    |                                                                                                    |
> [2022-12-29 15:27:22,596] [builder.py:501]            [DEBUG]    | Validating Method: delete_not_scheduled                                                            |
> [2022-12-29 15:27:22,596] [builder.py:502]            [DEBUG]    | Value: True                                                                                        |
> [2022-12-29 15:27:22,596] [builder.py:506]            [DEBUG]    |                                                                                                    |
> [2022-12-29 15:27:22,596] [builder.py:507]            [DEBUG]    | Validating Method: schedule                                                                        |
> [2022-12-29 15:27:22,596] [builder.py:511]            [DEBUG]    | Value: range(11/01-11/30)                                                                          |
> [2022-12-29 15:27:22,785] [builder.py:527]            [INFO]     | Collection Thanksgiving Movies deleted                                                             |
> [2022-12-29 15:27:22,786] [plex_meta_manager.py:725]  [INFO]     |                                                                                                    |
>                                                                  | Scheduled between November 1st and November 30th                                                   |
>                                                                  |                                                                                                    |
>                                                                  | Collection Thanksgiving Movies not scheduled to run and was deleted                                |
> [2022-12-29 15:27:24,332] [plex_meta_manager.py:565]  [DEBUG]    | Traceback (most recent call last):                                                                 |
>                                                                  |   File "//plex_meta_manager.py", line 604, in run_collection                                       |
>                                                                  |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
>                                                                  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
>                                                                  |   File "/modules/builder.py", line 532, in __init__                                                |
>                                                                  |     raise NotScheduled(f"{err}\n\n{self.Type} {self.name} not scheduled to run{suffix}")           |
>                                                                  | modules.util.NotScheduled:                                                                         |
>                                                                  | Scheduled between November 1st and November 30th                                                   |
>                                                                  |                                                                                                    |
>                                                                  | Collection Thanksgiving Movies not scheduled to run and was deleted                                |
>                                                                  |                                                                                                    |
>                                                                  | During handling of the above exception, another exception occurred:                                |
>                                                                  |                                                                                                    |
>                                                                  | Traceback (most recent call last):                                                                 |
>                                                                  |   File "//plex_meta_manager.py", line 555, in run_libraries                                        |
>                                                                  |     run_collection(config, library, metadata, collections_to_run)                                  |
>                                                                  |   File "//plex_meta_manager.py", line 727, in run_collection                                       |
>                                                                  |     library.notify_delete(e)                                                                       |
>                                                                  |   File "/modules/plex.py", line 481, in notify_delete                                              |
>                                                                  |     self.config.notify_delete(message, server=self.PlexServer.friendlyName, library=self.name)     |
>                                                                  |   File "/modules/config.py", line 991, in notify_delete                                            |
>                                                                  |     self.Webhooks.delete_webhooks(message, server=server, library=library)                         |
>                                                                  | TypeError: 'list' object is not callable                                                           |
>                                                                  |                                                                                                    |
> [2022-12-29 15:27:24,336] [plex_meta_manager.py:566]  [CRITICAL] | 'list' object is not callable                                                                      |
> [2022-12-29 15:27:24,337] [plex_meta_manager.py:292]  [INFO]     |                                                                                                    |


[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/10322182/meta.log)

**Comment by meisnate12** [comment]
this was fixed in today's nightly
