### ISSUE TITLE
Season overlays have issues when a series does not have specified season posters

### ISSUE THREAD

**Issue by muddro1** [Kometa-Team/Kometa#1251]
### Version Number

1.18.1

### What branch are you on?

master

### Describe the Bug

As a preface, there are some shows that do not have a season poster for whatever reason. Plex defaults by using the main show poster for the seasons when this is the case. The problem is, after applying overlays, the seasons now have all the overlays that were placed on the main show poster. This is undesirable in cases where people do not want any overlays on season posters, or where it varies from the main show. Not sure if there is a check that can be built into PMM so that if a show has seasons which don't have their own posters, a copy of the original main poster will be placed in there, and then the normal process would proceed.

**Comment by meisnate12** [comment]
fallback to the show poster has been added to nightly
