### ISSUE TITLE
[Defaults]: imdb_watchlist:

### ISSUE THREAD

**Issue by Umholzer** [Kometa-Team/Kometa#1254]
### Link to File

https://metamanager.wiki/en/latest/metadata/builders/imdb.html#imdb-watchlist

### Version Number

Version: 1.18.1-develop4 (Docker) 

### What branch are you on?

develop

### Describe the Bug

log says: "| Collection Error: No builders were found |"

example with used watchlist:

collections:
  My Watch Watchlist:
    imdb_watchlist: ur160261859
    collection_order: custom
    sync_mode: sync

**Comment by meisnate12** [comment]
are you still having this issue on 1.18.3 and if so can you please post a log

**Comment by Umholzer** [comment]
Its working. Many thanks for your good work
