### ISSUE TITLE
[Defaults]: Ribbon

### ISSUE THREAD

**Issue by stevenffrench** [Kometa-Team/Kometa#1274]
### Link to File

https://stevenfrench-my.sharepoint.com/:u:/p/steven/Edhy8x2vkQNOs6EB3AaZdHMBwTlkhkDtF78GpJZbMpn0FA?e=dmssiX

### Version Number

1.18.2 (Docker)

### What branch are you on?

master

### Describe the Bug

When I try to use the [ribbon](https://metamanager.wiki/en/latest/defaults/overlays/ribbon.html) default overlay with either Movies or TV shows it doesn't even attempt to load.  Additionally, if I try to directly link to the relevant GIT file(s), they cannot be found.

Log with ribbon default overlay [here](https://stevenfrench-my.sharepoint.com/:u:/p/steven/Edhy8x2vkQNOs6EB3AaZdHMBwTlkhkDtF78GpJZbMpn0FA?e=dmssiX).
Log with git direct call [here](https://stevenfrench-my.sharepoint.com/:u:/p/steven/EcfBmf9lurRLohNv43ImSOEBPvMJkq03-e5AdotaJArPRQ?e=Hg5LCc).

**Comment by meisnate12** [comment]
you have `ppm: ribbon` its `pmm`
