### ISSUE TITLE
TMDb Attributes - region

### ISSUE THREAD

**Issue by Kevin2kkelly** [Kometa-Team/Kometa#1277]
### What is the improvement or update to the Wiki you wish to see?

The wiki example for a tmdb mapping uses the uppercase value "US" for region which is an invalid input. It looks like the valid input would be the lowercase "us" based on the result from PMM:

Config Warning: tmdb sub-attribute region: US is an invalid input using None as default
|     ad (Andorra)
|     ae (United Arab Emirates)
|     af (Afghanistan)
|     ag (Antigua and Barbuda)
|     ai (Anguilla)
|     al (Albania)
etc...

I would suggest updating the example and perhaps adding a note in the "Allowed Values" field of the table for the region row to state that the input should be lowercase.

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/config/tmdb.html

**Comment by meisnate12** [comment]
fixed in nightly
