### ISSUE TITLE
[Docs]: Update Synology Walkthrough to reflect DSM 7

### ISSUE THREAD

**Issue by BigCheeze45** [Kometa-Team/Kometa#1286]
### What is the improvement or update to the Wiki you wish to see?

Synology walkthrough is out of date if running DSM 7.1 or later. The container creation workflow in this version has changed and doesn't line up with the guide.

For example, the Advanced Settings dialog doesn't show all options (e.g. Environment, Volume). This has been broken down into separate steps:

### DSM 7.1 Advanced Settings
<img width="676" alt="Screen Shot 2023-01-25 at 11 41 50 PM" src="https://user-images.githubusercontent.com/6273184/214760054-e07f2943-f9ed-4f20-954a-c413d3e5148a.png">

### DSM 7.1 Volume Settings
<img width="618" alt="Screen Shot 2023-01-25 at 11 43 44 PM" src="https://user-images.githubusercontent.com/6273184/214760342-4fb60b9e-6015-4bb8-9304-f96dd3384f56.png">

More than happy to submit a PR with these changes.

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/home/guides/synology.html

**Comment by YozoraXCII** [comment]
I don't use Synology personally, can you advise if the nightly docs images are still out of date?

https://metamanager.wiki/en/nightly/home/guides/synology.html

If they are, I would be grateful if you could reproduce each image and then either submit a PR or drop the images here for someone to update.

**Comment by BigCheeze45** [comment]
The nightly doc images are also out of date. I'll submit a PR. Which branch should I target (e.g. master, nightly, develop)?

**Comment by YozoraXCII** [comment]
All PR's go to nightly :)
