### ISSUE TITLE
Add information about the content of the examples.

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#1299]
### What is the improvement or update to the Wiki you wish to see?

Hi,

the Wiki is great and has many examples, which are needed by noobs like me!

Some wiki-pages have a helpful explanation, what those examples are about, but unfortunately, many have not.

The context is not always helpful enough to understand or find specific examples.

Here is an example of that I mean:
(taken from https://metamanager.wiki/en/latest/metadata/details/schedule.html)

"Below is an example of a scheduled collection:"

Well, all examples on this page are about a scheduled collection. So what does this example fulfill in particular?

Its not stated. (You have to fully understand the example first, but if you can not, then you're lost)

So users with experience or gurus have no problem to understand the example,
but noobs can not know, what this example is about.
Its likewise with little children. You should not teach them something new from an expert perspective, they don't know or understand. 
You need to support them by explaining it for a child. Because this is what they are. No experts, but childs.

So, a more descriptive text, because it helps us to understand the example, could be:

"Below is an example of a scheduled collection which runs monthly on the first and fifteenth day of the month:"

or at least:

"Below is an example of a scheduled collection (run on 1st and 15th day each month):"

I'm not telling to change all examples preambles to exhausted texts, but just a little description, what are those examples are trying to accomplish for the users.

Also, it will give the wiki search more exact words, which could help to locate the right spot to search for help.

Thank you.

And let me repeat: The wiki is great and very clearly arranged!

**Comment by YozoraXCII** [comment]
I have submitted a PR to update this page.

You can preview my changes here: https://github.com/meisnate12/Plex-Meta-Manager/blob/06431d7afe6572465cac66b7d66b48c67aacb211/docs/metadata/details/schedule.md
