### ISSUE TITLE
Obsolete command in Windows Local Walkthrough

### ISSUE THREAD

**Issue by kiwichick888** [Kometa-Team/Kometa#1310]
### What is the improvement or update to the Wiki you wish to see?

Please update the Windows Local Walkthrough to reflect that the 3 is no longer required for python3 --version. This threw an error for me in PowerShell saying Python was not found. The solution was enter python --version instead.

https://metamanager.wiki/en/latest/home/guides/local.html

**Comment by chazlarson** [comment]
Depending on the version of Windows [and maybe the version os Python] it might be.  It was required under Windows 10 when I wrote that.  I've added some notes suggesting that if `python3` doesn't work, you should try `python` before installing going through the python install.

**Comment by kiwichick888** [comment]
> Depending on the version of Windows [and maybe the version os Python] it might be. It was required under Windows 10 when I wrote that. I've added some notes suggesting that if `python3` doesn't work, you should try `python` before installing going through the python install.

Thank you :-)
