### ISSUE TITLE
[Defaults]: Star Trek timeline playlist is missing 4 episodes

### ISSUE THREAD

**Issue by cplieger** [Kometa-Team/Kometa#1314]
### Link to File

https://trakt.tv/users/pedrohcramos/lists/star-trek-timeline

### Version Number

18.3

### What branch are you on?

master

### Describe the Bug

The star trek timeline playlist seems to be missing Star Trek Enterprise episodes 4, 5, and 6. They are missing from the trakt list.
https://trakt.tv/users/pedrohcramos/lists/star-trek-timeline

**Comment by cplieger** [comment]
I propose this playlist as a replacement: https://trakt.tv/users/username57/lists/star-trek-prime-canon-timeline
2x the items, updated recently.

**Comment by YozoraXCII** [comment]
This has been changed in the nightly build and will be released with the next release of PMM
