### ISSUE TITLE
Example config error for video format

### ISSUE THREAD

**Issue by TheLidlMan** [Kometa-Team/Kometa#1320]
### What is the improvement or update to the Wiki you wish to see?

On this page it has an error under the config it says in the TV section of it to use audio_codec rather than video_format

![image](https://user-images.githubusercontent.com/75203773/219961160-94dcfebe-2d60-40b5-959e-29f985f13382.png)

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/defaults/overlays/video_format.html

**Comment by YozoraXCII** [comment]
This has already been fixed in the nightly docs and the fix will be pushed with the next release of PMM.

https://metamanager.wiki/en/nightly/defaults/overlays/video_format.html
