### ISSUE TITLE
KeyError: 'movie'   in trakt_trending

### ISSUE THREAD

**Issue by vaparr** [Kometa-Team/Kometa#133]
Running the latest develop.. this used to work:

    Trending:
        sort_title: "*110"
        **trakt_trending: 20**
        tmdb_trending_weekly: 50
        sync_mode: sync
        trakt_list:
          - https://trakt.tv/users/giladg/lists/top-10-movies-of-the-week?sort=added,asc
        filters:
          original_language: en

|====================================================================================================|
|                                        Trending Collection                                         |
|====================================================================================================|
|                                                                                                    |
| Scanning Trending Collection                                                                       |
|                                                                                                    |
| Method: sort_title                                                                                 |
| Value: *110                                                                                        |
|                                                                                                    |
| Method: trakt_trending                                                                             |
| Value: 20                                                                                          |
|                                                                                                    |
| Method: tmdb_trending_weekly                                                                       |
| Value: 50                                                                                          |
|                                                                                                    |
| Method: sync_mode                                                                                  |
| Value: sync                                                                                        |
|                                                                                                    |
| Method: trakt_list                                                                                 |
| Value: ['https://trakt.tv/users/giladg/lists/top-10-movies-of-the-week?sort=added,asc']            |
|                                                                                                    |
| Method: filters                                                                                    |
| Value: ordereddict([('original_language', 'en')])                                                  |
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Collection Filter original_language: ['en']                                                        |
|                                                                                                    |
| Method: trakt_trending                                                                             |
| Values: [20]                                                                                       |
|                                                                                                    |
| Value: 20                                                                                          |
| Data: 20                                                                                           |
| Traceback (most recent call last):                                                                 |
|   File "/modules/config.py", line 462, in update_libraries                                         |
|     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)      |
|   File "/modules/builder.py", line 765, in run_methods                                             |
|     elif "trakt" in method:                             items_found += check_map(self.config.Trakt.get_items(method, value, self.library.is_movie)) |
|   File "/modules/trakttv.py", line 151, in get_items                                               |
|     movie_ids, show_ids = self.get_pagenation(method[6:], data, is_movie)                          |
|   File "/modules/trakttv.py", line 118, in get_pagenation                                          |
|     elif is_movie:                              return [item["movie"]["ids"]["tmdb"] for item in items], [] |
|   File "/modules/trakttv.py", line 118, in <listcomp>                                              |
|     elif is_movie:                              return [item["movie"]["ids"]["tmdb"] for item in items], [] |
| KeyError: 'movie'                                                                                  |
|                                                                                                    |
| Unknown Error: 'movie'

**Comment by meisnate12** [comment]
ok fix should be in develop

**Comment by vaparr** [comment]
looks good, thanks

**Comment by meisnate12** [comment]
leaving open until pushed to master
