### ISSUE TITLE
[Docs]: Library Operations

### ISSUE THREAD

**Issue by tigerkzr** [Kometa-Team/Kometa#1336]
### What is the improvement or update to the Wiki you wish to see?

the attribute for "Mass Originally Available Update" is "mass_original_title_update".  I don't know what it's supposed to be but I did not think it was supposed to be the same as "Mass Original Title Update"

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/config/operations.html#mass-originally-available-update

**Comment by chazlarson** [comment]
FIxed in nightly wiki.
