### ISSUE TITLE
file_background returning unknown error

### ISSUE THREAD

**Issue by vitadome** [Kometa-Team/Kometa#135]
I was able to update file poster but file background keeps returning an unkown error.  Below I have included the error, the path to my image and a snippet from my shows.yml.  Any insight is appreciated.

### **ERROR MESSAGE**
Unknown Error: (406) not_acceptable; http://xx.x.xx.xxx:42405/library/metadata/557322/arts?url=C%3A%5C_pmm%5Cconfig%5Cassets%5Cshows%5CHBOMax%5Cbg_HBOMax.jpg <html><head><title>Not Acceptable</title></head><body><h1>406 Not Acceptable</h1></body></html>

### **IMAGE PATH**
C:\_pmm\config\assets\shows\HBOMax\bg_HBOMax.jpg

### **SHOWS.YML**
    HBO Max:
        tmdb_network: https://www.themoviedb.org/network/3186
        sync_mode: sync
        collection_mode: default
        collection_order: alpha
        sort_title: "*302"
        file_poster: C:/_pmm/config/assets/shows/HBOMax/HBOMax.jpg
        file_background: C:/_pmm/config/assets/shows/HBOMax/bg_HBOMax.jpg

**Comment by meisnate12** [comment]
ok im getting the same error so ill look into it when I get some time later today for now just add `C:/_pmm/config/assets/shows` as an asset directory in the config.yml and then do a couple of renames
* Rename `HBOMax` folder to `HBO Max` (to match the collection name)
* Rename `HBOMax.jpg` file to `poster.jpg`
* Rename `bg_HBOMax.jpg` file to `background.jpg`

and then just take out `file_poster` and `file_background` from the config and then see if that works

**Comment by meisnate12** [comment]
figured out what was happening and pushed a fix to develop for `file_background`
