### ISSUE TITLE
PMM never finishes

### ISSUE THREAD

**Issue by dube920** [Kometa-Team/Kometa#1364]
### Version Number

1.18.3 (Docker) 

### What branch are you on?

master

### Describe the Bug

PMM seems to start and run just fine, except it never finishes. I see no error in the logs, it just sort of stops running and never finishes.
Same thing happens when running manually, it kicks off fine and runs as expected for awhile before just stalling out and never finishing.

### Logs

https://gist.github.com/dube920/0f49ed94bb75f767ebb8d02cf9df9df4

**Comment by dube920** [comment]
Also posted in the Discord, someone suggested switching to the Nightly build. Gave that a go and it's running longer than it was before, will let it go overnight and see if that did the trick.

**Comment by dube920** [comment]
Switching to the nightly build seems to have solved the problem! It completed successfully this morning.

**Comment by YozoraXCII** [comment]
Hi @dube920, just so you're aware we will be pushing a 1.19 release to the master branch imminently. Once you see that pushed we recommend you move back onto the master branch for stability.

Thanks,

**Comment by dube920** [comment]
> Hi @dube920, just so you're aware we will be pushing a 1.19 release to the master branch imminently. Once you see that pushed we recommend you move back onto the master branch for stability.
> 
> Thanks,

Definitely more comfortable being on Master branch, so will do! Thank you for the heads up :)
