### ISSUE TITLE
Folder "logs" can not be created, if a symlink with same name exists.

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#1367]
### Version Number

1.18.3-nightly170 (Docker) 

### What branch are you on?

nightly

### Describe the Bug

Coming from here: https://github.com/meisnate12/Plex-Meta-Manager/discussions/1350

I'm not sure, this is really a bug, but -to be honest- I would like to have a nicer handling. So let me explain:

I'm trying to "move" the PMM `logs` folder to `/tmp` because they don't need to be permanent IMHO.

I stopped the container, deleted the old `logs` folder, created a symlink, restarted the container and started PMM:
```
root@UnRaid:~# docker exec -it pmm python plex_meta_manager.py --run -c config/config.yml --no-missing -is
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 129, in <module>
    logger = MyLogger("Plex Meta Manager", default_dir, screen_width, divider[0], ignore_ghost, test or debug, trace)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/logs.py", line 53, in __init__
    os.makedirs(self.log_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/config/logs'
```

I guess, the message tells me, that PMM can not create its `logs` folder, because something (the symlink?) is in the way.

There is a workaround, to tell the docker container config to use that `/tmp` path directly, like `-v '/tmp/pmm.logs/':'/config/logs':'rw'` , and then create a symlink, say `logs2` which points to `/tmp/pmm.logs` , but PMM still creates its own `logs` folder. 
So there is an empty `logs` folder and the user needs to use the symlinked `logs2`. 
Not exactly nice/transparent.

So my request would be: 
Can we have the option to let PMM use the symlink instead of quitting with an error?

Thank you.

**Comment by chazlarson** [comment]
Is this only a problem when running in docker, or does the native run also show it?  Is this perhaps a docker-specific thing unrelated to PMM?

**Comment by gitttt54** [comment]
> Is this only a problem when running in docker, or does the native run also show it? Is this perhaps a docker-specific thing unrelated to PMM?

I have no idea, but I would be happy to test this, IF I knew how...

(I only got PMM installed via the unraid "docker manager" and can't see how to run it native)

**Comment by meisnate12** [comment]
@gitttt54 is this still an issue?

**Comment by gitttt54** [comment]
> @gitttt54 is this still an issue?

Unfortunately, yes, there is no difference since my initial post:

I just reproduced it via:

> I stopped the container, deleted the old logs folder, created a symlink, restarted the container and started PMM:

```
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 168, in <module>
    logger = MyLogger("Plex Meta Manager", default_dir, run_args["width"], run_args["divider"][0], run_args["ignore-ghost"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/logs.py", line 54, in __init__
    os.makedirs(self.log_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/config/logs'
```

I reverted the changes (removed link and created a log folder) and it worked flawlessly.

**Comment by mrdynamo** [comment]
I noticed that you are using pmm.logs as the folder for symlink. Perhaps PMM is seeing the .logs and thinks it's a file rather than directory, causing the error?

Do you have any change in behavior if you use '/tmp/pmm/logs'?

**Comment by meisnate12** [comment]
@gitttt54 can you test with the latest nightly i think i figured out a fix

**Comment by gitttt54** [comment]
> @gitttt54 can you test with the latest nightly i think i figured out a fix

atm, I can‘t test. It‘ll take a month at least I think. 
I‘ll reply again, when test is done. 

EDIT: works great! thank you!

EDIT EDIT: 

it runs smoothy, with this:

`docker exec -it kometa python kometa.py -r -c /config/config_WL.yml`

**but not with this:**
`docker run --rm -v /mnt/user/appdata/kometa:/config --name kometa kometateam/kometa:latest python kometa.py --run -c /config/config_WL.yml`
```
Traceback (most recent call last):
  File "//kometa.py", line 200, in <module>
    logger = MyLogger("Kometa", default_dir, run_args["width"], run_args["divider"][0], run_args["ignore-ghost"],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/logs.py", line 55, in __init__
    os.makedirs(self.log_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/config/logs'
```

Dunno, what the problem is here...
