### ISSUE TITLE
Encode Character Error

### ISSUE THREAD

**Issue by b101marc** [Kometa-Team/Kometa#137]
Getting the following when running on linux via CLI. Hits when the scripts gets to "Matching Movies"

`'latin-1' codec can't encode character '\u0103' in position 28: ordinal not in range(256) `

**Comment by b101marc** [comment]
Got a little bit further on the develop branch. 

```
| Mapping Movie Library: Movies                                                                      |
| Cache | + | plex://movie/5d77686a3ab0e7001f500a54          | 37087  | tt0042176  | None   | None  | None  | 711 Ocean Drive |
| Traceback (most recent call last):                                                                 |
|   File "plex_meta_manager.py", line 106, in start                                                  |
|     config.update_libraries(is_test, collections)                                                  |
|   File "/opt/appdata/Plex-Meta-Manager/modules/config.py", line 397, in update_libraries           |
|     movie_map, show_map = self.map_guids(library)                                                  |
|   File "/opt/appdata/Plex-Meta-Manager/modules/config.py", line 652, in map_guids                  |
|     length = util.print_return(length, f"Processing: {i}/{len(items)} {item.title}")               |
|   File "/opt/appdata/Plex-Meta-Manager/modules/util.py", line 795, in print_return                 |
|     print(adjust_space(length, f"| {text}"), end="\r")                                             |
| UnicodeEncodeError: 'latin-1' codec can't encode character '\u0103' in position 28: ordinal not in range(256) |
|                                                                                                    |
| 'latin-1' codec can't encode character '\u0103' in position 28: ordinal not in range(256)          |
```

**Comment by meisnate12** [comment]
do you know the title of the movie that is failing it would probably be alphabetically after 711 Ocean Drive

**Comment by b101marc** [comment]
I was able to figure out it was a movie with the special character ã. It would end on any movie it found with a special character. I was able to change the name of movie and it runs now, and made some other adjustments to hopefully correct. Seems to have been on my end.

**Comment by meisnate12** [comment]
i still want to try and have it work with special characters. lemme see if I can force the error

**Comment by meisnate12** [comment]
the plex UI  wont even let me copy that character into a movie title lol

**Comment by b101marc** [comment]
haha! Unfortunately I've gone and adjusted them all but I'll let you know if another one imports. Seemed to happen primarily with Romanian language films, as it wasn't always just the character above.

**Comment by meisnate12** [comment]
i guess ill just close this then if anyone has this error reopen this and let me know
