### ISSUE TITLE
[Docs]: Wrong default value for starting attribute in "Year" collections

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1378]
### What is the improvement or update to the Wiki you wish to see?

In this table, the default of `current_year-5` is wrong. After testing in my library, the default seems to be `current_year-10`

<table class="clearTable"><tr><th>Attribute</th><th>Description & Values</th></tr><tr><td><code>starting</code></td><td>Controls the starting year for collections<hr><strong>Default:</strong> current_year-5<hr><strong>Values:</strong> Number greater than 0</td>

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/develop/defaults/both/year.html

**Comment by YozoraXCII** [comment]
PR submitted to resolve

**Comment by Droppisalt** [comment]
Thanks!
