### ISSUE TITLE
GitHub Feature Request Typo

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1380]
### What is the improvement or update to the Wiki you wish to see?

Not a wiki issue, it's on GitHub. Typo here, or maybe intended lol who am I to judge:

![image](https://user-images.githubusercontent.com/67336980/231918508-302fd4c8-1e62-4d2a-9355-edcbc15841f5.png)

### Does the docs page already exist? Please link to it.

https://github.com/meisnate12/Plex-Meta-Manager/issues/new/choose

**Comment by YozoraXCII** [comment]
Only @meisnate12 can resolve this one, hopefully will get done soon.

**Comment by meisnate12** [comment]
lies anyone can https://github.com/meisnate12/Plex-Meta-Manager/blob/master/.github/ISSUE_TEMPLATE/config.yml
