### ISSUE TITLE
Discord invite link is dead?

### ISSUE THREAD

**Issue by karl0ss** [Kometa-Team/Kometa#1428]
### What is the improvement or update to the Wiki you wish to see?

The current link for the discord invite - https://discord.gg/NfH6mGFuAB - seems to be dead and give an invalid invite link, can we possibly get a new one please?

Thanks

**Comment by YozoraXCII** [comment]
Apologies, https://discord.gg/plexmetamanager

I've tested the link you used and it seems to be working for me

**Comment by karl0ss** [comment]
Can confirm both links worked fine on my phone, but both said invalid when I tried via my laptop (and I do have discord installed)

All good, thank you for your response.
