### ISSUE TITLE
Typo for IMDB

### ISSUE THREAD

**Issue by kevbentz** [Kometa-Team/Kometa#1435]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

In configuration file I have:

  - pmm: imdb

This causes PMM to try to load the default imdb.yml file but I get this error:

File Error: Default does not exist imbd.yml 

Notice the spelling of the file in the error.  Changing the default imdb.yml file to imbd.yml causes the file to load properly and the error goes away.

**Comment by meisnate12** [comment]
@kevbentz are you still having this issue if so can you post a log

**Comment by kevbentz** [comment]
> @kevbentz are you still having this issue if so can you post a log

I

**Comment by kevbentz** [comment]
I think I was the one with the spelling mistake.  My workaround worked, but turns out I had imdb mispelled in the config file so it was looking for a file that wasn't there until I renamed it to my incorrect spelling.

Sorry!
