### ISSUE TITLE
alway get FlixPatrol Error:  failed to parse

### ISSUE THREAD

**Issue by xcybermanx** [Kometa-Team/Kometa#1445]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

hello i make top10.yml with this content :
```
collections:
  Top 20 mensuel de Netflix aux Etats-Unis:
    flixpatrol_top:
      platform: netflix
      location: united_states
      time_window: this_month
      limit: 20
    collection_order: custom
    sync_mode: sync
```

but in log alway i have this message : 

Top 20 mensuel de Netflix aux Etats-Unis |     0 |     0 |     0 |  0:00:00 | PMM Failure          |
| FlixPatrol Error: https://flixpatrol.com/top10/netflix/united-states/2023-04/full/ failed to parse

i have change time_window to year week days but not sucess

Thank You

### Logs

[2023-05-23 11:27:13,428] [builder.py:890]            [DEBUG]    | Validating Method: flixpatrol_top                                                                  |
[2023-05-23 11:27:13,428] [builder.py:891]            [DEBUG]    | Value: ordereddict([('platform', 'netflix'), ('location', 'united_states'), ('time_window', 'last_month'), ('limit', 20)]) |
[2023-05-23 11:27:13,625] [flixpatrol.py:62]          [INFO]     | []                                                                                                 |
[2023-05-23 11:27:13,703] [flixpatrol.py:68]          [INFO]     | []                                                                                                 |
[2023-05-23 11:27:13,709] [plex_meta_manager.py:827]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 691, in run_collection                                       |
                                                                 |     builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
                                                                 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/builder.py", line 958, in __init__                                                |
                                                                 |     self._flixpatrol(method_name, method_data)                                                     |
                                                                 |   File "/modules/builder.py", line 1401, in _flixpatrol                                            |
                                                                 |     if self.config.FlixPatrol.validate_flixpatrol_dict(method_name, data, self.language, self.library.is_movie): |
                                                                 |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/flixpatrol.py", line 90, in validate_flixpatrol_dict                              |
                                                                 |     return len(self.validate_flixpatrol_lists(self.get_url(method, data, is_movie), language, is_movie)) > 0 |
                                                                 |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |
                                                                 |   File "/modules/flixpatrol.py", line 86, in validate_flixpatrol_lists                             |
                                                                 |     raise Failed(f"FlixPatrol Error: {list_url} failed to parse")                                  |
                                                                 | modules.util.Failed: FlixPatrol Error: https://flixpatrol.com/top10/netflix/united-states/2023-04/full/ failed to parse |
                                                                 |                                                                                                    |
[2023-05-23 11:27:13,710] [plex_meta_manager.py:828]  [ERROR]    | FlixPatrol Error: https://flixpatrol.com/top10/netflix/united-states/2023-04/full/ failed to parse |
[2023-05-23 11:27:13,710] [plex_meta_manager.py:839]  [INFO]     |                                                                                                    |

**Comment by Tibbar-Retep** [comment]
Can confirm the same "FlixPatrol Error's" on netflix/disney/hbo/hulu/paramount-plus/amazon-prime/apple-tv Flixpatrol  failed to parse

**Comment by strumswell** [comment]
This issue might be related https://github.com/meisnate12/Plex-Meta-Manager/issues/1217

EDIT: I get an error on this url https://flixpatrol.com/top10/apple-tv/world/2023-020/full/ but it seems pretty full, so not sure if the issue above really applies.

**Comment by GOATpotts** [comment]
Can confirm same issue for overlay / collection configs:
FlixPatrol Error: https://flixpatrol.com/top10/amazon-prime/united-states/2023-05/full/
It errors out on every network for movies and TV.
Time_window changes do not seem to help or location. Making the config default with no template variable doesn't work either.

**Comment by chazlarson** [comment]
A fix for this has been put into the nightly branch.

**Comment by GOATpotts** [comment]
Just ran the nightly build, it works. Thanks.
