### ISSUE TITLE
Trakt User Collection

### ISSUE THREAD

**Issue by AnthonyFaxlandez** [Kometa-Team/Kometa#145]
Add support for pulling your own user’s collection, similar to how the user’s watchlist is currently pulled. 

https://trakt.tv/users/USERNAME/collection

https://trakt.docs.apiary.io/#reference/users/collection

I write this after realizing that the existing `trakt_collected` is not in fact the user collection, and setting the limit to 1000 in order to leave room for my Trakt collection to grow would in fact pull the top 1000 collected shows across all of Trakt. Luckily I had a backup because Sonarr does not have a mass delete feature 😂

**Comment by meisnate12** [comment]
`trakt_collection` has been added in develop if you'd like to test it out
