### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by toonarmy14** [Kometa-Team/Kometa#1472]
### What is the improvement or update to the Wiki you wish to see?

Just need to change "dictionary" to "list" in the description for in-line lists for yaml. 

Current:
> In-Line Lists
>   
>   you can represent a dictionary on a single line by using [ and ]

Expected: 
> In-Line Lists
>   
>   you can represent a list on a single line by using [ and ]

Thanks for everything you do! 

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/home/guides/yaml.html#in-line-lists

**Comment by chazlarson** [comment]
https://github.com/meisnate12/Plex-Meta-Manager/pull/1481
