### ISSUE TITLE
Date regex filter logic appears to be broken

### ISSUE THREAD

**Issue by cjohnk** [Kometa-Team/Kometa#1492]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

It does not appear that this line is ever reachable, which I believe causes date regular expressions to match all items:

https://github.com/meisnate12/Plex-Meta-Manager/blob/3bf1c25990a0eee9e1c907e516795fd8a92b0afb/modules/util.py#L521

jailbreak is set to true at 516, can be updated to true at 519, but nothing ever assigns it a value of false so "if not jailbreak" will never pass.

**Comment by meisnate12** [comment]
wish i had seen this before i released 1.20.0 the fix for this is in the next push

**Comment by cjohnk** [comment]
All good.  I would have actually tried tackling it myself back when I found it, but I never felt confident that I wasn't breaking whatever behavior made that change in the first place.
