### ISSUE TITLE
Install on Qnap

### ISSUE THREAD

**Issue by hakankarakis** [Kometa-Team/Kometa#1493]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

I get this error when I try to run it on qnap_

### Logs

https://gist.github.com/hakankarakis/9e5b4bd466f3234f782b53744522c35a

**Comment by chazlarson** [comment]
That typically indicates that one of the dependencies didn't install or is incompatible with the machine.

Are you using the docker image?

**Comment by hakankarakis** [comment]
> 

yes

**Comment by chazlarson** [comment]
OK so it isn't a missing  or failed-to-install dependency problem.  What specific QNAP is this?  What CPU?

**Comment by hakankarakis** [comment]
QNAP TS431+

**Comment by hakankarakis** [comment]
CPU: Annapurna Labs Alpine AL212 Dual-core ARM Cortex-A15 CPU @ 1.40GHz

**Comment by chazlarson** [comment]
I suspect the ARM CPU is the issue.  You may try running on bare metal to see if lxml can get built for ARM.

**Comment by hakankarakis** [comment]
How do I do that?

**Comment by hakankarakis** [comment]
https://metamanager.wiki/en/latest/home/guides/qnap.html[](url)

**Comment by chazlarson** [comment]
<https://metamanager.wiki/en/latest/home/guides/local.html>

**Comment by chazlarson** [comment]
> [https://metamanager.wiki/en/latest/home/guides/qnap.html[](url)](https://metamanager.wiki/en/latest/home/guides/qnap.html%5B%5D(url))

Note that the QNAP being used on that page has an intel CPU

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/8f468767-2dae-41a4-a3f0-c4cb4d56863c)

**Comment by hakankarakis** [comment]
can you want to connect to my computer and do it?

**Comment by hakankarakis** [comment]
are*

**Comment by hakankarakis** [comment]
please ?

**Comment by chazlarson** [comment]
I'm afraid that's not possible.  This is an inherently technical tool, and installing the python script is the simplest part.  I would suspect that you would be frustrated running it on a low-powered NAS anyways. If you have another more powerful computer you could run it there.

**Comment by hakankarakis** [comment]
Thank you very much anyway.

**Comment by hakankarakis** [comment]
> I'm afraid that's not possible. This is an inherently technical tool, and installing the python script is the simplest part. I would suspect that you would be frustrated running it on a low-powered NAS anyways. If you have another more powerful computer you could run it there.

hi dude ! are you there ?

**Comment by chazlarson** [comment]
You should probably take this up in the Discord; github issues aren't generally intended for open-ended discussion.
