### ISSUE TITLE
Error: 'Config' object has no attribute 'get_movie_show_or_collection'

### ISSUE THREAD

**Issue by calboi91** [Kometa-Team/Kometa#15]
I am getting the error when using `tmdb_background`. The TMDb ID is correct, as it works for other fields that use it. It happens for all collections that have this attribute. 
```
[2021-02-11 07:50:42,840] [util.py:575]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/home9/calboi/Plex-Meta-Manager/modules/config.py", line 564, in update_libraries
                                                                 |     elif method_name == "tmdb_background":                              backgrounds_found.append(("url", "{}{}".format(self.TMDb.image_url, self.get_movie_show_or_collection(util.regex_first_int(collections[c][m], "TMDb ID"), library.is_movie).poster_path), method_name))
                                                                 | AttributeError: 'Config' object has no attribute 'get_movie_show_or_collection'
                                                                 | 
[2021-02-11 07:50:42,840] [config.py:1029]            [ERROR]    | Unknown Error: 'Config' object has no attribute 'get_movie_show_or_collection'
```

Also, is it possible to add collection details from a movie or show? If I have a collection built with `tmdb_collection` using a collection ID, it gives me the following error when I set the `tmdb_poster` using a show ID: `No Movie or Collection found for TMDb ID ###`.

**Comment by meisnate12** [comment]
i got a fix for your issue and it is not currently possible to do that with the ID but you can always just give the collection a direct link to the tmdb poster using `url_poster`

**Comment by calboi91** [comment]
Thanks for the quick fix. 

So it is not possible for `tmdb_summary` and `tmdb_background` too? For background, I can also use a direct link, but for summary, is there another way to link besides copy/pasting the text into the .yml file?

**Comment by meisnate12** [comment]
There is not currently another way other then just copying to text
