### ISSUE TITLE
TMDb connection: Name resolution does not work

### ISSUE THREAD

**Issue by tobi-github** [Kometa-Team/Kometa#1533]
### Version Number

1.19.0 (Docker)

### What branch are you on?

master

### Describe the Bug

When connecting to TMDb the name resolution does not work.
The error occurred in a running configuration for the first time two days ago and occurs continuously. The name resolution on the host system works without problems.

### Logs

https://gist.github.com/tobi-github/3075e1184f24ecf46367f89d5efe7ede

**Comment by chazlarson** [comment]
PMM doesn't handle this itself, this is going to be a problem or misconfiguration in the container setup.

**Comment by tobi-github** [comment]
> PMM doesn't handle this itself, this is going to be a problem or misconfiguration in the container setup.

Makes sense, I should have known. Something was wrong with the container. Now it works again. Thanks a lot!

**Comment by isaacolsen94** [comment]
How did you fix this? I'm also getting this issue

**Comment by tobi-github** [comment]
I simply rebooted the machine and it worked again. I would imagine that a reboot of the Docker image would also do the trick.

**Comment by tobi-github** [comment]
Closed
