### ISSUE TITLE
Sorting Collections holds up Plex (Waited over 10 seconds for busy db)

### ISSUE THREAD

**Issue by blazenelams** [Kometa-Team/Kometa#1540]
### Version Number

1.19

### What branch are you on?

master

### Describe the Bug

A few of my collections get stuck on the step to Sort the collection. When I go to Plex's console, the error message 'waiting for db' and 'the transaction was held too long'. It seems to only move one movie every 10 seconds which takes forever, plus I cannot watch anything on Plex when this is running. 

I have been working to correct a corrupt Plex DB, but why do only a few of my collections perform this sorting step? 
Is there a way to skip this? In my config file for this collection, sorting is set to release. 

I can provide more info, but this causes PMM to run for a very long time (12+ hours), and Plex is unusable in this time. 

In the attached log, I stoped the run, but at the bottom you can see the moving tasks with the timestamps. 

### Logs

https://gist.github.com/blazenelams/2a4a001506e1ae97af832c9dadfa188f

**Comment by YozoraXCII** [comment]
Ultimately PMM is just making API calls, it is Plex that is taking a long time to respond.

We have seen increasing issues of newer PMS servers slowing down API requests, and on of our users raised a ticket with Plex, which you can track here:

https://forums.plex.tv/t/adding-metadata-via-api-takes-way-too-long-with-recent-plex-server-versions/846957

There are some steps you can take to try and reduce the amount of calls made - such as moving to Smart Label collections, which do not require manual sorting.

https://metamanager.wiki/en/latest/metadata/builders/smart.html#smart-label

**Comment by blazenelams** [comment]
Thank you for the quick reply. I went through that Plex forum, and it does seem to describe my issue exactly. 
I will continue to monitor that thread, and maybe try to Downgrade Plex to a previous version. 

Feel free to close this bug, as it is a Plex issue.
