### ISSUE TITLE
Enhancement: Option to resume script execution

### ISSUE THREAD

**Issue by paulmcclellan** [Kometa-Team/Kometa#156]
Sometimes the script doesn't complete successfully (due to a timeout or other issue not related to Plex-Meta-Manager).  Or with a mistake in the metadata file.  As I have a long metadata file, I want to resume, not restart.  

It would be nice to have the option to restart, either from a specific collection, or to be able to rerun by collection type (genre, decade, people, etc.)

**Comment by meisnate12** [comment]
You could run it as tests. Put test: true in the template you want to run and then run the app with the --test flag

I think I could add a resume so look for that soon

**Comment by meisnate12** [comment]
i added to the develop branch a command line flag of `-re` or `--resume` followed by the exact name of a Collection and then PMM will start once it hits that collection

**Comment by paulmcclellan** [comment]
Nice!  This tool is taking Plex to another level!
