### ISSUE TITLE
Docker image not working on Qnap NAS

### ISSUE THREAD

**Issue by treemandan88** [Kometa-Team/Kometa#1563]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

When trying to setup PMM on my Qnap TS-431P using the Qnap guide on metamanager.wiki

I get to the point where I am to test the newly created config file when the terminal gives me this:

Traceback (most recent call last):
  File "//plex_meta_manager.py", line 176, in <module>
    from modules.builder import CollectionBuilder
  File "/modules/builder.py", line 4, in <module>
    from modules import anidb, anilist, flixpatrol, icheckmovies, imdb, letterboxd, mal, plex, radarr, reciperr, sonarr, tautulli, tmdb, trakt, tvdb, mdblist, util
  File "/modules/tvdb.py", line 3, in <module>
    from lxml.etree import ParserError
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

I asked for help on the pmm discord and it was suggested that the docker image isn't compatible with the Qnap processor which is an ARM processor

Also no log file was created

**Comment by meisnate12** [comment]
latest and develop have arm7 dockers as seen [here](https://hub.docker.com/r/meisnate12/plex-meta-manager/tags)
