### ISSUE TITLE
Newest Version Check crashes when not avai;lable

### ISSUE THREAD

**Issue by mihidumh** [Kometa-Team/Kometa#1585]
### Version Number

1.19.0

### What branch are you on?

nightly

### Describe the Bug

When checking for newer versions, the page is returning a not expected result causing PMM to crash before starting.
This is occurring on the current develop & nightly branch. By the time I switched to master the external issue had resolved itself.

Possibly the code needs a simple check to ignore if not a valid value in case of outages?

### Logs

https://gist.github.com/mihidumh/70745cbacb28ea972e68e675a3956e7b

**Comment by meisnate12** [comment]
this should be fixed if youre still having this issue on 1.20.0 please reopen
