### ISSUE TITLE
AniList Genre/Tags Not Working

### ISSUE THREAD

**Issue by jak64950** [Kometa-Team/Kometa#159]
Running script using anilist_genre or anilist_tag results in error "attribute not supported".

-

**Comment by meisnate12** [comment]
can you share the config for that collection

**Comment by jak64950** [comment]
[TV Shows - Anime.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/6247295/TV.Shows.-.Anime.txt)
![error](https://user-images.githubusercontent.com/39564839/113373108-27cb0400-9338-11eb-84bf-a66d83a1db9e.png)

**Comment by meisnate12** [comment]
which version of PMM are you using? if its current can you try the develop branch and see if your error still occurs

**Comment by jak64950** [comment]
Just pulled latest develop. Same error.

**Comment by meisnate12** [comment]
can you send me you meta.log file

**Comment by jak64950** [comment]
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6247446/meta.log)

**Comment by meisnate12** [comment]
the log say version 1.5.1 can you run this again with the develop branch and send me the log from that?

**Comment by jak64950** [comment]
How do I switch branches? Tried git checkout develop and git pull but says up to date.

**Comment by meisnate12** [comment]
try git fetch

**Comment by jak64950** [comment]
I figured it out, my docker command wasn't set to pull from develop. It's working now.
