### ISSUE TITLE
Discord Server Invite invalid

### ISSUE THREAD

**Issue by stevezau** [Kometa-Team/Kometa#1621]
### Version Number

NA

### What branch are you on?

master

### Describe the Bug

Hi,

The Discord server link does not work, it returns a invalid invite error.

**Comment by stevezau** [comment]
I'd love to join the discord, is there an updated link? :)

**Comment by chazlarson** [comment]
https://discord.gg/xUmRb3a65R

**Comment by stevezau** [comment]
thanks

**Comment by YozoraXCII** [comment]
#1678 contains the fix
