### ISSUE TITLE
Flixpatrol has gone to subscription 

### ISSUE THREAD

**Issue by stevezau** [Kometa-Team/Kometa#1623]
### Version Number

ALL

### What branch are you on?

master

### Describe the Bug

Hi, It looks like Flixpatrol is requiring subscriptions for access to full data. It appears you can only view top 10 data for the current day in the basic view (not full) for free.

Flagging this to understand how Plex Meta Manager plans to handle this? 

right now the plugin is broken.

Thanks

**Comment by mikenobbs** [comment]
As of right now there isn’t a fix. Flixpatrol have been contacted to discuss prices for what we need, though it’s highly likely that it will just be removed from PMM completely if the price isn’t reasonable.

**Comment by ohmybahgosh** [comment]
Their cheapest tier is 49.99 USD.. what a joke.  What this does is create a need for competion, so in time another provider will pop-up

**Comment by Navino16** [comment]
I think with some (minor or not I don't know) change we can at least keep the daily top10 free.

**Comment by stevezau** [comment]
I also contacted them but they didn't want to budge on $49/month for a personal licence. Way too expensive. 

I actually have my own script that used to scrape the top 10 data. I was about to move to plex meta manager but i mightj just update my script for now as i think we can still easily get the top10 data at least.

**Comment by Navino16** [comment]
> I also contacted them but they didn't want to budge on $49/month for a personal licence. Way too expensive.
> 
> I actually have my own script that used to scrape the top 10 data. I was about to move to plex meta manager but i mightj just update my script for now as i think we can still easily get the top10 data at least.

Can you share it ?

**Comment by stevezau** [comment]
The script was built for my purposes so i am not sure there is any value sharing it show it looks today. I can share how i am scraping the data tho. 

```

**Comment by stevezau** [comment]
The script was built for my purposes so i am not sure there is any value in sharing it show it looks today. I can share the scraper component tho. It is pretty simple. See the gist below

https://gist.github.com/stevezau/4119ba5a32cf1ffa91d261436a78e7ee

So, the script pulls the top 10 titles, then i call get_item_data to enrich it with the identifiers. To do this I have to lookup the title page for each item to find the tmdb, imdb id's.. I use a cache. to reduce calls https://gist.github.com/stevezau/e82f864bc65024e6c7c8ffb9dce2b859
