### ISSUE TITLE
Values such as "mdb_average" can cause Overlays to be rewritten every time a run is executed

### ISSUE THREAD

**Issue by cj0r** [Kometa-Team/Kometa#1624]
### Version Number

1.19.1 

### What branch are you on?

master

### Describe the Bug

Recently I noticed that my overlays were constantly being rewritten. I tracked down the culprit to utilizing mdb_average as my source for ratings on my overlays. Because the mdb_average is constantly changing, due to amount of sources that are used to calculate it, this causes the value to regularly change from e.g. 5.2 to 5.3 back to 5.2 etc. depending on how frequently the Movie or TV Show is being rated on social sites such as trakt/letterboxd etc. Perhaps if there was a flag to skip updating entries that have already had custom ratings applied via the mass*update operations, the issue could be avoided?

**Comment by chazlarson** [comment]
There's not really any way for PMM to know if a rating has been updated, unless it tracks it outside Plex, and that's brittle.

Perhaps a simpler solution would seem to be to schedule the mass update to happen less frequently?

**Comment by cj0r** [comment]
The only issue with less frequent mass updates is that depending on what data the user is expecting to see in their collection, they will temporarily see ratings that don't align with their expectations. Unfortunately this is somewhat the nature of having such a unstable value such as the mdb_average. My original thought was along the same lines of the "Overlay" tag that PMM applies to entries it has already customized. Perhaps a similar tag could be applied when it comes to custom information such as ratings coming from PMM?

Food for thought. I have already switched my config over to use mdb_tomatoes on the overlays themselves since I don't foresee a quick solution for this. It's a shame though since mdb_average is an all encompassing value that can give a clearer view to the quality of content.

**Comment by chazlarson** [comment]
Adding a flag to skip updates seems like it would cause the same "values don't match" issue.  MDBList average for Barbie is 79 today.  If PMM sets it today along with a flag to never touch it again, then when it changes the site and the overlay will diverge.

Probably the actual solution, *assuming that 0.1 swings in this average is what's causing the issue* is to round it to an integer before using it, so only 1-point swings cause an overlay update.  MDBList displays it as an integer, so that should match user expectations as well.

**Comment by cj0r** [comment]
My flag would only really work if the user was ok with essentially settling with whatever the value was when they ran that mass update. It would be a snapshot in time of whatever that score was at that point and what was used for their library.

Your rounding idea could work but it really depends on how often mdb's value actually changes in integers. Using Barbie as the example again, it still says 79 today so that's a good sign that it could be a solution for the way mdb_average gets pulled in.

**Comment by chazlarson** [comment]
Is there log output showing specifically why the overlays were being reapplied in these cases?

Looking at a trace log just now it's not clear how the numerical value would cause this.

**Comment by cj0r** [comment]
Hey @chazlarson sorry real life got in the way of fiddling with this. Circling back, I think this might be a simple case of ambiguous logging? The trace log would lead me to believe that the Overlays are being regenerated over and over each time I run this as the Audience score is constantly changing (this is mdblist based which is constantly changing in value). However, I took a look at Plex's image cache and I only see the one PMM image there which would lead me to believe that only 1 instance exists? If it really reapplying the Overlays, and recreating image files over and over, I would see multiple images in Plex no?

I just ran my Movies library back to back (didn't bother with test since I wanted to get as much data as possible) and saw all the trace logging in the form of "Overlay Reason: Overlay changed Special Text Changed from 7.8 to 7.9" which Special Text Changed referring to the Audience score which is NOT on the overlays (only critic score). However, as you'll see in my screenshot, only 1 instance of each PMM poster is in Plex. The only exception being the forced change I did to 28 Weeks Later which you can see the previous variation along with the new one.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/8386969/c56f40ab-14ed-4dff-85d4-491763727467)

[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/12861522/meta.log)
[meta.log.1.log](https://github.com/meisnate12/Plex-Meta-Manager/files/12861577/meta.log.1.log)
