### ISSUE TITLE
Collection Error: schedule attribute daily invalid

### ISSUE THREAD

**Issue by AwesomeAustn** [Kometa-Team/Kometa#164]
```
IMDb Top 250:
  imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250
  sync_mode: sync
  collection_mode: default
  collection_order: alpha
  sort_title: '*100'
  schedule: daily
```
`Collection Error: schedule attribute daily invalid`

Removing the schedule line works. The Wiki seems like it says you can have it if you want.
https://github.com/meisnate12/Plex-Meta-Manager/wiki/Schedule-Attribute

**Comment by meisnate12** [comment]
fix should be in develop

**Comment by AwesomeAustn** [comment]
Confirmed fixed. Thank you!

**Comment by meisnate12** [comment]
leaving open until pushed to master
