### ISSUE TITLE
Need Support Discord Invalid invitation

### ISSUE THREAD

**Issue by Crosus97** [Kometa-Team/Kometa#1642]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

This is not a support isue, i want to ask something in discord, the invitation link is down

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/46854222/8c353847-3067-4294-a154-7fa6f7046b85)

**Comment by chazlarson** [comment]
https://discord.gg/q6Fq5wsMFG
