### ISSUE TITLE
Discord invite link is dead? 

### ISSUE THREAD

**Issue by Magikarplvl4** [Kometa-Team/Kometa#1662]
### What is the improvement or update to the Wiki you wish to see?

Im trying to join the plex meta manager discord server. But both links are dead (https://discord.com/invite/plexmetamanager , and discord.gg/plexmetamanager)

Is it possible to create a new invite link?

**Comment by chazlarson** [comment]
https://discord.gg/c22uUAE7gs

**Comment by YozoraXCII** [comment]
#1678 contains the fix
