### ISSUE TITLE
The Discord Invite appears to have expired so unable to connection to the Server is not possible

### ISSUE THREAD

**Issue by davidfleischmann** [Kometa-Team/Kometa#1674]
### What is the improvement or update to the Wiki you wish to see?

The link at the following URL doesnt work as the invite has expired - https://discord.gg/plexmetamanager

### Does the docs page already exist? Please link to it.

https://github.com/meisnate12/Plex-Meta-Manager/blob/master/README.md

**Comment by YozoraXCII** [comment]
Use this for now:
https://discord.gg/gYU8wATxKw

We will get the documentation amended.
