### ISSUE TITLE
Nightly branch references non-existent tmdbapis version as dep

### ISSUE THREAD

**Issue by aptalca** [Kometa-Team/Kometa#1688]
### Version Number

Nightly commit 50a64ae8

### What branch are you on?

nightly

### Describe the Bug

Nightly branch currently references a non-existent version for `tmdbapis` as a dep, which results in failed installs/builds

Here's the culprit: https://github.com/meisnate12/Plex-Meta-Manager/commit/50a64ae8#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R14

The current latest version of `tmdbapis` on pypi is `1.20`: https://pypi.org/project/tmdbapis/#history

Here's our failed build log for the nightly branch: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-plex-meta-manager/detail/nightly/244/pipeline

I realize the same dev is behind pmm and tmdbapis and they're likely planning on releasing a new version of tmdbapis soon. I just wanted to bring to their attention that we have hourly checked and auto triggered ci docker image builds for the nightly branch :-) as well as develop branch and the stable releases: https://github.com/linuxserver/docker-plex-meta-manager#version-tags

Thanks

**Comment by JohnFawkes** [comment]
It actually doesn't. Soh forked it. It's in one of his repos


Edit.... I misread. I do see it hasn't been published yet

**Comment by YozoraXCII** [comment]
This is resolved
