### ISSUE TITLE
setuptools is missing from requirements

### ISSUE THREAD

**Issue by jimger** [Kometa-Team/Kometa#1699]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

I tried to run with python 3.12 but it failed. Did some track-down and found out that was the issue. I added to requirements and it worked. Error was
import pkg_resources ModuleNotFoundError: No module named 'pkg_resources

Solution came from

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by JDIacobbo** [comment]
I can confirm that adding `setuptools==69.0.2` to `requirements.txt` resolved this issue for me.

**Comment by Furglitch** [comment]
> I can confirm that adding `setuptools==69.0.2` to `requirements.txt` resolved this issue for me.

+1
