### ISSUE TITLE
Wrong links from Docker Hub

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1702]
### What is the improvement or update to the Wiki you wish to see?

Not in the wiki itself, but the links in the Getting Started of the Docker Hub page point to the GitHub wiki, which seems to no longer exist. 

### Does the docs page already exist? Please link to it.

https://hub.docker.com/r/meisnate12/plex-meta-manager

**Comment by YozoraXCII** [comment]
This has been resolved and can be closed.
