### ISSUE TITLE
Important note at (probable) wrong location

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1708]
### What is the improvement or update to the Wiki you wish to see?

This paragraph was probably meant for `Mass * Ratings Update` and not `Mass Poster Update`

> IMPORTANT NOTE: This does not affect the icons displayed in the Plex UI. This will place the number of your choice in the relevant field in the Plex database. In other words, if Plex is configured to use Rotten Tomatoes ratings, then no matter what happens with this mass rating update operation, the icons in the Plex UI will remain Rotten Tomatoes. The human who decided to put TMDB ratings in the critic slot and Letterboxd ratings in the audience slot is the only party who knows that the ratings are no longer Rotten Tomatoes. One primary use of this feature is to put ratings overlays on posters. More information on what PMM can do with these ratings can be found [here](https://metamanager.wiki/en/develop/home/guides/ratings.html).

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/develop/config/operations.html#mass-poster-update

**Comment by YozoraXCII** [comment]
This has already been resolved in nightly @Droppisalt

**Comment by Droppisalt** [comment]
Woops! Only checked latest and dev
