### ISSUE TITLE
Template Variables not being accepted in config.yml

### ISSUE THREAD

**Issue by fizzyhd** [Kometa-Team/Kometa#1724]
### Version Number

1.19.1-nightly29

### What branch are you on?

nightly

### Describe the Bug

I am trying to add template variables to config.yml file for a -pmm,  but every time I do I get this error:
YAML Error: mapping values are not allowed here in "/config/config.yml", line 11, column 27.

How am I supposed to set custom variables?

### Relevant Collection/Overlay/Playlist Definition

libraries:            
  Movies:
    metadata_path:
    - file: config/Movies.yml
    - pmm: imdb
    - pmm: content_rating_us
    - pmm: universe
    - pmm: genre
    - pmm: year
        template_variables:
          use_separator: false
          sep_style: purple
          sort_by: title.asc
          sort_by_2022: release.desc
    overlay_path:
    - pmm: ribbon
    - pmm: ratings
    - pmm: resolution
    
  TV:
    metadata_path:
    - file: config/TV.yml
    - pmm: imdb
    - pmm: universe
    - pmm: genre
    overlay_path:
      - pmm: ratings
        template_variables:
          overlay_level: episode

### Logs

https://gist.github.com/fizzyhd/371f6ee260c4a8cfca233564a1b93047

**Comment by chazlarson** [comment]
Indentation is incorrect under the `year` item.

this template_variables section should be two spaces to the left.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/1f6f308d-f523-4941-a247-2271fbbda14f)

**Comment by fizzyhd** [comment]
> Indentation is incorrect under the `year` item.
> 
> this template_variables section should be two spaces to the left.
> 
> ![image](https://user-images.githubusercontent.com/3865541/282271792-1f6f308d-f523-4941-a247-2271fbbda14f.png)

thank you!!
