### ISSUE TITLE
RESLUTION OVERLAY BUG

### ISSUE THREAD

**Issue by zantag** [Kometa-Team/Kometa#1732]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

Hi, many hybrid movies ( DV + HDR) doesn't receive correct overlays... I think the script must add DV+HDR overlay for any movie which have DV - HDR in the file name or somehow to get the info directly from PLEX DB...

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/1080384/810248a2-434c-41b6-947a-c54153a284d3)
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/1080384/4191c251-20ae-4a5a-a95f-2902ce9a521f)

**Comment by zantag** [comment]
I think i fixed it... The problem was in the resolution.yml regex for dvhdr ... it have to be like this: 

      regex:
        conditions:
          - alt: plus
            value: '(?i)\bhdr10(\+|p(lus)?\b)'
          - alt: dvhdr
            value: '(?i)\bdv(?:hdr(?:10?)?)?|dovi\b

**Comment by JohnFawkes** [comment]
This isnt a bug. All of our overlays that use filepath.regex need media filenames to be in the Trash naming style to work correctly

[https://trash-guides.info/](url)

**Comment by zantag** [comment]
> This isnt a bug. All of our overlays that use filepath.regex need media filenames to be in the Trash naming style to work correctly
> 
> [https://trash-guides.info/](url)

Yeah but it seems the most of the scene groups doesn't follow it... so we need more flexible regex... In my library only 5% was correctly recognized like HYBRIDS before i make the correction of the regex...Now more than 95%...

**Comment by JohnFawkes** [comment]
well yea. this isnt for scene groups to follow. scene groups have their own naming scheme to follow. Trash naming is for you to use in something like sonarr/radarr or filebot. We cant support a bunch of different naming styles

**Comment by chazlarson** [comment]
Anything that is targeting filenames has to have a fixed target, and in this case that target is TRaSH naming.  This decision was made because supporting random filenames quickly grew out of hand.  You can of course make copies of the files and modify them to meet your specific requirements.
