### ISSUE TITLE
Nightly Branch reports all collections as duplicate

### ISSUE THREAD

**Issue by wellingssimon** [Kometa-Team/Kometa#1772]
### Version Number

1.19.1-nightly50 

### What branch are you on?

nightly

### Describe the Bug

I switched to the nightly branch some time ago as it resolved some issues I was having at that point but from some time yesterday each scheduled run has failed:

|========================================= Warning Summary ==========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     2 | Config Warning: Skipping duplicate collection: "Trending Now"                              |
|     2 | Config Warning: Skipping duplicate collection: "Most Watched This Week"                    |
|     2 | Config Warning: Skipping duplicate collection: "Most Watched This Year"                    |
|     1 | Config Warning: Skipping duplicate collection: "Netflix"                                   |
|     1 | Config Warning: Skipping duplicate collection: "Marvel Cinematic Universe"                 |
|     1 | Config Warning: Skipping duplicate collection: "DC Extended Universe"                      |
|                                                                                                    |
|========================================== Error Summary ===========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     2 | YAML Error: metadata attribute is required                                                 |
|                                                                                                    |
|====================================================================================================|
|                                         Finished 11:25 Run                                         |
|                                     Version: 1.19.1-nightly50                                      |
|                          Finished: 11:25:33 2023-12-13 Run Time: 0:00:03                           |
|====================================================================================================|

Every collection reports as a duplicate. I am certain I do not have duplicate collections configured.

The same setup running the develop branch works correctly.

**Comment by hdemel** [comment]
Reporting the exact same behaviour. Rolling back to the main branch with the same configuration files yields no error so does seem to be something in the new nightly.

**Comment by YozoraXCII** [comment]
Can we have a log of this behaviour please?

As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.

**Comment by wellingssimon** [comment]
> Can we have a log of this behaviour please?
> 
> As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.

I can get a log later this evening. The standard meta.log?
I’ve already switched to the develop branch and it is working as expected but will switch back to nightly to get the log file for you. Thanks.

**Comment by YozoraXCII** [comment]
> > Can we have a log of this behaviour please?
> > As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.
> 
> I can get a log later this evening. The standard meta.log? I’ve already switched to the develop branch and it is working as expected but will switch back to nightly to get the log file for you. Thanks.

If you've only done one run, then meta.log.1/meta.1.log would be the "n-1" log, you can check the log header which will tell you what branch was running.

**Comment by wellingssimon** [comment]
> > > Can we have a log of this behaviour please?
> > > As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.
> > 
> > 
> > I can get a log later this evening. The standard meta.log? I’ve already switched to the develop branch and it is working as expected but will switch back to nightly to get the log file for you. Thanks.
> 
> If you've only done one run, then meta.log.1/meta.1.log would be the "n-1" log, you can check the log header which will tell you what branch was running.

Meta log attached using nightly build

[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/13664451/meta.log)

**Comment by YozoraXCII** [comment]
> > > > Can we have a log of this behaviour please?
> > > > As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.
> > > 
> > > 
> > > I can get a log later this evening. The standard meta.log? I’ve already switched to the develop branch and it is working as expected but will switch back to nightly to get the log file for you. Thanks.
> > 
> > 
> > If you've only done one run, then meta.log.1/meta.1.log would be the "n-1" log, you can check the log header which will tell you what branch was running.
> 
> Meta log attached using nightly build
> 
> [meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/13664451/meta.log)

Thanks

Can you send me the contents of `/config/TV Shows.yml`

**Comment by wellingssimon** [comment]
> > > > > Can we have a log of this behaviour please?
> > > > > As a side-note I would suggest using develop as we are reworking some things in nightly, but I would really appreciate those logs.
> > > > 
> > > > 
> > > > I can get a log later this evening. The standard meta.log? I’ve already switched to the develop branch and it is working as expected but will switch back to nightly to get the log file for you. Thanks.
> > > 
> > > 
> > > If you've only done one run, then meta.log.1/meta.1.log would be the "n-1" log, you can check the log header which will tell you what branch was running.
> > 
> > 
> > Meta log attached using nightly build
> > [meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/13664451/meta.log)
> 
> Thanks
> 
> Can you send me the contents of `/config/TV Shows.yml`

TV Shows and Movies config attached.

[pmm.zip](https://github.com/meisnate12/Plex-Meta-Manager/files/13664718/pmm.zip)

If you spot any other obvious improvements I can make, hints would be appreciated ;)

**Comment by YozoraXCII** [comment]
Thanks - we know why this is happening, just trying to break it down.

Are you on the Discord? Can chat easier there if you want.

**Comment by YozoraXCII** [comment]
This should be fixed in nightly54

**Comment by wellingssimon** [comment]
> This should be fixed in nightly54

Really appreciate the efforts to get this fixed so quickly. You definitely deserve the sponsorship money for this kind of response. Off topic, I read that FlixPatrol has gone subscription based which has broke the integration. Have you considered (is it even possible) to charge PMM users a small fee to cover the costs of that?

**Comment by chazlarson** [comment]
The subscription is insanely expensive, and chances are the sort of use PMM would put it to would not be allowed, anyways.

**Comment by JohnFawkes** [comment]
> > This should be fixed in nightly54
> 
> Really appreciate the efforts to get this fixed so quickly. You definitely deserve the sponsorship money for this kind of response. Off topic, I read that FlixPatrol has gone subscription based which has broke the integration. Have you considered (is it even possible) to charge PMM users a small fee to cover the costs of that?

its like 50k a month for api access. Flixpatrol is in nightly and develop versions of pmm anyway
