### ISSUE TITLE
[Error/Typo] Use of overlay_path instead of overlay_files

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1819]
### What is the improvement or update to the Wiki you wish to see?

In the example config file, both the Movies and TV libraries specify overlay_path instead of overlay_files
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/67336980/dda47c59-dbfc-4e0a-8810-a7de5b7ab6f0)

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/nightly/config/overview/#configuration-file-example

**Comment by YozoraXCII** [comment]
PR #1815 will resolve this

**Comment by jflad17** [comment]
It looks like this issue is no longer an issue 
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/56899029/3a230784-d3d8-484e-a080-72ef7793021e)

**Comment by Droppisalt** [comment]
Yup, looks fixed. Thanks for pointing it out!

**Comment by ovizii** [comment]
Doesn't quite look fixed everywhere, the docker walkthrough: https://metamanager.wiki/en/latest/pmm/install/docker/ 

shows this example:

```
## This file is a template remove the .template to use the file

libraries:                       # This is called out once within the config.yml file
  Movies:                        # Each library must match the Plex library name
    collection_files:
      - pmm: basic               # This is a file within the defaults folder in the Repository
      - pmm: imdb                # This is a file within the defaults folder in the Repository
      # see the wiki for how to use local files, folders, URLs, or files from git
    remove_overlays: false       # Set this to true to remove all overlays
    overlay_files:
      - pmm: ribbon              # This is a file within the defaults folder in the Repository
      # see the wiki for how to use local files, folders, URLs, or files from git
```

but links to this template: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager/master/config/config.yml.template 

which contains: 
```
libraries:                       # This is called out once within the config.yml file
  Movies:                        # These are names of libraries in your Plex
    collection_files:
      - pmm: basic               # This is a file within PMM's defaults folder
      - pmm: imdb                # This is a file within PMM's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_path:
      - remove_overlays: false   # Set this to true to remove all overlays
      - pmm: ribbon              # This is a file within PMM's defaults folder
      # see the wiki for how to use local files, folders, URLs, or files from git
```

Pay attention to the use of `remove_overlays`, `overlay_files `and `overlay_path` – it is pretty mixed up and confusing for new users I'd say.
