### ISSUE TITLE
Wait for Plex Restart because of plex busy_db

### ISSUE THREAD

**Issue by wuast94** [Kometa-Team/Kometa#1820]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

On huge libarys plex starts to throw errors because of busy_db. that results in slow down and lags in plex and ends in a completly unusable plex server. i have this since i use pmm, its a known issue.
to fix this i inspect the plex logs and restart plex, here comes the issue i have with pmm.
pmm instantly detects this and stops itself. so pmm is repeating the same steps over and over again but never finishes.

a solution i have in mind is to have some sort of retry timeout, so instead of exitting wait for x seconds, retry (retry x times and each time wait x seconds before next try) and resume if the connection is back.

**Comment by cscattaglia917** [comment]
I have the same issue unfortunately with frequent plex DB hangs due to PMM since updating to 1.20 from 1.18.

There already is a general timeout setting - have you tried increasing that?

**Comment by wuast94** [comment]
yes but no luck
