### ISSUE TITLE
If a rating isn't found, it can be replaced by an incorrect value. 

### ISSUE THREAD

**Issue by batman2999** [Kometa-Team/Kometa#1822]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

When ratings values don't exist (for example, there's a missing value in metacritic), the data from plex is added to the overlay. This can result in incorrect information appearing on the overlay. Although the program is working as expected, it still results in incorrect overlays. The solution would be to have an option to add blank critic/audience/user rating when there's missing info. 

/u/chazlarson explained the situation better on reddit: 

(I was discussing the movie MobKing)

> That movie, on MDBlist, has only IMDb, Trakt, and TMDb ratings, https://i.ibb.co/V01Rh6k/image.png

> Which means these aren't available:

> mass_critic_rating_update: mdb_tomatoes mass_audience_rating_update: mdb_metacritic Which means PMM can't set them, so those are being left as whatever Plex stuck in those fields.

> Did a little more digging. This movie, on Rotten Tomatoes, has a 98% audience rating and no critic rating.
> https://i.ibb.co/4JVw48z/image.png

> I imagine you have this library set to Rotten Tomatoes ratings, so Plex has filled in the audience rating with that 98% and left the critic slot empty.

> PMM doesn't overwrite the value in "audience" or "critic" since the data doesn't exist at mdb.

> When PMM goes to apply ratings overlays, the ratings in Plex for this movie are:
> audience: 98% [set by Plex, not overwritten by PMM] critic: empty [set by Plex, not overwritten by PMM] user: 7.2 [set by PMM with data from mdblist] 

> Your ratings overlay config:
> - pmm: ratings template_variables: rating1: critic rating1_image: rt_tomato rating2: audience rating2_image: metacritic rating2_extra: "%" rating3: user rating3_image: imdb

> There is no critic rating on the item, so that gets skipped.

> The audience rating contains 98%, and you've told PMM to show that value as a metacritic rating with a '%', which is how it shows up on the poster.

> The user rating contains 7.2, and you've told PMM to display that one as an IMDB rating, which, again, is how it is showing up on the poster.

**Comment by YozoraXCII** [comment]
Whilst not detracting from the original issue, the "workaround" would be to remove all ratings so that nothing has a rating, and then apply your desired overlays on top of it

```
mass_audience_rating_update: reset
mass_critic_rating_update: reset
mass_user_rating_update: reset
```
