### ISSUE TITLE
[Defaults]: trek collection no longer exists

### ISSUE THREAD

**Issue by michaeltieso** [Kometa-Team/Kometa#1833]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager/blob/56961ccca1ab55aa7c1e289c6ed27a91de0c7172/defaults/both/universe.yml#L87C9-L87C13

### Version Number

n/a

### What branch are you on?

master

### Describe the Bug

Trek found in the universe default (specifically https://trakt.tv/users/wdvhucb/lists/star-trek) no longer exists. I found this here to replace it https://trakt.tv/users/dgw/lists/star-trek-canon (not my list)

**Comment by YozoraXCII** [comment]
This is already resolved in the nightly branch
