### ISSUE TITLE
Overlays not working with SSL even though verify_ssl: false

### ISSUE THREAD

**Issue by slikone27** [Kometa-Team/Kometa#1838]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

I have plex set to required (not preferred) for secure connections so I can no longer connect to HTTP.  The cert doesn't match localhost because its generated by plex.  The PMM docs say:

verify_ssl - Turn SSL Verification on or off.
Turn SSL Verification on or off.
Note: set to false if your log file shows any errors similar to "SSL: CERTIFICATE_VERIFY_FAILED"

Everything is working except for overlays... looking at the logs I see:

HTTPSConnectionPool(redacted): Max retries exceeded with url: /library/metadata/2/thumb/1704619324?X-Plex-Token=(redacted) (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.254'. (_ssl.c:1002)")))

I am guessing its ignoring the verify ssl false setting?  I don't care the cert is invalid, it should just write the thumbnail image correct?  setting plex to preferred for secure connections and using HTTP doesn't seem like a great solution.

**Comment by gareth-c** [comment]
I'm having this issue. I changed from required to preferred and did not change the error.

Any extra logs be useful? please let me know.

**Comment by slikone27** [comment]
so there are 2 work around for now... go to plex network settings and change to preferred and not required and use http url or the one I ended up doing:

If you are running tautulli go into the settings and get the long plex server url from it that is https.  That one will work and nto have a cert error so you can keep plex set to require ssl.
