### ISSUE TITLE
User Rating (IMDB) rating layer not shown

### ISSUE THREAD

**Issue by miladmyled** [Kometa-Team/Kometa#1851]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

User Rating (IMDB) rating layer not shown for the movies that are in IMDB Top 250 
<img width="1105" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/30826499/dad4468c-4c62-4538-9125-8d52148f5a92">
But for regular movies it is showing , that's strange
<img width="1113" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/30826499/b0dfa9ad-6b3d-4fa9-8e1b-f0b095065b0b">

**Comment by meisnate12** [comment]
post your meta.log or theres not a whole lot to go on
