### ISSUE TITLE
Filter on rating in Plex

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#187]
I've been trying to create a collection of my top rated movies, but it looks like filtering on Plex rating is not possible. If I use `rating`, it converts to `critic_rating`, and `audience_rating` is not what I'm after either. I want the rating I set myself on the movies

**Comment by meisnate12** [comment]
i can probably add user_rating

**Comment by Alaksin** [comment]
If you look in plex on there is:
- Critic rating
- Audience rating
- Rating

So it would make sense that the filtering options reflect the same names

**Comment by meisnate12** [comment]
i get that but i dont want to be ambiguous about it so I'm gonna go with user_rating

**Comment by meisnate12** [comment]
also it makes it a little confusing codewise because in plex's backend they use rating, userRating, and audienceRating to store the values. Critic rating is stored in rating which is why rating translates to critic_rating. I find it confusing to instead call userRating,  rating when rating is actually critic rating.

**Comment by Alaksin** [comment]
Ok, I see. In that case I think it would be more clear to remove `rating` completely

**Comment by meisnate12** [comment]
im probably gonna leave it in converting to critic_rating because that's what it was before the change and I don't wanna mess up an old config but it shouldn't be listed on the wiki. It is lol I apparently forgot to remove it

**Comment by meisnate12** [comment]
added user_rating to dev

**Comment by Alaksin** [comment]
I tested it out and it works great
