### ISSUE TITLE
Playlist documentation do not match with the code

### ISSUE THREAD

**Issue by benbou8231** [Kometa-Team/Kometa#1873]
### What is the improvement or update to the Wiki you wish to see?

The following template variables to not match what the code is looking for:
- sync_to_user
- sync_to_user_<<key>>
- exclude_user
- exclude_user_<<key>>

Source: https://metamanager.wiki/en/latest/defaults/playlist/#template-variables

The code looks for those variables:
- sync_to_users
- sync_to_users_<<key>>
- exclude_users
- exclude_users_<<key>>

Source: https://github.com/meisnate12/Plex-Meta-Manager/blob/master/defaults/playlist.yml

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/defaults/playlist/#template-variables

**Comment by meisnate12** [comment]
this is already fixed in nightly
