### ISSUE TITLE
Overlays not applying to library items, "500 internal server error"

### ISSUE THREAD

**Issue by slunat** [Kometa-Team/Kometa#1875]
### Version Number

1.20

### What branch are you on?

master

### Describe the Bug

I have two plex servers and two PMM servers currently setup on two separate pieces of hardware. 

Setup 1: Windows 11 host, Docker, pmm v1.19.1, Plex v1.32.8.7639-fb6452ebf
Setup 2: Proxmox host, Debian 12 container, local install (no docker), pmm v1.20, Plex v1.32.8.7639-fb6452ebf

On setup 1, I am having no issues at all. On setup 2 based (no docker) server I have just set up, I am getting the 500 internal server error. The setups are identical in terms of overlays and collections, I have just made the necessary changes to things like the Trakt API details, plex server details, library names and file paths.

I have seen this issue in the past has occurred when Plex has updated and broken something. However, Setup 1 is running the same Plex version as Setup 2, which is 1.32.8.7639-fb6452ebf so I don't think that is the issue. Everything seems to be fine up until the point of applying the posters.

### Logs

https://gist.github.com/slunat/52910fc15215c9424db01aa1cc414eb5

**Comment by ccueto36** [comment]
Any update on this? Having the exact same issue on latest 1.20.0

**Comment by YozoraXCII** [comment]
500 Internal Server errors are generally Plex saying "something unexpected happen, but we didn't code for it so don't know how to report on it or fix it".

I'd suggest joining our Discord server to see if there's anything that we can suggest on there.

I'm going to mark this as resolved for now as this isn't a PMM issue.
