### ISSUE TITLE
Feature Request: Music Library Support

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#189]
im sure i could but the biggest problem is I don't use plex for music so I don't really have much testing capabilities there but make an issue requesting it and ill try to get to it

_Originally posted by @meisnate12 in https://github.com/meisnate12/Plex-Meta-Manager/discussions/188#discussioncomment-582758_

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Hey @meisnate12 - I just had to manually add sharing labels to a bunch of stuff in music library today and started thinking about this again.

I see you added a prio someday label 9 days ago, I assume that means it's on the backburner for now?

**Comment by meisnate12** [comment]
yea it kinda is especially since you can do most collection via smart collections bbut i guess you want it so you can use PMM to add labels?

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Yeah, I personally don't really need collections for music... I mean I guess I could do genre collections, but I care more about labels for sharing purposes. Currently I have all my users locked behind different labels, so if the content doesn't have a label then by default only I can view it.

**Comment by isaacolsen94** [comment]
+1 to this! I can help with providing a library to test on

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I have a new use case for needing music library support. I have all the music I want synced to my phone in a collection, so being able to back that collection up would be extremely beneficial.

**Comment by meisnate12** [comment]
im gonna try and get this in 1.13.0

**Comment by meisnate12** [comment]
ok so not quite 1.13.0 but i just added it to the develop branch for testing to be released in the 1.15.0 release the only builders that work with it are `plex_all`, `plex_search`, `smart_filter` and `filters`
