### ISSUE TITLE
Feature request - Collection templates

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#19]
I have some different types of collections: Actors, Directors, Genres and the normal movie collections. My issue is that there is only one folder where all the collections assets go. Instead of having these different types of collections mixed together in the assets  folder, I would like them to have their own sub folders, like `assets/Actors` and `assets/Directors` . That would make organizing the files a lot easier. 

For each category I have a certain prefix for the sort title: `++D_` for directors, `++A_` for actors and so on. These common settings could be put into a collection template, which would make it easier to handle these different types of collections. Example:

```
templates:
  Directors:
    sort_title_prefix: ++D_
    asset_directory: assets/Directors

  Actors:
    sort_title_prefix: ++A_
    asset_directory: assets/Actors

collections:
  David Cronenberg:
    template: Directors
    director: tmdb
    tmdb_person: 224

  Arnold Schwarzenegger:
    template: Actors
    actor: tmdb
    tmdb_person: 1100
```

So with this, the sort titles for the collections would be `++D_David Cronenberg` and `++A_Arnold Schwarzenegger` and they would have the asset folders `assets/Directors/David Cronenberg` and `assets/Actors/Arnold Schwarzenegger`

I'm sure there are a lot more uses with templates, this is just what I have thought of with my own collections.

**Comment by meisnate12** [comment]
ok done! can you test in develop look at the new template file to figure out how they work. I'll be writing up something soon

**Comment by Alaksin** [comment]
Trying to run it but I get
```
| Connecting to Movies Library...                                                                    |
| local variable 'Radarr' referenced before assignment                                     |
```

**Comment by meisnate12** [comment]
ok now it should work

**Comment by meisnate12** [comment]
[Template Details](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Template-Attributes) Wiki Page is up
