### ISSUE TITLE
Option to Apply Collection Labels to Each Item

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#193]
I didn't see support for this in the wiki, or an open feature request, so I'm creating it.

I'm thinking something along the lines of a flag that takes the options "append" or "overwrite", or whatever options would be good, and if that exists it applies the collection labels to each item.

yes that sets the sharing label but not there's no way to mass edit it via a collection i could add that just submit a feature request

_Originally posted by @meisnate12 in https://github.com/meisnate12/Plex-Meta-Manager/discussions/21#discussioncomment-360664_

**Comment by cpt-kuesel** [comment]
i would like to add the ability to change metadata, like metadata language, in the same style (for every movie in a collection) to this feature request.

**Comment by meisnate12** [comment]
ok you can now use `item_label`, `item_label.sync`, `item_episode_sorting`, `item_keep_episodes`, `item_delete_episodes`, `item_season_display`, `item_episode_ordering`, `item_metadata_language`, `item_use_original_title` under the collection to edit every item in that collection
