### ISSUE TITLE
tvdb_show_details doesn't return summary

### ISSUE THREAD

**Issue by pterisaur** [Kometa-Team/Kometa#1962]
### Version Number

1.2.0

### What branch are you on?

nightly

### Describe the Bug

When using tvdb_show_details as a builder, it returns the poster art but not the summary text. This isn't resulting in any errors, but no collections using this builder have summaries in my library.

### Relevant Collection/Overlay/Playlist Definition

```yml
Peanuts Collection:
  tvdb_show_details: https://www.thetvdb.com/series/peanuts
```

**Comment by YozoraXCII** [comment]
this has been addressed in nightly @pterisaur

If you're happy, please close this

**Comment by pterisaur** [comment]
Thanks! It's fixed. :)
