### ISSUE TITLE
Docker image: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by arthuraltino** [Kometa-Team/Kometa#1974]
### Version Number

1.21.0

### What branch are you on?

master

### Describe the Bug

The app won't run with the new 1.21.0 docker image.
If i try to run it with environment variable `PMM_RUN=true` or if i bash into the container and run `python app/pmm/plex_meta_manager.py --run` i'll always get the following error:
`Illegal instruction (core dumped)`

If i use 1.20.0 version, everything works just fine.
I'm using Ubuntu Server 22.04 on an amd64 cpu.
Thanks for any help in advance.

**Comment by YozoraXCII** [comment]
Can you try running PMM on the nightly branch and seeing if that resolves your error?

**Comment by arthuraltino** [comment]
> Can you try running PMM on the nightly branch and seeing if that resolves your error?

I've already tried it and the same error occurs. 😕

**Comment by YozoraXCII** [comment]
> > Can you try running PMM on the nightly branch and seeing if that resolves your error?
> 
> I've already tried it and the same error occurs. 😕

Do you have Discord? may be easier to discuss and troubleshoot there.

https://metamanager.wiki/en/latest/discord/

**Comment by arthuraltino** [comment]
> > > Can you try running PMM on the nightly branch and seeing if that resolves your error?
> > 
> > 
> > I've already tried it and the same error occurs. 😕
> 
> Do you have Discord? may be easier to discuss and troubleshoot there.
> 
> https://metamanager.wiki/en/latest/discord/

Sure! I'll contact you over there
