### ISSUE TITLE
[Defaults]: Need to update images...

### ISSUE THREAD

**Issue by nobodyspecial** [Kometa-Team/Kometa#1993]
### Link to File

docs/_static/favicon.png

### Version Number

latest

### What branch are you on?

master

### Describe the Bug

Images in docs/_static are old PPM logos

**Comment by YozoraXCII** [comment]
#1994

**Comment by YozoraXCII** [comment]
Merge into nightly, this will get deployed with the next Kometa release.

Marking as resolved.
