### ISSUE TITLE
Nightly docs are not available

### ISSUE THREAD

**Issue by javierlopeza** [Kometa-Team/Kometa#1997]
### Version Number

n/a

### What branch are you on?

master

### Describe the Bug

<img width="1387" alt="Screenshot 2024-04-23 at 9 45 58 PM" src="https://github.com/Kometa-Team/Kometa/assets/11431769/d5ed63dd-43a0-46f2-94cc-8daece7bba4d">

**Comment by YozoraXCII** [comment]
This has been resolved, it was an issue between ReadTheDocs and GitHub
