### ISSUE TITLE
README - Example configurations

### ISSUE THREAD

**Issue by squk** [Kometa-Team/Kometa#2]
It'd be useful to see what a working config looks like. The documentation is helpful but it's a lot to digest.

**Comment by meisnate12** [comment]
There's an example in the project under the config folder [Movies.yml.template](https://github.com/meisnate12/Plex-Meta-Manager/blob/master/config/Movies.yml.template) 

I also created another Repo where users can share configs [Plex Meta Manager Configs](https://github.com/meisnate12/Plex-Meta-Manager-Configs)

**Comment by squk** [comment]
Thank you. This is exactly what I was looking for!
