### ISSUE TITLE
Error executing Kometa

### ISSUE THREAD

**Issue by Crosus97** [Kometa-Team/Kometa#2015]
### Version Number

2.0.0

### What branch are you on?

master

### Describe the Bug

![image](https://github.com/Kometa-Team/Kometa/assets/46854222/8677948a-1b7e-420e-97a0-60a6e38fcc69)

```
Traceback (most recent call last):
  File "D:\Servidores\Plex-Meta-Manager\kometa.py", line 183, in <module>
    from modules.builder import CollectionBuilder
  File "D:\Servidores\Plex-Meta-Manager\modules\builder.py", line 4, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by meisnate12** [comment]
try installing you requirements again

**Comment by YozoraXCII** [comment]
@Crosus97 have you tried the above? Let us know please or this issue will be closed.

**Comment by YozoraXCII** [comment]
Closing as no response
