### ISSUE TITLE
[Defaults]: myanimelist season collection is outputting “season -  continued” instead of “season - new”

### ISSUE THREAD

**Issue by king8084** [Kometa-Team/Kometa#2020]
### Link to File

Na

### Version Number

1

### What branch are you on?

master

### Describe the Bug

I know i didnt provide what you want so you can ignore if you wish

theres a mistake in the code. Mal for some reason has two seasons lists. One is useless since its the same as top airing which is “season - continued”. And the other is the useful one which is “season - new”. Kometa is currently pulling the season continued

**Comment by YozoraXCII** [comment]
Resolved in nightly, closing
