### ISSUE TITLE
Mapping Movie Library Issue for new title 'City Hunter' - invalid literal for int() with base 10

### ISSUE THREAD

**Issue by kingwoftam** [Kometa-Team/Kometa#2030]
### Version Number

2.0.0

### What branch are you on?

master

### Describe the Bug

During the 'Mapping Movies Library' stage, the mapping fails with the following error when new title 'City Hunter' is found:
invalid literal for int() with base 10: 'tt24478470'.

Removing the movie from my Plex library resolves the problem, and other new movies map correctly. However I would like to add the movie back into the library, so this needs a permanent fix.

### Logs

https://gist.github.com/kingwoftam/5d0c5d3f1c5efeabdcbb8031d817cea6

**Comment by chazlarson** [comment]
This should be addressed in 2.0.1.  The actual cause is broken metadata from Plex for that movie.

**Comment by YozoraXCII** [comment]
Closing as resolved in 2.0.1
