### ISSUE TITLE
Collection Error: anilist_userlist score.gte attribute not supported  

### ISSUE THREAD

**Issue by Tomatoshadow** [Kometa-Team/Kometa#2034]
### Version Number

2.0.1

### What branch are you on?

master

### Describe the Bug

None of the "score" attributes of anilist_userlist work.

The username, list_name and sort_by attributes all work. But trying to use any of the score attributes (score.gt, score.gte, score.lt, score.lte) will result in the following error:

Collection Error: anilist_userlist score.gte attribute not supported

**Comment by meisnate12** [comment]
@Tomatoshadow pushed a fix to nightly let me know if it fixes the issue
