### ISSUE TITLE
People Collections - error 

### ISSUE THREAD

**Issue by melbasuonyy** [Kometa-Team/Kometa#207]
I'm having error in  People Collections 
using docker all collections are working except people collection - below is sample for the log 

 Adam Sandler Collection 
Scanning Adam Sandler Collection 
 Plex Error: actor: Adam Sandler not found 
Collection Warning: No valid actor values found in ['Adam Sandler']  
Plex Error: writer: Adam Sandler not found 
Collection Warning: No valid writer values found in ['Adam Sandler']   
Sync Mode: sync 

  Adam Sandler:
    template: {name: Actor Writer, person: 19292}

  Actor:
    actor: tmdb
    tmdb_person: <<person>>
    sort_title: ++++_<<collection_name>>
    sync_mode: sync
    collection_order: release

**Comment by meisnate12** [comment]
can you switch to the develop version and try again?

**Comment by meisnate12** [comment]
were you ever able to get this working?

**Comment by melbasuonyy** [comment]
Yes please you can close the issue sorry for delayed response
