### ISSUE TITLE
Edit movie images like poster and background

### ISSUE THREAD

**Issue by TheBinaryLoop** [Kometa-Team/Kometa#209]
Add a possibility to change the poster or background of a movie through the metadata config.

**Comment by TheBinaryLoop** [comment]
If there was better documentation, I would include the feature myself.

**Comment by TheBinaryLoop** [comment]
If i want to implement it, where do i need to do it. Which file/function? What funtions would i need to use?

**Comment by meisnate12** [comment]
added `url_poster`, `file_poster`, `url_background`, and `file_background` under the metadata map, season map, and episode map to edit the poster and background
