### ISSUE TITLE
Unraid walkthrough tells use to use `sudo apt install nano` which doesn't work

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#2091]
### What is the improvement or update to the Wiki you wish to see?

instructions should work on unraid.  If some other thing has to be installed to provide nano access, that should be made clear.

### Does the docs page already exist? Please link to it.

https://kometa.wiki/en/nightly/kometa/install/unraid/#editing-the-config-template

**Comment by deepfriedmind** [comment]
Nano is built into Unraid so that section can be removed.

**Comment by chazlarson** [comment]
Is this version-dependent?  I opened this issue after trying to help someone on the Discord who did not have nano available on unraid.

Years ago I recall having to install something like "nerd pack" or the like [as did another person in the discord] in order to get nano on unraid.

**Comment by deepfriedmind** [comment]
I think it's been built-in for nearly a decade.

**Comment by vanbushi** [comment]
Were you able to find the solution for this? I'm also having issues with the same thing.

**Comment by TheIndieArmy** [comment]
I'm new to Unraid and trying to follow this guide on Unraid 6.12.10 and I am also getting the following errors when trying to follow the guide:

`root@b2f29516defc:/# nano "config/Movies.yml"`
`bash: nano: command not found`
`root@b2f29516defc:/# sudo apt install nano`
`bash: sudo: command not found`

**Comment by TheIndieArmy** [comment]
I was able to get nano installed using the following inside a Docker terminal:
`apt update`
`apt install nano`

I could then continue on with the guide.

**Comment by chazlarson** [comment]
nano should already be installed on unraid, I am told, so there should be no reason to install it.  Those commands in the wiki don't work on unraid, but they can just be skipped.

**Comment by TheIndieArmy** [comment]
If you skip `nano "config/movies.yml"` then how would you go about getting the file created for editing within the system? I'm sure it's possible to connect through Windows and create/edit it there, but that seems outside the scope and intention of the guide.

I assume the error `bash: nano: command not found` meant that I did not have Nano installed on my system (I tried in both a Docker and the Unraid terminal). But I was able to solve this by getting it installed per my previous comment.

**Comment by chazlarson** [comment]
Oh, OK.  I didn't mean to skip *that* command, just the `sudo apt` stuff as my impression is that nano should be available and you should be able to go straight to `nano config/whatever`.  Seems like it wasn't in your case, which makes me think there's some disconnect or version-dependency here.

I haven't used unraid in years, but @deepfriedmind above claims it's built in and has been for a long time.

I've asked for some unraid users to review those instructions.

**Comment by deepfriedmind** [comment]
> `root@b2f29516defc:/# sudo apt install nano` 
> `bash: sudo: command not found`

@TheIndieArmy Here you don't even have the `sudo` command, so I assume you did this within the container and not the Unraid shell. Unraid has Nano built-in. It was last updated to v7.2 in [Unraid 6.12.0](https://docs.unraid.net/unraid-os/release-notes/6.12.0/) as you can see under "Base Distro updates".

**Comment by TheIndieArmy** [comment]
I want to say I tried both, but I may not have. I for certain tried within the container console, because that's what the directions say to do. "Use Linux tab below for the Unraid Kometa _>Console", which I read as I need to open the container terminal through the container's _>console option. 

https://kometa.wiki/en/latest/kometa/install/unraid/#editing-the-config-template

The directions are fine to be such, but if so then I believe the "install nano" command needs to be changed to `apt install nano` instead so that nano can be installed inside Docker.

**Comment by deepfriedmind** [comment]
It says "open the copy in an editor on the machine of your choice". I'm not sure what exactly "the Unraid Kometa _>Console" is supposed to mean so that could probably be re-worded (just "the Unraid Terminal"?), but it definitely does not mean to use the shell inside the container, since the image doesn't include nano (or even sudo). Those instructions for installing nano are for a general Linux machine and don't mean to do it inside the container.

**Comment by TheIndieArmy** [comment]
I agree that the wording should be changed to specify the Unraid terminal. 

More information on what caused my confusion.

Previously in the guide it points out how to access the terminal: https://kometa.wiki/en/latest/kometa/install/unraid/#important-note-on-docker-images
> Open up an unRAID terminal session by clicking on the terminal icon >_ in the top right of unRAID.

Then further down it points out how to access the container console:
> Open a Console by left-clicking on the running Kometa Container and selecting >_Console. This will open up an interactive session within the container to be able to run the commands we want.

Then you go back to "Use Linux tab below for the Unraid Kometa _>Console", and I think it's understandable why someone would read _>Console and think it means the container console.

**Comment by chazlarson** [comment]
The wiki is open to pull requests if you have ideas about how to make that more clear.

**Comment by YozoraXCII** [comment]
Closing as resolved in nightly
