### ISSUE TITLE
Github rate-limiting breaks everything. 

### ISSUE THREAD

**Issue by Write** [Kometa-Team/Kometa#2101]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

Hello, I think there's a serious issue with how Kometa works.

I was doing a huger number of restart to test my script, which ended in errors like this : 

![image](https://github.com/Kometa-Team/Kometa/assets/541722/c025b450-d675-45e9-8af2-d73f094db5ab)

Took me an hour to figure out that it was GitHub that was rate-limiting me because of endless reboot to test my yaml config.

File(s) should really be cached up so that issue like this doesn't arise.
Also, the GitHub error should be shown on console clearly. 

Thanks for reading.

**Comment by meisnate12** [comment]
each translation file is already set to only be loaded once per run of Kometa ill try and add some better error reporting

**Comment by Write** [comment]
> each translation file is already set to only be loaded once per run of Kometa ill try and add some better error reporting

What is your stance on caching the file(s) ? This would allow to Kometa to still run even if GitHub is not available.

**Comment by meisnate12** [comment]
its cached though the run so it only pings github once per run for the translation file this ensures that any changes to the translation are picked up by kometa

**Comment by Write** [comment]
> its cached though the run so it only pings github once per run for the translation file this ensures that any changes to the translation are picked up by kometa

Yeah sure, but any subsequent run so close to each other, this shouldn't happen.

And even, honestly, if the server isn't available, it would seem sane to just use whatever is the latest local cached file available. For everything, not just translation. I'm assuming if GitHub is down, nothing will run.

**Comment by YozoraXCII** [comment]
Closing as this is somewhat expected - a feature request could be raised to reduce the dependancy on GitHub if OP wishes to do so

https://features.kometa.wiki/
