### ISSUE TITLE
[Defaults]:  Trakt.tv X-Men list deleted (returns a 404)

### ISSUE THREAD

**Issue by vanburenx** [Kometa-Team/Kometa#2150]
### Link to File

https://raw.githubusercontent.com/Kometa-Team/Kometa/27674ef4dfe3905188d9780d5394726f6e9a46d4/defaults/playlist.yml

### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

The default x-men playlist on trakt.tv appears to have been deleted (returns a 404) [X-Men (Timeline Order)](https://trakt.tv/users/heyitsbea/lists/x-men).

**Comment by YozoraXCII** [comment]
Cosing as resolved in nightly
