### ISSUE TITLE
Pre-Rolls

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#2159]
### Version Number

latest version

### What branch are you on?

master

### Describe the Bug

Not a bug,

Just found out today that PMM was nolonger working and is not this app

Was using PMM and had pre-rolls setup to use daily, weekly, monthly, and yearly. I am unsure how to set them up in this new version and how to specify dates.

Also is there any documentation on how to convert from PMM to this?

I was only using collections (tautulli, trending  and popular for videos only found in my collection) and pre-roll functions.

Just having a hard time finding the info I need in the wiki.

can somone post some of their files that desl with tv collections and movies collections with pre rolls?

TIA.

**Comment by chazlarson** [comment]
Nothing has changed in pre-roll config as part of the rebranding.

The wiki is available here:
<https://kometa.wiki/en/latest/files/settings/?h=pre+roll>

Your existing setup should work fine with Kometa assuming it was working with a recent PMM.  There were no required config changes as part of the rebrand.

**Comment by almulder** [comment]
last known working was a month ago with PMM when it switch my pre-rolls to June prerolls, since then pmm updated to the new setup and was not aware until today, so the most recent version of pmm was no longer working. guess thats where I am struct. Was not aware of the new changes to the config layouts.

so does the pre-roll info in the config file? or is that a sperate file? and how would I convert these to the new format:

Here is my old Pre-roll setup:

```
# Pre-rolls
  Yearly change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/Plex Pre Roll 01.mp4;/Media/PreRoll/Plex Pre Roll 02.mp4;/Media/PreRoll/Plex Pre Roll 03.mp4;/Media/PreRoll/Plex Pre Roll 04.mp4;/Media/PreRoll/Plex Pre Roll 05.mp4;/Media/PreRoll/Plex Pre Roll 06.mp4;/Media/PreRoll/Plex Pre Roll 08.mp4
    schedule: range(01/01-12/31)

# Monthly
  JAN change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/01-Jan/Winter Forest LoFi Plex Pre-roll.mp4;/Media/PreRoll/01-Jan/Winter Ice Plex Pre-roll.mp4;/Media/PreRoll/01-Jan/Winter Snow Plex Pre-roll.mp4
    schedule: range(01/03-01/31)
    
#  FEB change preroll:
#    build_collection: false
#    server_preroll:/Media/PreRoll/02-Feb/
#    schedule: range(02/01-02/28)
       
  MAR change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/03-Mar/Melting Snow Plex Pre-roll.mp4;/Media/PreRoll/03-Mar/Winter is Comming.mp4
    schedule: range(03/01-03/31)

  APR change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/04-Apr/Spring_Blooming_Flower.mp4;/Media/PreRoll/04-Apr/Spring_Dancing_Butterflies.mp4;/Media/PreRoll/04-Apr/Spring_Flower_Field.mp4
    schedule: range(04/01-04/30)      
    
#  MAY change preroll:
#    build_collection: false
#    server_preroll: /Media/PreRoll/05-May/
#    schedule: range(05/01-05/31)
           
#  JUN change preroll:
#    build_collection: false
#    server_preroll: /Media/PreRoll/06-June/
#    schedule: range(06/01-06/30)      
        
  JUL change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/07-July/Summer_Summer_Vibes.mp4
    schedule: range(07/01-07/31)

#  AUG change preroll:
#    build_collection: false
#    server_preroll: /Media/PreRoll/08-Aug/
#    schedule: range(08/01-08/31)
   
  SEP change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/09-Sept/Fall_Fox.mp4;/Media/PreRoll/09-Sept/Fall_Simple.mp4
    schedule: range(09/01-09/30)
    
  OCT change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/10-Oct/Blood Splatter Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Bloody Horror Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Dark Hotel Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/final comp 2_1.mp4;/Media/PreRoll/10-Oct/Garage Screams Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Horror Movies Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Monster Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Zombieland Plex Pre-roll.mp4;
    schedule: range(10/01-10/31)

  NOV change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/11-Nov/Winter is Coming Plex Pre-roll.mp4
    schedule: range(11/01-11/30)
    
  DEC change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/12-Dec/Christmas_Ornaments.mp4;/Media/PreRoll/12-Dec/Christmas_Train.mp4;/Media/PreRoll/12-Dec/Christmas_Tree.mp4;/Media/PreRoll/12-Dec/Glitter_Santa.mp4;/Media/PreRoll/12-Dec/Glitter_Snow.mp4;/Media/PreRoll/12-Dec/Glitter_Trees.mp4;/Media/PreRoll/12-Dec/Snowflakes.mp4;/Media/PreRoll/12-Dec/Snowman.mp4
    schedule: range(12/01-12/31)    

# Week Pre-Rolls
  Jan 1_2 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Weekly/12-Dec26_Jan2/Christmas Card.mp4;/Media/PreRoll/00-Weekly/12-Dec26_Jan2/Disney Christmas Plex Pre-roll.mp4
    schedule: range(01/01-01/02)

  MAR 20_27 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Weekly/3-Mar20_27/Mar_20_Apr_17_Cherry_blossoms_Sakura.mp4
    schedule: range(03/20-03/27)

  OCT 27_31 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V01.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V02.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V03.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V04.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V05.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V06.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V07.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V08.mp4
    schedule: range(10/27-10/31)

  DEC 26_31 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Weekly/12-Dec26_Jan2/Christmas Card.mp4;/Media/PreRoll/00-Weekly/12-Dec26_Jan2/Disney Christmas Plex Pre-roll.mp4
    schedule: range(12/26-12/31)
        
# Day Pre-Rolls
  FEB 14 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Days/Feb_14_Valentines_Flowers.mp4;Feb_14_Valentines_Hearts.mp4
    schedule: yearly(02/14)    

  APR 1 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Days/Apr_1_April_Fools.mp4
    schedule: yearly(04/01) 

  APR 17 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Days/Apr_17_2022_Happy_Easter.mp4
    schedule: yearly(04/17) 

  JULY 4 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Days/July_4_ID4_Fireworks.mp4;/Media/PreRoll/00-Days/July_4_ID4_Stars.mp4
    schedule: yearly(06/04)

  NOV 24_25 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Days/Nov_24_25_2022_Thanksgiving_Happy_Thanksgiving.mp4
    schedule: range(11/24-11/25) 
        
  DEC 24_25 change preroll:
    build_collection: false
    server_preroll: /Media/PreRoll/00-Weekly/12-Dec24_25/Glitter Merry Christmas Plex Pre-roll.mp4;/Media/PreRoll/00-Weekly/12-Dec24_25/Merry Christmas Plex Pre-roll.mp4;/Media/PreRoll/00-Weekly/12-Dec24_25/Snow Globe Plex Pre-roll.mp4
    schedule: range(12/24-12/25)
```

**Comment by almulder** [comment]
So I created the config.yml file, but when I relaunch the docker it says 

```
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

I have the files placed in the "\appdata\kometa" folder same place the template is located and just removed the template part of the name. so the file is "config.yml" but does not seem to pick it up

**Comment by chazlarson** [comment]
> last known working was a month ago with PMM when it switch my pre-rolls to June prerolls, since then pmm updated to the new setup and was not aware until today, so the most recent version of pmm was no longer working. guess thats where I am struct. Was not aware of the new changes to the config layouts.
> 
> so does the pre-roll info in the config file? or is that a sperate file? and how would I convert these to the new format:
> 
> Here is my old Pre-roll setup:
> 
> ```
> # Pre-rolls
>   Yearly change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/Plex Pre Roll 01.mp4;/Media/PreRoll/Plex Pre Roll 02.mp4;/Media/PreRoll/Plex Pre Roll 03.mp4;/Media/PreRoll/Plex Pre Roll 04.mp4;/Media/PreRoll/Plex Pre Roll 05.mp4;/Media/PreRoll/Plex Pre Roll 06.mp4;/Media/PreRoll/Plex Pre Roll 08.mp4
>     schedule: range(01/01-12/31)
> 
> # Monthly
>   JAN change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/01-Jan/Winter Forest LoFi Plex Pre-roll.mp4;/Media/PreRoll/01-Jan/Winter Ice Plex Pre-roll.mp4;/Media/PreRoll/01-Jan/Winter Snow Plex Pre-roll.mp4
>     schedule: range(01/03-01/31)
>     
> #  FEB change preroll:
> #    build_collection: false
> #    server_preroll:/Media/PreRoll/02-Feb/
> #    schedule: range(02/01-02/28)
>        
>   MAR change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/03-Mar/Melting Snow Plex Pre-roll.mp4;/Media/PreRoll/03-Mar/Winter is Comming.mp4
>     schedule: range(03/01-03/31)
> 
>   APR change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/04-Apr/Spring_Blooming_Flower.mp4;/Media/PreRoll/04-Apr/Spring_Dancing_Butterflies.mp4;/Media/PreRoll/04-Apr/Spring_Flower_Field.mp4
>     schedule: range(04/01-04/30)      
>     
> #  MAY change preroll:
> #    build_collection: false
> #    server_preroll: /Media/PreRoll/05-May/
> #    schedule: range(05/01-05/31)
>            
> #  JUN change preroll:
> #    build_collection: false
> #    server_preroll: /Media/PreRoll/06-June/
> #    schedule: range(06/01-06/30)      
>         
>   JUL change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/07-July/Summer_Summer_Vibes.mp4
>     schedule: range(07/01-07/31)
> 
> #  AUG change preroll:
> #    build_collection: false
> #    server_preroll: /Media/PreRoll/08-Aug/
> #    schedule: range(08/01-08/31)
>    
>   SEP change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/09-Sept/Fall_Fox.mp4;/Media/PreRoll/09-Sept/Fall_Simple.mp4
>     schedule: range(09/01-09/30)
>     
>   OCT change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/10-Oct/Blood Splatter Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Bloody Horror Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Dark Hotel Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/final comp 2_1.mp4;/Media/PreRoll/10-Oct/Garage Screams Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Horror Movies Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Monster Plex Pre-roll.mp4;/Media/PreRoll/10-Oct/Zombieland Plex Pre-roll.mp4;
>     schedule: range(10/01-10/31)
> 
>   NOV change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/11-Nov/Winter is Coming Plex Pre-roll.mp4
>     schedule: range(11/01-11/30)
>     
>   DEC change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/12-Dec/Christmas_Ornaments.mp4;/Media/PreRoll/12-Dec/Christmas_Train.mp4;/Media/PreRoll/12-Dec/Christmas_Tree.mp4;/Media/PreRoll/12-Dec/Glitter_Santa.mp4;/Media/PreRoll/12-Dec/Glitter_Snow.mp4;/Media/PreRoll/12-Dec/Glitter_Trees.mp4;/Media/PreRoll/12-Dec/Snowflakes.mp4;/Media/PreRoll/12-Dec/Snowman.mp4
>     schedule: range(12/01-12/31)    
> 
> # Week Pre-Rolls
>   Jan 1_2 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Weekly/12-Dec26_Jan2/Christmas Card.mp4;/Media/PreRoll/00-Weekly/12-Dec26_Jan2/Disney Christmas Plex Pre-roll.mp4
>     schedule: range(01/01-01/02)
> 
>   MAR 20_27 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Weekly/3-Mar20_27/Mar_20_Apr_17_Cherry_blossoms_Sakura.mp4
>     schedule: range(03/20-03/27)
> 
>   OCT 27_31 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V01.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V02.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V03.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V04.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V05.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V06.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V07.mp4;/Media/PreRoll/00-Weekly/10-Oct27_Oct31/Halloween Pack V08.mp4
>     schedule: range(10/27-10/31)
> 
>   DEC 26_31 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Weekly/12-Dec26_Jan2/Christmas Card.mp4;/Media/PreRoll/00-Weekly/12-Dec26_Jan2/Disney Christmas Plex Pre-roll.mp4
>     schedule: range(12/26-12/31)
>         
> # Day Pre-Rolls
>   FEB 14 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Days/Feb_14_Valentines_Flowers.mp4;Feb_14_Valentines_Hearts.mp4
>     schedule: yearly(02/14)    
> 
>   APR 1 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Days/Apr_1_April_Fools.mp4
>     schedule: yearly(04/01) 
> 
>   APR 17 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Days/Apr_17_2022_Happy_Easter.mp4
>     schedule: yearly(04/17) 
> 
>   JULY 4 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Days/July_4_ID4_Fireworks.mp4;/Media/PreRoll/00-Days/July_4_ID4_Stars.mp4
>     schedule: yearly(06/04)
> 
>   NOV 24_25 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Days/Nov_24_25_2022_Thanksgiving_Happy_Thanksgiving.mp4
>     schedule: range(11/24-11/25) 
>         
>   DEC 24_25 change preroll:
>     build_collection: false
>     server_preroll: /Media/PreRoll/00-Weekly/12-Dec24_25/Glitter Merry Christmas Plex Pre-roll.mp4;/Media/PreRoll/00-Weekly/12-Dec24_25/Merry Christmas Plex Pre-roll.mp4;/Media/PreRoll/00-Weekly/12-Dec24_25/Snow Globe Plex Pre-roll.mp4
>     schedule: range(12/24-12/25)
> ```

There have been no config layout changes.  That would go in an external file just as it always has.

**Comment by chazlarson** [comment]
> So I created the config.yml file, but when I relaunch the docker it says
> 
> ```
> [custom-init] No custom files found, skipping...
> [ls.io-init] done.
> ```
> 
> I have the files placed in the "\appdata\kometa" folder same place the template is located and just removed the template part of the name. so the file is "config.yml" but does not seem to pick it up

I would guess you are using the linuxserver image; that message is not something that Kometa is producing.

Kometa's config file needs to be called config.yml, same as PMM, and goes in the config dir, same as PMM.

My primary config file is unchanged from and I the same place as when it was PMM.

**Comment by almulder** [comment]
> > So I created the config.yml file, but when I relaunch the docker it says
> > ```
> > [custom-init] No custom files found, skipping...
> > [ls.io-init] done.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have the files placed in the "\appdata\kometa" folder same place the template is located and just removed the template part of the name. so the file is "config.yml" but does not seem to pick it up
> 
> I would guess you are using the linuxserver image; that message is not something that Kometa is producing.
> 
> Kometa's config file needs to be called config.yml, same as PMM, and goes in the config dir, same as PMM.
> 
> My primary config file is unchanged from and I the same place as when it was PMM.

you are correct, theirs has a bug of some kind i guess, as I got it running something. I copied all my files over from PMM to Kometa. Will see how it goes. Thanks for the direction

**Comment by almulder** [comment]
[meta.log](https://github.com/user-attachments/files/16188330/meta.log)
ok so getting this error:
`
|========================================|

|                        Running Movies Collection File                           |

|                                 /config/Movies.yml                                     |

|========================================|

|                                                                                                     |

|   Collection: false not in Collection File: config/movies.yml        |

|                                                                                                     |

|=========================================|
`
here is my movies.yml file: Note: copied from the example (https://kometa.wiki/en/latest/files/collections/#collection-operations-attributes)

`collections:
  Trending:
    trakt_trending: 10
    tmdb_trending_daily: 10
    tmdb_trending_weekly: 10
    sort_title: +1_Trending
    sync_mode: sync
    smart_label: random
    summary: Movies Trending across the internet
  Popular:
    tmdb_popular: 40
    imdb_search:
      type: movie, tv_movie
      limit: 40
    sort_title: +2_Popular
    sync_mode: sync
    smart_label: random
    summary: Popular Movies across the internet
`

What am i missing? I have attached my log file

also how do I call the pre-roll stuff now. I know it goes into an external file, before it was at the end of my movies.yml file i now have it in a separate file called server_preroll.yml file, but how do I call it in the config file. not seeing that info in the wiki

**Comment by almulder** [comment]
Moved to reddit for help instead of here since its not a bug. thanks for the help
