### ISSUE TITLE
Issue uploading to plex (I think)

### ISSUE THREAD

**Issue by Racer540** [Kometa-Team/Kometa#2160]
### Version Number

2.0.2 (Latest version of Docker/Unraid)

### What branch are you on?

master

### Describe the Bug

Looks there is an issue uploading certain covers/posters for collections to plex.

Edit: I suppose I should say, collections/playlists work. With no issue. Just not posters. Also noticed overlays aren't working. Assuming its stemming from same issue?

<img width="938" alt="image" src="https://github.com/user-attachments/assets/5d3e2bfd-2ae5-45c3-84ed-277e95a291fe">

(Realized there was more to the error)
<img width="938" alt="image" src="https://github.com/user-attachments/assets/638922de-6404-49ee-a029-32071fca4e46">

If there is further information I can give, just ask. I will try and check back on this.

### Logs

https://gist.github.com/Racer540/80e02a53efa93218ee08bc9fb19fbeec

**Comment by chazlarson** [comment]
How big is the image you are trying to upload?  If it's over 10MB this is a Plex limitation.

Ah, probably not this since this is a default image.  In this case, Kometa is just telling Plex "set the poster to the image behind this URL", so it appears that perhaps your Plex server is having trouble retrieving the image from github.

Kometa isn't sending the image itself to Plex.

**Comment by Racer540** [comment]
WIth the collection posters? It worked just fine with the old pmm system. This script is what the default one was on the wiki. I was troubleshooting and no matter what config I used, it errored. Overlays nor collection (default/stock) posters works.

**Comment by chazlarson** [comment]
There have been no changes here as part of the rebrand.

this config:
```
libraries:
  Kometa-Demo-TV:
    collection_files:
     - default: bafta
       template_variables:
         data:
           starting: latest-10
           ending: latest
  Kometa-Demo-Movies:
    collection_files:
     - default: bafta
       template_variables:
         data:
           starting: latest-10
           ending: latest
```

Just worked fine for me in three runs [nightly, master, docker master] against my test server, so it seems like there's something in the environment of your plex server.

```
|======================================== Plex Configuration ========================================|
|                                                                                                    |
| Using Asset Directory: config/assets/movies/                                                       |
| Using Asset Directory: config/assets/shared/                                                       |
| Connected to server kometa-demo version 1.40.0.7998-c29d4c0c8                                      |
| Running on Linux version 6.5.0-14-generic                                                          |
| Plex DB cache setting: 2048 MB                                                                     |
| PlexPass: False on Public update channel.                                                          |
| Scheduled maintenance running between 2:00 and 5:00                                                |
| Connected to library Kometa-Demo-Movies                                                            |
| Type: Movie                                                                                        |
| Agent: tv.plex.agents.movie                                                                        |
| Scanner: Plex Movie                                                                                |
| Ratings Source: Rotten Tomatoes                                                                    |
```
