### ISSUE TITLE
how to control when Kometa itself runs,like if you want Kometa to only run on Tuesdays and Thursdays

### ISSUE THREAD

**Issue by miaobaka** [Kometa-Team/Kometa#2177]
### What is the improvement or update to the Wiki you wish to see?

https://kometa.wiki/en/latest/config/schedule/  there has a paragraph “If you want to control when Kometa itself runs, like if you want Kometa to only run on Tuesdays and Thursdays, see (https://kometa.wiki/en/latest/config/kometa/scheduling.md).”
but i found this page is lost.can you update it? thanks.

**Comment by chazlarson** [comment]
PR created to fix the link.

**Comment by YozoraXCII** [comment]
Closing as merged into nightly
