### ISSUE TITLE
Collections Altered by Plex-Meta-Manager are Removed from Plex Home

### ISSUE THREAD

**Issue by sysmoon14** [Kometa-Team/Kometa#218]
Plex has recently added the ability for collections to be added to the home screen (which is something I've been waiting for), this means that I can put my Plex-Meta-Manager collections like "Trending Movies" etc. front-and-centre for my shared users.

Unfortunately though, it seems that when I my collections get updated they're removed from the home screen. This doesn't happen when updating a collection via the Plex Web GUI so I can only assume it's caused by Plex-Meta-Manager.

For information, I'm running version 1.8.0 via Docker and below is an example of a collection config I'm having these issues with.
```Trending Movies:
    trakt_trending: 40
    tmdb_trending_daily: 40
    tmdb_trending_weekly: 40
    sort_title: ++++_1Trending
    sync_mode: sync
    summary: Movies Trending across the internet
    collection_order: alpha
    filters:
      year.gte: 2018```

**Comment by meisnate12** [comment]
confirmed that this is happening. Ill try and look into this soon

**Comment by meisnate12** [comment]
this seems to be an error with Plex itself. When you change the Collection Order or Collection Mode it erases whatever visibility settings you have. This also happens if you do it just through the Web UI.

**Comment by meisnate12** [comment]
Bug Reported to Plex Here: https://forums.plex.tv/t/bug-collection-visability-resets-to-nothing-when-editing-advance-options/712589

**Comment by jluis2k10** [comment]
This seems to be fixed?
