### ISSUE TITLE
X-men trakt link is dead 

### ISSUE THREAD

**Issue by nemchik** [Kometa-Team/Kometa#2198]
### Link to File

https://github.com/Kometa-Team/Kometa/blob/master/defaults%2Fplaylist.yml

### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

The X-Men playlist from trakt seems to be missing (dead link) 

https://trakt.tv/users/heyitsbea/lists/x-men

It should probably be replaced or removed.

**Comment by antwanchild** [comment]
This has been fixed in nightly

**Comment by YozoraXCII** [comment]
Closing as duplicate of #2150
