### ISSUE TITLE
invalid literal for int() with base 10: 'movie'

### ISSUE THREAD

**Issue by Roguyt** [Kometa-Team/Kometa#22]
Hello, 

Thanks for you work, the tools is amazing however I have an issue with the MAL integration.
Whenever I'm trying to add collections to my Anime Library it keeps failing on this error.
![image](https://user-images.githubusercontent.com/8149856/107688031-7ac4fb00-6ca7-11eb-84b0-96c3333803cb.png)

Any idea on how I can enable some kind of verbose mode to help debugging it ?

Thanks !

**Comment by meisnate12** [comment]
there should be a log file created in your config folder can you post that?

**Comment by Roguyt** [comment]
![image](https://user-images.githubusercontent.com/8149856/107691818-3ab44700-6cac-11eb-886c-99eae1214abf.png)

**Comment by meisnate12** [comment]
what anime comes after Gekijouban Fate/Kaleid in you plex?

**Comment by Roguyt** [comment]
This one
![image](https://user-images.githubusercontent.com/8149856/107693201-18bbc400-6cae-11eb-936c-2b0efd862baf.png)

**Comment by meisnate12** [comment]
ok i see the problem and another problem as well ill try to have a fix out in the next couple of days

**Comment by Roguyt** [comment]
No problem at all
Thanks !

**Comment by meisnate12** [comment]
the fix has been pushed to develop can you test also delete your config.cache before you run the develop branch

**Comment by Roguyt** [comment]
It is currently running and seems to be processing correctly.

**Comment by Roguyt** [comment]
I can confirm the fix works.

**Comment by meisnate12** [comment]
awesome im gonna keep this open untill it moves to master
