### ISSUE TITLE
Collectionless collection sees items in the previous Collectionless collection, and treats that as being in a real collection

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#220]
I realize title is kind of confusing...

Basically on a first run the collectionless collection gets created as normal. Now that Collectionless exists, if you run PMM again it will see that previous collectionless collection and think that everything within is part of a collection, causing them to be removed.

Running PMM once more after this happens, everything will be added back to Collectionless as expected.

**Comment by meisnate12** [comment]
the collectionless collection needs to be an exclusion for collectionless. That's why if you look at the template the collectionless collection sort title starts with `~` and `~` is one of its exclude_prefixes. whats your collectionless collection look like in your metadata file.

PS I like the title haha

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Gotcha. I did see that, I thought that prefix was just being used to move it's Alphabetical sort position in Plex to the end. Didn't realize it was looking at it's own title for exclusions.

I had mine set as ~!Collectionless, which wasn't added as an exclude_prefix. Changing it seems like it's working.

Is there a reason for that being the case, other than it just being the default behavior? I'm trying to think of a situation where a collection wouldn't want to exclude itself when using plex_collectionless.

**Comment by meisnate12** [comment]
Tbh just didn't think about it lol I could set it to automatically exclude itself
