### ISSUE TITLE
radarr tag

### ISSUE THREAD

**Issue by melbasuonyy** [Kometa-Team/Kometa#223]
I'm having issue to get radarr tags it's not adding movie with the desired tag below is example 

  Oscars:
    imdb_list: https://www.imdb.com/search/title/?title_type=feature&groups=oscar_winner
    sort_title: ++++_1Oscars
    sync_mode: sync
    summary: Oscar Winning Movies
    collection_order: release
    radarr_tag: Oscars
    url_poster: https://theposterdb.com/api/assets/10049/

Config File
radarr:                                         # Can be individually specified per library as well
  url: http://192.168.0.******/
  token: ****************
  version: v3
  add: true
  root_folder_path: /Movies/
  monitor: true
  availability: announced
  quality_profile: Any
  tag:
  search: false
it add movie without tag in radarr

**Comment by meisnate12** [comment]
can you find that collection in your meta.log file and send me the output for the whole section

**Comment by meisnate12** [comment]
fix is in develop

**Comment by melbasuonyy** [comment]
ok it might look as stupid question but how to install develop version by docker I'm using Synology

**Comment by meisnate12** [comment]
instead of using the latest tag use the develop tag
