### ISSUE TITLE
Feature Request - Set collection's background when asset_folders is set to false

### ISSUE THREAD

**Issue by Alex1331xela** [Kometa-Team/Kometa#225]
When using `asset_folders: false` (where poster files are all in the base assets folder and named using the collection's name), you're unable to do the same with collection backgrounds files.

I imagine it could work by having the background file alongside the poster file, except with `_background` appended to the end. Example of what I mean:
```
assets
├── DCEU.png
├── DCEU_background.png
├── John Wick.png
├── John Wick_background.png
├── MCU.png
├── MCU_background.png
├── Star Wars.png
├── Star Wars_background.png
```

**Comment by meisnate12** [comment]
added in develop along with `_Season##` and `_S##E##`

**Comment by Alex1331xela** [comment]
Wow you're speedy, thanks very much!
