### ISSUE TITLE
Not all movies added to studio collection

### ISSUE THREAD

**Issue by mkaflowski** [Kometa-Team/Kometa#2268]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

I want to make collection with A24 movies but it doesn't collect all of them. Civil War or Love lies bleeding is not added for example.

**Comment by YozoraXCII** [comment]
Need more info - what builder are you using to create the collection?

**Comment by mkaflowski** [comment]
>     - default: studio
>       template_variables:
>         include:
>         - A24

**Comment by YozoraXCII** [comment]
> > ```
> > - default: studio
> >   template_variables:
> >     include:
> >     - A24
> > ```

Plex lists the Studios for `Civil War` as `DNA Films` and for `Love Lies Bleeding` as `Film4 Productions`

Plex generally lists the production studio, not the distribution studio.

**Comment by mkaflowski** [comment]
Thank you.
