### ISSUE TITLE
[Defaults]: The decade default collection doesn't correctly apply the item limit

### ISSUE THREAD

**Issue by diamkil** [Kometa-Team/Kometa#2290]
### Link to File

movie/decade

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Using the decade collection, with the template option `limit: 100` doesn't actually limit the number of items in the collection to 100

![image](https://github.com/user-attachments/assets/87777044-7a98-4f95-b63f-0c47477db8ec)

**Comment by antwanchild** [comment]
if looking on the collections page, it is a smart collection, and will always show more than the actual collection.  if you open the single collection, then the limit would only be 100

**Comment by diamkil** [comment]
I see, that is a bit confusing but I can confirm it's right. I guess that anyone else confused will find this here

**Comment by antwanchild** [comment]
this isn't a Kometa thing, it's a plex thing
