### ISSUE TITLE
Feature Request - Automatic Text-Posters (for Genre, Actor, Chart Collections)

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#230]
Would be great to have a automatic Poster generator based on the Collection Name for Collections without Posters (Trending, Popular, Halloween, Christmas etc). 

https://code-maven.com/create-images-with-python-pil-pillow

Option for own Background Image, Position and font could make this really personalized
maybe even on a per template and per collection basis (christmas could be given a red background)

<img width="111" alt="Bildschirmfoto 2021-05-05 um 16 51 34" src="https://user-images.githubusercontent.com/5986024/117161437-3044ad80-adc2-11eb-8f56-afdfd1851f6a.png">

**Comment by snickers2k** [comment]
or maybe you could even add theposterdb ? they have a great set of "categorie-posters"
don't understand why they still have no plex-agent :/

https://theposterdb.com/discover?category=Categories&textless=All&language=all&variation=_orig
(only shows a few - you need to refresh your browser to get a random view of those O_o)

**Comment by meisnate12** [comment]
I won't be adding theposterdb specifically but you can always just use url_poster and give it any hyperlink you want

**Comment by meisnate12** [comment]
I've decided not to try and create subpar posters using code when there's many many beautiful posters already out there so I'm gonna close this

**Comment by snickers2k** [comment]
indeed, you are right.
but how to get those automatically if no posterdb nor automatic-text?
thx

**Comment by meisnate12** [comment]
just use a direct url link to the poster

```yaml
url_poster: https://theposterdb.com/api/assets/72648/
```

**Comment by snickers2k** [comment]
i have to ask for this request again.. or to open it again... or to think again about it :D

especially for categories there are almost no posters to find. especially for sub-genres almost none - and of course no chance at all for self-named-collections :(

and of course this would allow a more "unified" look.

thanks

**Comment by snickers2k** [comment]
https://www.reddit.com/r/PlexPosters/comments/oke22w/collection_templates_are_the_way_to_go/

![df6iqznxw8b71](https://user-images.githubusercontent.com/5986024/148541023-1bb8b793-f586-4744-bd36-db73856f9553.jpg)

😄 

maybe only as a fallback if there is no poster otherwise
