### ISSUE TITLE
collection_order: custom

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#231]
In addition to Alphanumerical and Release-date orders, it would be great to have the original orders of the input-list respected and given through to plex with it's "custom"-Order.

**Comment by meisnate12** [comment]
even though the custom order option is in the UI it doesn't actually do anything yet. So theres nothing i can do to make it work we will just have to wait untill plex fully releases that feature. 

I'm going to close this for now as its not possible but once plex makes it a thing dont worry ill be adding it in

**Comment by jluis2k10** [comment]
Hi, in case you missed it, this feature already works on app.plex.tv which uses client v4.62.1

**Comment by meisnate12** [comment]
Yup ive seen it and have added it to the develop branch of PMM! check it out!

**Comment by jluis2k10** [comment]
I'm sorry to ask this as it's probably just my personal needs. I've seen the commit hoping I would find anything to sort the collection by release date in desc order (just the opposite as what Plex does when ordering by date).
And btw, keep up the good work, this tool is awesome thanks.

**Comment by meisnate12** [comment]
not as a basic collection but you can as a smart collection

**Comment by jluis2k10** [comment]
Aham good to know thanks again i'll look into it.
