### ISSUE TITLE
[Defaults]: Year Collections items doesn't logging

### ISSUE THREAD

**Issue by JohnnyKatswell** [Kometa-Team/Kometa#2315]
### Link to File

https://github.com/Kometa-Team/Kometa/blob/master/defaults/both/year.yml

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

All best of Year collections aren't logging existing\missing items, and they aren't show in report as well

**Comment by YozoraXCII** [comment]
There would be no "missing" items since the `Best of XXXX` collections are based on the already existing items in your library, it does not check against any third-party site.
