### ISSUE TITLE
Feature Request: Genre re-mapper

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#232]
would be great to have actual genres remapped to another (more common) genre.
in not english countries, there are weird english/foreign genre mixes

like emby has for years offically :/
https://emby.media/community/index.php?/topic/896-genre-cleaner/

**Comment by meisnate12** [comment]
That could maybe be a thing in the future. I already have mass_genre_update but it will just sync your library's genres with either IMDb or TMDb

**Comment by meisnate12** [comment]
added [`genre_mapper` Library Operation](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Operations-Attributes#genre-mapper)
