### ISSUE TITLE
Golden Globe example config contains "name_format: Emmys <<key_name>> Winners"

### ISSUE THREAD

**Issue by monstermsp** [Kometa-Team/Kometa#2321]
### What is the improvement or update to the Wiki you wish to see?

Revised example config

libraries:
  Movies:
    collection_files:
      - default: golden
        template_variables:
          collection_mode: show_items 
          collection_order: alpha 
          radarr_add_missing: true 
          name_format: Golden Globe <<key_name>> Winners 
          data: 
            starting: latest-10
            ending: latest

### Does the docs page already exist? Please link to it.

https://kometa.wiki/en/latest/defaults/award/golden/

**Comment by antwanchild** [comment]
this should have been submitted as a PR to nightly...
i submitted as a PR

**Comment by YozoraXCII** [comment]
Fixed in #2322
