### ISSUE TITLE
Some posters keep getting set back to freeze frames from the film?

### ISSUE THREAD

**Issue by elliottmarter** [Kometa-Team/Kometa#2335]
### Version Number

2.1.0 (Docker: master)

### What branch are you on?

master

### Describe the Bug

Some of my films are getting the posters set to freeze frames of the film and not the films poster.

If I manually set them to the correct poster, Kometa changes them back.

Some examples...

![image](https://github.com/user-attachments/assets/1948c291-8c4c-4e16-a627-2e1ba6b88e3d)

Let me know what logs to attach and I will send them over...

**Comment by chazlarson** [comment]
This is behaving as expected.  If you change art after overlays have been applied, you need to remove the "Overlay" label from the thing so Kometa knows not to use the backed up art it grabbed when it first applied overlays.
If you change the art using the asset directory or a metadata file, you won't have to worry about the label, OR if you ensure things are properly matched in Plex prior to the initial overlay run (so no screenshots as posters ), this won't happen in the first place.

**Comment by elliottmarter** [comment]
Thank you, this makes sense so I'll give it a go.

I'll close this off now, thanks again :)
