### ISSUE TITLE
entire library very slow since installing kometa

### ISSUE THREAD

**Issue by buugaas** [Kometa-Team/Kometa#2349]
### Version Number

2.1.0 

### What branch are you on?

master

### Describe the Bug

ever since i installed kometa  my entire library has slowed down dramatically. adding files take 5 times longer than what they used to. seems like everything is just hanging.  very annoying. 

### Relevant Collection/Overlay/Playlist Definition

```yml
the issue is happening on plex now even if i end kometa's run.
```

**Comment by YozoraXCII** [comment]
This is outside of Kometa's control, and could be an indicator that you maybe have database corruption. Maybe look into using Plex DBRepair to check for and resolve any issues.

Closing as not a Kometa issue.
