### ISSUE TITLE
Feature Request - Manage existing for Radarr/Sonarr

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#235]
Would be great to have Plex-Meta-Manager as a bridge between Plex-DB and Radarr/Sonarr, even for existing Movies. Because it already does half of it, or not? (for missing ones)
 
- Sonarr isn't speaking German (and has problems with my library), where is Plex 100% capable off.
- I don't really want Sonarr/Radarr to have my library scanned permanently, since Plex does that already.
- Plex already knows the actual quality, where 'arr is working with titles only (when turned off analyzes in 'arr)

btw awesome project

**Comment by meisnate12** [comment]
i dont really get what you asking me to add lol

**Comment by snickers2k** [comment]
:D 
Just like Plex-Meta-Manager is adding missing ones to 'arr. I would like to have Plex-Meta-Manager added my existing Movies/Series to Sonarr/Radarr (with path, quality etc), so that Radarr does not need to check the filesystem itself.

**Comment by meisnate12** [comment]
oh yea i could have it do that
