### ISSUE TITLE
[Defaults]: Seasonal collection defaults - unable to set the show_missing setting per seasonal collection

### ISSUE THREAD

**Issue by EnSt0rm** [Kometa-Team/Kometa#2353]
### Link to File

defaults/movie/seasonal.yml

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

When running the default seasonal collections, I don't want to see a report of hundreds of Christmas movies that I don't have, however I don't see a way to currently use the 'show_missing: false' variable with these default seasonal collections.

Can the seasonal.yml file be updated to have a show_missing_<<key>>: default value of true, but expose it so that like other variables, we can use a 'show_missing_<<key>>' variable to set it false where preferred?

**Comment by antwanchild** [comment]
Show missing isn’t a variable anywhere in any context.

**Comment by antwanchild** [comment]
show_missing is a setting

**Comment by EnSt0rm** [comment]
Sorry if I got the terminology wrong, setting is what I meant.

I thought from reading https://kometa.wiki/en/latest/config/settings/#show-missing, that the setting/attribute could be controlled on a per-collection basis, where it says:

_show_missing - Used to show missing items from collections or playlists.

While show_missing is true items missing from collections or playlists will be displayed.
Attribute: show_missing

Levels with this Attribute: Global/Library/**Collection**/Playlist

Accepted Values: true or false
Default Value: true_

Is there any way to set the value for this setting to false on a per-collection basis for default collections, such as the seasonal collections?

**Comment by antwanchild** [comment]
Settings are either global or per library, not collection

**Comment by chazlarson** [comment]
You can set `show_missing` at the collection level, but this is not currently exposed for customization in the defaults.
<https://kometa.wiki/en/nightly/files/settings/?h=show_missing>

You could open a feature request to add this, but that's no guarantee of course.

You could also make a copy of the seasonal yaml and add support yourself, or create your own collections outside the defaults.

**Comment by EnSt0rm** [comment]
Thanks, makes sense. 
I'll open the feature request and see how that goes, and look at those other options you mentioned in the meantime, thanks.
