### ISSUE TITLE
[Defaults]: Exclude documentaries from Decade collections

### ISSUE THREAD

**Issue by d3mystified** [Kometa-Team/Kometa#2364]
### Link to File

https://github.com/Kometa-Team/Kometa/blob/master/defaults/movie/decade.yml

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Pretty much what the title is. I'm using the default decades collections and didn't see a way to exclude certain genres like documentaries. Would be great if this was possible.

**Comment by chazlarson** [comment]
Filtering is not generally supported on the defaults.  This was a deliberate decision, and not likely to change.  It is certainly something that could be added as a feature request.

**Comment by YozoraXCII** [comment]
Closing as per above comment
