### ISSUE TITLE
Feature Request: summary by collection

### ISSUE THREAD

**Issue by paulmcclellan** [Kometa-Team/Kometa#238]
I have a lot of collections (more than 250).  It would be nice to see a summary of changes for each collection.

After each collection is processed, there is a summary of the number of titles that have been removed from the collection.  It would be useful to extend this to also include the number added and unchanged.  

Ideally I would be able to grep for 'summary' in the log file, and see the collection name along with changes (+, -, =).  

Thanks!

**Comment by meisnate12** [comment]
ill see what i can do
