### ISSUE TITLE
TVDb Show Issue

### ISSUE THREAD

**Issue by wildsavage** [Kometa-Team/Kometa#24]
Running into the following error when trying to add a TVDb show to a filter.

| Processing TVDb Show: https://thetvdb.com/series/pixar-shorts                                      |
| No items found to add to this collection                                                           |
|                                                                                                    |
| TVDb Error: Could not find a TVDb Series ID at the URL https://www.thetvdb.com/dereferrer/series/<modules.tvdb.TVDbObj object at 0x148ae756bf40> |

**Comment by meisnate12** [comment]
can you post the log?

**Comment by wildsavage** [comment]
Attaching a log with just the one section included in the config.
[log.log](https://github.com/meisnate12/Plex-Meta-Manager/files/5974096/log.log)

**Comment by meisnate12** [comment]
just pushed a fix to the dev branch can you test?

**Comment by wildsavage** [comment]
you nailed it, appreciate the quick fix and great work!
