### ISSUE TITLE
Low Storage Space after running PMM

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#241]
I noticed about 250GB missing today and realized it's related to old Plex metadata bundles. It would be nice if there was an option to automatically run the Optimize Database and Clean Bundles functions located in Plex Server Settings > Troubleshooting after PMM is finished.

**Comment by meisnate12** [comment]
added `clean_bundles`, `empty_trash`, and `optimize` to the plex attribute and by default, they're set to false. If these are true PMM will run the specified operation on the library at the end of the run

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Does it empty trash first?

It doesn't look like it does. You'd want that first so clean_bundles gets the fresh trash.

There might also be a timing issue there... But it shouldn't actually break anything if there is, you just wouldn't have all the trash emptied.

**Comment by meisnate12** [comment]
i always thought the order of doing those didn't matter but its in this order 
1. `clean_bundles`
2. `empty_trash`
3. `optimize`

**Comment by meisnate12** [comment]
i figured if it didnt do everything that day well it should finish up the next

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Yeah it wouldn't make a difference unless you decide to add something that waits until the trash finished being emptied before calling optimize and clean_bundles

**Comment by meisnate12** [comment]
i could put in a wait but I don't think there's a way for me to know that  its done all I could do is base it on time

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Sometimes it takes the trash awhile to empty if you're changing a lot of things... A wait wouldn't do much good if it couldn't be accurate :thinking: 

One possibility could be letting the user set an optional wait time themselves. Users with large libraries could figure out the average trash empty time and add the delay, and smaller libraries wouldn't really need it

**Comment by meisnate12** [comment]
everything leftover will just get cleaned up the next day anyways so I don't think its really needed

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Yeah, either way having this is way better than before :+1:

**Comment by meisnate12** [comment]
im gonna leave this open untill i merge 1.9
