### ISSUE TITLE
Mapping Movies Library unmatched films

### ISSUE THREAD

**Issue by bigdork** [Kometa-Team/Kometa#242]
I've a massive library, and although I have no unmatched or duplicate movies in Plex, every time I run the script the mapping portion takes quite some time and is littered with these messages:
- No ID to convert to TMDb ID
- Unable to convert IMDb ID: ttXXXXXXX to TMDb ID using TMDb or Trakt

I refreshed the Movies library metadata overnight and these still pop up.
Curious what the resolution is? Do I need to go edit TMDb/Trakt?

Not a showstopper, the script proceeds, I just don't like seeing this...

**Comment by meisnate12** [comment]
Yea basically you need to go find the item on tmdb and add the external source as IMDb for those conversions to work or in plex match the item to its respective TMDb ID over its IMDb ID

**Comment by bigdork** [comment]
Yeahhh... there's a lot, maybe one day ;) 
Thanks!

**Comment by meisnate12** [comment]
i would do it more on a case by case basis when you notice that something isn't in a collection it should be. Also are you using the New Plex Movie Agent, if not upgrading it will probably help with matching

**Comment by bigdork** [comment]
Yes, on the new Movie and TV Agents. Just... there's +30K movies, and apparently several are obscure enough to not have proper IMDb/TMDb/Trakt details. *sigh* First world problems...
