### ISSUE TITLE
command line wildcard option?

### ISSUE THREAD

**Issue by bigdork** [Kometa-Team/Kometa#243]
Is there a way to run the command line with a wildcard?

Examples: 
```
$ python3 plex_meta_manager.py -cl Author*
$ python3 plex_meta_manager.py -cl Director*
$ python3 plex_meta_manager.py -cl Writer*
```

**Comment by meisnate12** [comment]
there currently is not i could probably add it. what I do to run a section is to use the --tests option and give the respective template the `test: true` option so it runs everything that uses that template.

are you expecting `Author*` to run every collection that starts with Author?

**Comment by bigdork** [comment]
Yeah that's what I'd expect, but whatever syntax works. I just added 20+ of these "people" collections to my config, I'll deal with it, but this would be a useful (low priority) enhancement IMO.

**Comment by bigdork** [comment]
That `test: true` trick works well! I for some reason thought the `--tests` option was "list only" and did not make modifications. File this as a feature request, or don't, this trick works for my immediate needs!

**Comment by meisnate12** [comment]
something you might like even better going forward is that in develop you can have multiple metadata files now so you can just section off your collections into different files and just run the files you want to run
