### ISSUE TITLE
Cache function not working - No ID to convert to TMDb ID

### ISSUE THREAD

**Issue by LeendertPlas** [Kometa-Team/Kometa#244]
I have a problem when running the script. For every movie i get the error that there is no ID to convert to TMDb:

`| Cache | ! | plex://movie/5d9f356d06d220001feb5561          | No ID to convert to TMDb ID for Nowhere Boy |
| Cache | ! | plex://movie/5d776a62f617c9002016c73f          | No ID to convert to TMDb ID for The Nut Job |
| Cache | ! | plex://movie/5d9f3d15d5fd3f001ee1fb53          | No ID to convert to TMDb ID for Oasis: Supersonic |
| Cache | ! | plex://movie/5d7768b96f6af7001ee5bc7f          | No ID to convert to TMDb ID for Oblivion |
| Cache | ! | plex://movie/5d9f3d02adeb7a0021cea10d          | No ID to convert to TMDb ID for Oceans Eight |
| Cache | ! | plex://movie/5d9f3504e4fc29001eb65755          | No ID to convert to TMDb ID for October Sky |
| Cache | ! | plex://movie/5d776c36ad5437001f7b7272          | No ID to convert to TMDb ID for Official Secrets |
| Cache | ! | plex://movie/5d776c9dad5437001f7c3a8a          | No ID to convert to TMDb ID for Oklahoma City |
| Cache | ! | plex://movie/5d7768373c3c2a001fbcea01          | No ID to convert to TMDb ID for Old School |`

I'm quite sure that all those movies exist and that they are properly indexed in plex. As every movie can't be cached, it makes every run very slow. It takes hours for the initial scan to be done and when i run the script again it repeats this process as it does not make use of the cache.

My settings are as follows:
`settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  assets_for_all: false
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: true
  run_again_delay: 2`

**Comment by meisnate12** [comment]
you need to refresh the metadata on your items or update your server and then refresh. Plex originally didn't include external IDs (like TMDb or IMDb) with their output from your library so you either haven't refreshed since you've updated or haven't updated yet. without one of those external IDs PMM has no idea what you movie it

**Comment by LeendertPlas** [comment]
Ah thank you, I’ll try that first then.

I am using the new media agent but maybe it did not scan all of the older movies.

**Comment by meisnate12** [comment]
it should have scanned everything fine if they're showing up but they have incorrect metadata. start with a refresh all metadata and try again. If you're still getting errors let me know

**Comment by LeendertPlas** [comment]
It's even stranger. I updated all the metadata information and the first time that i ran it, it started to add the movies to a the cache with 2 Id's in the terminal. 

When i ran it today, it's giving me the same output as last time. So the problem can't be in the metadata. It is also strange that it would scan everything again as it should already be in the cache.

**Comment by meisnate12** [comment]
can you try again with v1.9.0 and then send me the resulting meta.log file

**Comment by LeendertPlas** [comment]
im trying it again now with v1.9.1. The cache functions seems to be a lot faster when initializing. But i have a lot of movies so i hope that it will be done in 3 hours. Then i'll send the meta.log file and report if the cache function is fast the second time.

**Comment by LeendertPlas** [comment]
A lot of movies still don't match but the runtime is 18 minutes now, which is fine!

https://drive.google.com/file/d/16EDlR6bje2Vf5lRWpaj_lazT4vbOiL_E/view?usp=sharing

**Comment by meisnate12** [comment]
what version of PMS are you using?

**Comment by meisnate12** [comment]
so are you still having the `No ID to convert to TMDb ID` issue? version 1.10.0 might help fix it

**Comment by LeendertPlas** [comment]
i'll try the newest version now. I still have the `No ID to convert to TMDb ID` in i think 5% of all movies in version 1.9.1 but this may also be an issue with the obscurity of the movies itself.

**Comment by LeendertPlas** [comment]
I have now run it with version 1.10 and it is amazingly faster. Almost all the movies that were not added to the cache have been added and even accounting for the fact that it had to add a lot of movies to the cache, it still finished faster.

Version 1.9.1 finished in 0:12:03
version 1.10 on the first run finished in 0:03:16
Version 1.10 on the second run finished in 0:01:32, with most of the time being spend waiting for the movie library to load - not sure what it does there or why it has to wait

**Comment by meisnate12** [comment]
awesome glad its all working again! Im going to close this for now If you have any further issue feel free to reopen or make a new issue.

it has always waited for the library to load i just didnt have the message before. the plex api only loads 100 items per call so what its doing there is loading your whole library into an array.
