### ISSUE TITLE
Feature Request: Plex-Renamer

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#259]
With all those information Plex-Meta-Manager already gets, i thought maybe it's possible to organize the folder structure off of those informations. 
Like merging different qualities of the same Movie cluttered in different folders (because Sonarr/Radarr would not recognize a second+ folder of the same item)
Or renaming everything to English (because Sonarr doesn't recognize foreign titles)

**Comment by meisnate12** [comment]
i dont plan on PMM having the ability to change any part of the file system
