### ISSUE TITLE
Enhancement: Collection "Visible on" options

### ISSUE THREAD

**Issue by bigdork** [Kometa-Team/Kometa#260]
Plex's Smart collections have a "Visable on Library/Home/Shared Users' Home" option.
Is this something we can set/modify via PMM?
![Screen Shot 2021-05-19 at 8 09 06 AM](https://user-images.githubusercontent.com/58086116/118810439-e35cde80-b879-11eb-8dd5-2629bdceaf0d.png)

**Comment by meisnate12** [comment]
Not at the moment but it's a planned feature!
