### ISSUE TITLE
Smart Label Collection that is Empty Creates Multiple Copies of Collection

### ISSUE THREAD

**Issue by efaden** [Kometa-Team/Kometa#268]
I have a collection I am using for multiple libraries.  When that collection is run on a library that results in that collection having 0 items in it I wind up getting a new "collection" in plex for each run.  Instead of just leaving the one that is there.  

So it should either not create the smart label collection or only create it once.  Honestly not creating it at all would be ideal, but I would settle for just an empty collection.  But multiples is a problem.

<img width="508" alt="Screen Shot 2021-05-22 at 10 07 19 AM" src="https://user-images.githubusercontent.com/12599300/119229349-95e4a980-bae5-11eb-8fb6-358e1d708fa6.png">

**Comment by efaden** [comment]
This is the error it gives.... but it does exist.

<img width="756" alt="Screen Shot 2021-05-22 at 10 10 27 AM" src="https://user-images.githubusercontent.com/12599300/119229422-04c20280-bae6-11eb-9e06-8b6d73d50e9d.png">
<img width="681" alt="Screen Shot 2021-05-22 at 10 10 50 AM" src="https://user-images.githubusercontent.com/12599300/119229423-04c20280-bae6-11eb-84e9-5c159fb3c9da.png">

**Comment by meisnate12** [comment]
I'm planning on checking to make sure they a smart collection has items before I build it

**Comment by efaden** [comment]
Awesome.

**Comment by fdeross** [comment]
Came here to say the same things going on for me too. Thank you for all the hard work.

**Comment by meisnate12** [comment]
fix is in develop
