### ISSUE TITLE
Genre/year using plex_search not working with TV Shows

### ISSUE THREAD

**Issue by rbehal** [Kometa-Team/Kometa#27]
Applied a few plex_search collections for my TV shows library and they turned out empty even though I definitely have TV shows with these genres. Very strange, because it worked perfectly with my Movies Library, and I was also able to get other collections working with my TV Shows library (Star Wars from TVDB List). 

This is the plex_search portion of my current setup in TV Shows.yml:

```
collections:
  Animated TV Shows:
    plex_search:
      genre: Animation
    sort_title: ++_Animated TV Shows
    sync_mode: sync
    collection_order: alpha          
  Comedy TV Shows:
    plex_search:
      genre: Comedy
    sort_title: ++++_Comedy TV Shows
    sync_mode: sync
    collection_order: alpha
  Drama TV Shows:
    plex_search:
      genre: Drama  
    sort_title: ++_Drama TV Shows
    sync_mode: sync
    collection_order: alpha
```

It seems to be working perfectly fine with movies, with almost an identical setup. Added this after line 904 in config.py to see if I could debug a bit more

```
items = library.Plex.search(**search_terms)
items_found += len(items)
print("[DEBUG]: \n", library.Plex.search(genre=["Comedy"]))
```

and I was able to get a list for the Movies without an issue. However, with the TV shows it results in an "Unknown filter" error for both genre and year. Might be an issue on the end of PlexAPI or I could be doing something wrong here as well.

**Comment by doctarrwho** [comment]
I have the same issue, and it does appear to be an issue with PlexAPI. I was able to workaround this by using the following config instead for the TV Library. It appears to be slower vs a plex_search, but at least it works.

```
    '* Comedy':
        sort_title: "* Comedy"
        sync_mode: sync
        plex_all: true
        filters:
            genre: Comedy
```

**Comment by meisnate12** [comment]
yea this pull request will fix the errors so once it goes to the main release this will get fixed https://github.com/pkkid/python-plexapi/pull/598

**Comment by rbehal** [comment]
Perfect, makes sense, thank you! Might be nice to edit the [WIki ](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Plex-Builders) too for now. I would do it, but AFAIK Github doesn't support PRs for the Wiki stuff.

**Comment by meisnate12** [comment]
follow this PR for updates https://github.com/pkkid/python-plexapi/pull/693
