### ISSUE TITLE
Smart filters (??) somehow corrupting database

### ISSUE THREAD

**Issue by twhiting9275** [Kometa-Team/Kometa#280]
It seems that if there's nothing for a smart filter to build a collection on, it still tries to do so, and in the process corrupts the Plex movie library. Had this happen a few times on the people collection (quite a few of them in there I don't have), when set to validate : false

Every single time, the Plex process would kill itself, and the library would become corrupted, after the collection which should not be added (say, for example Alfred Hitchcock) was attempted to be added to Plex.

I DID verify this wasn't just that one name, once removed, it went on to others, stopped at the next name on the list that would have had none, Bruce Lee

Output from the log:
|=============================== Building Alfred Hitchcock Collection ===============================|
|                                                                                                    |
| Smart Movie Filter                                                                                 |
| Sort By: random                                                                                    |
| Validate: False                                                                                    |
| Filter:                                                                                            |
|   Match any of the following:                                                                      |
|                                                                                                    |
|========================= Updating Details of Alfred Hitchcock Collection ==========================|
|                                                                                                    |
|====================================================================================================|

At this point, the process just hangs until I kill it. It hangs, because Plex isn't running as it's killed itself

Solution:
Validate that there are filters to match. If not, move on to the next collection. 
Switching validate back to true , this doesn't happen, assuming because it's not actually trying to build those collections, but in THAT case, it only builds if strict conditions are met (actor+writer+director+producer)

**Comment by twhiting9275** [comment]
If it helps, this is running on Win10, no docker, straight Windows box.

**Comment by meisnate12** [comment]
If you use the latest develop it shouldn't be able to build blank smart collections like this. The issue was reported earlier to me on discord

**Comment by twhiting9275** [comment]
I'm using what's right here, available to download from github, as of a couple of days  ago, so 1.9.3

**Comment by meisnate12** [comment]
Try the develop branch
