### ISSUE TITLE
In windows , 'schedule' is frequently missed

### ISSUE THREAD

**Issue by twhiting9275** [Kometa-Team/Kometa#283]
So, I've run across an issue. I have a dedicated Plex box, Windows 10. Using Multiplicity, I can control both this, and my primary (work) PC, view what's going on, transfer files, etc. However, this box is not always 'active' per se. Since it's got a dedicated focus and purpose, I don't always login to it, turn that monitor on and see what's happening. I expect (rightly so) that processes are handled as they should be

Over the past couple of weeks, while running PMM, I think it's successfully scheduled, and run the nightly run, a handful of times. Most of the time, the PC clock will display the correct time, but according to PMM, 'current time' is off. See the image in https://imgur.com/a/X6Q7I5I for example. That's just the latest one (today's).

**Comment by twhiting9275** [comment]
It seems like what's happening here is the same thing that happened with previous iterations of the scripts. Python will from time to time just 'hang' , not do anything, and require some sort of input. I've seen this happen a few times on PMM, even when running, where it'll just sit there, frozen as it were, until I hit enter, then all of the sudden pick right back up

**Comment by meisnate12** [comment]
ive noticed the same behavior before but didn't realize it would affect pulling the current datetime from the system. The reason I display the current time is that sometimes when using docker the docker instance time will be off and I wanted people to know he it was running. I'll look into a way to fix the time issue,

PS nice background

**Comment by twhiting9275** [comment]
Why was this closed? It's certainly not fixed, or resolved by any means. Same behavior still today

If you look at what time the window thought it was, vs what time it actually is, you can see, this is still an issue, almost a year later, that has not been addressed properly

![Screen Shot 02-26-22 at 08 31 AM](https://user-images.githubusercontent.com/20139282/155847008-91adb5c8-754d-4a19-8cd4-3a8af0f9aa41.PNG)

**Comment by meisnate12** [comment]
It was closed because it's not really an issue with PMM. all PMM does is grab the system time if it's grabbing a time that differs the reason is because of something  special in your setup which would be extremely hard for me to figure out. 

And as for the occasional freezing and having to hit a key to get it going that's either some windows thing or python thing because like you said it happens with other versions of the script as well and I've had it happened before with completely different scripts too so it's not a PMM issue.

**Comment by twhiting9275** [comment]
There you go blaming others for your script failures, again.  Not the first time you’ve done this .  Might as well just call the project abandoned since it’s developer doesn’t want to fix their own bugs

**Comment by meisnate12** [comment]
This is a script I make in my free time. I'm sorry that I can't fix an issue with your setup that no one else reports. You're welcome to just not use it, but it far from abandoned.
