### ISSUE TITLE
Feature Request: Modify Posters to Contain HDR/4K/Dolby Vision/Remux Banners

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#287]
See: https://github.com/jkirkcaldy/plex-utills

If merging multiple file types into a single collection, that contains 4K, HDR, 4K HDR, Dolby Vision, etc, it would be cool if the program could add to the normal poster to include the 4k, hdr, etc banners.  See the above referenced project.

from efaden

**Comment by KrunchMuffin** [comment]
Add to this the audio as well. Atmos, DTS-X, etc.

**Comment by meisnate12** [comment]
your going to be able to make your own overlays
