### ISSUE TITLE
Feature Request - Add TAG to Radarr attributes

### ISSUE THREAD

**Issue by b101marc** [Kometa-Team/Kometa#29]
Is it possible to add the option to include a tag to all items added from running Meta Manager in the config?

**Comment by meisnate12** [comment]
not sure but ill look into it

**Comment by b101marc** [comment]
Appreciate it. Likely isn't possible but even implementing it in the metadata file for each collection would be truly ideal, to help in building each collection slowly.

**Comment by meisnate12** [comment]
so this is possible can you explain what tags are used for in radarr?

**Comment by b101marc** [comment]
I suppose that's different for everyone, but personally I use tags to sort various collections of movies (since I use the Lists feature quite extensively). If only possible to add one tag to the Media added from PMM, it would allow me to see only those movies added after the script has run.

**Comment by meisnate12** [comment]
Yea i can have it add multiple tags. I was thinking of putting a library level attribute `arr_tag` under radarr/sonarr (Gotta make it work for both) and then have it possible to add `arr_tag` at the collection level to override the library level attribute

**Comment by b101marc** [comment]
Sounds great. Important to note with the tag function in the arrs is that it will only apply to new items added. It doesn't go back and tag items already in the library.

**Comment by meisnate12** [comment]
correct because the request is denied if the movie is already in radarr/sonarr

**Comment by meisnate12** [comment]
ok this is in develop. Use `tag` under the radarr or sonarr attribute and specify a comma separated list of tags to go on every movie that goes through radarr. Alternatively, you can use the attribute `arr_tag` under any collection and specify a comma separated list of tags to set just that collection to the tag specified

**Comment by meisnate12** [comment]
can you test?

**Comment by b101marc** [comment]
Testing now, will let you know shortly.

**Comment by b101marc** [comment]
Tested both methods and worked great. Thanks so much.
