### ISSUE TITLE
Feature Request: Tag existing movies in radarr with the collection name (or else)

### ISSUE THREAD

**Issue by theotocopulitos** [Kometa-Team/Kometa#290]
The problem is that radarr allows to add tags to movies grabbed form a list, but it will only tag newly added movies, no already existing ones.

This feature is an addition to how PMM interacts with radarr: now it can add and tag missing movies; this feature would tag existing movies.

**Comment by meisnate12** [comment]
added `item_radarr_tag`, `item_radarr_tag.sync`, `item_radarr_tag.remove`, `item_sonarr_tag`, `item_sonarr_tag.sync` and `item_sonarr_tag.remove` which can be used to edit the tags of the movies/series in the collection in radarr/sonarr.

**Comment by theotocopulitos** [comment]
Sounds great, cannot wait to have this in the master branch, and be able to test it! Thanks
