### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by paulmcclellan** [Kometa-Team/Kometa#293]
Since the 1.10.0 upgrade, I receive the following errors.  It appears to start with a Trakt authentication error, which I believe is bogus.  This is in an Unraid docker.  

Note it executes  manually  (python3 plex_meta_manager.py --run) but not automatically.  

| |
| ____ _ __ __ _ __ __ |
| | _ \| | _____ __ | \/ | ___| |_ __ _ | \/ | __ _ _ __ __ _ __ _ ___ _ __ |
| | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__| |
| | __/| | __/> < | | | | __/ || (_| | | | | | (_| | | | | (_| | (_| | __/ | |
| |_| |_|\___/_/\_\ |_| |_|\___|\__\__,_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_| |
| |___/ |
| Version: 1.10.0 |
|====================================================================================================|
| Starting 03:00 Run |
|====================================================================================================|
| Locating config... |
| Using //config/config.yml as config |
|====================================================================================================|
| Using cache database at //config/config.cache |
|====================================================================================================|
| Connecting to TMDb... |
| TMDb Connection Successful |
|====================================================================================================|
| omdb attribute not found |
|====================================================================================================|
| Connecting to Trakt... |
| Refreshing Access Token... |
| Navigate to: https://trakt.tv/oauth/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code |
| If you get an OAuth error your client_id or client_secret is invalid |
| |
|====================================================================================================|
| Finished 03:00 Run |
| Run Time: 0:00:00 |
|====================================================================================================|
| Traceback (most recent call last): |
Error in sys.excepthook:
Traceback (most recent call last):
File "/modules/util.py", line 333, in my_except_hook
print_multiline(line, critical=True)
File "/modules/util.py", line 325, in print_multiline
logger.handlers[1].setFormatter(logging.Formatter(" " * 65 + "| %(message)s"))
IndexError: list index out of range

Original exception was:
Traceback (most recent call last):
File "//plex_meta_manager.py", line 487, in <module>
hours = int(seconds // 3600)
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

**Comment by meisnate12** [comment]
this is fixed in develop
