### ISSUE TITLE
Feature Request: Summary of "Missing" Season Posters from Assets Folder

### ISSUE THREAD

**Issue by trogdorsmith** [Kometa-Team/Kometa#295]
Would it be possible to spit out a summary of shows that there are more seasons of a show in plex than there are posters in the assets folder? 
For example, I have season posters for 1-12 in the folder and when season 13 comes out, I need to go find the poster for that season. Ideally only for shows that exist within the assets folder, and not shows I don’t have local posters for.

**Comment by meisnate12** [comment]
Added `show_missing_season_assets` under settings
