### ISSUE TITLE
Feature Request: Log output of files found in Assets folder that do not match

### ISSUE THREAD

**Issue by trogdorsmith** [Kometa-Team/Kometa#296]
If I mislabel a folder in the assets folder, the only way I can verify it didn't apply is to look at the posters in plex. It would be great if the log could show files it finds, but does not match.

You Rock!

**Comment by meisnate12** [comment]
so instead of show unmatched files in the assets folder how do you feel about just letting you know when an assets folder is not found during the collection run

**Comment by trogdorsmith** [comment]
That would be great!
