### ISSUE TITLE
item_episode_ordering not being applied anymore

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#297]
I just tried adding a new show to change item_episode_ordering and noticed it wasn't being applied. I went back and tested the previous working examples I had and they aren't working anymore either.

Logs don't show any useful errors, but I am running version 1.10.0 on develop

Here's an example of my YML

```
  "Show Name":
    item_episode_ordering: tvdb_aired
```

**Comment by meisnate12** [comment]
ok ill look into it

**Comment by meisnate12** [comment]
so this is still working for me can you give me your collection.log for a collection where its not working

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Well that last comment cleared it up - this is an error with my YML.

I copied an example from a collection and didn't remove the "item_" prefix. Using just episode_ordering fixes it.
