### ISSUE TITLE
Collection posters updating both collections and shows/movies if the names match

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#307]
I have a collection that matches the name of a show, so when PMM tries to set the collection poster it sees that it matches the show name and changes both. In this example I just need it to update the collection's poster and leave the show poster alone.

If there was an option to make PMM only look at assets for collections, that could be a quick fix to this issue. I let Plex handle local assets on it's own, so this is only an issue with collections: https://support.plex.tv/articles/200220677-local-media-assets-movies/

**Comment by meisnate12** [comment]
ok now by default collections wont check for item assets and you can add `item_assets: true` to any collection to have it check for assets

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
You say collections won't check for items assets, did you mean shows/movies won't check for assets by default? If collections don't check for assets by default now, then the problem with it overriding the show's poster will still happen (on top of the 150+ new lines I'll need to add)

**Comment by meisnate12** [comment]
yes that is what i ment haha

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Looks like that's working :+1: Thanks for getting to it so quickly
