### ISSUE TITLE
Script doesn't like folder names with ' in them

### ISSUE THREAD

**Issue by xela-nosretap** [Kometa-Team/Kometa#310]
I have a series called `Clarkson's Farm` which I have in a folder called `Clarkson's Farm (2021)`

I have created a folder in the assets directory with the same name but any posters, backgrounds or episode images aren't being picked up by the script.

I'm assuming it is because of the `'` in the folder name.

Obviously as a work around I can rename the folder but this is the name that Sonarr automatically gave it and I'd rather not have to rename things if I didn't have to.

**Comment by meisnate12** [comment]
you shouldnt have to rename the folder. was this working previously and just stop working or was it never working at all?
Also how are you trying to update the assets for the item? (like which method are you using)

**Comment by meisnate12** [comment]
Also its not because of `'` i just ran a test that was able to work with a file that has a year and `'` in its folder name

**Comment by xela-nosretap** [comment]
I have `asset_folders` and `assets_for_all` set to `true`, I put the folder called `Clarkson's Farm (2021)` in my assets directory and ran the script and in the folder I have files named `S01E01.png`, `S01E02.png` etc.

This seems to be working for all other series I have done it with except this one and I assumed it was just because of the `'` in the folder name.

**Comment by meisnate12** [comment]
are you using the develop branch if not can you try it on the develop branch and then send me the meta.log

**Comment by xela-nosretap** [comment]
I'm using the develop branch, still isn't picking up the folder. Should I just paste the content in here, pastebin or email it to you?

**Comment by meisnate12** [comment]
Pastebin or git gist either works

**Comment by xela-nosretap** [comment]
https://gist.github.com/alexander-paterson/8fdeebe748befa325ae83759f393fe24

**Comment by xela-nosretap** [comment]
So, I've nuked my git folder and re-downloaded the dev repo, now when I run the script the show I was having issues with has had its images changes.

Not sure what the issue was, maybe I didn't update/change to the dev repo. I guess this can be closed now.
