### ISSUE TITLE
Read Time Out Error

### ISSUE THREAD

**Issue by ccigas** [Kometa-Team/Kometa#311]
Just started with this program today and the set up was easy but running into issues with scanning my library and it seems one other thing but I think that is a IMDb issue? 

` Mapping Error | plex://movie/5f40d613cae2c600420d5d5f          | Unable to convert IMDb ID: tt8075016 to TMDb ID for The Courier |
| HTTPConnectionPool(host='streamer.name.home', port=32400): Read timed out. (read timeout=30)      `

The HTTP connection pool is stalling out on one Movie, specifically Fight Club which kind of seems fitting. Not really sure if its a problem with a file causing the hang up or what so thought I would ask. It is about my 359 movie so it got pretty far before stalling out and it was the first movie it tried on retry since cache. 

As for the Courier IMDb issue, I am assuming thats an IMDb issue right? Nothing for me to really do?

Thanks!

**Comment by meisnate12** [comment]
It's really weird that it keeps erroring out on the same movie. Try doing the plex dance with that movie (remove and readd it)

As for the IMDb error there is something you can do if you want it to match. Go to TMDb and login to your account find the movie and edit it's metadata data and add it's IMDb ID. Then next time you run PMM it will pick that up

**Comment by ccigas** [comment]
> It's really weird that it keeps erroring out on the same movie. Try doing the plex dance with that movie (remove and readd it)
> 
> As for the IMDb error there is something you can do if you want it to match. Go to TMDb and login to your account find the movie and edit it's metadata data and add it's IMDb ID. Then next time you run PMM it will pick that up

That fixed it thank you. Was able to run a libraries only after a full run and was able to pull in the new download. Quick quesiton since I cant find out how to do this anywhere at the moment, how do I get rid of the Actors collections the script makes?

**Comment by meisnate12** [comment]
if you just need to get ride of them in plex just delete them

if you want PMM to no longer create them in your config.yml when you define your metadata files one should say `git: meisnate12/People` this runs the metadata file that in the configs repo [here](https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/meisnate12/People.yml) 

each one of those git lines runs a different metadata file in the git referenced above
