### ISSUE TITLE
Feature Request: Add ability to split versions apart

### ISSUE THREAD

**Issue by cpt-kuesel** [Kometa-Team/Kometa#313]
While playing with the new overlay feature I recognized I would like to split versions of the same movie apart through PMM rather than doing it manually in Plex GUI.

![image](https://user-images.githubusercontent.com/79487102/124196599-0ad7d580-dacd-11eb-9f9c-d219fd2a532e.png)

**Comment by meisnate12** [comment]
add `split_duplicates: true` to you library setup in your config.yml to split all duplicates at the beginning of your run.
