### ISSUE TITLE
Radarr V4 nightly not getting connecting 

### ISSUE THREAD

**Issue by melbasuonyy** [Kometa-Team/Kometa#315]
I am trying to use PMM but I'm getting the below error from docker log

![image](https://user-images.githubusercontent.com/29347988/124352289-9a39d180-dc10-11eb-88bd-e0e3c3c53a4a.png)

![image](https://user-images.githubusercontent.com/29347988/124352330-b89fcd00-dc10-11eb-8109-bceb8fc8ef82.png)

**Comment by meisnate12** [comment]
I your config folder you should have a logs folder can you send me your meta.log

**Comment by melbasuonyy** [comment]
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6758530/meta.log)

here you go

**Comment by meisnate12** [comment]
ok added some more error checking can you grab the latest dev branch, try again, and then send me the log (It will still fail i just need more info)

**Comment by melbasuonyy** [comment]
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6758637/meta.log)
New Logs

**Comment by meisnate12** [comment]
Ok thanks I'll have to set up a test instance for radarr v4 and figure out what's going on so it could be a couple days

**Comment by meisnate12** [comment]
ok the latest develop should fix the issue you have the install requirements again if you're not using docker
