### ISSUE TITLE
Feature Request: Sync personal Trakt Ratings with Plex User Ratings

### ISSUE THREAD

**Issue by Wdvh** [Kometa-Team/Kometa#316]
Add the stars from trakt to Plex if possible as half stars.

**Comment by meisnate12** [comment]
added `mass_trakt_rating_update` to settings defaulting to False when set to True it will update the user rating of all movies in your library with any trakt ratings you have

**Comment by Wdvh** [comment]
Works like a charm for movies and tv shows. Would be nice if it would pull them at season and episode level too but is a low level priority.
