### ISSUE TITLE
Feature Request: Emby & Jellyfin Support

### ISSUE THREAD

**Issue by darthShadow** [Kometa-Team/Kometa#321]
**Is your feature request related to a problem? Please describe.**
Add Emby support for Collections.

**Describe the solution you'd like**
Add Emby support for Collections.

**Describe alternatives you've considered**
N/A

**Additional context**
Emby API Docs: https://swagger.emby.media/?staticview=true#/

Smart Collections depends on this Feature Request to be added: https://emby.media/community/index.php?/topic/36916-smart-playlists/

**Comment by sparky002** [comment]
Jellyfin uses a similar API as well, so this could be a Emby/Jellyfin addition. =) 

- This is one thing Jellyfin/Emby has to automatic collections. https://github.com/jellyfin/jellyfin-plugin-tmdbboxsets

- It creates movie collections based on TMDB collections for movies. Very restrictive and no choice as to which movie collections to grab.

- A closer implementation to "Plex-Meta-Manager" https://github.com/mcarlton00/jellyfin-collections is actually the pre-successor to Jellyfin's C# plugin linked above. This is a python script in a cut down form of the published plugin.

- Another few good resources that use python to translate plex playlists/users/watch-history to jellyfin: https://github.com/nwithan8/Plex2Jellyfin and https://github.com/wilmardo/migrate-plex-to-jellyfin

-    This may help speed up implementation of Jellyfin's/Emby's api into "Plex-Meta-Manager".

**Comment by pekempy** [comment]
Would love JF too, would make keeping my collections between Plex/JF instances consistent a lot easier.

**Comment by JourneyOver** [comment]
+1 Would love to see this as well, as I have been thinking more and more on switching to jellyfin and it would be nice to have a nice meta manager to go along with it.

**Comment by iamwoz** [comment]
Recently moved to Emby. So much more performant and stable than Plex. I miss PMM so much though!

**Comment by iamwoz** [comment]
As Plex continues to try to find ways to monetise (https://www.plex.tv/blog/end-the-streaming-struggle-with-plex/) I expect we're gonna see a bump in migrations from Plex to Emby and JF. Would be a great time to get PMM becoming a multi platform tool 🙏

**Comment by karan** [comment]
I believe the box sets plugin functionality is now part of Jellyfin itself (much like Plex). Would still love the ability to apply my PMM configs to JF.

**Comment by Protektor-Desura** [comment]
I would love to see this support Jellyfin as well. I've moved away from Emby since it is no longer open-source and is exactly the same as Plex in that to fully unlock Emby you need to pay, like Plex and both Plex and Emby are closed source programs now.

**Comment by yeyeoke** [comment]
This would be a great addition! Right now I’m running Plex parallell to Jellyfin but I’m certain that in the future plex is going to be replaced by Jellyfin.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/emby-jellyfin-support)
