### ISSUE TITLE
Duplicates in Collections

### ISSUE THREAD

**Issue by Breakingx** [Kometa-Team/Kometa#323]
Hey, firstly thanks for this awesome program!

After running the config template all Colletions are duplicated. I can delete one duplicated collection without the other so they are indepentend?

Any way to fix this? I have the default setup of the program.

**Comment by meisnate12** [comment]
are the collections named the exact same thing? if you delete both and run does PMM create two again?

**Comment by Breakingx** [comment]
Weird. They are named exact the same. Deleting both of them has the same result after restarting the script two playlist with the same name appear. But deleting just one fixes it (?) the duplicate doesn't appear.

**Comment by meisnate12** [comment]
you typed playlist but you meant collection right? Ill look into this

**Comment by Breakingx** [comment]
oh yeah. I mean collection. Thanks! :)
