### ISSUE TITLE
Feature Request: Raspberry Pi Support

### ISSUE THREAD

**Issue by Breakingx** [Kometa-Team/Kometa#327]
Hey, currently the docker image isn't working on a raspberry pi system.
Maybe it is possible to give a docker-compose.yml for portainer?

Example:
sudo docker run -it -v "/srv/dev-disk-by-uuid-7fee3a3d-367f-4931-91bd-c9dfd7b20d59/AppData/Plex Meta Manager\config:/config:rw" meisnate12/plex-meta-manager

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

**Comment by 2fst4u** [comment]
More generically, arm support. It would be awesome if the docker image supported arm, then we can use it on raspberry pi instead of needing a more power hungry machine to run the script.

Thanks.

**Comment by SolidRhino** [comment]
Please add this option.

Here is an overview how to do this https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

**Comment by meisnate12** [comment]
Unfortunately that doesn't tell me what I need to know. I know how to make docker builds and use GitHub actions. The problem I'm having with this is I don't know what's required of a Dockerfile for it to work on a raspberry pi.

**Comment by SolidRhino** [comment]
@meisnate12 I can test the builds. Or I can try to help you create the builds.

**Comment by SolidRhino** [comment]
> Unfortunately that doesn't tell me what I need to know. I know how to make docker builds and use GitHub actions. The problem I'm having with this is I don't know what's required of a Dockerfile for it to work on a raspberry pi.

The base image you use is already Raspberry Pi (ARM) compatible. So I think the only thing that is needed is to build the docker file on an ARM computer like a Raspberry Pi. This is done with the GitHub actions in the article above.

**Comment by meisnate12** [comment]
i think my develop image now supports arm if anyone wants to test

**Comment by 2fst4u** [comment]
Works brilliantly, thanks so much.

**Comment by fafoulon** [comment]
Hi,
How did you manage to install it with docker on your raspberry? I tried the master or the develop branch, but I only get this error:

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by meisnate12** [comment]
i added `linux/arm64` image but whenever i try to add `linux/arm/v7` the build just fails

**Comment by fafoulon** [comment]
@2fst4u How did you manage to use it on your raspberry?

**Comment by 2fst4u** [comment]
@fafoulon @meisnate12 I'm just running the Dev branch. Maybe I started running it prior to builds having issues because the script is still running daily for me.

**Comment by meisnate12** [comment]
You're probably running a newer OS  on your pi is it a 3 or a 4?

**Comment by fafoulon** [comment]
Yes, I have a Pi 4. Am I doomed? 😀

**Comment by 2fst4u** [comment]
Ah good catch I missed that. Yes I'm running a 64 bit os.

@fafoulon if you have a raspberry pi 4, look into running a 64 bit os on it. I run the official Ubuntu raspberry pi image.

**Comment by fafoulon** [comment]
No hope it will work on the 32bit of arm? I already have lots of stuff installed on that Pi...

**Comment by 2fst4u** [comment]
Great news, you're running docker so transferring things over should be easy ;)

**Comment by meisnate12** [comment]
I'll look into adding the image again that was failing

**Comment by fafoulon** [comment]
Ok, thanks

**Comment by fafoulon** [comment]
Just tell me if you want me to test it out

**Comment by jfgoncalves** [comment]
32 bits support for those of us using Raspberry Pi OS would be very appreciated. I tried running a version of Ubuntu arm64 previously but that came with its bag of problems.
