### ISSUE TITLE
Feature Request: Automatically create movie folder for assets

### ISSUE THREAD

**Issue by Breakingx** [Kometa-Team/Kometa#328]
Is it possible to automatically create the asset folder of the movies, for example inside the, for example "Pixar Movies"-Collection? That would spare many hours of work. But only if the movie is already on plex, otherwise there would be thousands of movie folders.

ADDITION: All movies got some extension like "Title_1080p_x265" maybe thats a thing you could consider.

Maybe it is even possible to grab the current poster and background and put it into the folder?

**Comment by meisnate12** [comment]
Added `create_asset_folders` to settings which defaults to False to use it you must be using `assets_for_all` and `asset_folders`
