### ISSUE TITLE
Feature Request: Use the TVDb as a metadata agent 

### ISSUE THREAD

**Issue by isaacolsen94** [Kometa-Team/Kometa#334]
It would be nice to be able to use the "tvdb_show" and similar tags under the metadata label. I'll call out my problem below, but in general I think the option to pull metadata from that source would be a good alternative to TMDb. 

**Is your feature request related to a problem? Please describe.**
My particular problem is that "The Bad Batch" for the Plex agent isn't working for me, but I can pull the info from TMDb. However, the info isn't has good as TVDb and since I'm pointing to TMDb it removed it from my Star Wars collection (I'll attach the terminal output). 

**Describe the solution you'd like**
So with all the being said I'd like to change my call out under metadata from: tmdb_show: 105971   to:  tvdb_show: 385376

**Additional context**
![image](https://user-images.githubusercontent.com/52682311/125388258-7129e700-e35c-11eb-9c77-ad0b0687f24a.png)

![image](https://user-images.githubusercontent.com/52682311/125388345-94549680-e35c-11eb-9414-67ca21db1854.png)

**Comment by meisnate12** [comment]
tvdb doesnt have the fields i need for this so im going to close until their api is open and has the right fields

`tmdb_movie` and `tmdb_show` were not designed to fill in metadata that should be taken care by your agent these are here so if you have a show compiled as a movie you can use tmdb_show to get the right metadata and visa versa
