### ISSUE TITLE
Feature Request: Adding overlays to tv show episodes 

### ISSUE THREAD

**Issue by cpt-kuesel** [Kometa-Team/Kometa#345]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.
I want PMM to be able to apply overlays to a title card of a tv show episode.

**Describe the solution you'd like**
I am using overlays with country flags to signal to my users which audio languages are available for a given media item.
This is working flawlessly for movies, but for tv shows adding an overlay to the show poster is often not true for every single episode in the series. 
To be able to apply a label to the episode title card in a similar fashion as is already possible for movies and show posters is helpng me tell my users that only watch content in a certain audio language which episodes can be watched. Also they can raise issues more easily when they are watching a show and they can see immediately that some episodes don't have the expected overlay.

**Describe alternatives you've considered**
Applying the overlay manually outside of PMM and letting PMM only apply a new title card is certainly possible for a few shows but definitely not feasible for every single episode in my library. So a solution to automate it would be greatly appreciated.

**Additional context**
My overlays and my initial idea for the collection builder can be found here: https://github.com/meisnate12/Plex-Meta-Manager-Configs/tree/master/cpt-kuesel

**Comment by KnifeFed** [comment]
I guess this would also be the only way to add Dolby Vision overlays to TV shows/episodes? Or is there already a way to do that?

**Comment by meisnate12** [comment]
no way for episode overlays yet

**Comment by Shayne55434** [comment]
Hate come off as naggy, but is there an update on this? Happy to help in any way I can. Whether that's testing, providing logs, or whatever.

**Comment by YozoraXCII** [comment]
> Hate come off as naggy, but is there an update on this? Happy to help in any way I can. Whether that's testing, providing logs, or whatever.

Not at all naggy :) This isn't implemented yet, Dynamic Collections were the primary focus for v1.16 which was recently released  and I believe that this is part of the focus for the next major release (guessing v1.17)

**Comment by Shayne55434** [comment]
> > Hate come off as naggy, but is there an update on this? Happy to help in any way I can. Whether that's testing, providing logs, or whatever.
> 
> Not at all naggy :) This isn't implemented yet, Dynamic Collections were the primary focus for v1.16 which was recently released and I believe that this is part of the focus for the next major release (guessing v1.17)

Awesome! Thanks for the update. :-)

**Comment by zhdenny** [comment]
I would love to apply this feature to create a Dual-Audio overlay for Anime Episodes

**Comment by meisnate12** [comment]
Added in 1.17.0
