### ISSUE TITLE
Feature Request: Order by trakt list rank in plex collections?

### ISSUE THREAD

**Issue by stevezau** [Kometa-Team/Kometa#346]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to order the items in the plex collection by the rank in trakt list. Is this possible?

**Describe alternatives you've considered**
None

**Comment by meisnate12** [comment]
Duplicate of #308

**Comment by Juansit0** [comment]
How this feature coming along? @meisnate12

Not to bug or rush you or anything
