### ISSUE TITLE
Feature Request: Minimum Items for a Collection

### ISSUE THREAD

**Issue by extrobe** [Kometa-Team/Kometa#356]
**Is your feature request related to a problem? Please describe.**
Not wanting collections with only 2 items, but without having to remove the config for that collection

**Describe the solution you'd like**
Being able to set (either at a library level or a collection level) the minimum number of items you should have in your library from that collection before it creates that collection in your library.

eg, If you set your minimum as 3, the collection has 5, but you only have 2 of them, it doesn't create that collection

**Describe alternatives you've considered**
The alternative if removing the config from your collections file until you're ready to use it.

**Comment by meisnate12** [comment]
added `collection_minimum` and `delete_below_minimum` to develop
