### ISSUE TITLE
Bug: config.yml keeps getting auto-indented with 4 spaces after PMM adds a new setting

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#363]
**Describe the Bug**
My config.yml is indented with 2 spaces, after running PMM the file gets overridden with a 4 space indent. This has been driving me crazy, and I actually didn't notice until writing up this bug that it was because it was adding a new setting to the config - "missing_only_released".

**Relevant Collection Config**
There's nothing specific to show for this bug, everything happens in config.yml. My YML files for Movies and Shows are unaffected, but  would probably be affected if there were a future auto-correcting function for anything in those files.

To replicate this, just remove the config.yml setting "missing_only_released" and indent your YML more or less than 4 spaces.

**Plex Meta Manager Info**
Version: 1.12.0

**Link to logs (required)**
https://gist.github.com/ngInit/22bbd0070dc2a7c4a37f238e4122c0d2

Ideally if we're adding missing settings this way, it would indent to whatever the file was previously indented to

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Update: It's actually overriding the file whether or not it's trying to add a missing setting. After running it again with that new setting that was added, there are no longer any errors in the logs and it still re-indents the entire file.

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Update 2: It also removes anything you had commented out, which would be a bigger problem than it is if I didn't already have the file open in an editor that can Ctrl+Z undo it.

**Comment by meisnate12** [comment]
its due to me trying to make PMM work with any version of the config file I've had I could probably turn it off by now because you'd have to be upgrading from like 1.3.0 or before to need the feature ill look into redoing that section and getting it working better

**Comment by meisnate12** [comment]
ok i think i fixed this

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Seems like it's fixed on my end - Good works as always
