### ISSUE TITLE
Feature Request: Support selecting plex server by friendlyName

### ISSUE THREAD

**Issue by jenil** [Kometa-Team/Kometa#364]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding a config var to select the Plex server based on name and filtering based on `friendlyName` when running the script

**Comment by meisnate12** [comment]
im not sure what your asking for

**Comment by jenil** [comment]
@meisnate12 Users can have multiple plex servers on their account and might want to run the scripts only on a "selected" server. I think there should be an option to choose the plex server based on the "Friendly name" of the server

<img width="784" alt="Screen Shot 2021-08-17 at 12 25 09 PM" src="https://user-images.githubusercontent.com/971411/129764095-74b3a931-cfa7-4052-8490-b5644e3de535.png">

**Comment by jenil** [comment]
my bad, it seems like the URL+token combination points only to 1 server even if the user has multiple servers on their account.
