### ISSUE TITLE
Feature Request: ability to create tv episode collections

### ISSUE THREAD

**Issue by jacobc1204** [Kometa-Team/Kometa#365]
**Is your feature request related to a problem? Please describe.**
Currently you can only add entire series to a collection, but episode collections are possible in plex.

**Describe the solution you'd like**
I would like to be able to create tv collections based on trakt lists that add just specific episodes instead of the entire series like for a Halloween and Christmas collection for example. Like [this](https://trakt.tv/users/efreakiel/lists/halloween-tv-episodes)

**Describe alternatives you've considered**
Using plex-trakt-scobbler to bring the list into plex as a playlist, but a collection is preferred because it can be added to the homescreen for everyone. 

**Additional context**
I just want all encompassing Halloween and Christmas tv episode collections.

**Comment by justinxfisher** [comment]
Just chiming in to say this would be beneficial for a trakt list like this, [The Essential X-Files Episodes](https://trakt.tv/users/travisg100/lists/the-essential-x-files-episodes?sort=rank,asc), which only includes some episodes within a single series.

I tried making this the other day and it adds the entire series.

**Comment by meisnate12** [comment]
ive got this almost done

**Comment by meisnate12** [comment]
added `collection_level` as a Collection Detail you can give it either `season` or `episode` to create a collection of that type. You can only use `plex_search` and `trakt_list` with `season` or `episode` but it should work well if you add `collection_order: custom` as well.

Note. Plex doesn't allow shows in season or episode collections, doesn't allow seasons in show or episode collections, and doesn't allow episodes in show or season collections. Basically, you can't combine shows, seasons, and episodes into the same collection.

Note 2. How season and episode collections play on your players and if they actually play in order could vary. i have a player that will play them in order but only from the beginning and then one player that just goes to that spot in the show and then just plays the next episode in the show order, not the collection order.

For either of the Notes to change we would have to bitch at Plex lol
