### ISSUE TITLE
Feature Request: Other Videos Library Support

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#366]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup a Music VIdeos "Other Videos" type library with PMM handling the metadata. 

**Describe the solution you'd like**
An Other Videos library is essentially just a Movie library, so I don't think it should be too difficult adding a check for it

**Describe alternatives you've considered**
Because Other Videos type libraries don't connect to any online data sources, everything would have to be manually edited, which of course is all work that would be thrown out if you ever need to rebuild the library.

**Comment by meisnate12** [comment]
this should already work just treat it like a Movie library. `plex_search` and `smart_filter` will still work as well

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
You're right, I had some other issue with the YML file I was using to test it.

I think what was throwing me off from finding that out is that there is a lot of Mapping error log spam for this type of library. I currently only have 2 videos that I was testing, so it's not that bad yet. But it'll quickly grow out of control as I fill out the library.

Here's what I'm talking about

```
|=================================== Mapping Music Videos Library ===================================|
|                                                                                                    |
| Loading All Movies from Library: Music Videos                                                      |
| Loaded 2 Movies                                                                                    |
| Mapping Movie Library: Music Videos                                                                |
|                                                                                                    |
| Mapping Error | com.plexapp.agents.none://7660da242943a6921f4cbbb9779d9a4ad9449743?lang=xn | Agent none not supported for SonReal — Hot Air Balloon |
| Mapping Error | com.plexapp.agents.none://dfd0c113202738ca5943401929d86e2e4e280466?lang=xn | Agent none not supported for Tenacious D — Rize of the Fenix |
|                                                                                                    |
| Processed 2 Movies                                                                                 |
|                                                                                                    |
|====================================================================================================|
```

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Instead of hiding the mapping errors, it might even make things faster to just skip those checks in the first place for Other Videos library. I don't think there's an example where they'd ever map correctly...
