### ISSUE TITLE
Bug: Trakt Trending collection failing with error Unknown Error: 'type'          

### ISSUE THREAD

**Issue by vaparr** [Kometa-Team/Kometa#367]
|=================================== Building Trending Collection ===================================|
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Builder: trakt_trending: 66                                                                        |
|                                                                                                    |
| Processing Trakt Trending: 66 Movies                                                               |
| Traceback (most recent call last):                                                                 |
|   File "//./plex_meta_manager.py", line 487, in run_collection                                     |
|     builder.find_rating_keys()                                                                     |
|   File "/modules/builder.py", line 1091, in find_rating_keys                                       |
|     ids = self.config.Trakt.get_trakt_ids(method, value, self.library.is_movie)                    |
|   File "/modules/trakt.py", line 221, in get_trakt_ids                                             |
|     return self._pagenation(method[6:], data, is_movie)                                            |
|   File "/modules/trakt.py", line 193, in _pagenation                                               |
|     return self._parse(items, typeless=pagenation == "popular", item_type="movie" if is_movie else "show") |
|   File "/modules/trakt.py", line 160, in _parse                                                    |
|     id_type = "tmdb" if item["type"] == "movie" else "tvdb"                                        |
| KeyError: 'type'                                                                                   |
|                                                                                                    |
| Unknown Error: 'type'                             

Config looks like:

    Trending:
        sort_title: "*110"
        smart_label: audience_rating.desc
        trakt_trending: 66
        tmdb_trending_weekly: 66
        sync_mode: sync
        radarr_add: true
        run_again: false
        visible_library: true
        visible_home: true
        visible_shared: true
        trakt_list:
          - https://trakt.tv/users/infi704/lists/top-movies-of-the-week-excluding-netflix?sort=rank,asc            

Running latest develop docker: (Works in latest)

meisnate12/plex-meta-manager:develop 

Edit: Looks like removing this line fixes it:
#        trakt_trending: 66

**Comment by meisnate12** [comment]
its fixed in develop
