### ISSUE TITLE
YAML Error: mapping values are not allowed here

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#37]
I'm noticing consistent YAML errors that I can't find the source of in either my config.yml or my movies.yml file. The error is

```
 YAML Error: mapping values are not allowed here
               in "<unicode string>", line 4741, column 10:
                     19666: 'Lagaan: Once Upon a Time in I ... 
                          ^ (line: 4741) |
```

I see it repeated over and over in my logs. Neither my config.yml or movies.yml file has a line 4741 though. I also see that this is a reference to a movie I don't even have in my collection or yml files. 

https://www.imdb.com/title/tt0169102/

Any ideas what else I can check?

**Comment by meisnate12** [comment]
if you notice next to your movies.yml there should be a movies_missing.yml that saves all the movies list as missing in your collections. delete that file and re run and see if the error still occurs 

cab you also send me your meta.log file so i can see where exactly in the code this is occuring

**Comment by Tharic99** [comment]
Removing the movies_missing.yml file appears to have resolved this. It's running through now, but it'll be a few hours to complete. My log's usually around 5mb or 6mb in size, just as an FYI. Not sure if it would still help since the error appears to be gone with the movies_missing.yml file being deleted.

**Comment by meisnate12** [comment]
its cool im rewriting that whole section anyways to hopefully not ever have this error again
