### ISSUE TITLE
Feature Request: audio_language collection filter for show libraries

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#372]
**Is your feature request related to a problem? Please describe.**
audio_language collection filter doesn't work for show libraries. Says it's only available for movie libraries in the logs, but I went in to the Plex Web UI and that filter exists and works for show libraries too.

**Relevant Collection Config**
config.yml
```
collections:
  "Crunchyroll":
    plex_search:
      genre:
        - Anime
        - Animation
    filters:
      audio_language.not: English
      filepath: Anime
```

**Link to logs (required)**
```
[2021-08-29 23:12:40,337] [builder.py:518]            [DEBUG]    | Validating Method: filters                                                                         |
[2021-08-29 23:12:40,337] [builder.py:519]            [DEBUG]    | Value: ordereddict([('audio_language.not', 'English')])                                            |
[2021-08-29 23:12:40,339] [util.py:144]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 470, in run_collection
                                                                 |     builder = CollectionBuilder(config, library, metadata, mapping_name, no_missing, collection_attrs)
                                                                 |   File "/modules/builder.py", line 555, in __init__
                                                                 |     elif method_name == "filters":                                              self._filters(method_name, method_data)
                                                                 |   File "/modules/builder.py", line 1055, in _filters
                                                                 |     raise Failed(message)
                                                                 | modules.util.Failed: Collection Error: audio_language.not filter attribute only works for movie libraries
                                                                 | 
[2021-08-29 23:12:40,339] [util.py:141]               [ERROR]    | Collection Error: audio_language.not filter attribute only works for movie libraries
```

![image](https://user-images.githubusercontent.com/38122413/131268701-12978d02-5e04-45b9-90bd-8dd80ef3b2d9.png)

**Comment by meisnate12** [comment]
Use it under the plex_search not under filters

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Alright. How would that work for this collection then, because the studio requirement is independent of the plex_search, but the filter would need to apply to both.

```
  "FUNimation":
    studio.begins: FUNimation
    plex_search:
      genre:
        - Anime
        - Animation
      audio_language: English
    filters:
      audio_language: English
```

**Comment by meisnate12** [comment]
Studio.begins is just a one line plex search

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Right... I thought you could only have one plex_search per collection

**Comment by meisnate12** [comment]
Is that in the wiki somewhere because you can have more then one using a list but you should be able to combine all that into one plex search

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
In the wiki it just says use any or all, which I'm apparently not doing. (I'm assuming it defaults to one of them)

If there is a way to do more than one plex_search, I don't see an example anywhere.

They can't both be under the same plex_search, unless I'm misunderstanding plex_search.
If I were programming this, I would want:
```
if ( (genre === "Anime/Animation" || studio.begins === "FUNimation") && audio_language === "English") { }
```
and with my understanding of plex_search, I would actually be doing this if I combined them
```
if ( (genre === "Anime/Animation" && studio.begins === "FUNimation") && audio_language === "English") { }
```

**Comment by meisnate12** [comment]
Can you make the search you're asking for using advanced filters on plex? Once I'm home and not on my phone I can give you a proper example

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
I think it would be this
![image](https://user-images.githubusercontent.com/38122413/131271281-cc16db3e-9420-4fce-9ad1-c57cc6003cce.png)

The results aren't exactly what I want, but that's just because I don't have a filepath filter on Plex Web UI.

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Oh, well after making that in the Plex UI and looking it over it was pretty obvious what to do. Just nested any/alls. And now I see that in the wiki too :facepalm:

I think there's a typo though. Where it talks about nesting them, It says you can nest **any** or **and**. Unless **and** is another thing that I'm unaware of, there's no mention of nesting **all**

**Comment by meisnate12** [comment]
Yea that's a typo any is or and all is and
