### ISSUE TITLE
Feature Request: Dynamic Collections based on anidb relations

### ISSUE THREAD

**Issue by tadly** [Kometa-Team/Kometa#377]
As discussed in #374 it would be nice to have collections be dynamically created based on the anidb relation graph.

Let's say I have 100 Anime in my library.
Each one of those 100 Anime could be related to one or more of the other 99.

I would wan't PMM to:
1. Check **each** anime if a relation **within my library** exists (based on the anidb relation graph)
2. Create a new collection (it if doesn't already exist) with a name based on the "root" Anime name on anidb (I't be nice to specifiy if Main Title or Original Title should be used)
3. Add the Anime to said Collection

Actuall implemenation might obviously look different. This example is just to outline the feature request.

**Comment by meisnate12** [comment]
so this can get a little crazy as some of the relation graphs get kinda ridiculous like https://anidb.net/anime/715/relation/graph which could be overridden another problem is the collection name the new `tmdb_collections` operation uses the collections on tmdb those same type of collection are not on anidb there's no base name of the relation graph on tmdb.
This can all be done just not dynamically so until i have a way to do that I'm going to close this issue

**Comment by mikaeltarquin** [comment]
I just discovered making collection files with anidb relations and came here looking for exactly this feature. That's a bummer to see it was closed with no solution, I think this would be very useful. Funny enough, that relation graph for 715 - Mobile Suit Gundam was the very first one I attempted to make, and it made exactly the collection I wanted.
