### ISSUE TITLE
Creating this as requested by Cpt Kuesel from Discord

### ISSUE THREAD

**Issue by Autoexec56** [Kometa-Team/Kometa#378]
**Describe the Bug**
Fresh local install of PMM on existing server with all other apps working fine.
Not dockers
Version: 1.12.1
executing the following command: 
python3 plex_meta_manager.py --run
getting a lot of there errors

Adding to Radarr and Sonarr
 Unknown Error: (404 [Not Found]) Item Not Found {'message': 'NotFound'}

**Relevant Collection Config**
- Having a problem with a collection include the collection config from your metadata file.

**Plex Meta Manager Info**
- Version Number (can be found at the beginning of your meta.log file.

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by cpt-kuesel** [comment]
Start of the Discord Discussion:

https://discord.com/channels/822460010649878528/826911404866273300/884293499489513562

**Comment by cpt-kuesel** [comment]
Hi @Autoexec56,

someone in the Discord suggested using http://localhost:7909 to reach Radarr with PMM on QuickBox.

Have you tried that?

**Comment by Autoexec56** [comment]
Yes tried and failedTony Barbaria(316) ***@***.***
-------- Original message --------From: cpt-kuesel ***@***.***> Date: 9/8/21  10:40 AM  (GMT-06:00) To: meisnate12/Plex-Meta-Manager ***@***.***> Cc: Autoexec56 ***@***.***>, Mention ***@***.***> Subject: Re: [meisnate12/Plex-Meta-Manager] Creating this as requested by Cpt
  Kuesel from Discord (#378) 
Hi @Autoexec56,
someone in the Discord suggested using http://localhost:7909 to reach Radarr with PMM on QuickBox.
Have you tried that?

**Comment by cpt-kuesel** [comment]
Alright, just wanted to make sure. Thanks for reporting back!

**Comment by chazlarson** [comment]
Can you attach the log output here?

**Comment by Autoexec56** [comment]
Currently at work will not be able to respond until 8pm CDT.Tony Barbaria(316) ***@***.***
-------- Original message --------From: Chaz Larson ***@***.***> Date: 9/8/21  12:03 PM  (GMT-06:00) To: meisnate12/Plex-Meta-Manager ***@***.***> Cc: Autoexec56 ***@***.***>, Mention ***@***.***> Subject: Re: [meisnate12/Plex-Meta-Manager] Creating this as requested by Cpt
  Kuesel from Discord (#378) 
Can you attach the log output here?

**Comment by meisnate12** [comment]
if this is still an issue lets start a new one
