### ISSUE TITLE
Feature Request: Exclude items from collection

### ISSUE THREAD

**Issue by CherryKitten** [Kometa-Team/Kometa#379]
**Is your feature request related to a problem? Please describe.**

I have a lot of collections based on lists from imdb,tmdb, etc.

I have also set up automatic adding of missing items to radarr/sonarr.

Sometimes a list is a good base for a collection, but includes a movie or two that I don't actually want in there. If I remove those from radarr/sonarr, they get added again on the next running of plex-meta-manager. I would like a way to exclude specific items from a collection.

**Describe the solution you'd like**

My idea would be to implement this the same way as all builders, but with an exclusion tag.

For example:

```
collections:
  Name:
    imdb_list: 
      - https://www.imdb.com/list/id
    exclude:
      imdb_id: tt123456, tt98765
  NextCollection: [...]
```

Any match in the exclusion part would take precence over matches in the builder.

**Comment by kieron** [comment]
Is there any way this could hook into Sonarr's `Add List Exclusion` setting you get when you delete a show within the web UI?

Would be one less thing to maintain in configs if you just deleted the show in Sonarr, but I don't know if sonarr exposes that list etc.

**Comment by meisnate12** [comment]
Added `ignore_ids` which can be given a list or comma-separated values of TMDb Ids for movies or TVDb IDs for shows and those ids will be ignored

i also added `ignore_imdb_ids` which can be used the same as above but with imdb_ids


In addition to all of the above Radarr and Sonarr now respect their list exclusions so if its excluded in radarr/sonarr pmm shouldn't add it to them

**Comment by meisnate12** [comment]
you can also specify both the attributes above under settings for a global/library level ignore over just a collection ignore
