### ISSUE TITLE
Bug: IndexError: list index out of range - during scheduled run

### ISSUE THREAD

**Issue by ShrinkWrapper** [Kometa-Team/Kometa#380]
**Describe the Bug**
While running the :develop docker image in schedule mode I receive the following error after it has completed the run.
The task gets executed and the collection updates but as soon as it prints the error the container crashes.
Related to #293  ? There is no error if I run the task manually with `PMM_RUN:true`
```
|====================================================================================================|
|                                         Finished 14:07 Run                                         |
|                                         Run Time: 0:00:22                                          |
|====================================================================================================|
| Traceback (most recent call last):                                                                 |
Error in sys.excepthook:
Traceback (most recent call last):
  File "/modules/util.py", line 154, in my_except_hook
    print_multiline(line, critical=True)
  File "/modules/util.py", line 146, in print_multiline
    logger.handlers[1].setFormatter(logging.Formatter(" " * 65 + "| %(message)s"))
IndexError: list index out of range
Original exception was:
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 554, in <module>
    hours = int(seconds // 3600)
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

**Plex Meta Manager Info**
- Version: 1.12.1

**Link to logs (required)**
- https://gist.githubusercontent.com/SilentFez/a3a5d32ca602aa7c320a3b566bef1967/raw/aee302cb3e68c8e76c5ff5e7b44f3475d16e4bf9/meta.log

**Comment by meisnate12** [comment]
i think ive fixed this in develop can you test

**Comment by ShrinkWrapper** [comment]
Already running the docker develop image.

Edit: I might have misunderstood. Looks like the github develop branch indeed works. 
Just pulled it and built the docker image manually. So far so good. Been testing for a while now and no crashing.

But the [develop image on docker](https://hub.docker.com/layers/meisnate12/plex-meta-manager/develop/images/sha256-35de96e62de9052c2544ea73bb272bbb841f3800baed4ba81c8a3d0bc01b0f56?context=explore) does not work, heads up.
