### ISSUE TITLE
Feature Request: Set metadata rules in collection

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#389]
**Is your feature request related to a problem? Please describe.**
The default language in my library is English, but my native language is Swedish so I like to keep Swedish movies in shows in their original language. Right now I have to either set it in Plex or use the metadata where I have to define it for every single movie and show. This is too much maintenance to keep up with and if this could just be automated it would save so much time and keep my library consistent

**Describe the solution you'd like**
I can see two solutions for this. One is to be able to set general metadata rules, like `use_original_title: true` for all movies that have Swedish language in my case. You could set up a filter just like for collections and apply the rules to it. I'm sure there could be a lot more uses with general rules for the metadata.

**Describe alternatives you've considered**
The second solution is if I can set `use_original_title: true` on a collection, as well as other relevant metadata. This is not as good though, since it would require the creation of collections for the specific rules, and the metadata is on a movie level, not collection level.

**Additional context**

**Comment by meisnate12** [comment]
so you can kinda do this already it's a little odd way for now but once a GUI is done it'll be much better organized.

```yaml
collections:
  Change Original Title:
    plex_search:
      all:
        audio_language: Swedish
    build_collection: false
    item_use_original_title: yes
```

you use `plex_search` or any other builder to choose what movies this operation affects.
you use `build_collection: false` to not actually make this collection in your plex
you use `item_use_original_title` to tell PMM to set `use_original_title` of all the items found by the builders the options are either `yes`, `no`, or `default`.
