### ISSUE TITLE
Oscars List not pulling correctly.

### ISSUE THREAD

**Issue by b101marc** [Kometa-Team/Kometa#39]
In my Movies YAML I use the Oscars list as shown in the template which had worked well before.

The link is `https://www.imdb.com/search/title/?title_type=feature,documentary&groups=oscar_winner`

While running, it is attempting to pull from the following:

`https://www.imdb.com/search/title/?title_type=feature` Seems to be ignoring the `,`.

**Comment by b101marc** [comment]
Update: Tried the following: `https://www.imdb.com/search/title/?title_type=feature&groups=oscar_winner` which worked.

**Comment by meisnate12** [comment]
thats my mistake and this is why i have a dev branch lol

**Comment by meisnate12** [comment]
this should be fixed in dev and since this was never in master just close once you've tested
