### ISSUE TITLE
Feature Request: Add Missing Is/Is Not Modifiers to String Searches

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#390]
**Is your feature request related to a problem? Please describe.**
Trying to modify a smart collection to use `title.is:`, and is/is not is only supported by [Tag Searches](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Plex-Builders#tag-searches)

This functionality exists in the Plex Web UI for all the [string attributes](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Plex-Builders#tag-searches) listed in the wiki

**Describe the solution you'd like**
I'd like to be able to use `title.is:` in one of my smart collections. If you added this though, something to keep in mind is that Tag Searches `is not` modifier uses `.not`, which is the same as the `does not contain` modifier. So if you wanted consistent naming you'd run into a duplicate modifiers there. Maybe changing the Tag Searches modifier to be `.isnot` instead of `.not` would solve that?

**Comment by meisnate12** [comment]
added .is and .isnot to string searches and filters
