### ISSUE TITLE
Fails run with "__init__() got an unexpected keyword argument 'session'" for every config file

### ISSUE THREAD

**Issue by codesterribly** [Kometa-Team/Kometa#395]
Tried multiple configs, templates, recent versions etc. 

Every run starts with:

"
| Connecting to TMDb...                                                                              |
| __init__() got an unexpected keyword argument 'session'    "

My TMDB api key is correct. Verified.

Took a spin through the code, and nothing jumped out. 

User error or is there something that needs to be changed?

**Comment by meisnate12** [comment]
update your requirements your using an old version of the tmdbv3api module
