### ISSUE TITLE
Refresh Metadata on Library

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#397]
### Discussed in https://github.com/meisnate12/Plex-Meta-Manager/discussions/396

<div type='discussions-op-text'>

<sup>Originally posted by **ngInit** September 23, 2021</sup>
So I've run into a weird situation. I started trying to integrate my YouTube feed into Plex using an Other Videos Library. Got it kind of working, but I found a weird bug on Plex's side. Only on the TV app, the Other Videos library doesn't use the thumbnail as the thumbnail. It actually uses the fanart as the thumbnail, and the thumbnail as the poster when viewing the item.

To fix this, I created a script that runs through the YouTube directory and symlinks all the thumbnails, appending `-fanart` to the end. That works great, I can put this script on a timer and keep it running. All except for one thing: I still need to go in and manually refresh the metadata on the library.

So I figured this is where PMM would come into play. The solution I'd like is to run PMM on a basically empty metadata/collection file and have it call a refresh metadata on the library after I run my symlink script.</div>

**Comment by meisnate12** [comment]
add `item_refresh` to a collection config to have PMM refresh the metadata of every item in the collection
