### ISSUE TITLE
Feature Request - Unraid Support

### ISSUE THREAD

**Issue by isaacolsen94** [Kometa-Team/Kometa#4]
There is a large community of Plex users who use Unraid/Community Applications to manage Plex. It would be fantastic to have this project's docker file added to their application library as well. Thanks for the fantastic work on this!!!

**Comment by wjziv** [comment]
I agree that the Unraid community would love this, but the [configuration](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Configuration-File) and [metadata](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Metadata-File) files are much too dense to fold up every possible input into some Unraid XML.

I'd set expectations here such that you may only input basic configuration data into Unraid's docker setup page, and then instruct the user to find a blank metadata file in their appdata folder. This requires some tweaks to the Dockerfile to search environment variables for applicable fields.

Ideally, in the future, there's a GUI which points back to these settings and edits them internally so the user does not need to fuss with YAML files after deployment.

**Comment by Tharic99** [comment]
> I agree that the Unraid community would love this, but the [configuration](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Configuration-File) and [metadata](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Metadata-File) files are much too dense to fold up every possible input into some Unraid XML.

I don't believe anyone is looking for configuration and metadata files to be built for them. Simply looking for a Template to be added into Unraid so that it can be pulled down from the Community Apps without needing to manually create the docker container.

I manually built a custom container yesterday relatively easily.

Name = PlexMetaManager
Repository = meisnate12/plex-meta-manager
Network Type = bridge
Time to Run. Key = time
Run Without the Scheduler. Key = run
Divider Character. Key = divider
Screen Width. Key = width
Config Storage Path. Container path = /config and Host path = /mnt/user/appdata/plex-meta-manager

![image](https://user-images.githubusercontent.com/39832147/107539579-187ad600-6b93-11eb-865d-1032eea47d22.png)

**Comment by isaacolsen94** [comment]
Thank you, this is exactly what I was looking for. Tried doing a custom image myself and wasn't able to figure it out.

**Comment by PuppyLover101** [comment]
> > I agree that the Unraid community would love this, but the [configuration](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Configuration-File) and [metadata](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Metadata-File) files are much too dense to fold up every possible input into some Unraid XML.
> 
> I don't believe anyone is looking for configuration and metadata files to be built for them. Simply looking for a Template to be added into Unraid so that it can be pulled down from the Community Apps without needing to manually create the docker container.
> 
> I manually built a custom container yesterday relatively easily.
> 
> Name = PlexMetaManager
> Repository = meisnate12/plex-meta-manager
> Network Type = bridge
> Time to Run. Key = time
> Run Without the Scheduler. Key = run
> Divider Character. Key = divider
> Screen Width. Key = width
> Config Storage Path. Container path = /config and Host path = /mnt/user/appdata/plex-meta-manager
> 
> ![image](https://user-images.githubusercontent.com/39832147/107539579-187ad600-6b93-11eb-865d-1032eea47d22.png)

I've already had this setup on unRAID, but have never been able to connect to MAL. How does one copy paste the link in?

**Comment by meisnate12** [comment]
You can find instructions on unRAID setup in the new [unRAID Installation](https://github.com/meisnate12/Plex-Meta-Manager/wiki/unRAID-Installation) page including specific [instructions](https://github.com/meisnate12/Plex-Meta-Manager/wiki/unRAID-Installation#advanced-installation-authenticating-trakt-or-myanimelist) on how to authenticate Trakt and MyAnimeList

**Comment by Data-Monkey** [comment]
I created a template from the data above. It works for me.
https://github.com/Data-Monkey/docker-templates/blob/master/Data-Monkey/plex-meta-manager.xml
I think it would be much better if you would take a copy of it and host it in your repo. 
A quick note to Squid in the unRAid forum will get the template added to the master list of templates.

It will now probably come via my list, but it would be much better from you.

**Comment by meisnate12** [comment]
so I just make one of those XML file files in the main part of my repo does it matter what I call it id probably do `unraid.xml` unless there's a specific name it more needs to be

**Comment by Data-Monkey** [comment]
I think you need a special repo. 
See here for details: https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

btw: my version of the template is now available in the unRAID Community Applications :-)

**Comment by meisnate12** [comment]
ill work getting this when i get a chance
