### ISSUE TITLE
PlexAPI Unknown Error during Overlay

### ISSUE THREAD

**Issue by jak64950** [Kometa-Team/Kometa#401]
I'm receiving the following error when running the overlay on the 4K overlay function.

![error](https://user-images.githubusercontent.com/39564839/135733302-1d5638cc-36bd-4c02-9580-d25de00d4a08.PNG)

Might be a problem with plex and not pmm. Would be useful if pmm skipped the error and moved through the rest of the library though.

**Comment by LeendertPlas** [comment]
I'm not getting an error but the entire feature doesn't seem to work anymore. It just waits endlessly on the Plex Movie Search command.

The Debug log in Meta.log mentions that it has found X amount of keys and then displays the keys, but after that nothing happens.

**Comment by jak64950** [comment]
I figured this out. Seems obvious now, but I'm using a read-only shared metadata mount between multiple plex instances and so it was messing with the permissions.
