### ISSUE TITLE
Bug: Fails to run "ImportError: cannot import name 'python_utils' from 'modules'"

### ISSUE THREAD

**Issue by b101marc** [Kometa-Team/Kometa#407]
**Describe the Bug**
Updated my local installation on the master branch, had been working fine previous about two weeks ago. When attempting to run I get the following error:
`Traceback (most recent call last):
  File "/opt/appdata/Plex-Meta-Manager/plex_meta_manager.py", line 6, in <module>
    from modules import util
ImportError: cannot import name 'util' from 'modules' (/usr/local/lib/python3.9/dist-packages/modules.py)`

**Relevant Collection Config**
Not required.

**Plex Meta Manager Info**
v1.12.2

**Link to logs (required)**
Error above, no log required.

**Comment by meisnate12** [comment]
this is some kind of setup issue basically python python cant find the util.py file that should be in the same folder as all the others i would try downloading a fresh copy and reinstalling the requirements again

**Comment by b101marc** [comment]
I did as suggested but a new error:

`File "plex_meta_manager.py", line 70
    print(f"Argument Error: width argument invalid: {screen_width} must be an integer between 90 and 300 using the default 100")`

**Comment by meisnate12** [comment]
thats an odd one to get but it shouldn't have killed the run

**Comment by b101marc** [comment]
Not sure how to proceed.

**Comment by b101marc** [comment]
I attempted again this morning to run it just using `python plex_meta_manager.py` and received the original error again:

`root@A175:/opt/appdata/Plex-Meta-Manager# python plex_meta_manager.py
Traceback (most recent call last):
  File "/opt/appdata/Plex-Meta-Manager/plex_meta_manager.py", line 6, in <module>
    from modules import util`

**Comment by meisnate12** [comment]
try setting up a virtual environment for PMM you can use this guide [here](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Walkthrough-Local#setting-up-a-virtual-environment)

**Comment by b101marc** [comment]
> try setting up a virtual environment for PMM you can use this guide [here](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Walkthrough-Local#setting-up-a-virtual-environment)

I attempted to run as instructed and received this error. I think something must be wrong with my python that is beyond my understanding.

`Error: Command '['/opt/appdata/Plex-Meta-Manager/pmm-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.12th

**Comment by meisnate12** [comment]
Have you tried removing your Python installation and installing a new one? 

I know there's an issue with Python 3.10 so make sure to download the latest 3.9 release

**Comment by b101marc** [comment]
I have concerns doing so may break other parts of my system. I've never had very good luck with python for whatever reason.￼

**Comment by meisnate12** [comment]
Understood I'll look up the error more later when I'm back in front of a computer but for now check out this page. You might be able to run one of the commands there to get the venv working 

https://askubuntu.com/questions/1268833/error-command-path-to-env-bin-python3-7-im-ensurepip-upgrade
