### ISSUE TITLE
Feature Request: Add periods to Trakt listings

### ISSUE THREAD

**Issue by c4mz** [Kometa-Team/Kometa#418]
Hi, is it possible to add the period filters to the 'recommended' 'watched' 'collected' lists.

Filters would be: daily, monthly, yearly, all

eg. https://trakt.tv/movies/watched/daily

Cheers!

**Comment by meisnate12** [comment]
this was actually really easy its done in develop

**Comment by c4mz** [comment]
You're awesome.

**Comment by meisnate12** [comment]
new trakt builders `trakt_collected_daily`, `trakt_collected_weekly`, `trakt_collected_monthly`, `trakt_collected_yearly`, `trakt_collected_all`, `trakt_recommended_daily`, `trakt_recommended_weekly`, `trakt_recommended_monthly`, `trakt_recommended_yearly`, `trakt_recommended_all`, `trakt_watched_daily`, `trakt_watched_weekly`, `trakt_watched_monthly`, `trakt_watched_yearly`, `trakt_watched_all`

`trakt_collected` will now run as `trakt_collected_weekly`
`trakt_recommended` will now run as  `trakt_recommended_weekly`
`trakt_watched` will now run as  `trakt_watched_weekly`

**Comment by c4mz** [comment]
Does this need to be added?

"trakt_collected_daily", "trakt_collected_weekly", "trakt_collected_monthly", "trakt_collected_yearly", "trakt_collected_all",
    "trakt_recommended_daily", "trakt_recommended_weekly", "trakt_recommended_monthly", "trakt_recommended_yearly", "trakt_recommended_all",
    "trakt_watched_daily", "trakt_watched_weekly", "trakt_watched_monthly", "trakt_watched_yearly", "trakt_watched_all",
    "trakt_collection", "trakt_list", "trakt_list_details", "trakt_popular", "trakt_trending", "trakt_watchlist"

to line 149 in builder.py

to support custom_sort_builders

**Comment by meisnate12** [comment]
yes its been added

**Comment by meisnate12** [comment]
i leave these open until the feature is in the main branch

**Comment by c4mz** [comment]
Ahh sorry my bad.
