### ISSUE TITLE
Feature Request: Replacement for plex's automatic collection feature

### ISSUE THREAD

**Issue by CherryKitten** [Kometa-Team/Kometa#421]
**Is your feature request related to a problem? Please describe.**

Plex has a feature to automatically create collections for existng movies, based on their tmdb collections.

That feature has a few problems:
1. It does not create collections for titles with a locked collection tag. So if a movie for example already is in a thematic collection, or a company collection, it would not automatically get its tmdb collection without unlocking the tag.

2. When the tag is unlocked, the system can create duplicate collections if they are not named exactly the same. For example, tmdb has the word "collection" in most collection names. My manually created collections do not, since it's redundant.
So if I already have a collection called "{movie series name}", which is created by PMM based on the tmdb collection for that movie series, plex will automatically create "{movie series name} collection", with identitcal movies to the existing one.

**Describe the solution you'd like**
1. A setting to enable automatic creation of tmdb collections
1.5. optional setting to specify to which config file the collections should be added (and maybe a setting to specify if it should use `tmdb_collection` or `tmbd_collection_details`?)
2. The feature should then check if movies in the library have a collection on tmdb, then check if a collection with that tmdb ID already exists in the PMM config and create it if it doesn't.
3. Optional: After creating the collections, save which movies have a tmdb collection to skip checking those again on the next run.

**Describe alternatives you've considered**
Alternatively a check could be added to merge collections which have  the same name with only an added "collection" being the difference (this would not fix the problem of locked collection tags, though), or the collections could be created unmanaged and combined with [this](https://github.com/meisnate12/Plex-Meta-Manager/issues/169) existing feature request.

**Comment by snickers2k** [comment]
+1
i'm setting plex up again from an old backup and was wondering about the exact same thing. should i delete all existing to not get dupes? or delete all (hundreds of) dupes by hand afterwards 🤔 

also i would like to still have the ability to create and maintain collections inside plex (as long as PMM hasn't a webui yet^^) but maybe interact with it later in PMM.

maybe a two way sync could be a solution? like adding all plex created collections back to PMM ? to make further interactions easier aswell (not having to manually search for the right tmdb-id etc)

and please auto-set poster and background if this feature gets added

**Comment by meisnate12** [comment]
Created [`tmdb_collections` Library Operation](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Operations-Attributes#tmdb-collections)
