### ISSUE TITLE
Feature Request: Support for IMDB "filmosearch" URLs

### ISSUE THREAD

**Issue by fmr-iv** [Kometa-Team/Kometa#423]
**Is your feature request related to a problem? Please describe.**
Creating a collection from a "filmosearch" URL in IMDB fails. My use case is for getting all feature films from a specific actor:

1. Go to actor's IMDB page (example: [Ryan Reynolds](https://www.imdb.com/name/nm0005351/))
2. Under Filmography, click the dropdown and select By Rating
3. Under Refine > Movies or TV, select Feature Film (here is an [example URL](https://www.imdb.com/filmosearch/?explore=title_type&role=nm0005351&sort=user_rating,desc&mode=detail&page=1&title_type=movie))

The result is the same as a list - it contains all movies, but Plex-Meta-Manager displays the following error in the command prompt:
![image](https://user-images.githubusercontent.com/4317891/140084464-544aee78-2084-4a80-ab78-b435b229cdf3.png)

**Describe the solution you'd like**
Allow these URLs to work with the imdb_list property for collections (or add a new property type for them)

**EDIT:** For a little more context, I'm basically looking to identify which movies I'm missing in my PLEX server from certain actors I like. I set the config with **build_collection: false** and then view the _Movies_missing.yml_ file to determine what I need to download.

Here's an example of my config:
```
  Ryan Reynolds Filmography Check:
    imdb_list: https://www.imdb.com/filmosearch/?explore=title_type&role=nm0005351&sort=user_rating,desc&mode=detail&page=1&title_type=movie
    build_collection: false
    sync_mode: append
```

Using this IMDB feature is much faster than manually creating lists for all the actors I want to check, so adding support for these URLs would be a huge help.

**Comment by meisnate12** [comment]
added to develop for release in v1.13.0
