### ISSUE TITLE
Feature Request: Radarr - Don't add movies in the "Exclusion List"

### ISSUE THREAD

**Issue by jluis2k10** [Kometa-Team/Kometa#424]
**Is your feature request related to a problem? Please describe.**
Once in a while a movie I don't want in my library is added to the download queue via Radarr. So I proceed to delete the movie and add it to the Exclusion List, but in the next run of Plex Meta Manager this movie is added again. Could be possible to make it so Plex Meta Manager won't add a movie to Radarr if said movie is in the Exlusion List? I don't even know if Radarr offers this info through its API, but if it does shouldn't be so difficult right?

**Describe the solution you'd like**
Some kind of parameter in the collection details for Radarr, like "add_excluded: [true|false]"

**Describe alternatives you've considered**
Just delete movies manually :(

**Additional context**
For example in a collection of trending movies, movies I don't want are constantly added to my library until they are removed from the trending list.

Thanks!

**Comment by meisnate12** [comment]
added to develop for release in v1.13.0
