### ISSUE TITLE
Error adding series to Sonarr

### ISSUE THREAD

**Issue by Schnoopie-Doopie** [Kometa-Team/Kometa#427]
When the script runs it adds movies to Radarr using the tag defined with no issues however displays an error when adding to Sonarr with or without a tag. 
The error is 

> "Unknown Error: 'Series' object has no attribute 'extend'"

Even with the Sonarr logging turned to debug, the report shows the below

> 2021-11-09 05:27:50.3|Debug|Api|[GET] /api/v3/series/lookup?apikey=(removed)&term=tvdb%3A131921: 200.OK (339 ms)
> 2021-11-09 05:27:53.1|Debug|Api|[GET] /api/v3/command: 200.OK (1 ms)
> 2021-11-09 05:28:00.0|Debug|Api|[GET] /api/v3/queue?apikey=(removed) 200.OK (2 ms)
> 2021-11-09 05:28:08.2|Debug|Api|[GET] /api/system/status?apikey=(removed) 200.OK (1 ms)
> 2021-11-09 05:28:08.2|Debug|Api|[GET] /api/system/status?apikey=(removed) 200.OK (1 ms)
> 2021-11-09 05:28:08.2|Debug|Api|[GET] /api/v3/languageprofile?apikey=(removed) 200.OK (1 ms)
> 2021-11-09 05:28:08.2|Debug|Api|[GET] /api/tag?apikey=(removed) 200.OK (1 ms)

I do have Sonarr and Radarr configured with a base URL for reverse proxy needs and both have a login using the forms style. I cannot see any base config differences between Sonarr and Radarr except for the root folder path. In Radarr it doesnt have a space however with Sonarr it does. I contain this in quotes "" as demonstrated in the template example however on running the script these are removed. My config extract is below:

> libraries:                                      # Library mappings must have a colon (:) placed after them
>   Movies:
>     metadata_path:
>       - file: config/Movies.yml
>       - git: meisnate12/MovieCharts
>       - git: meisnate12/Studios
>       - git: meisnate12/IMDBGenres
>       - git: meisnate12/People
>   TV Shows:
>     metadata_path:
>       - file: config/TV Shows.yml
>       - git: meisnate12/ShowCharts
>       - git: meisnate12/Networks
> settings:                                       # Can be individually specified per library as well
>   cache: true
>   cache_expiration: 60
>   asset_directory: config/assets
>   asset_folders: true
>   assets_for_all: false
>   sync_mode: append
>   show_unmanaged: true
>   show_filtered: false
>   show_missing: true
>   save_missing: true
>   run_again_delay: 2
>   missing_only_released: false
>   create_asset_folders: false
>   collection_minimum: 1
>   delete_below_minimum: false
> plex:                                           # Can be individually specified per library as well
>   url: http://10.1.1.9:32400
>   token: "REMOVED"
>   timeout: 60
>   clean_bundles: false
>   empty_trash: false
>   optimize: false
> tmdb:
>   apikey: "REMOVED"
>   language: en
> tautulli:                                       # Can be individually specified per library as well
>   url: http://10.1.1.218:8181/tautulli
>   apikey: "REMOVED"
> radarr:                                         # Can be individually specified per library as well
>   url: http://10.1.1.213:7878/radarr
>   token: "REMOVED"
>   version: v3
>   add: true
>   root_folder_path: /Videos/Movies
>   monitor: false
>   availability: announced
>   quality_profile: Ultra-HD
>   tag: Scripts-Meta-Manager
>   search: true
>   add_existing: false
> sonarr:                                         # Can be individually specified per library as well
>   url: http://10.1.1.214:8989/sonarr
>   token: "REMOVED"
>   version: v3
>   add: true
>   root_folder_path: /Videos/TV Shows
>   monitor: all
>   quality_profile: Ultra-HD
>   language_profile: English
>   series_type: standard
>   season_folder: true
>   tag: Scripts-Meta-Manager
>   search: false
>   cutoff_search: false
>   add_existing: false
> omdb:
>   apikey: "REMOVED"
> trakt:
>   client_id: "REMOVED"
>   client_secret: "REMOVED"
>   authorization:
>     access_token: "REMOVED"
>     token_type: Bearer
>     expires_in: "REMOVED"
>     refresh_token: "REMOVED"
>     scope: public
>     created_at: "REMOVED"
> 

Script log shows:

> [2021-11-09 16:16:29,303] [sonarr.py:57]              [DEBUG]    | TVDb IDs: [382152, 395130, 83268, 362280, 382154, 385376] |
> [2021-11-09 16:17:15,672] [util.py:144]               [DEBUG]    | Traceback (most recent call last):                                                                 |
>                                                                  |   File "C:\Scripts\Plex-Meta-Manager-master-new\Plex-Meta-Manager-master\plex_meta_manager.py", line 517, in run_collection
>                                                                  |     builder.run_missing()
>                                                                  |   File "C:\Scripts\Plex-Meta-Manager-master-new\Plex-Meta-Manager-master\modules\builder.py", line 1674, in run_missing
>                                                                  |     self.library.Sonarr.add_tvdb(missing_tvdb_ids, **self.sonarr_details)
>                                                                  |   File "C:\Scripts\Plex-Meta-Manager-master-new\Plex-Meta-Manager-master\modules\sonarr.py", line 69, in add_tvdb
>                                                                  |     added, exists, invalid = self.api.add_multiple_series(tvdb_ids, folder, quality_profile, language_profile, monitor, season, search, cutoff_search, series, tags, per_request=100)
>                                                                  |   File "C:\Users\david\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\arrapi\sonarr.py", line 251, in add_multiple_series
>                                                                  |     series.extend([Series(self, data=s) for s in self._post_series_import(json[i:i+per_request])])
>                                                                  | AttributeError: 'Series' object has no attribute 'extend'
>                                                                  | 
> [2021-11-09 16:17:15,673] [plex_meta_manager.py:544]  [ERROR]    | Unknown Error: 'Series' object has no attribute 'extend'

Any help would be great.

**Comment by meisnate12** [comment]
Pretty sure I fixed this bug in the develop branch can you switch to it then and reinstall your requirements and try again
