### ISSUE TITLE
Feature Request: Ability to change season background with Image Asset Directory

### ISSUE THREAD

**Issue by Alex1331xela** [Kometa-Team/Kometa#428]
I use the image asset directory feature to manage all my posters, backgrounds and title cards, and it works perfectly. However, there seems to be no way to set a season's background (or if there is, I am unable to find it on the [wiki page](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Settings-Attributes#image-asset-directory)).

The way I'd imagine this working is adding the season background image to the correct asset folder, named according to whether `asset_folders` is `true` or `false`.

Example:
<html>
<body>

Image Type | `asset_folders: true` | `asset_folders: false`
-- | -- | --
Season background | `assets/ASSET_NAME/Season##_background.ext` | `assets/ASSET_NAME_Season##_background.ext`

</body>
</html>

**Comment by meisnate12** [comment]
added to develop for release in v1.13.0
