### ISSUE TITLE
Feature Request: Fix Matches From Arrs

### ISSUE THREAD

**Issue by bakes82** [Kometa-Team/Kometa#438]
**Is your feature request related to a problem? Please describe.**
Sometimes plex mismatches files.

**Describe the solution you'd like**
Ability to configure multi arr support to check if shows/movies are properly matched in plex and fix match/scan.

**Describe alternatives you've considered**
Plexarr

**Additional context**
Priority Low :)

**Comment by meisnate12** [comment]
so do you want multi arr support or this fix match/scan thing

**Comment by snickers2k** [comment]
i guess with multi-arr he meant sonarr AND radarr

https://github.com/l3uddz/plexarr
"Simple CLI tool to fix Plex library matches according to Sonarr/Radarr"

should be enough for the moment. but +1 for having it sometime in pmm

**Comment by meisnate12** [comment]
ok so im not going to guess which tmdb is correct the one in radarr or the one in plex but ive added a whole new section that will display all the discrepancies between the two

**Comment by bakes82** [comment]
> 

both?  dont most people run 1080p in one arr and 4k in another so you have 2 versions lol?

**Comment by snickers2k** [comment]
Plex already supports IDs in foldernames, i think that one already should take care of right matches in Plex.

**Comment by bakes82** [comment]
Plex still mismatches stuff why do you think there are tools to fix it lol

**Comment by snickers2k** [comment]
you are right. plex does this unfortunately .. don't know why the imdb-id is supported in folders, if the movie gets still recognized on it's own.

does the merge mean it's implemented already ?

**Comment by meisnate12** [comment]
it being merged means i implemented what i though i could and that was to display mismatches in the output
