### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Chuchodavids** [Kometa-Team/Kometa#443]
**Describe the Bug**
Filter does not fully work. I have filtered release date, original language and duration, And only original language seems to be working.

**Relevant Collection Config**
```collections:
  Popular:
    tmdb_popular: 30
    imdb_list:
      url:  https://www.imdb.com/search/title/?title_type=feature,tv_movie,documentary,short
      limit: 30
    sync_mode: sync
    filters:
      original_language: en
      release.after: 1/1/1990
  Top Rated:
    tmdb_top_rated: 30
    sync_mode: sync
    filters:
      original_language: en
      release.after: 1/1/1990
  Disney:
    tmdb_company: 3475
    sync_mode: sync
    filters:
      original_language: en
      release.after: 1/1/2000
      duration.gte: 60
  Pixar:
    tmdb_company: 3
    sync_mode: sync
    filters:
      original_language: en
      release.after: 1/1/2000
      duration.gte: 60
  Trending this Week:
    trakt_trending: 10
    tmdb_trending_weekly: 10
    sync_mode: sync
    filters:
      original_language: en
      release.after: 1/1/1990
  Box Office:
    trakt_boxoffice: true
    sync_mode: sync
```

**Plex Meta Manager Info**
- 1.12.2-develop1115

**Link to logs (required)**
- https://gist.github.com/Chuchodavids/6677155cc075b763fd01a7eb7c5db7c4

**Comment by meisnate12** [comment]
looking at your log everything appears to be in working order. Mind that only specific filters can filter missing movies and shows most filters like `release` do not filter missing. Notice how under [Number Filters](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Collection-Filters#number-filters) it says `The tmdb_vote_count and tmdb_year filters will also filter out movies/shows from being added to Radarr/Sonarr.`
