### ISSUE TITLE
TypeError on first run

### ISSUE THREAD

**Issue by dannyvfilms** [Kometa-Team/Kometa#445]
Fresh Docker install from Unraid Community App Store. 

No log file available (latest docker version)

**Link to logs (required)**
`TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 69, in <module>
    if screen_width < 90 or screen_width > 300:
TypeError: '<' not supported between instances of 'str' and 'int'`

**Comment by meisnate12** [comment]
can you try using the develop tag and see if it works

**Comment by dannyvfilms** [comment]
It appears that corrected the issue. Trakt authentication finished, and now it has connected to my libraries. Thanks!

**Comment by meisnate12** [comment]
no problem!
