### ISSUE TITLE
Feature Request: Discord webhooks

### ISSUE THREAD

**Issue by SuperMario22922** [Kometa-Team/Kometa#463]
**Is your feature request related to a problem? Please describe.**
Whenever I want to use discord webhooks it gives the error `(400 [Bad Request]) {'message': 'Cannot send an empty message', 'code': 50006}`

**Describe the solution you'd like**
Another way to send messages specifically for discord webhooks.

**Describe alternatives you've considered**
I would have tried notifiarr but my internet doesnt support port forwarding

**Additional context**
My meta.log file is attached here

[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/7613006/meta.log)

**Comment by mjr128** [comment]
https://discord.com/developers/docs/resources/webhook#execute-webhook
> Note that when sending a message, you must provide a value for at least one of content, embeds, or file.

Current Webhooks function post raw json. Encapsulate this json with `{"content" : json}` in case of discord webhook url should works.

**Comment by meisnate12** [comment]
Added in 1.17.0
