### ISSUE TITLE
Bug: more an exception than an actual bug

### ISSUE THREAD

**Issue by sw4rl3y79** [Kometa-Team/Kometa#470]
**Describe the Bug**
After adding the sonarr config, i always get an error (404 not found) This is NOT because the sonarr server is unreachable as this would trow another error (could not connect to) 
my radarr config is working fine though

**Relevant Collection Config**
`sonarr:                                         # Can be individually specified per library as well
  url: http://xxx.xxx.xxx.xxx:8989/
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  add: true
  root_folder_path: /mnt/data4/serien.en
  monitor: missing
  quality_profile: HD-1080p
  series_type: standard
  season_folder: true
  search: true
  cutoff_search: false
  add_existing: false
  language_profile:
  tag:
  sonarr_path:
  plex_path:`

**Plex Meta Manager Version**
1.13.1

**Link to logs (required)**

https://gist.github.com/sw4rl3y79/c849c440badbd19ad57c8bb0f9c0af70

**Comment by meisnate12** [comment]
what version of sonarr are you running and do you have any list exclusions in sonarr i tested this functionality more with radrr but they usually function the same so i might have messed up how it works in sonarr

**Comment by sw4rl3y79** [comment]
sonarr is on 2.0.0.5344 so still on v2. maybe that's the issue? v2 vs. v3? I have no exclusions

**Comment by sw4rl3y79** [comment]
yeah, what should i say....that was it ;) v2 isn't working but v3 is. I've upgraded to v3 and now it's working fine. 

Thanks for your time!

**Comment by meisnate12** [comment]
no problem glad it worked for you
