### ISSUE TITLE
Plex URL is invalid

### ISSUE THREAD

**Issue by Eddi101** [Kometa-Team/Kometa#485]
![2021-12-05 22 42](https://user-images.githubusercontent.com/86011893/144766819-98e4de11-283c-4444-a98e-5b6b7b646a7d.png)

{from config.yml}

plex:   
  url: https://10.10.10.10:32400
  token: reVb#############
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 60

**Comment by muff7** [comment]
Had this issue myself on my Unraid setup. 

I changed the url to localhost:32400 and the script runs now.
