### ISSUE TITLE
Feature Request: support for official IMDb charts

### ISSUE THREAD

**Issue by 2fst4u** [Kometa-Team/Kometa#495]
**Is your feature request related to a problem? Please describe.**
IMDb builders are great, but they only support searches and lists. IMDb also has "charts". Support for charts would be good.

**Describe the solution you'd like**
Adding charts support to the IMDb builders would allow these charts to be used directly, rather than needing to find a corresponding list or search based off that chart.

**Describe alternatives you've considered**
Some lists and searches exist, but they are inconsistent. For example this is a search for the IMDb top 250:
https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc

And this is the actual IMDb top 250 chart:
https://www.imdb.com/chart/top/?ref_=ats_top250serp_to_top250chart

As of the point in time I'm writing this, a relatively new movie called Jai Bhim (2021) with a relatively low number of votes, but a high overall rating has made it to the top of this search. While I'm sure this movie is very good, I think the official chart probably filters out new additions with low numbers of votes like this to keep from having new movies jump to the top over long-time classics. The official IMDb chart shows this movie at position number 130 at the time of writing.

If the actual official chart could be linked to then this much better statistical average could be used.

**Additional context**
This FAQ gives more information on vote and rating discrepancies:
https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV?recentlyAuthenticated=true#

**Comment by meisnate12** [comment]
ok i added them to develop you can now use `imdb_chart` and the options you can give it are: `box_office`, `popular_movies`, `top_movies`, `top_english`, `top_indian`, `lowest_rated`, `popular_shows`, and `top_shows`

**Comment by 2fst4u** [comment]
Awesome. It appears to be working brilliantly. Thanks for that.

**Comment by 2fst4u** [comment]
Actually one thing that doesn't seem to be quite right is the sort order now. The chart option throws an error about "custom" sort order not being supported but that leaves all items in the wrong order because it doesn't go through the sorting phase if you leave it out.

**Comment by meisnate12** [comment]
so this is a problem in two parts 

1. I forgot to add imdb_chart to custom sort its already been pointed out to me and if you update develop again it should work now.
2. Because of 1 its just being sorted by whatever the default plex option is which is either alphabetical or release order

**Comment by 2fst4u** [comment]
Awesome that's working great now. Nice work.

**Comment by iamwoz** [comment]
@2fst4u can you please share a sample collection you have built using `imdb_chart` - I'm struggling to get something that will work. Thanks!

**Comment by iamwoz** [comment]
> @2fst4u can you please share a sample collection you have built using `imdb_chart` - I'm struggling to get something that will work. Thanks!

Looks like I've sorted it - was overcomplicating it by trying to use my own chart URL - just needed `imdb_chart: [option]`

**Comment by 2fst4u** [comment]
Yep that's the one, simply name the supported official chart.
