### ISSUE TITLE
Feature Request: Replace Plex "tis season"

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#499]
Hey. 
Since PMM is so awesome for building Collections, i thought why not replace Plex Original "tis Season" with our own fancy ones :D
The original one can be disabled through the (per library) settings.

Question now is, how to get it back with PMM? 

- In a perfect world, pinning a collection would be available through the plex-api. but i don't know.

- Second method could be a dedicated "this season" collection, which gets updated by PMM for every Season. Empty collections are already removed by Plex automatically from from Home-Screen until they have entries again. So if there is no special season at a given time, the collection could be emptied by PMM and it's not showing up anymore  - just like the original feature. So this would work most definitely. 

thanks

**Comment by meisnate12** [comment]
This really isn't a feature request because you can do all of this for example here is my holiday collections

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/meisnate12/Holiday.yml

Just make whatever timed collections you want!
