### ISSUE TITLE
Feature Request - Add all occurences of a movie

### ISSUE THREAD

**Issue by henningBunk** [Kometa-Team/Kometa#5]
Just noticed this:

I got Midsommar and Midsommar (Director's cut) as split entries for the same Plex Movie metadata match. I updated my manually created A24 collection with the script and it removed the non director's cut from the collection.

When I create a new collection with it only one of these entries are added to the collection.

Would be great when both entries would be added.

Workaround for me for now is to add it manually and use `append`.

**Comment by meisnate12** [comment]
I'll see what i can do but without plex supporting different copies of the same movie its going to be difficult to accomplish since they use the same TMDb ID

**Comment by meisnate12** [comment]
closed by mistake this is still an active issue

**Comment by meisnate12** [comment]
i figured this out its in develop if you want to test
