### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by dgiffen** [Kometa-Team/Kometa#500]
**Describe the Bug**
I get an error with PMM from sonarr over the show Winter House, [301:Winter House]' Options: ['standard', 'daily', 'anime'] it claims that the value isn't set. It is indeed set for standard in Sonarr. The error is mostly harmless as the script runs as intended and the show is added to the correct collection. Thanks for this excellent script. I really like it a lot. 

**Relevant Collection Config**
creates error on each Plex genre search

**Plex Meta Manager Info**
Version: 1.13.3 

**Link to logs (required)**
[- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.
](https://gist.github.com/dgiffen/0f4a23d4fbb7c074b52fcd9731cbe6a6)

**Comment by meisnate12** [comment]
fix is in develop

**Comment by dgiffen** [comment]
Thank you. It is most appreciated.
