### ISSUE TITLE
movies not being added to Radarr

### ISSUE THREAD

**Issue by kilgil27** [Kometa-Team/Kometa#508]
I have it set to add missing movies to radarr, but not search for them. It runs through and finds the missing movies, says it's adding them to Radarr, but they never show up. It was working before, haven't changed anything other than the update a few days ago. Any ideas?

**Comment by meisnate12** [comment]
Are you using master or the latest develop?

**Comment by kilgil27** [comment]
I'm running it in docker on unraid, installed through the instructions here: https://github.com/meisnate12/Plex-Meta-Manager/wiki/unRAID-Installation

**Comment by meisnate12** [comment]
Since you didn't answer my question I'm going to assume you're just on master can you add :develop to the end of the image tag when pulling the image ie meisnate12/plex-meta-manager should be changed to meisnate12/plex-meta-manager:develop run the develop version and then send me your meta.log if you're still having the issue.

**Comment by kilgil27** [comment]
updated to the develop image, still having the same issue, noticing it says "Skipped: In Cache" when it's trying to add the movies to Radarr, but I've confirmed they're not in Radarr anywhere. Attached the [meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/7729789/meta.log)

**Comment by meisnate12** [comment]
ok so the skipped in cache is because it though it was added on a previous run delete your config.cache file and run it again

**Comment by kilgil27** [comment]
that seemed to work, thanks!

**Comment by palla89** [comment]
hi @meisnate12 , maybe I had a bad timing but I can't pull develop right now, I see latest commit is 1 hour ago so I think I chose the worst time to update the image :D 

```
sudo docker run -it --name plex-meta-manager-dev -v /volume1/docker/plex-meta-manager:/config:rw meisnate12/plex-meta-manager:develop --time 05:00
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 10, in <module>
    from modules import util
  File "/modules/util.py", line 4, in <module>
    from modules import plex
  File "/modules/plex.py", line 2, in <module>
    from modules import builder, util
  File "/modules/builder.py", line 3, in <module>
    from modules import anidb, anilist, flixpatrol, icheckmovies, imdb, letterboxd, mal, plex, radarr, sonarr, stevenlu, tautulli, tmdb, trakt, tvdb, util
  File "/modules/anidb.py", line 3, in <module>
    from modules.util import Failed
ImportError: cannot import name 'Failed' from partially initialized module 'modules.util' (most likely due to a circular import) (/modules/util.py)
```
