### ISSUE TITLE
Bug:  Pre-Rolls set for just a day

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#511]
**Describe the Bug**
Pre-Rolls 

Noticed an issue, If the schedule is set from (12/13-12/13) I believe its treating it as a full year, not just for the day. 

I have my file set like so:

Yearly
Monthly
Weekely
Daily

I did it this way as I noticed whatever collection is last in the current date it selects it. And that is prefect. I make it so I yearly set so if the is no monthly, weekly, or daily it uses that collection, if there is a monthly it uses the monthly set. and so on, But I put a daily one in and it always selects that one if the date range is the same (12/13-12/13), but if i change it to (12/12-12/13) then it skips it and grabs the correct on. 

So if you can look into the date range so I can have single daily ones that would be awesome, else it works great.

Also going to put in a feature request on this to make life easier.

**Comment by meisnate12** [comment]
im not quite getting what your describing here `I did it this way as I noticed whatever collection is last in the current date it selects it. And that is prefect. I make it so I yearly set so if the is no monthly, weekly, or daily it uses that collection, if there is a monthly it uses the monthly set. and so on, But I put a daily one in and it always selects that one if the date range is the same (12/13-12/13), but if i change it to (12/12-12/13) then it skips it and grabs the correct on.`

you can schedule a collection for a year using yearly(12/13) if you want it to only happen on that day

**Comment by almulder** [comment]
ok so we dont need a range just put range: (12/13) for day only. That work I did not even think to try. Thanks.
