### ISSUE TITLE
Feature Request:  Pre-Rolls based on folder

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#512]
So currently with Pre-rolls we have to give the path and every file name.

`Example: /Media/PreRoll/PreRoll01.mp4;/Media/PreRoll/PreRoll02.mp4;/Media/PreRoll/PreRoll03.mp4;/Media/PreRoll/PreRoll04.mp4;`

Would be nice if we had an option to just specify a path and it would generate the list from all file in that folder (But not sub folders)

`Example: /Media/PreRoll/`

That would grab the files in that folder and generate the list like in the first example and adding the ; between each file.

This way we could add or remove files from folders without having to edit the file each time.

Yet leave the ability for use to still have the file names also.

Maybe something like this:

```
  DEC change preroll:
    build_collection: false
    server_preroll: 
    sever_preroll_folder:
    schedule: range(12/01-12/31)
```

if the server_preroll is filled in skip the server_preroll_folder, if the server_preroll is empty then use the server_preroll_folder, if both are empty skip this preroll collection.
```

  DEC change preroll:
    build_collection: false
    server_preroll:  /Media/PreRoll//DEC/PreRoll01.mp4; /Media/PreRoll/DEC/PreRoll02.mp4;
/Media/PreRoll/DEC/PreRoll03.mp4; /Media/PreRoll/DEC/PreRoll04.mp4;
    sever_preroll_folder:
    schedule: range(12/01-12/31)

VS

  DEC change preroll:
    build_collection: false
    server_preroll: 
    sever_preroll_folder: /Media/PreRoll/DEC
    schedule: range(12/01-12/31)

```

**Comment by meisnate12** [comment]
see the problem with this is that PMM doesn't need access to those files or that directory and most likely cannot see that directory which is why all i can do is update the string.
