### ISSUE TITLE
Feature Request: Rename posters and background based upon image dimensions

### ISSUE THREAD

**Issue by Drazzilb08** [Kometa-Team/Kometa#513]
**Is your feature request related to a problem? Please describe.**
Consistantly having to name files `poster.ext` and `background.ext`

**Describe the solution you'd like**
The idea is to download posters and backgrounds and place them into their proper folder (folders generated by the `assets_for_all: true` tag) and have the script automatically name the assets. This would eliminate the need to repetitively name them `poster` and `background`. Possibly have a tag in the settings (per library) to allow for this renaming feature

**Describe alternatives you've considered**
Manually adding each poster and background to each directory

**Additional context**

**Comment by snickers2k** [comment]
yeah would be great - so i requested it already: https://github.com/meisnate12/Plex-Meta-Manager/issues/468

**Comment by Drazzilb08** [comment]
Works super well. I can consider this one closed.
