### ISSUE TITLE
Feature Request: simkl.com (trakt alternative)

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#516]
simkl.com
interesting alternative for trakt (with hopefully faster development and better recommendations - but who knows^^)

the UI is much faster already and allows importing from trakt and many other services

but i don't know about their pricing model and whats free via API 

https://simkl.docs.apiary.io

**Comment by meisnate12** [comment]
Any particular reason you no longer want this added?

**Comment by meisnate12** [comment]
@snickers2k is there a reason I shouldn't add this or do you just not want me to spend development time on it?

**Comment by snickers2k** [comment]
sorry, i'm always like "how much time should one steal the dev's with support chat?" :D

of course it's your choice, but maybe i was too quick to already open up a request.

checked it with https://web.archive.org/web/20150601000000*/simkl.com 
and it's up for years without anyone taking notice (first thought it was something new). 

second bummer was that even recommendations needs a VIP ... a pricey VIP... don't know whats free via API, but before i pay them, i pay trakt^^

there probably other things that are important
