### ISSUE TITLE
Feature Request: add \*arr cleanup based on PMM Tag

### ISSUE THREAD

**Issue by bakerboy448** [Kometa-Team/Kometa#517]
**Is your feature request related to a problem? Please describe.**

collections can result in many movies and shows added to \*arr potentially by accident

**Describe the solution you'd like**

options should be added for \*arr to cleanup items and remove them if they have the pmm configured tag and are no longer in a PMM collection 

**Describe alternatives you've considered**
Manually reviewing added by date and sorting those out by hand 

**Additional context**

**Comment by meisnate12** [comment]
I'll make a library operation that can mass remove from the arrs based on tags so you can remove everything PMM added and then just have PMM add back what you want
