### ISSUE TITLE
Feature Request: Add Environment File for API Keys & Git Config Sync

### ISSUE THREAD

**Issue by bakerboy448** [Kometa-Team/Kometa#518]
**Is your feature request related to a problem? Please describe.**

No config sync from GitHub 

**Describe the solution you'd like**

create an .Env file to allow a user to place their sensitive information such as api keys and a path to a config file similar to collections

this will allow users to easily share config files and allows users to keep config files on GitHub and easily maintain them + version control

the .env file would contain the api keys as applicable and use them if the api keys in the config file are blank. 

The env file would also have a line for a config file to apply it too.

the config file would then be pulled like the other YML are

**Describe alternatives you've considered**
Scrubbing the config by hand and manually syncing to git

**Additional context**

**Comment by meisnate12** [comment]
This is why the config file is separate from the metadata file where configs are stored there's not much of a need to share you're config.yml just all the metadata files you use
