### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by 2fst4u** [Kometa-Team/Kometa#525]
**Describe the Bug**
Docker develop version exits with an error. I'm aware the develop branch is essentially a beta so I'm not too concerned, but I'm running develop in order to use the IMDb chart support you introduced because it's great.

**Relevant Collection Config**
- my collections work fine on the "latest" tag, but changing to develop breaks. The difference being the inclusion of IMDb charts if that's relevant but on the latest branch it just ignores this and says it isn't supported as expected.

**Plex Meta Manager Info**
- Version Number 1.13.3

**Link to logs (required)**
- the error given is:
` File "/modules/util.py", line 4, in <module>
    from modules import plex                                                File "/modules/plex.py", line 2, in <module>                                from modules import builder, util                                       File "/modules/builder.py", line 3, in <module>
    from modules import anidb, anilist, flixpatrol, icheckmovies, imdb, letterboxd, mal, plex, radarr, sonarr, stevenlu, tautulli, tmdb, trakt, tvdb, util                                                                      File "/modules/anidb.py", line 3, in <module>                               from modules.util import Failed                                       ImportError: cannot import name 'Failed' from partially initialized module 'modules.util' (most likely due to a circular import) (/modules/util.py)`

**Comment by meisnate12** [comment]
should be fixed
