### ISSUE TITLE
Feature Request: Global Filters and more excludes

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#526]
Would be great if there could be global filters like exclude, not only for tmdb, but based on tmdb.
the tmdb id's are fetched anyway, or not? so could be easily processed with further filtering i guess?

also please add the ability for an "advanced mode".
like setting negative value's; for example to "with_original_language" - which i would like to set to "!hindi" or something like that. the negative value could work for anything else like "with_cast: !Bill Cosby". without you having to add all these "with and without".

or, if you don't want to add that "advanced",
please add "exclude_original_language" at least :)

also missing (deeply): tmdb content_ratings (age restrictions) so i can make a few kids collections easily

(i really want to exclude bollywood :D)

thanks

**Comment by meisnate12** [comment]
i can add a tmdb exclude thats easy as for your request about filters what youre asking for isnt going to happen the tmdb_discover endpoint functions the way it functions i dont make how the values work tmdb does.

**Comment by meisnate12** [comment]
> Would be great if there could be global filters like exclude, not only for tmdb, but based on tmdb.
the tmdb id's are fetched anyway, or not? so could be easily processed with further filtering i guess?

I could try and add some kind of ability to add builders to the filters or something so it'll filter out whatever the builder finds from the collection

> also please add the ability for an "advanced mode".
like setting negative value's; for example to "with_original_language" - which i would like to set to "!hindi" or something like that. the negative value could work for anything else like "with_cast: !Bill Cosby". without you having to add all these "with and without".
> 
> or, if you don't want to add that "advanced",
please add "exclude_original_language" at least :)

For tmdb_discover this is a limitation of tmdb the only operation they accept is `with_original_language` you can request from them to add `without_original_language` to their discover endpoint. 

But this has been a problem before and the solution is using the `original_language` filter which can use the `.not` modifier

> also missing (deeply): tmdb content_ratings (age restrictions) so i can make a few kids collections easily

do you want a filter again i cannot edit discover

**Comment by meisnate12** [comment]
most of this is not really anything PMM can control. you can use `original_language.not` filter and `content_rating.not` filters to filter content from collections and theres a global `ignore_ids` for tmdb although it is static. So I'm going to close this as i dont really see anything to implement
