### ISSUE TITLE
Bug: arr error: not sending info

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#532]
**Describe the Bug**
when adding to sonarr, I have an error:
| Sonarr Error: Invalid Series Type: '[722:The Great]' Options: ['standard', 'daily', 'anime'] |
TV_missing.yml is filled correctly

when adding to radarr
no movies are added
I don't know if there is a link but in the meta.log the path seems wrong.
Missing Path: //config/Films_missing.yml
but it is filled correctly

**Relevant Collection Config**

**Plex Meta Manager Info**
 Version: 1.13.3    

**Link to logs (required)**
https://gist.github.com/Nexius2/0c7e09e3d9f977b57bf4fc164139346e

**Comment by meisnate12** [comment]
the title isnt very descriptive but #500 is the same issue and its been fixed in develop
