### ISSUE TITLE
Mapping Error: Agent xbmcnfo not supported

### ISSUE THREAD

**Issue by laryan61** [Kometa-Team/Kometa#534]
New installation of PMM.

On my first run of "python plex_meta_manager.py -r", I'm seeing many of the following similar error message.

| Mapping Error | com.plexapp.agents.xbmcnfo://tt5215088?lang=xn | Agent xbmcnfo not supported for "A.I. Rising"

I've installed and using the https://github.com/gboudreau/XBMCnfoMoviesImporter.bundle Plex Agent to allow for the use of locally created .nfo files. Is there an option to correct this in PMM? Can the error messages be ignored? Suggestions?

Thanks,
Lee

**Comment by meisnate12** [comment]
lol i actually just added this in the develop maybe a week ago it hasn't made it to master yet but it will be in 1.14.0 if you switch to the develop branch you can try now

**Comment by laryan61** [comment]
That was a lightning response! I'll switch to the develop branch and give that a try. Let you know the results.

**Comment by laryan61** [comment]
PMM is installed as a docker in unRaid. How do I upgrade to the develop branch?

**Comment by meisnate12** [comment]
add `:develop` to the image name `meisnate12/plex-meta-manager:develop`

**Comment by laryan61** [comment]
Thanks. Changing to develop version fixed the error messages I was seeing. I've started with just using your "MovieCharts & ShowCharts" libraries. Slowly expanding from there.

**Comment by meisnate12** [comment]
thats how you want to do it take it slow and add on slowly if you try and do to much you'll get overwhelmed

**Comment by giantsfan006** [comment]
Not sure if I should be opening a new issue but I'm having a similar issue:

`| Mapping Error | com.plexapp.agents.xbmcnfo://5374491386487609200?lang=xn | XMBC NFO Local ID: 5374491386487609200 for "Your Luckiest Night" |`

I'm on 1.16

**Comment by meisnate12** [comment]
i would start with updating to 1.17.2

**Comment by hicane0** [comment]
Same issue

Would the problem be resolved if I switch to the develop branch?

I'm on  1.19.0

@meisnate12 

 Mapping Error | com.plexapp.agents.xbmcnfo://6732994698911575996?lang=xn | XMBC NFO Local ID: 6732994698911575996 for "风雨哈佛路" |
| Mapping Error | com.plexapp.agents.xbmcnfo://2951277432324376236?lang=xn | XMBC NFO Local ID: 2951277432324376236 for "海贼王：最强之敌Z" |
| Mapping Error | com.plexapp.agents.xbmcnfo://7027796298658184421?lang=xn | XMBC NFO Local ID: 7027796298658184421 for "巨齿鲨2：深渊" |
| Mapping Error | com.plexapp.agents.xbmcnfo://5351671303490943682?lang=xn | XMBC NFO Local ID: 5351671303490943682 for "加菲猫2" |
| Mapping Error | com.plexapp.agents.xbmcnfo://3843023204272998871?lang=xn | XMBC NFO Local ID: 3843023204272998871 for "尖峰时刻" |
| Mapping Error | com.plexapp.agents.xbmcnfo://6100437934403127129?lang=xn | XMBC NFO Local ID: 6100437934403127129 for "尖峰时刻2" |
| Mapping Error | com.plexapp.agents.xbmcnfo://6100438934403127135?lang=xn | XMBC NFO Local ID: 6100438934403127135 for "尖峰时刻3" |
