### ISSUE TITLE
Automate Sub-Folder Creation

### ISSUE THREAD

**Issue by fisher745** [Kometa-Team/Kometa#539]
It is known that PMM can create the assets folders, but what I noticed is that it does not create sub folders under assets folder, even though there is a setting of `asset_depth`.

Here's what I have created using the settings for my Movies library, per collection basis, see the pic
![Untitled](https://user-images.githubusercontent.com/81430462/147203735-986f0118-9b4b-49cf-a9da-a24b131afa00.png)

**Comment by meisnate12** [comment]
pmm isnt going to guess at what the user wants but you can specify a folder per metadata file now so it doesnt have to search all of them for each file
