### ISSUE TITLE
Bug: Loading and processing is done twice

### ISSUE THREAD

**Issue by LeendertPlas** [Kometa-Team/Kometa#542]
**Describe the Bug**
When you have both a yml file for collections and an operations command, the program does the loading of the library part and the processing part 2 times. With the second one being much slower.

**Relevant Collection Config**
  Movies:
    library_name: Films
    operations:
      tmdb_collections:
        remove_suffix: Collection

**Plex Meta Manager Info**
Version: 1.13.2    

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by meisnate12** [comment]
can you update to 1.14.0 and let me know if you're having the same issue
