### ISSUE TITLE
Bug: Adding to Radarr error

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#548]
**Describe the Bug**
when adding movies to radarr it sometimes fail.
File "//plex_meta_manager.py", line 733, in run_collection
radarr_add, sonarr_add = builder.run_missing()
File "/modules/builder.py", line 1793, in run_missing
added_to_radarr += self.library.Radarr.add_tmdb(missing_tmdb_ids, **self.radarr_details)
File "/modules/radarr.py", line 88, in add_tmdb
 if path.lower() in arr_paths:
 AttributeError: 'NoneType' object has no attribute 'lower'
  [2021-12-29 06:05:44,402] [plex_meta_manager.py:789]  [ERROR]    | Unknown Error: 'NoneType' object has no attribute 'lower'

**Plex Meta Manager Info**
- 1.14.0

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by meisnate12** [comment]
this should already be fixed in develop

**Comment by Nexius2** [comment]
I'm running develop already ;-)

**Comment by meisnate12** [comment]
update again this bug was introduced into develop [here](https://github.com/meisnate12/Plex-Meta-Manager/commit/9214b3bd02fcc7978ce39b6c65608141fcf367ce) and was fixed after about 5 hours [here](https://github.com/meisnate12/Plex-Meta-Manager/commit/672cdbd2cefaa12e45b8db30de5a2fc096835e62)
