### ISSUE TITLE
Bug: Missing items not being added to Radarr

### ISSUE THREAD

**Issue by zseymour** [Kometa-Team/Kometa#552]
**Describe the Bug**
Missing items (fewer than 100 items) are not being added to Radarr.

Items are added to Radarr in [this loop](https://github.com/meisnate12/Plex-Meta-Manager/blob/6788fa8ae4d3fe8ed97ca4d7751397226d02a90a/modules/radarr.py#L75), using [this check](https://github.com/meisnate12/Plex-Meta-Manager/blob/6788fa8ae4d3fe8ed97ca4d7751397226d02a90a/modules/radarr.py#L102).
However, recent changes added some `continue`s to the above lines, so the final check `len(tmdb_ids) == i` may be skipped.

**Relevant Collection Config**
Any collection that needs to add fewer than 100 items to Radarr.

**Plex Meta Manager Info**
- Version Number 1.14.1

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.

**Comment by meisnate12** [comment]
ok this fix is in develop
