### ISSUE TITLE
Feature Request: Add summary describing how collections work with/without Plex pass

### ISSUE THREAD

**Issue by ark-** [Kometa-Team/Kometa#555]
There should be a note to say collections appearing in home screen recommendations are **only possible with a Plex pass**. Otherwise these collections are only visible by accessing the collections page. 

A summary of this should be front and centre on the readme page.

The reason I have raised this is I spent some time getting some nice collections up and running and spending a long time trying to find out why they wouldn't show up on the Home Screen. Turns out this option isn't available without Plex Pass.

Additionally I feel like the main readme should have a nice images of what the end result of using this script could be. e.g. Some screenshot of recommendations on the home page and another of the collections page.

**Comment by meisnate12** [comment]
> There should be a note to say collections appearing in home screen recommendations are only possible with a Plex pass. Otherwise these collections are only visible by accessing the collections page.

Did not even realize this as ive had a plex pass for years thanks for letting me know
