### ISSUE TITLE
Feature Request: external builders (create trakt lists)

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#557]
i'd love to have the ability to create trakt lists based on pmm-collections

maybe even with a two-way-sync.
trakt -> pmm -> plex
plex -> pmm -> trakt

**Comment by Mushin** [comment]
Just to add, this could be a useful method to sync up plex collections between multiple arr instances (e.g. 1080p and 4K radarr instances / https://github.com/meisnate12/Plex-Meta-Manager/issues/561). As currently, with different arr instances (and root folders) in the same plex library, the arr add functionality doesn't work.

https://discord.com/channels/822460010649878528/862041837500628993/946776146329079858

**Comment by meisnate12** [comment]
Added in 1.17.0
