### ISSUE TITLE
TVDB Error: getget_seriesmove requires either tvdb_url or tvdb_id  

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#56]
I'm toying around with the TVDB side of things now as well and I ran into a ton of these types of errors.

My log is attached. I stripped it out so it's only the TV Shows side of things though.

[meta tvshows.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6025484/meta.tvshows.log)

**Comment by meisnate12** [comment]
theres a fix in dev for this
