### ISSUE TITLE
Feature Request: crossmatch 2nd sonarr/radarr

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#561]
Would be great to have a crossmatch option for 2nd/3rd sonarr/radarr instances.

for example; i have a second radarr and sonarr for anime and daily tv to have more flexibility over manual searches. but it's not doing so well with PMM :D

**Comment by meisnate12** [comment]
so what exactly do you want PMM to do? Sync the radarr instances or to just be able to check multiple instances if theres a movie?

**Comment by snickers2k** [comment]
basically both, option for checking for existing movies across radarr's / sonarr's , to avoid duplicates across different 'arrs when adding collections

**Comment by Blasman** [comment]
This would be a much appreciated feature as it is common for users to run two instances of Radarr, one for 1080p and one for 4K content. Being able to use PMM for this would be ideal, as currently I have to decide which Radarr to use with PMM.

**Comment by meisnate12** [comment]
If you have a separate 4k vs normal library you can define a separate radarr per library

**Comment by meisnate12** [comment]
You could even define the same library twice with separate radarrs and only run metadata files you want sent to each

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/multiple-radarrsonarr-instances-per-library)
