### ISSUE TITLE
Feature Request: Save to Assets folder

### ISSUE THREAD

**Issue by bobokun** [Kometa-Team/Kometa#564]
**Is your feature request related to a problem? Please describe.**
Faster way of converting from `url_poster`/`url_background` to asset folder.

**Describe the solution you'd like**
A `save_to_assets` option o upon run it will take whatever url_poster or url_background link defined in the collection and save it in the correct assets directory.

**Describe alternatives you've considered**
Manually saving each image and putting it in the right location

**Comment by bobokun** [comment]
Oh also, if a previous `poster.ext` or `background.ext` exists in the assets folder maybe rename the previous one to `poster_old.ext` or something similar so it doesn't get accidentally overwritten? Just a thought, and if the size/hash of the image is the same as `poster_old.ext` then don't overwrite the old one (in case you run PMM multiple times with this option on)

**Comment by meisnate12** [comment]
Probably just gonna make it only save a file if there is no poster/background
