### ISSUE TITLE
Feature Request: global language filter

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#567]
like tvdb_language can be set globally; would be great to have this for tmdb (and maybe others like flixpatrol) aswell.

right now my collections with tmdb are in english instead of german (both poster and summery). 
and the language setting is only working with tmdb_discover... :/

**Comment by meisnate12** [comment]
you can change tmdb default language to de under the tmdb attribute in the main config file

**Comment by snickers2k** [comment]
oh.. sorry, i overlooked that one .. 
got confused by the global setting where tvdb_language is stored.

**Comment by meisnate12** [comment]
Yea I would change some of the settings locations if I started over
