### ISSUE TITLE
Feature Request: force run (--now)

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#568]
would be great to have a "--force" or "--now" option to disable all schedulers and run everything directly (for when testing or edited a lot)

**Comment by meisnate12** [comment]
Lmao this is actually already in develop I haven't detailed it in the wiki yet but it's --ignore-schedules

**Comment by snickers2k** [comment]
thats great, thanks :) but now i have another problem^^ how to deal with "holidays.yml" for example? i now got all my holiday collections at once :D like halloween, christmas and so on.

which is not too bad at all - for testing, to see if everything went well. but not for just syncing edited stuff.

probably needs a another way of exclusion ? like **--ignore-templates=holidays** , or **--ignore-metadata=holidays.yml** ?

**Comment by meisnate12** [comment]
ok try it now having a schedule with range supersedes `--ignore-schedules`
