### ISSUE TITLE
Hide Episode Spoilers

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#569]
**Is your feature request related to a problem? Please describe.**
A lot of episode title card images often have spoilers for what happens in the episode (i.e. competition shows final episode image can show who is in the final and who isn't).

**Describe the solution you'd like**
To be able to take the background image of the show/season and apply it to each of the episodes within the show/season. This could be either library-wide or for specific shows.

**Describe alternatives you've considered**
Tautulli already provides a similar functionality but it relies on media being recently added - you cannot call out specific shows for it to apply to.
https://github.com/blacktwin/JBOPS/blob/master/utility/hide_episode_spoilers.py

**Additional context**

**Comment by YozoraXCII** [comment]
I just wanted to follow this up with an expansion to the idea ahead of the overlay and asset rework.

Similar to Dynamic Collections, a neat idea would be Dynamic Posters/Title Cards.

This touches slightly on @chazlarson's poster-thing idea: <https://github.com/chazlarson/poster-thing>

The general idea is that for the identified shows, you take the episode banner image from TMDB, apply the episode text to it and then attach it to the episode within Plex. There could be another variant of this to avoid spoilers which does the same thing, but uses the season's banner image rather than specific episode banners to avoid spoilers. 

The logo could also be applied to the image, similar to this:
![image](https://user-images.githubusercontent.com/96386153/158668280-d86a9510-a0e9-44f7-8893-d981e67402d0.png)
Credit: <https://www.reddit.com/r/PlexTitleCards/comments/tfnziq/station_eleven_title_cards/>

Lots of example layouts available here:
<https://www.reddit.com/r/PlexTitleCards/>

**Comment by meisnate12** [comment]
Added in 1.17.0
