### ISSUE TITLE
Feature Request - Ignore processing of library with a pre-existing cache

### ISSUE THREAD

**Issue by ExDominatus** [Kometa-Team/Kometa#57]
I have a massive library (hence, the use of collections). Caching is amazing and is definitely an improvement over having to remap files repeatedly. However, my issue is that the execution still takes longer than expected to run because it chooses to reprocess all the items in the library to ensure they are in the cache (and to cache them if they aren't).

Is there a way to avoid this check and go straight to execution/collection building? I think verifying cache, as fast as it is still slows down the script, preventing it from running multiple times an hour, for example. Maybe it could look at Recently Added from Plex so it doesn't have to check each previous item (unless you want to on initial execution or to completely refresh the cache).

Not sure if I missed a way to do this, I tried to go through all the documentation but the way it's structured makes it tough if you don't already know what everything means.

**Comment by meisnate12** [comment]
Short Answer: No

Long Answer: the map is essential to how the program runs having it pull from the cache is the fastest way to get them all. The map is linking plex's `ratingKey` (which is a unique identifier for every item in plex) and the item's TMDb ID which must either be pulled from the cache or looked up. So unfortunately I don't think it would be possible to get it working quickly.

Out of curiosity how many movies do you have?

I'm not the greatest at explaining things but I'm happy for feedback on the wiki and if you're willing to help a little you can always fork [Plex Meta Manager Wiki repo](https://github.com/meisnate12/Plex-Meta-Manager-Wiki) and then submit a pull request with changes. I'd love for the wiki to be explained better.
