### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by romprod** [Kometa-Team/Kometa#58]
After running this on a very large library and using the example from [https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/meisnate12/Movies.yml](https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/meisnate12/Movies.yml) it almost finished and errored with the following message.

`| Processing: 5232/22439 The Damned: Don't You Wish That We Were Dea| Processing: 5233/22439 Damsel                                     | Unknown Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))      |
|                                                                                                    |
|====================================================================================================|
|                              Unmanaged Collections in Movies Library                               |
|====================================================================================================|
|                                                                                                    |
| HTTPConnectionPool(host='server', port=42400): Max retries exceeded with url: /library/sections/1/all?type=18&X-Plex-Container-Start=0&X-Plex-Container-Size=100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f298d0e6760>: Failed to establish a new connection: [Errno 111] Connection refused')) |
|                                                                                                    |
|====================================================================================================|`

Docker run command
`docker run -it -v "/hdd/1tb1ssd/data/docker/plex-meta-manager/config:/config" meisnate12/plex-meta-manager --config /config/config.yml --run`

The server is hosted in the cloud.

**Comment by romprod** [comment]
Safe to close, I reckon this was due to a scheduled reboot by the ISP.

**Comment by Sergimenez** [comment]
I try to enter by url to plex meta manager, I get a screen with user and password but I don't know what I have to put.

**Comment by chazlarson** [comment]
Plex meta manager has no URL of its own nor any UI that would ask for a user and pass; if you are seeing such a thing it's not part of PMM.
