### ISSUE TITLE
Feature Request: Manage "Only allow Label" & "Exclude Label" in the user sharing restrictions tab

### ISSUE THREAD

**Issue by cpt-kuesel** [Kometa-Team/Kometa#583]
**Is your feature request related to a problem? Please describe.**
I have a few collections I assigned the label "Admin" that should really only be visible to me so I manually added "Admin" as a label to exclude for everyone of my users in their sharing restrictions.
For the future if a user shares their preferred method of a watchlist with me I want to create a collection for them and then share that collection only with them.

**Describe the solution you'd like**
While building the collection with PMM I can choose a user or users for which the collection shall be visible. 
If someone wants an account for a kid that could be a way to assign the kid account labels they are allowed to watch as well.

**Describe alternatives you've considered**
Considered and practiced: adding those labels manually.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/manage-user-restrictions)
