### ISSUE TITLE
Multi-Library Collection

### ISSUE THREAD

**Issue by userspaced** [Kometa-Team/Kometa#606]
I know this might not make sense from a Plex point of view, but I have two movie libraries, movies and kids movies. I have setup a trending collection that uses tmdb and trakt. The collection is currently in the movies library and displays on the home screen. I was wondering if it's at all possible to make it also include movies from the kids movies library.

**Comment by meisnate12** [comment]
no its not possible pmm cant make plex do anything it cant already do

**Comment by userspaced** [comment]
Ok, thanks. That's what I assumed, but I wasn't 100% sure there wasn't some other settings for the home screen even in plex that I wasn't aware of. Sounds like my best bet would be to combine them into a single library.
