### ISSUE TITLE
Feature Request: Allow "duration" filter to use values lower than a minute

### ISSUE THREAD

**Issue by CherryKitten** [Kometa-Team/Kometa#607]
**Is your feature request related to a problem? Please describe.**
Quoting what I said on Discord:
"can the "duration" filter be changed to allow seconds instead of minutes?

I want to exclude music tracks under 20 seconds from a collection, to filter out sound effects and jingles in video game soundtracks

The current minimum of a minute would also filter out some actual music tracks"

**Describe the solution you'd like**
Either change "duration" filter to be in seconds, or allow decimals to go lower than 1. (the latter would keep existing configurations intact)

**Comment by meisnate12** [comment]
you can now use decimals
