### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by paulmcclellan** [Kometa-Team/Kometa#61]
The error is: 'utf-8' codec can't decode byte 0x92 in position 17055: invalid start byte

It happens when I execute:  python3 plex_meta_manager.py --config config/config.yml --run

I didn't find any log files.

**Comment by meisnate12** [comment]
run it with the debug option and paste the output 

python3 plex_meta_manager.py --config config/config.yml --run --debug

**Comment by paulmcclellan** [comment]
Here's the results:
python3 plex_meta_manager.py --config config/config.yml --run -- debug
Traceback (most recent call last):
  File "/mnt/user/Unraid/PlexMM/plex_meta_manager.py", line 1, in <module>
    import argparse, logging, os, re, schedule, sys, time, traceback, datetime
ModuleNotFoundError: No module named 'schedule'

Looks like it didn't import 'schedule'?   Does something else need to be imported first?

**Comment by meisnate12** [comment]
that should have been installed when you installed the requirements.txt. Run this in the same command prompt that you were running the python command from
`pip install -r requirements.txt --ignore-installed`

**Comment by paulmcclellan** [comment]
I had installed requirements.txt, but didn't use the --ignore-installed option.  I ran it, and now see the following:

| Connecting to Movies Library...                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "/mnt/user/Unraid/PlexMM/plex_meta_manager.py", line 76, in start                           |
|     config = Config(default_dir, config_path)                                                      |
|   File "/mnt/user/Unraid/PlexMM/modules/config.py", line 274, in __init__                          |
|     library = PlexAPI(params, self.TMDb, self.TVDb)                                                |
|   File "/mnt/user/Unraid/PlexMM/modules/plex.py", line 26, in __init__                             |
|     try:                                                                    self.data, ind, bsi = yaml.util.load_yaml_guess_indent(open(params["metadata_path"], encoding="utf-8")) |
|   File "/usr/lib64/python3.9/site-packages/ruamel/yaml/util.py", line 85, in load_yaml_guess_indent |
|     yaml_str = stream.read()                                                                       |
|   File "/usr/lib64/python3.9/codecs.py", line 322, in decode                                       |
|     (result, consumed) = self._buffer_decode(data, self.errors, final)                             |
| UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 17055: invalid start byte     |
|                                                                                                    |
| 'utf-8' codec can't decode byte 0x92 in position 17055: invalid start byte                         |

**Comment by meisnate12** [comment]
It doesn't like some character in you Metadata File can you post it?

**Comment by paulmcclellan** [comment]
Here's the file.  I don't see any issues with it...

[Movies.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/6047499/Movies.txt)

BTW Thanks for taking this to the next level.  I've been using Plex-Auto-Collections for a long time, but your revision is awesome!

**Comment by meisnate12** [comment]
ok so your dreamworks collection has to have quotes around it in order to use `*` (this is also why I switched to using `+` instead because it doesn't require quotes.

Second thing is that i think its having a problem with a specific character in the file. try replacing all your single quotes with double quotes and see if it works or even better take them out and switch the `*` to `+` so you don't need them

**Comment by paulmcclellan** [comment]
Thanks for your help!  I was finally able to get it to run properly.  This tool works great, but the error messages are cryptic.

**Comment by meisnate12** [comment]
I'm glad you got it working. If there's ever a specific error message that's confusing please let me know and I'll do my best to make the output more understandable
