### ISSUE TITLE
Assets path by metadata file

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#610]
As shown below, I would like to be able to create the assests path by metadata file so that the resulting directory structure is a little better organized

 Movies:
    metadata_path:
      - file: config/metadata/movies/Movies.yml
      - file: config/metadata/movies/overlays4k.yml
      - file: config/metadata/movies/MovieCharts.yml
      - file: config/metadata/movies/Studios.yml
      - file: config/metadata/movies/IMDBGenres.yml
      - file: config/metadata/movies/People.yml
    **settings:
      asset_directory:
        - config/assets/movies/collections
        - config/assets/movies/movies
        - config/assets/movies/moviecharts
        - config/assets/movies/studios
        - config/assets/movies/imdbgenres
        - config/assets/movies/people**
    operations:
      split_duplicates: true
      assets_for_all: true
      mass_trakt_rating_update: true
      mass_critic_rating_update: tmdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb
      tmdb_collections:
        template:
          tmdb_collection_details: <<collection_id>>
          sort_title: <<collection_name>>
  TV Shows:
    metadata_path:
      - file: config/metadata/shows/TVShows.yml
      - file: config/metadata/shows/overlays4k.yml
      - file: config/metadata/shows/ShowCharts.yml
      - file: config/metadata/shows/Networks.yml
    **settings:
      asset_directory:
        - config/assets/shows/collections
        - config/assets/shows/series
        - config/assets/shows/showcharts
        - config/assets/shows/networks**
    operations:
      assets_for_all: true
      mass_trakt_rating_update: true
      mass_critic_rating_update: tmdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb

**Comment by meisnate12** [comment]
Added in 1.17.0
