### ISSUE TITLE
Feature Request: inject extras/specials

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#611]
hey.
just thought it would be cool to inject some specials for movies inside certain collections.

maybe like

  - jacky-chan-collection
     - extras: /asset_folder/extras/10 Scenes Jacky Chan almost died.mp4 (https://www.youtube.com/watch?v=RKRUYJarcEk)

  - minions-collection
     - extras: /asset_folder/extras/Minions Short.mp4 (https://www.youtube.com/watch?v=Cxy88GeEAxg)

maybe even with the help of youtube-dl/yt-dlp to skip that manual download? 

if you do metadata-exporting sometime, and pmm can handle the folders(+paths) anyway then, would be awesome if you could add this aswell.

**Comment by isaacolsen94** [comment]
+1

**Comment by meisnate12** [comment]
this isnt something that can be accomplished using the API so this isn't going to be something i can add unless plex adds some feature that allows me to do so
