### ISSUE TITLE
[Feature req.] Req. via Petio where arr's are setup accordingly

### ISSUE THREAD

**Issue by xplorer990** [Kometa-Team/Kometa#619]
send request to petio where arr's are configured for different quality profiles and/or other things like language.

**Comment by meisnate12** [comment]
im not sure what you want

**Comment by snickers2k** [comment]
i could never get petio to working... but their filter feature is nice of course. could be great for further filtering. but i'm not that optimistic with mongodb hooking in etc .. never worked for me

**Comment by meisnate12** [comment]
all these options are configurable in pmm i dont plan on adding petio support unless it can do something that pmm cant do integrated with only radarr/sonarr
