### ISSUE TITLE
Feature Request: Enable multiple TMDB languages as fallback

### ISSUE THREAD

**Issue by foux** [Kometa-Team/Kometa#621]
**Is your feature request related to a problem? Please describe.**
When requesting metadata (for example artist biography) not available in a language, we should be able to use one (or several) fallback languages to replace the missing metadata.

**Describe the solution you'd like**
Set tmdbs language as a list so we can put multiple ones

**Comment by meisnate12** [comment]
This would be very difficult with how the  api wrapper is programmed so its not planned at this time
