### ISSUE TITLE
Feature Request: Allow Parsing of Secrets/Env File

### ISSUE THREAD

**Issue by GD-L** [Kometa-Team/Kometa#625]
**Describe the solution you'd like**
Allow for the use of a secrets.yaml or .env file to embed into `config.yml` file. Similar examples can be found from [HomeAssistant - loader.py](https://github.com/home-assistant/core/blob/ca2f343c519cc944d20a12856ff124aa3567e013/homeassistant/util/yaml/loader.py)

**Additional context**
Allowing a secrets file to be parsed will more easily allow users to share their git files and using `.gitignore` to keep tokens safe.

**Comment by meisnate12** [comment]
this is kinda youre whole config.yml thats why metadata files are separate from the config
