### ISSUE TITLE
Feature Request: Allow Custom Github Base

### ISSUE THREAD

**Issue by GD-L** [Kometa-Team/Kometa#630]
Per Line: https://github.com/meisnate12/Plex-Meta-Manager/blob/38818e8d4ee0aec59dc91a714e934648a07b1993/modules/meta.py#L10
Allowing users to input their own GitHub base and/or multiple bases from which to pull.

**Comment by meisnate12** [comment]
You can just use the raw url to any repo if you want to do this right now but I'll consider a custom repo tag of some kind

**Comment by GD-L** [comment]
Valid point. I may make a pull to the Wiki to make it clearer that the git points to `../Plex-Meta-Manager-Configs/` repo, or I may've missed that. 

I'm not super good at python but my thinking is:
`parser.add_argument("-g", "--git", dest="git", help="GitHub Repo", default="https://github.com/meisnate12/Plex-Meta-Manager-Configs, type=str)`
`gitrepo= get_arg("PMM_REPO", args.git, arg_bool=True)`

But, (personally) I'm not sure how to get `meta.py` to pass through the argument from `plex_meta_manager.py` without moving that module

**Comment by meisnate12** [comment]
you can now specify `custom_repo` in the global settings and then you can specify `repo` when defining metadata files

so if 
`custom_repo: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/`
and the metadata file is defined as `repo: meisnate12/Movies`
it will look for 
`https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/meisnate12/Movies.yml`

**Comment by nwithan8** [comment]
> you can now specify `custom_repo` in the global settings and then you can specify `repo` when defining metadata files
> 
> so if `custom_repo: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/` and the metadata file is defined as `repo: meisnate12/Movies` it will look for `https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/meisnate12/Movies.yml`

RE: this, the [docs](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Libraries-Attributes#:~:text=To%20use%20a%20Playlist%20File) still mention that this is for "Playlist Files" in the Metadata File section. Figured it was a typo, happy to fork and PR if needed, just wanted to confirm that this is indeed an error first.
