### ISSUE TITLE
Bug: Tautulli Error: Invalid url / OSError: [Errno 113] No route to host => can not connect to Tautulli

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#635]
Hello,

it seems PMM can not connect to tautulli.
The script seems to work greatly, I just have no idea, why it can not connect to tautulli. URL+API-KEY are correct.
Maybe a similar "verify_ssl" problem like [this](https://github.com/meisnate12/Plex-Meta-Manager/discussions/490)?

**Describe the Bug**
It seems, the script can not connect to tautulli.

My config:
Unraid Server IP 192.168.178.240
tautulli via docker: http://192.168.178.240:8183/
plex server via docker: https://192.168.178.241:32400

from my config.yml:
```
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.178.240:8183
  apikey: myapikey

```
**Plex Meta Manager Info**
Version: 1.15.0   

**Link to logs (required)**
https://gist.github.com/gitttt54/881281d8e880bc9b57a637f7a127c463

**Comment by gitttt54** [comment]
no one? (now using v1.15.1)

**Comment by bakerboy448** [comment]
"Tautulli URL: URL/api/v2?apikey=APIKEY&cmd=get_library_names"

Seems either the logging is wrong - if it's being cleansed then it should be (removed) - or based on all the other config errors in your log - your config file is not at all configured properly

Unless those logs were self censored and thus make troubleshooting near impossible.  Only the apikey would need to be censored.

The error is clear tho - the machine you're running PMM on has no route and no way to talk to the machine Tautulli is running on.

**Comment by meisnate12** [comment]
`"Tautulli URL: URL/api/v2?apikey=APIKEY&cmd=get_library_names"`
this is how i cleansed the logging in some spots.

sorry i missed this but as Baker said the error is happening because the containers are unable to talk to each other. If you can get on discord there's a lot more people available to help there but for now I'm going to close this as its not an error in the code itself
