### ISSUE TITLE
 Feature request: Please do not expose Api-Keys in meta.log (which needs to be linked in postings)

### ISSUE THREAD

**Issue by gitttt54** [Kometa-Team/Kometa#640]
### Feature description
When creating a Bugreport, we are informed, to add the full meta.log, which is fine.

Unfortunately, the log is not easy to read because of its format but I encountered 8 entries with my plain api-keys. (Those where for tautulli, which [I created a bug report ](https://github.com/meisnate12/Plex-Meta-Manager/issues/635)for)

Search for "myapikey" (which was my api-key) finds, i.e.: 
`
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.178.240', port=8183): Max retries exceeded with url: /api/v2?apikey=myapikey&cmd=get_library_names (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x145b446a5e50>: Failed to establish a new connection: [Errno 113] No route to host'))
`

It would be nice, if the log would not store any api-keys at all.

### Workarounds

Remove the secrets by hand via search&replace in your favorite texteditor.

**Comment by bakerboy448** [comment]
This can be cleansed by adding in some regex cleansing prior to writing the logs and replacing with `(removed)`

you can likely reuse the regex that \*arrs use

https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Common/Instrumentation/CleanseLogMessage.cs
