### ISSUE TITLE
Bug:  Plex Error : no Plex Libraries were connected to

### ISSUE THREAD

**Issue by Jackboxtv** [Kometa-Team/Kometa#641]
I had this script running; not sure why i keep running into this Plex Error; it was working before and suddenly stopped after adding Trakt; tried reverting to an older config however unable to get a successful run.

Not sure why but the discord channel invite is not available anymore
![Screenshot 2022-01-23 182205](https://user-images.githubusercontent.com/98289664/150702278-92046c88-0c4f-47a9-b988-9e31ec9f965d.png)
![Screenshot 2022-01-23 182018](https://user-images.githubusercontent.com/98289664/150702234-e9a9dd13-c908-41e4-aae7-6a2d0b0d216d.png)

**Comment by meisnate12** [comment]
It's probably because you have capital Libraries vs libraries also which link all the ones on the main read me seem to be working

**Comment by Jackboxtv** [comment]
not sure if i broke something; i swapped the letter for a small l

![Screenshot 2022-01-23 185009](https://user-images.githubusercontent.com/98289664/150703211-b31afe9e-4d0a-4c98-b046-e546433a140c.png)

**Comment by Jackboxtv** [comment]
I ended up resolving that thank you, however now its some other issue with tautilli
![Screenshot 2022-01-23 223306](https://user-images.githubusercontent.com/98289664/150717787-7456aaea-d97f-4a53-b76b-5ec4643de54b.png)

**Comment by Jackboxtv** [comment]
I got it to work; i somehow had two dockers sharing a port and it caused some issues

**Comment by gitthangbaby** [comment]
thanks, also had an extra letter in the config and didn't understand error "No Plex libraries were connected to", this helped me.
