### ISSUE TITLE
Bug: genre-mapper operation has no effect

### ISSUE THREAD

**Issue by Mushin** [Kometa-Team/Kometa#647]
**Describe the Bug**
The genre_mapper operation does not change any of the genre tags in the Plex library. In the logs, under the operations section the genre_mapper operation is not listed.

**Relevant Collection Config**
https://gist.github.com/Mushin/1ee00ab01e0f0729c2d9195f6c807f2e

**Plex Meta Manager Info**
- Version Number 1.15.0 

**Link to logs (required)**
- https://gist.github.com/Mushin/0d399520389d54de9e699c52e77d5c21

**Comment by YozoraXCII** [comment]
I was able to reproduce this issue

**Comment by Mushin** [comment]
This is working fine now on develop - thanks.

**Comment by Mushin** [comment]
It seems from my testing that this is working with the following syntax: 

```
genre_mapper:
  Action/Adventure:
    - Action
    - Adventure
```

But not with:

```
genre_mapper:
  Action/Adventure: Action, Adventure
```

**Comment by meisnate12** [comment]
ok try again with the latest develop
