### ISSUE TITLE
Feature Request: Convert Wiki from GH to MkDocs

### ISSUE THREAD

**Issue by bakerboy448** [Kometa-Team/Kometa#653]
**Is your feature request related to a problem? Please describe.**
The current wiki is difficult to read and navigate.

**Describe the solution you'd like**
Convert to MkDocs or similar proper wiki software like TRaSH did

**Describe alternatives you've considered**

-wikijs
-mkdocs
-??

**Additional context**

found a (old) script to convert that may work?
https://github.com/HerbFargus/Raspberry-Pi-Scripts/wiki/Github-Wiki-to-Mkdocs

**Comment by rclark213** [comment]
New wiki looks awesome!
