### ISSUE TITLE
Feature Request: assign Linux user/group to create directories when using "assets_for_all" operation

### ISSUE THREAD

**Issue by isaacolsen94** [Kometa-Team/Kometa#656]
**Is your feature request related to a problem? Please describe.**
When using the operation "assets_for_all" in docker on my linux machine it creates all the directories as root. Making it so I have to change the ownership of all directories so I can add assets into the directory.

**Describe the solution you'd like**
It would be nice to be able to specify which user/group to create the directories as.

**Describe alternatives you've considered**
I currently use the following command manually after I run the plex-meta-manager script:
`chown -chR nobody:users /mnt/user/appdata/plex-meta-manager/config/assets`

**Comment by chazlarson** [comment]
If you add the user to your `docker run` PMM will create artifacts as that user.

```
docker run -it --rm --user 1000:1000 -v /opt/pmm/config:/config meisnate12/plex-meta-manager:nightly --config config/config.yml -r
```
the `id` command will give you the values to use:
```
❯ id
uid=1000(seed) gid=1000(seed) groups=1000(seed),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lxd),999(docker)
    ^^^^           ^^^^
```
