### ISSUE TITLE
Feature Request: Rotate posters images within the same asset folder

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#668]
**Is your feature request related to a problem? Please describe.**
I think it would be cool that if an asset folder has two poster images within the same asset folder, PMM would randomly pick one of them to be the poster used in PLEX.

**Describe the solution you'd like**
For example. Let's say you have a collection of actors... like Al Pacino... and in your Al Pacino Folder, you have 3 different images that you like from Al Pacino in that folder....PMM could randomly pick one of those on each run to then add to Plex. On the next run, a different image could be picked. This would "freshen" up a stale library quite nicely.

**Describe alternatives you've considered**
No real alternative

**Additional context**

**Comment by meisnate12** [comment]
this is going to be too much in terms of having to search for files its not planned at this time
