### ISSUE TITLE
Feature Request: Clean Assets Folder

### ISSUE THREAD

**Issue by Drazzilb08** [Kometa-Team/Kometa#676]
This feature request is for a function that will clean the assets folders of folders/data that is not being used by PMM/plex? 

A simple `clean_assets_folder` true/false would be nice. 

Context: I’ve done a lot of manual work in my adventures with PMM and have a fair amount of unneeded folders. This can also happen when renaming collections

The general idea is for PMM to compare the list of folders to the list of entries of plex and remove unneeded folders and assets within

**Comment by meisnate12** [comment]
i dont want to give PMM this ability as it could lead to users deleting things they dont mean to
