### ISSUE TITLE
Feature Request: Spotify as a playlist source

### ISSUE THREAD

**Issue by Drazzilb08** [Kometa-Team/Kometa#677]
As discussed starting [here](https://discord.com/channels/822460010649878528/822460158684561428/937835635115438121) on discord. 

With the addition of music to PMM's capabilities, would it be possible to add spotify playlist syncs (much like with trakt or other list funcationality) with the usage of spotipy?
<https://spotipy.readthedocs.io/en/2.19.0/>

Further we discussed another discord project using python to create these playlists [here](https://github.com/XDGFX/ultrasonics)

Having music playlists synced from outside sources would be a great enhancement to PMM.

**Comment by hbooo** [comment]
Here is another project that allows to sync spotify/deezer playlists to plex : 

https://github.com/rnagabhyrava/plex-playlist-sync

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/spotify-builder-for-music)
