### ISSUE TITLE
Bug: locked DB

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#678]
**Describe the Bug**
in the log I can see that db is locked. 

**Relevant Collection Config**
- no

**Plex Meta Manager Info**
- 1.15.1-develop28 

**Link to logs (required)**
- If having an error with a specific collection include the collection.log otherwise please include the full meta.log file on [Gist](http://gist.github.com). _Do not upload attachments_.
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/7976436/meta.log)

**Comment by meisnate12** [comment]
does this happen on every run? or was this a one off?

**Comment by Nexius2** [comment]
it happened during a couple of days (even after restarting), then after an update, it vanished.... thought you sorted it out :-)
I'll keep checking if it happens again.

**Comment by meisnate12** [comment]
it was your sonarr db locking up doesnt seem to be a huge issue ill close this for now let me know if you see something again
