### ISSUE TITLE
Feature Request: Ratings/info from Common Sense Media and Does The Dog Die?

### ISSUE THREAD

**Issue by ponchohoncho** [Kometa-Team/Kometa#684]
**Is your feature request related to a problem? Please describe.**
The MPAA isn't always the best org to get ratings from, especially for older movies that wouldn't be PG these days.

**Describe the solution you'd like**
There are new orgs that provide ratings for movies of all ages, like Common Sense Media. They provide an API as well. Does The Dog Die is a site that provides crowdsourced warnings/spoilers for potentially traumatic scenes in media, like a dog dying or sexual assault.

**Additional context**
It would be pretty great if we could get additional/alternate ratings into the media's metadata from sources like Common Sense Media and Does The Dog Die

There's a few other projects that we could crib some notes and ideas from:
Common Sense Media Plex Agent, defunct: https://github.com/piplongrun/CSM.bundle
Does The Dog Watch Plex: https://github.com/valknight/DoesTheDogWatchPlex

**Comment by meisnate12** [comment]
I'm actually working on common sense but not though their api it's not easy to get a key. As for the other service I'll look into it.
