### ISSUE TITLE
Bug: 9.0 Movies copy pasted from the documentation doesn't work

### ISSUE THREAD

**Issue by jiquem** [Kometa-Team/Kometa#697]
**Describe the Bug**
A copy/past of the following configuration find in the documentation generate and error.

`
9.0 Movies:
    plex_all: true
    filters:
      rating.gte: 9
`
  

The error 
` Unknown Error: unsupported operand type(s) for /: 'NoneType' and 'int'  `

**Relevant Collection Config**
- Having a problem with a collection include the collection config from your metadata file.

**Plex Meta Manager Info**
Version: 1.14.1 

**Link to logs (required)**
`
|================================== Running 9.0 Movies Collection ===================================|
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| Collection Filter critic_rating.gte: 9.0                                                           |
|                                                                                                    |
| Processing Plex All Movies                                                                         |
| Loading All Movies from Library: Films                                                             |
| Loaded 1390 Movies                                                                                 |
| Unknown Error: unsupported operand type(s) for /: 'NoneType' and 'int'                             |
|                                                                                                    |
|====================================================================================================|
|                                   Finished 9.0 Movies Collection                                   |
|                                    Collection Run Time: 0:00:48                                    |
`

**Comment by YozoraXCII** [comment]
Can you try updating PMM first, you're running an old version.

**Comment by jiquem** [comment]
with the latest version, I dont have the message, but filter doesn't work. (I've tried with 8 instead of 9)

| Collection Filter critic_rating.gte: 8.0                                                           |
|                                                                                                    |
| Processing Plex All Movies                                                                         |
| Loading All Movies from Library: Films                                                             |
| Loaded 1390 Movies                                                                                 |
|                                                                                                    |
| Collection Minimum: 1 not met for 8.0 Movies Collection                                            |

**Comment by YozoraXCII** [comment]
Can you show me what your collection config looks like?
If you have a Discord account, drop a message in there as it will be easier to discuss there

**Comment by meisnate12** [comment]
also add `show_filtered: true` to the collection or turn it on globally under settings in the config.yml and you can see whats being filtered out.
