### ISSUE TITLE
Feature Request: build collection based on filename

### ISSUE THREAD

**Issue by edrock200** [Kometa-Team/Kometa#704]
Not sure if this is possible, but one filter that Plex lacks natively is audio format details such as Atmos. Radarr and Sonarr however are smart enough to include this in the file name if you have your media management rename rules set accordingly. So I'd like to build a collection based on Atmos audio, but the only way I know of to do so is to create a collection in which the actual movie file name contains "Atmos." Is this possible, or does anyone know of a better way to do this? Thanks in advance.

**Comment by meisnate12** [comment]
use the `filepath` `filter` with the `plex_all` buidler

**Comment by edrock200** [comment]
Thanks!
