### ISSUE TITLE
Feature Request: Show Added yml file created after run

### ISSUE THREAD

**Issue by fmr-iv** [Kometa-Team/Kometa#710]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Similar to the Movies_Missing.yml file that is created after a run, have the option to create a Movies_Added.yml file that shows the items added to a collection after a run.

It would also be nice to see Movies_Removed.yml (for sync collections that remove items from a collection).

**Describe alternatives you've considered**

**Additional context**

**Comment by meisnate12** [comment]
so would you expect this file to be replaced with each run or like the logs where it saves x number of runs back

**Comment by fmr-iv** [comment]
I envision it like the current behavior of the <LIBRARY>_missing.yml file that's created in the config directory after each run (and overwritten with each new run).

Ideally, the option to write:
- <LIBRARY>_missing.yml
- <LIBRARY>_added.yml
- <LIBRARY>_removed.yml

And maybe add a <LIBRARY>_changed.yml file, that is a combination of the added/removed outputs?

![image](https://user-images.githubusercontent.com/4317891/154310715-3f0aff9c-f9c8-4e3c-888d-aa87971000b1.png)

As background for this request, I have a large number of managed collections that I run every few weeks. I can't (easily) scroll through the entire log file or the CMD terminal to see what changed in a collection. Missing.yml is useful when I'm trying to expand my collections, but I often care about what's being added/removed if I disagree with a collection source (i.e. the IMDB list I use considers something a Horror film that I don't). Or I manually added a share label for a smart collection, but then it's removed since my config has "sync" enabled and that film isn't on the source list.

**Comment by meisnate12** [comment]
Added in 1.17.0
