### ISSUE TITLE
Feature Request: Change the way Overlays works so it copies the newly created overlays to a library specific directory.

### ISSUE THREAD

**Issue by JohnDoranNY** [Kometa-Team/Kometa#713]
Instead of having the Overlays created in the assets folder, and a copy of the original stored in the Overlays/4K (etc) folders, the Assets Folder should be treated as a central repository for images for all libraries (ie: 2D, 3D, 4K content).

Plex-Meta-Manager should find the original in the Assets folder, create the overlay, and save the newly generated file to a library specific folder.  In my case where I have separate folders for 2D (HD and SD), 3D and 4K content, its nice to have one central repository for all my posters so they are consistent across libraries.  If I run the overlay for 4K, and run the assets_for_all on a 3D library, it tries to use the 4K created images for posters. Not a very desirable effect.  If we can configure a saved images folder per library, and let Plex-Meta-Manager find the posters per library, copy them to the library specific assets folder, and if any overlays are created, overwrite them in the library specific assets library.  In this way, the original poster images are kept unmodified.

**Comment by JohnDoranNY** [comment]
Another thought (sorry)....

When an image is updated in the main repository of images, if the PMM scan for assets checks the datetime created and compares the images in the master to the images in the library specific folder of overlays created by PMM, if a newer version exists in the master repository, reprocess the overlay automatically using the newer image with the overlay?  It would ease up management of having to go into all versions of that title, manually delete the 4K Overlay tag from each, then go into the backup folder of images to delete the originals found there (currently) and reprocess. 

Thanks

**Comment by cpt-kuesel** [comment]
Overlays are designed in a way to work wether you have local posters or not, so basing it on the asset directory is not possible for the majority of people don't have a local poster for every item.
They are also designed in a way to update the poster in plex with a local poster before applying the overlay itself.

I don't follow your argument that you need four copies of a poster. my 4k and 1080p library share the same asset directory but have different overlay templates & collections. No need for the complicated workflow you describe above as overlays are only applied to the poster in plex which has been conveniently updated through pmm from my local assets.
