### ISSUE TITLE
Feature Request: Random collections displayed on home

### ISSUE THREAD

**Issue by kstanleyadams** [Kometa-Team/Kometa#717]
Problem: Too many collections to display on home screen. Can be slow and less interesting to see the same all the time.

Solution: Create the ability to add collections to a “random sets” to control their visibility as a randomly chosen subset of a group.

e.g. 

For a given collection, define:

```
visible_library: random0
visible_home: random0
visible_shared: random0
```

And to define random sets:

```
random_sets:
    random0:
         max_size: 10
    random1:
        max_size: 5
```

For each random set, aggregate all collections assigned to the random set, and only set the visibility to true for each `visible_x` attribute for up to `max_size` number of collections. If the number of collections assigned to the random set is larger than `max_size`, then a subset should be chosen at random.

This would speed up the home screen a bit, and also allow for the home screen to be freshened up each day or whichever frequency the script is run.

**Comment by meisnate12** [comment]
added this info to #520 but it falls in the same vain for me
