### ISSUE TITLE
Feature Request: Programmatically add custom info to summary

### ISSUE THREAD

**Issue by Mushin** [Kometa-Team/Kometa#718]
**Is your feature request related to a problem? Please describe.**
Some Plex clients either do not show audience and/or critic ratings, or make it difficult to access from the movie page without clicking on further links.

**Describe the solution you'd like**
To programmatically add custom info to the summary, from other metadata fields. 
For example, adding the IMDB and RT scores as a prefix to the existing summary (Alien - 1979):

_IMDB: 8.4; RT: 98%. After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun._

**Describe alternatives you've considered**
It could also be useful to extend this to add other info into the summary, for example play count or date added.

**Additional context**
This used to be possible with the old OMDB agent, before it was removed.

**Comment by YozoraXCII** [comment]
Just to expand upon this idea, you could theoretically add labels to the item too with `IMDB: 84` `rt: 98` etc, and maybe PMM could have a custom logic for let's say "rt.gte: 30" which would scan the labels with the "RT: x" format and make the collection of ones where it is greater than or equal to 30

**Comment by Mushin** [comment]
Could this be addressed in a similar way to as mentioned in #699 (e.g. using a more general metadata_mapper), in combination with a template that allows access to other metadata fields?

**Comment by meisnate12** [comment]
This is not gonna happen. i already have the mass rating operations and if thats done then it will work plex_search/smart_filter

> Just to expand upon this idea, you could theoretically add labels to the item too with IMDB: 84 rt: 98 etc, and maybe PMM could have a custom logic for let's say "rt.gte: 30" which would scan the labels with the "RT: x" format and make the collection of ones where it is greater than or equal to 30

This isnt really mapping the metadata itll be its own library operation
