### ISSUE TITLE
Genre_mapper - Leaving genre blank to remove the genre causes error

### ISSUE THREAD

**Issue by jrizz43** [Kometa-Team/Kometa#720]
Per the genre_mapper instructions it says "To just Remove a Genre without replacing it just set the Genre to nothing like this. Ex: Horror: (blank)" and it will remove that genre. Leaving any genre blank produces the following error:

|========================================================================================
============|
|                                        Movies Configuration                            
            |
|========================================================================================
============|
|                                                                                        
            |
| Connecting to Movies Library...                                                        
            |
| 'NoneType' object is not iterable

**Comment by meisnate12** [comment]
what version of pmm are you using

**Comment by jrizz43** [comment]
1.15.0

**Comment by meisnate12** [comment]
This feature was added in 1.15.1 update and you should be good
