### ISSUE TITLE
Bug: delete_unmanaged_collections deletes ALL collections

### ISSUE THREAD

**Issue by JohnDoranNY** [Kometa-Team/Kometa#724]
When I used delete_unmanaged_collections, it deleted all collections in my library... Those created by PMM as smart collections, those created by PMM via tmdb_collections operation, those created as standard collections with PMM, and any custom created by hand.

Wouldn't 'unmanaged' be any collection not created by PMM (since PMM is managing the collections it creates)?  Or am I misunderstanding the use of this operation?

**Comment by meisnate12** [comment]
you are indeed correct ill look into this are you on master or develop?

**Comment by JohnDoranNY** [comment]
I am on master... I am a programmer, but in c# .NET... I haven't used python in ages and ages.. though I think with PMM I might refresh myself so I can dig in and help.

**Comment by meisnate12** [comment]
feel free to contribute and if you wanna have an easier time chatting about it hop on the discord. PMM was actually the first time ive ever used python (I use Java by trade mainly)!

**Comment by JohnDoranNY** [comment]
Please see newly created bug issue #732, which I believe may be related in some way to this issue.

**Comment by JohnDoranNY** [comment]
So I think I found the issue (after much time)

delete_collections_with_less was set to "false" not to an integer value.  This seems to screw things up.  Perhaps there needs to be error checking code put in when reading this value that if it is not a valid integer, it throws an error message to the user (?) .  It should fail to run so as not to produce unpleasant results (like deleting every/all collection) when not set correctly.

**Comment by meisnate12** [comment]
sorry it took so long to get back to you so yes that should throw an error and default to None which doesn't delete collections i did just push a fix to the new nightly build if you wanna test
