### ISSUE TITLE
Bug: There seems to be a problem with Smart Collection Filter by Genre when a Genre does not exist.

### ISSUE THREAD

**Issue by JohnDoranNY** [Kometa-Team/Kometa#735]
When setting up a smart collection for, lets say cooking:  you set genres "cooking, food".  If the library contains the genres, then the smart collection works fine. However, if a genre does not exist, it defaults to the first genre it finds in the list... in my case, in TV library it found cooking shows fine.. in my Movie library, where neither cooking nor food genres exists, the smart collection becomes "where genre is Children AND genre is Children" (children is the first item in the list of genres that I see).  I have validation on for collections but did not see an error when this happened, just saw a cooking collection with > 5K movies in it...

**Comment by YozoraXCII** [comment]
This is an limitation with my configurations (which you seem to be using).
I'm sure the template has validation set to false, but you can turn it on for the ones that you have issues with to get around this issue.
Alternatively, I would suggest you comment out the collection where you do not have any of the desired genres.

This can be closed as it isn't really a PMM issue, it's an issue with my configs.
