### ISSUE TITLE
Bug: Incorrect number filtering when attribute value is equal to 0

### ISSUE THREAD

**Issue by johnny-onthespot** [Kometa-Team/Kometa#736]
I'm trying to filter out elements whose play count is > 0 (played elements).
My filter is thus :

    filters:
      plays.lt: 1

However, this does not seem to work. I traced the issue down to the function check_filters in builder.py

```python
                elif modifier in [".gt", ".gte", ".lt", ".lte"]:
                    divider = 60000 if filter_attr == "duration" else 1
                    test_number = getattr(item, filter_actual)
                    if not test_number:
                        return False
                    if util.is_number_filter(test_number / divider, modifier, filter_data):
                        return False
```

The ```if not test_number``` returns ```True``` whenever test_number is 0, which filters out the element.
I assume that the test should rather be ```if (not test_number and test_number != 0):```
This works on my side.

**Comment by meisnate12** [comment]
should be fixed in develop
