### ISSUE TITLE
Feature Request: Expand Functionality of Summary

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#738]
At present, the summary field at the end of the run only shows the addition, keep and remove of items from collections. As a result, if I change any of the fields in my collections (like the sort order), the Status of my collection in the summary shows "unchanged" which is somewhat misleading.

The Status column on the summary could be amended to say "sort_order field modified" or similar, and would list any of the changes that have been made to the collection.

**Comment by meisnate12** [comment]
Added in 1.17.0
