### ISSUE TITLE
Feature Request: Use tini for the docker container.

### ISSUE THREAD

**Issue by saltydk** [Kometa-Team/Kometa#743]
**Is your feature request related to a problem? Please describe.**
Docker container does not exit gracefully, use something like https://github.com/krallin/tini to properly shut things down. Instead of having to wait for docker to force kill the container.

**Describe the solution you'd like**
Use tini or something similar.

**Describe alternatives you've considered**
Not sure it applies.

**Additional context**
None.

**Comment by meisnate12** [comment]
im gonna be honest im not sure how to use this

**Comment by saltydk** [comment]
I can play around with it later and send a PR if you want.

**Comment by meisnate12** [comment]
sure im always open to PRs
