### ISSUE TITLE
Feature Request: `trakt_watched_weekly` filter by genre

### ISSUE THREAD

**Issue by brettpetch** [Kometa-Team/Kometa#751]
**Is your feature request related to a problem? Please describe.**
It is currently a pain to use mdblist to do something that can be filtered with the trakt api. 

**Describe the solution you'd like**
If we could add filtering by most watched in time period + genre, we would be able to more robustly define netflix-esque collections.

**Describe alternatives you've considered**
Using MDBList to get close.

**Additional context**
Discord Conversation: https://discord.com/channels/822460010649878528/822460010649878531/950110843482279987

**Comment by meisnate12** [comment]
Trakt Goals with links for later use 

* Add `sort_by` to [`trakt_list`](https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list) and [`trakt_watchlist`](https://trakt.docs.apiary.io/#reference/users/watchlist/get-watchlist)
* Add [`trakt_watched_personal`](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) and rename `trakt_collection` to [`trakt_collected_personal`](https://trakt.docs.apiary.io/#reference/users/collection/get-collection)
* Add all [Filters](https://trakt.docs.apiary.io/#introduction/filters) to `trakt_trending`, `trakt_popular`, `trakt_recommended_*`, `trakt_watched_*`, `trakt_collected_*`
