### ISSUE TITLE
[Feature]: IMDb keywords and Parental guide

### ISSUE THREAD

**Issue by Anuskuss** [Kometa-Team/Kometa#756]
### Is your feature request related to a problem? Please elaborate.

I found this [feature suggestion over at the Plex forums](https://forums.plex.tv/t/scrape-imdb-keywords-and-the-parental-guide/779709) which talks about the ability to restrict certain tags via labels and I think you'd be able to accomplish that in PMM. You can already [filter by IMDb keywords](https://www.imdb.com/search/title/?keywords=chase) (which will tag your media) but I don't think you're able to do that the other way around yet.
But maybe that's not necessary, as you could just compile a list of common keywords and tag your media like that. It's not elegant but it works.

### Describe the solution you'd like

Allow the user to tag media based on [IMDb keywords](https://www.imdb.com/title/tt1877830/keywords) and also convert the [Parental Guide](https://www.imdb.com/title/tt1877830/parentalguide) into keywords like `violence-none`, `violence-severe`, etc.

**Comment by meisnate12** [comment]
when you say tag what do you mean? add a sharing label or add the keyword/parental guide as a genre or some other meta tag?

**Comment by Anuskuss** [comment]
Adding the keywords as labels. That way you could restrict certain topics (keywords) or certain categories (nudity, violence, profanity, drugs, intensity). When you filter by IMDb keywords, the media already gets tagged/labeled with that keyword (which allows you to create a Smart Collection based on that tag). I want it the other way though: Instead of applying a specific tag to all relevant media, I want my media to be tagged with all available keywords.

**Comment by meisnate12** [comment]
You can add labels to all items found by the builders by using item_label and you can use build_collection: false to not actually create the collection. That's one way you could managed to get the tags right now. I know not what you're asking for but it's a stop gap until the feature is complete.

**Comment by Anuskuss** [comment]
> You can add labels to all items found by the builders by using item_label and you can use build_collection: false to not actually create the collection.

I mentioned that earlier but thanks for confirming. Yeah, it's not ideal but it works.

I would actually really like to see IMDb keywords being supported natively by Plex but sadly they don't care about these kind of features (a similar suggestion was made in 2017 but has since been ignored). I looked at a few movies and the keywords are very extensive. Not only admins would benefit from them but also managed users and friends (e.g. the current "Related movies" selection is garbage and would benefit immensely from keywords).

Anyway, back on topic: Hopefully you find the time to implement this someday. I think this would also speed up the creation of new collections because the tags would already be there. I've been using PMM for a few months now but haven't really dove deep. Can you create a trigger to potentially apply all tags after new media has been added or does PMM only support intervals?

**Comment by meisnate12** [comment]
so theres too many keywords to realistically add to your plex items (The Batman has 745) i could create a function where you can specify certain keywords and then if a movie has that keyword a label will get added to the movie.

**Comment by YozoraXCII** [comment]
> so theres too many keywords to realistically add to your plex items (The Batman has 745) i could create a function where you can specify certain keywords and then if a movie has that keyword a label will get added to the movie.

Just to counter this slightly, you could only include key words where more than 1 person found it relevant:

![image](https://user-images.githubusercontent.com/96386153/158401084-e4239d5e-7b24-4a52-8943-c8c7d793105b.png)

For The Batman this would reduce the list to 20, or you could do the top "X" keywords based on relevance

**Comment by meisnate12** [comment]
and then you have https://www.imdb.com/title/tt4154796/keywords endgame which has 256  by that count. Its honestly just a lot and i dont know if theres a cap on how many labels an item can have

**Comment by Anuskuss** [comment]
> Just to counter this slightly, you could only include key words where more than 1 person found it relevant

I thought about that as well but that's too unreliable. Same with excluding "0 of X found this relevant" keywords. It'd say we just trust the data, refresh periodically and hope that the truly irrelevant keywords get removed over time. That's the main approach to user contributed data anyway - "hope" that everything is correct(ed) in the end.


> i could create a function where you can specify certain keywords and then if a movie has that keyword a label will get added to the movie.

This sounds reasonable. The original idea was not to create collections based on some obscure topics but to limit certain keywords (e.g. rape, incest, drugs, etc.) so this approach works. I might look into creating such a list of "controversial" keywords but it would be helpful if you coud collect some data beforehand (maybe go through a bunch of movies and sort keywords by appearance).

Also don't forget about the Parental guide. That's useful, too.

**Comment by meisnate12** [comment]
> Also don't forget about the Parental guide. That's useful, too.

Oh i didnt i just didnt have any questions about it lol. The `mass_imdb_parental_labels` library operation has already been added to nightly

**Comment by meisnate12** [comment]
so i was thinking on this and you can already add keyword labels as you want just do this.

```yaml
collections:
  Label Iron Man Character Keyword:
    build_collection: false
    imdb_list: https://www.imdb.com/search/keyword/?keywords=iron-man-character
    item_label: Iron Man Character
    non_item_remove_label: true
```

**Comment by Anuskuss** [comment]
@meisnate12 I didn't try your approach myself but I thought we already established that this is possible in https://github.com/meisnate12/Plex-Meta-Manager/issues/756#issuecomment-1062394707. If that's all you want to offer, given the large number of keywords you've mentioned earlier, I'm totally fine with that. This will absolutely work for filtering sensitive topics. I didn't have much time lately but I'll make sure to deploy this in my own setup as soon as possible (not that this needs any feedback anyway).
Although the other part of this feature request was the ability to use the Parental guide which I don't think has been implemented yet.

**Comment by meisnate12** [comment]
it has `mass_imdb_parental_labels` is a library operation 

https://metamanager.wiki/en/nightly/config/operations.html?highlight=mass_imdb_parental_labels#operations

**Comment by thedenethor** [comment]
Is it possible to add this information also into library items "summary"  section? With this way data will be visible to users while browsing movies from apps. Would be very useful to select movie to watch with the kids. 

I manually edit one of my movies to demonstrate my request. (I don't know why Plex UI adds blank lines between PG categories)

![](https://i.imgur.com/LiuDkbL.jpeg)

By the way first line is MPAA detailed description and with quick google search looks like it can be parsed by imdbpy

> movie = ia.get_movie("1640718", info='parents_guide')
print(movie['mpaa'])

**Comment by meisnate12** [comment]
well #1 i dont use imdbpy but yea i could easily pull that info this needs to be added as its own feature request at features.metamanager.wiki

**Comment by thedenethor** [comment]
> well #1 i dont use imdbpy but yea i could easily pull that info this needs to be added as its own feature request at features.metamanager.wiki

Wow that was fast. I'm going to visit features.metamanager.wiki right away, thanks!
