### ISSUE TITLE
[Feature]: dry-run mode

### ISSUE THREAD

**Issue by mlsmithjr** [Kometa-Team/Kometa#759]
### Is your feature request related to a problem? Please elaborate.

No existing issue.

### Describe the solution you'd like

A commandline option to run in dry-run mode only, ie. don't make any Plex updates.  That way we can see changes as we're working on our configs before disrupting plex.

**Comment by meisnate12** [comment]
i dont plan on adding this as you can just delete the collection/playlist after the updates are made if you need to reset
