### ISSUE TITLE
[Feature]: Interface with Readarr server/Goodreads.com to also create Plex Collections for Audiobooks

### ISSUE THREAD

**Issue by Mantene** [Kometa-Team/Kometa#766]
### Is your feature request related to a problem? Please elaborate.

I use Plex as my audiobook server due in large part to the excellent Prologue app on iOS. There is no wat to automatically create collections in Plex for audiobooks. For example, I would love it is all the Stephen King books were in a collection, and all The Wheel of Time books in another.  Currently, the Readarr server application DOES use Author as the primary method of categorizing books., but Plex does not really interact with Readarr. Likewise, Goodreads (or even Audible) have information on what series a book belongs to, and both have public APIs, I believe. 

### Describe the solution you'd like

It would be nice if PMM were able to also work with an Audiobook library in Plex (it is a Music library as far as Plex is concerned). Even if all it did was use the metadata in plex to create collections, that would be a great addition to PMM. I use the AudNexus Plex Agent to help with Metadata, so it is a pretty good starting point, I guess? Just a thought.

**Comment by meisnate12** [comment]
you can use a plex_search or smart_filter on a music library right now ill look into the rest

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/integrate-readarr-and-add-builders-for-audiobooks)
