### ISSUE TITLE
[Feature]: AniList Userlist builder options

### ISSUE THREAD

**Issue by Frazzer951** [Kometa-Team/Kometa#768]
### Is your feature request related to a problem? Please elaborate.

Similar to how the MAL Builder has an option for user lists, it would be nice to have the same for AniList.

### Describe the solution you'd like

Basically the same usage as the mal_userlist but for AniList Instead.

**Comment by meisnate12** [comment]
Are the lists public?

**Comment by Frazzer951** [comment]
I believe so, If I switch to an Incognito browser I can still access my lists

**Comment by meisnate12** [comment]
Could you share one here for me to look at

**Comment by Frazzer951** [comment]
https://anilist.co/user/Frazzer/animelist                  - Has All Animes
https://anilist.co/user/Frazzer/animelist/Watching - Has Just Watching
https://anilist.co/user/Frazzer/animelist/Planning  - Has Planning to Watch
and so on for other user lists.

**Comment by Frazzer951** [comment]
Also looking at the API docs, It looks like you can get the user's lists through a `MediaList query` using a `userName` or `userId_in` with `status_in` to mark the list type
