### ISSUE TITLE
Plex Beta TV Agent

### ISSUE THREAD

**Issue by wildsavage** [Kometa-Team/Kometa#77]
Just moved to the beta TV agent released by Plex yesterday. Results in a number of "Agent plex not supported for [show name]" errors in the logs. I think the Plex agent holds the same TVDB, IMDB, TMDB data in it's metadata, so hoping it's just a quick fix to not error on the new agent.

**Comment by meisnate12** [comment]
I haven't had the chance to play with the new agent but this will get added

**Comment by meisnate12** [comment]
develop has an update that includes the New Plex TV Agent support can you test?

**Comment by meisnate12** [comment]
ok so support for the agent has been added to the develop branch and will be included with version 1.4.0
