### ISSUE TITLE
[Feature]: Push PMM generated collections to TRAKT as lists

### ISSUE THREAD

**Issue by littlebirdiegr** [Kometa-Team/Kometa#770]
### Is your feature request related to a problem? Please elaborate.

I would like to request this once more and put an official request on github for better management.

### Describe the solution you'd like

I would like for the lists to be what the collections look like in Plex. Each collection would have its own respective list on Trakt.

**Comment by snickers2k** [comment]
yes, great idea - but a duplicate

Feature Request: external builders (create trakt lists) #557

**Comment by meisnate12** [comment]
Added in 1.17.0
