### ISSUE TITLE
[Feature]: Plex Collections from Radarr/Sonarr Tags

### ISSUE THREAD

**Issue by tahmidul612** [Kometa-Team/Kometa#784]
### Is your feature request related to a problem? Please elaborate.

It seems that you can have PMM add radarr/sonarr tags to movies/shows in a plex collection. But it does not work the other way, where pmm gets content with a specified tag from the arrs and create collections for those tags.

### Describe the solution you'd like

I would like to have a feature so that PMM could create plex collections based of radarr/sonarr tags.

**Comment by meisnate12** [comment]
Added in 1.17.0
