### ISSUE TITLE
[Feature]: Add mal_search MyAnimeList Buidler

### ISSUE THREAD

**Issue by hbooo** [Kometa-Team/Kometa#785]
### Is your feature request related to a problem? Please elaborate.

I tried to implement collections based on mal_genre but it takes very long time to create Collections because parsing of each genre is very long due to the amount of items retrieve. The item list could be reduce if we could filter by type (tv, movies, oav, etc...)

### Describe the solution you'd like

Add the https://docs.api.jikan.moe/#operation/getAnimeSearch endpoint as `mal_search`

### Additional Information

Link to PMM thread : [https://discord.com/channels/822460010649878528/953652842596560896](https://discord.com/channels/822460010649878528/953652842596560896)

**Comment by meisnate12** [comment]
Added in 1.17.0
