### ISSUE TITLE
Add Dynamic Collection Sort

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#787]
### Is your feature request related to a problem? Please elaborate.

Dynamic collections have opened up a new "sorting" possibility

### Describe the solution you'd like

Ability to sort the Dynamic collections in ascending or descending based on the number of items in that collection.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/allow-dynamic-collections-to-be-sorted)
