### ISSUE TITLE
[Feature]: Operation to Change Release Date (Theatrical, Physical, Digital etc)

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#794]
### Is your feature request related to a problem? Please elaborate.

I had a thought, not sure how easy it would be to implement but it seems pretty straight forwards.

I'm not a massive fan that new movies such as Spider-Man don't appear at the top of release.desc collections because it's using the Theatrical release date which was in 2021.

I can see in the TMDB API that you can get the following release dates:
Premiere
Theatrical (limited)
Theatrical
Digital
Physical
TV

### Describe the solution you'd like

Would it be possible to have an operation to update the release dates such as  mass_release_date_update: Digital, which would place Spider-Man's release date as 03/15/2022 rather than 12/13/2021

In the scenario that this info isn't available, maybe it would be better as an ordering so you do Digital, Physical, Theatrical to set your preference levels?

### Additional Information

This may make more sense as an extension of `mass_originally_available_update` than being its own operation?

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/add-option-to-get-a-different-release-date-from-tmdb)
