### ISSUE TITLE
[Bug]:  TypeError: tv_show() got an unexpected keyword argument 'partial' 

### ISSUE THREAD

**Issue by codesterribly** [Kometa-Team/Kometa#795]
### Version Number

1.16.2

### What branch are you on?

develop

### Describe the Bug

movie() got an unexpected keyword argument 'partial' 

Lots of errors. I'm assuming something has changed under the hood, and I need to update/change config or a library version.

Searched around, didn't find anything.

" TypeError: tv_show() got an unexpected keyword argument 'partial' "

### Logs

https://gist.github.com/codesterribly/aca2ade941441e43edd63975e2f30f81

**Comment by kevbentz** [comment]
I had an error very much like this and was unable to figure it out.  I backed up my config files, wiped the directory, and did a fresh install and it worked fine.

**Comment by roaddolphin** [comment]
I did the same thing and nothing happened. I even pulled different branches. Same error.

Ubuntu 21.10

I figured it was a version mismatch in some Python library somewhere but I didn't see anything obvious.

**Comment by meisnate12** [comment]
basically the underlying dependency TMDbAPIs didn't properly update

**Comment by roaddolphin** [comment]
So what is the proper way to fix this error?

**Comment by meisnate12** [comment]
i would try reinstalling requirements and if that doesn't work follow the local installation guide and set up a brand new instance pmm with a brand new virtual environment.
