### ISSUE TITLE
[Feature]: option to run metadata files through YAML pretty-printer before use

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#798]
### Is your feature request related to a problem? Please elaborate.

It seems that there are regular problems with YAML formatting issues that don't have to do with PMM; things like using tabs and spaces to indent and so on.

It might be useful to provide a facility to run metadata YAML files through a linter to clear some of these things up [or make them more obvious in later inspection] prior to trying to process the file.

### Describe the solution you'd like

I'm imagining a global setting like `preflight_yaml_files=True` or the like that would lint the user's metadata files, saving a "Whatever.yml.original` if possible, and throwing an error if:
1. file can't be written
2. file fails linting

And a warning if:
1. backup can't be written

**Comment by meisnate12** [comment]
problem with this is most of the YAML errors we get are happening on the load of the file so we couldnt really prettify it when we cant load it. it would have to be something separate like http://www.yamllint.com/
