### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#813]
### Version Number

1.16.3

### What branch are you on?

develop

### Describe the Bug

For information, when starting the container, not when starting PMM, I have this message in the logs.
/modules/meta.py:994: SyntaxWarning: "is" with a literal. Did you mean "=="?
if season.seasonNumber is 0:

can't see any issues with it. I only have problems with smart_label: audience_rating.desc but doesn't seem to be concerned by this log.

### Logs

no log

**Comment by YozoraXCII** [comment]
Thanks for submitting this, we are aware of this issue - it is not believed to cause any functionality issues but is on the list of things to be addressed :)
