### ISSUE TITLE
[Feature]: basic web gui

### ISSUE THREAD

**Issue by admitguy** [Kometa-Team/Kometa#815]
### Is your feature request related to a problem? Please elaborate.

I think a functional web gui would help alot.. I am **constantly** finding myself wanting to update my collections several times a day, and the only way to do that is to manually run the command via a docker console (running on unraid docker). I think a gui with something as simple as a 'Run' button would make my life infinitely easier. 

### Describe the solution you'd like

Either a basic web gui with a run button and/or the ability to schedule runs every hour, not once a day.

**Comment by YozoraXCII** [comment]
A Web GUI is planned for future release - there are a couple things to be addressed first, but it is definitely in the pipeline.
