### ISSUE TITLE
TV Show posters not found

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#82]
I'm trying to add posters for a TV Show collection, but I don't get any result. I have the posters working fine for movie collections, so I know the basic setup. I'm just not sure if there is something else that goes for shows
```
| Scanning Dune Collection                                                                           |
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Processing TMDb Show: (19566) Frank Herbert's Dune (1 Show)                                        |
| Dune Collection | = | Dune                                                                         |
| 1 Show Processed                                                                                   |
|                                                                                                    |
| Processing TMDb Show: (9156) Frank Herbert's Children of Dune (1 Show)                             |
| Dune Collection | = | Children of Dune                                                             |
| 1 Show Processed                                                                                   |
|                                                                                                    |
| 0 Show Removed                                                                                     |
|                                                                                                    |
| No Files Found: /config/assets/Dune/TV Shows                                                       |
| No Files Found: /config/assets/Dune/TV Shows                                                       |
| Detail: asset_directory updated collection poster to [file] /config/assets/Dune/poster.png         |
|                                                                                                    |
```

I have tried to put the poster.ext files in `TV Shows/Dune` and `TV Shows/Children of Dune` in the assets folder for Dune, but no result. I tried putting the show folders in the Dune folder and that didn't work either. How do I set it up?

**Comment by meisnate12** [comment]
it should function exactly as it does for movies. It uses the exact same code lol

Also is it just not updating in plex because the output above is saying it updated the poster to `[file] /config/assets/Dune/poster.png`

**Comment by meisnate12** [comment]
oh I get it your trying to update the poster of the show in the collection it should look like this

```
├── config/assets
│   ├── Dune 
│       ├── poster.png
│       ├── background.png
│       ├── Dune
│           ├── poster.png
│           ├── background.png
│       ├── Children of Dune
│           ├── poster.png
│           ├── background.png
```

**Comment by meisnate12** [comment]
ok i figured out that this is in fact a bug because the Show Location is in a different format so that's why its not working ill get it patched soon

**Comment by meisnate12** [comment]
fix is in the develop branch

**Comment by Alaksin** [comment]
It's working fine now. And now that TV show poster is working that naturally leads me to a follow up question. What about Season posters? Looks like it's not implemented, but it would be very nice

**Comment by meisnate12** [comment]
yea i can do that

**Comment by meisnate12** [comment]
ok its been added to dev the Season posters need to be in the same folder as the show posters and they need to be called: `Season00.*`, `Season01.*`, `Season02.*`, `Season03.*`, ..., `Season10.*`, `Season11.*`, and so on.
