### ISSUE TITLE
[Feature]: Plex Search results and "parsing" output should be cached and reused

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#831]
### Is your feature request related to a problem? Please elaborate.

I'm running a series of overlays; most of them are based on `plex: all` with filepath filter.  This means that for every overlay PMM "parses" the same list of 884 IDs; this is happening 12 times in my case at a couple minutes each time.  I imagine that work is the same every time, so it seems like it could be done once instead of a dozen times, taking 4 minutes instead of close to 40.

For a larger library [like my 3000-item 4K library] this will be even longer, probably near 2 hours.

### Describe the solution you'd like

I'd like the output of the "plex search + parsing" to be cached and reused during a single run of PMM, similar to the way that builders can be cached.  I don't necessarily see a reason to cache them for longer than the duration of a single run.

The output of the "search+parse" operation as a whole could be cached, perhaps keyed on a hash of the search definition, or the parse output from individual items could be cached.  I haven't looked at the code yet, but I imagine that when PMM parses ID 12345 as part of one plex-search it does the same thing as for another plex-search, so if individual parse output were cached, that could benefit all subsequent searches.

The overlay case is the egregious offender, though, in my mind, since by definition it will often or likely involve repeated identical searches in close temporal proximity to one another.

**Comment by meisnate12** [comment]
Added in 1.17.0
