### ISSUE TITLE
[Bug]: Encoding Error: 'latin-1' codec can't encode character '\u2026'

### ISSUE THREAD

**Issue by BAlvernaz** [Kometa-Team/Kometa#834]
### Version Number

1.15.5

### What branch are you on?

master

### Describe the Bug

Same Issue as https://github.com/meisnate12/Plex-Meta-Manager/issues/137

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026'

### Logs

https://gist.github.com/BAlvernaz/25d04aa2286f247654ff08fdea7a4b19

**Comment by meisnate12** [comment]
Added in 1.17.0
