### ISSUE TITLE
[Bug]: smart_label issue with some sort options

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#839]
### Version Number

1.16.5

### What branch are you on?

develop

### Describe the Bug

when using smart_label, popularity.asc does not work

I have tested random, release and audience_rating they work well
return message is:
 Collection Error: smart_label attribute: popularity.asc is invalid defaulting to random 

### Logs

https://gist.github.com/Nexius2/cd3c81babe71715c695540d046478784

**Comment by YozoraXCII** [comment]
Popularity.asc is only valid for track-based collections (i.e. Music libraries)

<https://metamanager.wiki/en/nightly/metadata/builders/smart.html?highlight=smart_label#sort-options>

**Comment by Nexius2** [comment]
:-/
is there a way to sort it by popularity?

**Comment by GrangerGenetics** [comment]
popularity isnt a metadata field that plex has for movies so no you can sort by `audience_rating`, `critic_rating` or `user_rating`

**Comment by meisnate12** [comment]
no as its not a piece of metadata that plex tracks for movies or shows try using `critic_rating`, `audience_rating`, or `user_rating`
