### ISSUE TITLE
Setting url_background to null causes collection to be skipped

### ISSUE THREAD

**Issue by PleaseStopAsking** [Kometa-Team/Kometa#84]
I have set some of my collection backgrounds to a null value when I am unable to locate a nice enough image to use which previously prevented PMM from using whichever image it choose pre 1.3.0. With the latest release, PMM now skips the collection entirely with the message ```Collection Error: url_background attribute is blank```.

The workaround would be to remove the ```url_background``` parameter from all collections that do not leverage it but I prefer to leave it in and set to null so that I can quickly search for ```url_background: null``` in the future and replace when I come across images I like.

With this said, is this new behavior as designed or unintentional?

**Comment by meisnate12** [comment]
Thats the intended behavior. If you use an attribute but leave it blank I'm assuming you forgot to fill something in so I wanted a message for the user.

**Comment by meisnate12** [comment]
well after rereading your question the intended behavior is to skip the image not the collection let me look at this closer

**Comment by PleaseStopAsking** [comment]
> well after rereading your question the intended behavior is to skip the image not the collection let me look at this closer

Let me know if anything is needed from my end for validating the issue.

**Comment by meisnate12** [comment]
fix is in develop is you want to test
