### ISSUE TITLE
[Feature]: Remove from continue watching

### ISSUE THREAD

**Issue by Frazzer951** [Kometa-Team/Kometa#840]
### Is your feature request related to a problem? Please elaborate.

I have a set of shows that I like to have playing in the background that I have in a collection, but these shows start to fill up my continue watching screen with a bunch of junk, and I have to manually go in and remove them from the `continue watching` section.

### Describe the solution you'd like

An option for collections that would remove any shows in the collection from the continue watching section.

### Additional Information

Here is what it looks like from the UI, but I'm not sure how difficult it would be to implement on the API level
![image](https://user-images.githubusercontent.com/23227655/165807343-68513af9-4c0d-4e1c-85de-99dd42cee79a.png)

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/remove-from-continue-watching)
