### ISSUE TITLE
[Feature]: Adding icheckmovies as playlist/collection source 

### ISSUE THREAD

**Issue by levander051** [Kometa-Team/Kometa#843]
### Is your feature request related to a problem? Please elaborate.

I have been using www.icheckmovies.com for few years and I have made and collected many lists there not available elsewhere...

### Describe the solution you'd like

www.icheckmovies.com is simple movie list site with very rich list db made by users and "official" lists made by staff, it would be cool to have it as a source...

**Comment by meisnate12** [comment]
It's already a builder 

https://metamanager.wiki/en/latest/metadata/builders/icheckmovies.html
