### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#860]
### Version Number

latest (fresh install)

### What branch are you on?

master

### Describe the Bug

```
  File "plex_meta_manager.py", line 83
    print(f"Argument Error: width argument invalid: {screen_width} must be an integer between 90 and 300 using the default 100")
                                                                                                                              ^
SyntaxError: invalid syntax
```

already tried to fresh install, but same bug.

### Logs

haveno

**Comment by chazlarson** [comment]
How are you running PMM?

**Comment by snickers2k** [comment]
because you asked, i tried with "python3" instead of just "python" and it worked .. hmpf.. thank you
