### ISSUE TITLE
[Feature]: When running --collection-only or --libraries-only, don't run playlist operations

### ISSUE THREAD

**Issue by AevumDecessus** [Kometa-Team/Kometa#864]
### Is your feature request related to a problem? Please elaborate.

When running --collection-only or --libraries-only, playlists are also queued up

### Describe the solution you'd like

When running library only or collection only operations, don't also run playlist operations. Either skip playlist operations if running --collection-only or --libraries-only, or add a new flag such as --skip-playlists to not run them, as syncing playlists takes a long time with many users

**Comment by meisnate12** [comment]
Added in 1.17.0
