### ISSUE TITLE
[Docs]: Typo in Settings Details

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#867]
### What is the improvement or update to the Wiki you wish to see?

-In Settings Details-
First row (name):
"Description: Used to specify the name off the collection/playlist in Plex as different then the mapping name."
Should be:
"Description: Used to specify the name **of** the collection/playlist in Plex as different **than** the mapping name."

2nd row (limit):
"Values: Number greater then 0"
Should be:
"Values: Number greater **than** 0"

6th row (minimum_items):
"Values: number greater then 0"
Should be:
"Values: Number greater **than** 0"

The "then vs than" appears on other pages as well. I.e. https://metamanager.wiki/en/latest/metadata/details/metadata.html under `item_refresh_delay`. Let me know if you want me to look for these errors throughout the whole wiki. Could do it later today/this week.

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/metadata/details/setting.html

**Comment by meisnate12** [comment]
Added in 1.17.0
