### ISSUE TITLE
[Bug]: Trakt authorizeation failed if PIN is lowercase

### ISSUE THREAD

**Issue by imjuzcy** [Kometa-Team/Kometa#869]
### Version Number

1.16.5

### What branch are you on?

develop

### Describe the Bug

When authorized Trakt, although the PIN is shown in upper case letters, but when copied, it is copied in lower case letters. So when pasted into the config file and ran, authorization failed. This shouldn't be the case as it is supposed to be case insensitive (or should automatically be changed to upper case letters since the PIN is always in upper case).

### Logs

https://gist.github.com/ImjuzCY/10a659d8c75ee617ca4fb1eb18b4ab4f

**Comment by meisnate12** [comment]
were you able to get it working manually making it upper case?

**Comment by imjuzcy** [comment]
Yes. Hence this issue

**Comment by chazlarson** [comment]
What's the copy mechanism that's lower-casing it?  I just went through the process in OS X/Chrome and copy-paste gave me upper-case.
![image](https://user-images.githubusercontent.com/3865541/168127111-1d45392e-05d0-4ef0-b9e2-c82037c96ee3.png)

**Comment by imjuzcy** [comment]
Hmm, I'm using Firefox 101.0b5 on WIndows 11
![image](https://user-images.githubusercontent.com/12483281/168128348-a1944223-106d-43b4-8d06-6efb58dedcde.png)

**Comment by imjuzcy** [comment]
I'm guessing for me the text itself is lower case, but the font makes it look like its upper case
![image](https://user-images.githubusercontent.com/12483281/168128702-742ec7ef-eee1-4253-abbe-a5476145b11b.png)

**Comment by chazlarson** [comment]
Well, that's certainly weird.  You don't have some clipboard enhancer that's "helping", do you?  I'll try Firefox just for good measure.

**Comment by chazlarson** [comment]
"Thanks" for "helping", Firefox:
![image](https://user-images.githubusercontent.com/3865541/168129506-6640cfa4-958d-46df-8ac6-0d86a4261779.png)

**Comment by chazlarson** [comment]
So I guess PMM should string.upper() that after reading it.

**Comment by meisnate12** [comment]
That's the plan!

**Comment by imjuzcy** [comment]
@chazlarson but if you copy anything else it doesn't do that. Just the PIN

**Comment by chazlarson** [comment]
Yeah, I saw that. "Thanks", Firefox.  Safari does the right thing [the "right thing" being not manipulating the case of something it copies], as well.

**Comment by chazlarson** [comment]
Wait, it is a styling thing and different browsers handling that differently.  Chrome and Safari are respecting the displayed styling, while Firefox is copying the raw text in the page.  This is Chrome, showing that "TRAKT" and the code are lower-case in the source.  Firefox copies them that way, Chrome/Safari copy them as they are displayed.  Ugh.

![image](https://user-images.githubusercontent.com/3865541/168146215-588654e0-b337-49fb-b3be-642842ead457.png)

**Comment by meisnate12** [comment]
im finally able to get around to testing this and im able to authenticate using lowercase to trakt just fine with multiple tries so im going to assume there was just some weird temporary issue
