### ISSUE TITLE
Feature Request - Limit and sort for trakt lists

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#87]
Add limit and sort options to trakt lists original request from [PAC](https://github.com/mza921/Plex-Auto-Collections/issues/213)

**Comment by meisnate12** [comment]
currently, Trakt's API doesn't allow for sorting so once it does I can add this

**Comment by king8084** [comment]
any updates on this

**Comment by meisnate12** [comment]
you still cant limit the trakt lists but there are many ways to sort them using PMM what are you trying to accomplish

**Comment by blueJack92** [comment]
I would like to sort the tract list by popularity, is this somehow possible?
