### ISSUE TITLE
[Bug]:  argument of type 'NoneType' is not iterable when conntecting to radarr v4.1.0.6175

### ISSUE THREAD

**Issue by ljmerza** [Kometa-Team/Kometa#873]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

argument of type 'NoneType' is not iterable when conntecting to radarr v4.1.0.6175

### Logs

https://gist.github.com/ljmerza/6fdafb7984ceb6101bb5c1e70cd5e9c4

**Comment by meisnate12** [comment]
are you still having this issue?
