### ISSUE TITLE
[Feature]: Merging Multi Episodes, after following the plex mutli episode naming method.

### ISSUE THREAD

**Issue by fisher745** [Kometa-Team/Kometa#874]
### Is your feature request related to a problem? Please elaborate.

I have stumbled upon a GitHub page of a plex employee where he has created a bunch of plex scripts, which improve the plex experience. One of his script has an option to merge multiple episodes into one in plex even after following the plex mutli episode naming patter.

Here are links to refer to 

[Git of the plex employee](https://github.com/blacktwin/JBOPS)

[The Mutli Episode Code which this feature is referring to](https://github.com/blacktwin/JBOPS/blob/master/utility/merge_multiepisodes.py)

Here’s an example

Sponge Bob Collection

Usually, the case

S02E01-E02 ——> This in plex will result in two separate episodes but plex will not separate the video files as will also not mark the episodes as watch for both the episodes even though there in the first episode in plex where you have watched both the episodes, plex will not mark the second episode in their watch history as marked.

using the script from the link above will result in

S02E01-E02 ——> This will result in plex combining the two separated episodes into one including the naming of each episodes by append with a “/“ in between. And watching a single file will result in plex marking as both the episodes as watched.

Here’s proof

**Before**:

![](https://user-images.githubusercontent.com/9099342/159065426-94a576eb-c870-4768-b44b-6caf42f9e012.png)

**After**:

![](https://user-images.githubusercontent.com/9099342/159065709-35d68eb5-c3f6-49ed-bdf6-f55a0cbbeb8f.png)

### Describe the solution you'd like

Let’s hope that this will be there in PMM

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/merging-multi-episodes)
