### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Metropolis76** [Kometa-Team/Kometa#884]
### Is your feature request related to a problem? Please elaborate.

No

### Describe the solution you'd like

The ability to determine which films PMM adds to radarr based on their TMDB "Status". Example: Have an variable in PMM config which can filter out films that are not confirmed to be in production. If 'true', PMM will only add movies where their TMBD Status is "In Production", "In Post-Production", "Released". Otherwise, if 'false', PMM will add the movie no matter what.

### Additional Information

I don't believe this is too difficult to implement and I think it will be a great feature addition.
_No response_

**Comment by meisnate12** [comment]
This can be accomplished via the tmdb_status filter

![image](https://user-images.githubusercontent.com/1631064/169603330-10540aea-1678-4185-84c2-81d0a7a1f93e.png)
