### ISSUE TITLE
[Feature]: Definitive schedule dates

### ISSUE THREAD

**Issue by brandonhowlett** [Kometa-Team/Kometa#889]
### Is your feature request related to a problem? Please elaborate.

I have best-of-year builders for past and future years. On 2/1/2023 when the 2022 builder runs per schedule: yearly(02/01), the top 100 RT movies will be added and monitored by radarr. Awesome! However, movies released during January 2023 that meet the search criteria will also be added to radarr as part of best-of-2023. This is undesirable as those movies may not be on the list at the end of 2023.

### Describe the solution you'd like

schedule: specific(02/01/2024), range(02/01/2024-02/7/2024)

Perhaps in conjuncture with <<var + 1>>, <<var - 1>>

e.g.,
```
trakt_list: https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-<<year>>
schedule: specific(02/01/<<year + 1>>)
```

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[First Request](https://features.metamanager.wiki/features/p/definitive-schedule-dates)
[Second Request](https://features.metamanager.wiki/features/p/change-number-template-variable-values)
