### ISSUE TITLE
[Feature]: Discover Playlists in Home Screen 

### ISSUE THREAD

**Issue by poiy23** [Kometa-Team/Kometa#892]
### Is your feature request related to a problem? Please elaborate.

Would be a cool Feature If i can add the Playlists from the Discover Page directly on the Main Page.
For example "Coming Soon" or "avalible from your Wish list".

### Describe the solution you'd like

Idk

**Comment by cpt-kuesel** [comment]
you can just pin discover and then those will be available on the main page

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/discover-lists-as-builders)
