### ISSUE TITLE
[Feature]:  show_missing: false also removes missing from _missing.yml report

### ISSUE THREAD

**Issue by nishikan8000** [Kometa-Team/Kometa#894]
### Is your feature request related to a problem? Please elaborate.

When using `show_missing: false` it still reveals all missing items in the _missing.yml report after running

### Describe the solution you'd like

Please make either `show_missing: false` not include the items in the report, or
add another variable which will do so.

**Comment by meisnate12** [comment]
this is intended turn off using the file if you dont want it to run
