### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by Smashbros** [Kometa-Team/Kometa#897]
### What is the improvement or update to the Wiki you wish to see?

In the Local Walkthrough on nightly, have not checked the other versions, when you go to Editing the config template, the code block is not used when you go to check the Windows versions

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/nightly/home/guides/local.html

**Comment by chazlarson** [comment]
A pull request has already been put in to fix this.
