### ISSUE TITLE
Blank collections show on library tab even if hide collection is set to true.

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#898]
### Version Number

1.17

### What branch are you on?

nightly

### Describe the Bug

Blank collections show on library tab even if hide collection is set to true.

clicking on the advanced tab for the blank separator poster reveals that it is indeed set to hide.
1- set it back to library default and save changes
2- set it back to hide collection and save changes

This works and the collection becomes hidden on the library tab

### Relevant Collection/Overlay/Playlist Definition

```yml
Any blank collections
```

### Logs

https://gist.github.com/bullmoose20/96fdefd396548bfa0790ee3460a23de1

**Comment by G4Zz0L1** [comment]
I have tried also the default configs from the repo, without customizations, with the collection_mode hide as template_variables on every file included ending up with the same result.
But if I manually change the status inside plex, they switch from on and off everytime I save the next one, as if I haven't changed them at all.

**Comment by G4Zz0L1** [comment]
Is there any news on this?
The script from the repo of [bullmoose20](https://github.com/bullmoose20/Plex-Stuff/blob/main/advanced-plex-edits.py) works fine, but it's pointless as when PMM checks the collections, it will reset the separators.
I'm using the defaults from the pmm nightly, without touching anything on the collections side, apart from some overlays.

**Comment by bullmoose20** [comment]
Latest nightly has a fix. I have tested it at it works great!
________________________________

**Comment by G4Zz0L1** [comment]
If you mean the 1.17.3-develop186 I've already got it running, but the separators are visible on the library section, as before.
What configs do you have?

**Comment by bullmoose20** [comment]
> If you mean the 1.17.3-develop186 I've already got it running, but the separators are visible on the library section, as before.
> What configs do you have?

https://metamanager.wiki/en/nightly/defaults/separators.html#shared-separator-variables

`placeholder_imdb_id` Is what I use at the movies library level in a template_variables section and in TV Shows as well. So I added two lines to my config.yml. Problem solved

**Comment by G4Zz0L1** [comment]
I've found another solution, I've disabled the collections on the library tab of plex, as I always have them on the collection tab.
Thanks anyway.
