### ISSUE TITLE
[Bug]: fonts/ not found on FreeBSD

### ISSUE THREAD

**Issue by mvanbaak** [Kometa-Team/Kometa#899]
### Version Number

1.17.0-develop2

### What branch are you on?

nightly

### Describe the Bug

When adding a text overlay from the default overlays (in my case `- git: PMM/overlays/video_format`) PMM errors out since it cannot find the font. This is because I run PMM from cron, and the `fonts/` directory is not in the the current working directory in that case.
For linux, windows and macos there are some default font locations specified in the code. For FreeBSD this is not the case.

### Logs

https://gist.github.com/mvanbaak/28c70ca43b39f566f03c0f11d02ec535

**Comment by mvanbaak** [comment]
Adding the application directory to the paths to search for looks like the solution for the default provided fonts

**Comment by zimmra** [comment]
> Adding the application directory to the paths to search for looks like the solution for the default provided fonts

@mvanbaak do you mind clarifying what you mean by adding the application directory to the paths to search for?

I am running in to this with the PMM/overlays/ratings overlay, and not sure what you mean to resolve this

**Comment by mvanbaak** [comment]
> > Adding the application directory to the paths to search for looks like the solution for the default provided fonts
> 
> @mvanbaak do you mind clarifying what you mean by adding the application directory to the paths to search for?
> 
> I am running in to this with the PMM/overlays/ratings overlay, and not sure what you mean to resolve this

My 'solution':

```bash
cd /path/where/pmm/is/installed
cp -a fonts ..
```
Then I create a script to run pmm:

```bash
#!/usr/bin/env sh
set -e

cd /path/where/pmm/is/
./pmm/plex_meta_manager.py --config ./pmm-config/config.yml -ig -r
```

pmm comes with the fonts in the install. So I copied that directory one level up, and have a script that runs `cd` to that directory first before running pmm. This way it will find the fonts just fine
