### ISSUE TITLE
Config Error: config not found at //config

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#9]
I'm missing something and I'm not sure where it's at. I'm running the docker container under Unraid and I posted my setup over in issue #4. It starts up fine and I just put a `config.yml` and `movies.yml` into the folder this afternoon for the first time. I'm assuming the docker container is working because in my /config folder on Unraid that the docker image is pointing to, the logs folder got created fine and the meta.log is there.

But I'm getting this error in my docker log.

```Traceback (most recent call last):
File "//plex_meta_manager.py", line 26, in <module>
elif not os.path.exists(os.path.join(default_dir, "config.yml")): raise util.Failed("Config Error: config not found at {}".format(os.path.abspath(default_dir)))

modules.util.Failed: Config Error: config not found at //config
```

Looks like there's an extra `//` on the `//config` somewhere, but I don't see it in either yml file.

Any ideas what I've missed?

**Comment by meisnate12** [comment]
its not finding you config file if your getting that error

the program just looks at the path of `plex_meta_manager.py` and then looks in the same location for a folder named config with a config.yml inside.

You can specify your config location path if you start the program with the --config option

**Comment by b101marc** [comment]
When I tried to build from docker I got the same error, but the same path worked perfectly for local installation.

Docker install: `sudo docker run -it -v /opt/appdata/Plex-Meta-Manager:/config:rw meisnate12/plex-meta-manager --config config/config.yml --run`
The above gives me the following error:
```
Traceback (most recent call last):
  File "//plex_meta_manager.py", line 25, in <module>
    elif args.config and not os.path.exists(args.config):               raise util.Failed("Config Error: config not found at {}".format(os.path.abspath(args.config)))
modules.util.Failed: Config Error: config not found at /config/config.yml
```

After pulling git running locally:
`sudo python3 plex_meta_manager.py --config config/config.yml --run`
The above works just fine.

Not sure what the difference is, but it's running locally so not going to sweat it, just wanted to share.

**Comment by Tharic99** [comment]
I added a `--config-path /config.yml` to my Unraid and I didn't get an error this time. 

I think it's looking for `--config-path` and the wiki docs say `--config` perhaps?

```

|====================================================================================================|
| |
| ____ _ __ __ _ __ __ |
| | _ \| | _____ __ | \/ | ___| |_ __ _ | \/ | __ _ _ __ __ _ __ _ ___ _ __ |
| | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__| |
| | __/| | __/> < | | | | __/ || (_| | | | | | (_| | | | | (_| | (_| | __/ | |
| |_| |_|\___/_/\_\ |_| |_|\___|\__\__,_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_| |
| |___/ |
| Version: 1.0.0 |

|====================================================================================================|
```


So now I'll just let it sit until my 3am config runs and see how it looks tomorrow.

**Comment by meisnate12** [comment]
my code is definitely looking for `--config` or `-c`

```python
parser.add_argument("-c", "--config", dest="config", help="Run with desired *.yml file", type=str)
```

this is really weird it should not have worked with `--config-path`

**Comment by b101marc** [comment]
Just as a heads up in the wiki almost everywhere is says --config-path in the examples.

[Screenshot](https://snipboard.io/MnCvgo.jpg)

**Comment by wjziv** [comment]
I'm also using Unraid to host this container, and I'm seeing this double slash prefix as well. I'm combing through the Dockerfile to see if there's something about the application transition which causes it.

I'd like to point out to @Tharic99 that they may have set up their path mount incorrectly, if they need to pass the `--config` argument. I assume they made it an environment variable. This screenshot specifies `/mnt/user/appdata/plex-meta-manager` as the default directory holding the `config.yml` file which works for me. The `config.yml` file must exist prior to running the container.

![image](https://user-images.githubusercontent.com/29553646/107595332-58b57500-6be2-11eb-95f5-2b52cffc51cb.png)

I'll get around to pushing Unraid CA support later this week.

**Comment by isaacolsen94** [comment]
> I'm also using Unraid to host this container, and I'm seeing this double slash prefix as well. I'm combing through the Dockerfile to see if there's something about the application transition which causes it.
> 
> I'd like to point out to @Tharic99 that they may have set up their path mount incorrectly, if they need to pass the `--config` argument. I assume they made it an environment variable. This screenshot specifies `/mnt/user/appdata/plex-meta-manager` as the default directory holding the `config.yml` file which works for me. The `config.yml` file must exist prior to running the container.
> 
> ![image](https://user-images.githubusercontent.com/29553646/107595332-58b57500-6be2-11eb-95f5-2b52cffc51cb.png)
> 
> I'll get around to pushing Unraid CA support later this week.

Looking forward to this, will you post here when you've added it? Thanks for adding!

**Comment by Tharic99** [comment]
> I'm also using Unraid to host this container, and I'm seeing this double slash prefix as well. I'm combing through the Dockerfile to see if there's something about the application transition which causes it.
> 
> I'd like to point out to @Tharic99 that they may have set up their path mount incorrectly, if they need to pass the `--config` argument. I assume they made it an environment variable. This screenshot specifies `/mnt/user/appdata/plex-meta-manager` as the default directory holding the `config.yml` file which works for me. The `config.yml` file must exist prior to running the container.
> 

Path mount is below on my side...

Looks pretty much the same as yours..

![Selection_063](https://user-images.githubusercontent.com/39832147/107654886-0f503e80-6c51-11eb-9a0a-12c64deeda77.png)

**Comment by Tharic99** [comment]
@meisnate12 
Just as an additional follow-up, when I go to a console prompt for the unraid docker container.

```
# ls
Dockerfile  boot    dev  home  lib64  mnt      opt                   proc  run   srv  tmp  var
bin         config  etc  lib   media  modules  plex_meta_manager.py  root  sbin  sys  usr
# python plex_meta_manager.py --run
|====================================================================================================|
|                                                                                                    |
|        ____  _             __  __      _          __  __                                           |
|       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
|       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
|       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
|       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
|                                                                            |___/                   |
|           Version: 1.0.0                                                                           |
|====================================================================================================|
|====================================================================================================|
|                                         Starting Daily Run                                         |
|====================================================================================================|
| Locating config...                                                                                 |
| Using //config/config.yml as config                                                                |
|====================================================================================================|
| Using cache database at //config/config.cache                                                      |
|====================================================================================================|
| Connecting to TMDb...                                                                              |
| TMDb Connection Successful                                                                         |
|====================================================================================================|
| Connecting to Trakt...                                                                             |
| Trakt Connection Successful                                                                        |
|====================================================================================================|
| mal attribute not found                                                                            |
|====================================================================================================|
| Connecting to Plex Libraries...                                                                    |
|====================================================================================================|
| Connecting to Movies Library...                                                                    |
| Config Error: Skipping Movies Library default metadata_path not found at //config/Movies.yml       |
|====================================================================================================|
| Connecting to TV Shows Library...                                                                  |
| Config Error: Skipping TV Shows Library default metadata_path not found at //config/TV Shows.yml   |
|====================================================================================================|
| Plex Error: No Plex libraries were found                                                           |
|                                                                                                    |
|====================================================================================================|
|                                         Finished Daily Run                                         |
|====================================================================================================|
# 

```

It's explicitly looking for `Movies.yml` and not `movies.yml`, which under *nix is two different files. Renamed  the `movies.yml` to `Movies.yml` and the error goes away.

```
# python plex_meta_manager.py --run
|====================================================================================================|
|                                                                                                    |
|        ____  _             __  __      _          __  __                                           |
|       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
|       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
|       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
|       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
|                                                                            |___/                   |
|           Version: 1.0.0                                                                           |
|====================================================================================================|
|====================================================================================================|
|                                         Starting Daily Run                                         |
|====================================================================================================|
| Locating config...                                                                                 |
| Using //config/config.yml as config                                                                |
|====================================================================================================|
| Using cache database at //config/config.cache                                                      |
|====================================================================================================|
| Connecting to TMDb...                                                                              |
| TMDb Connection Successful                                                                         |
|====================================================================================================|
| Connecting to Trakt...                                                                             |
| Trakt Connection Successful                                                                        |
|====================================================================================================|
| mal attribute not found                                                                            |
|====================================================================================================|
| Connecting to Plex Libraries...                                                                    |
|====================================================================================================|
| Connecting to Movies Library...                                                                    |
| 'utf-8' codec can't decode byte 0x92 in position 13535: invalid start byte                         |
|                                                                                                    |
|====================================================================================================|
|                                         Finished Daily Run                                         |
|====================================================================================================|
# 
```

Of course now I have a different error, but that could very easily be related to my `Movies.yml`, so I'll check that out.

**Comment by meisnate12** [comment]
yea the name has to match exactly, capitalization and all. If you really want it called movies.yml you can always specify the metadata file path using the `metadata_path` attribute under the `plex` attribute

**Comment by meisnate12** [comment]
I think this issue is mostly related to unRAID so with the addition of the [unRAID Installation](https://github.com/meisnate12/Plex-Meta-Manager/wiki/unRAID-Installation) page I'm going to close this

**Comment by Jacob-Lasky** [comment]
apologies for the necro, just wanted to point out to anyone who may be having this issue that I was able to fix this by adding a trailing `/` to the container path like so:
![image](https://user-images.githubusercontent.com/6790237/138980969-a837150c-f36c-4788-b2c6-1311f5dcc3b6.png)

**Comment by akcryptoguy** [comment]
What does the "mal atttribute not found" in the log between Trakt and Plex mean?  My PMM is working, I've just been trying to eliminate as many of the errors as I can hunt down.

**Comment by chazlarson** [comment]
[MyAnimeList](https://metamanager.wiki/en/latest/config/myanimelist.html)

**Comment by Forusim** [comment]
I had same issue with the Unraid Docker container and there the reason was wrong owner. It must be root, otherwise the config.yml will not be detected.

**Comment by Awfulnaut** [comment]
For anyone else who sees this, I figured I'd share the solution that worked for me. I'm running this on a Synology NAS using Container Manager (ie. Docker). I had to move my config.yml up a level.
<img width="1016" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/26883394/54798bc2-e01a-4a37-a598-baa73ffe176e">
In other words NOT inside of a config directory.
