### ISSUE TITLE
TV Mapping Fails - `NoneType` object has no attribute `update_guid`

### ISSUE THREAD

**Issue by GsMumbo** [Kometa-Team/Kometa#90]
I started getting this all setup last night and can’t seem to get past this error. From what I can tell the config and mapping files are all correct, but it’s not grabbing a proper ID for the show The 100?

Everything is running on Docker with a shared network. I’ve included the full logs and relevant setup files/configs below. Once it hits this error the rest never runs, so as of right now I have a Movie collection up and running, but no TV or Anime. I also disabled Sonarr during troubleshooting to see if that had any impact (it was having some trouble connecting to it at one point) so you’ll see that commented out in the logs.

```

|====================================================================================================|

|                                      Mapping TV Shows Library                                      |

|====================================================================================================|

|                                                                                                    |

| Mapping Show Library: TV Shows                                                                     |

| Cache | + | com.plexapp.agents.thetvdb://268592?lang=en    | 48866  | tt0307683  | 268592 | None  | None  | The 100 |

| Traceback (most recent call last):                                                                 |

|   File "//plex_meta_manager.py", line 84, in start                                                 |

|     config.update_libraries(test, collections)                                                     |

|   File "/modules/config.py", line 396, in update_libraries                                         |

|     movie_map, show_map = self.map_guids(library)                                                  |

|   File "/modules/config.py", line 639, in map_guids                                                |

|     id_type, main_id = self.get_id(item, library, length)                                          |

|   File "/modules/config.py", line 787, in get_id                                                   |

|     self.Cache.update_guid("movie" if library.is_movie else "show", item.guid, tmdb_id, imdb_id, tvdb_id, anidb_id, mal_id, expired) |

| AttributeError: 'NoneType' object has no attribute 'update_guid'                                   |

|                                                                                                    |

| 'NoneType' object has no attribute 'update_guid'                                                   |

|                                                                                                    |

|====================================================================================================|
```

Log: https://pastebin.com/9XM9m0Zy
Docker Compose: https://pastebin.com/WGHhF1r3

config.yml: https://pastebin.com/R4JMd8QQ
Movies.yml: https://pastebin.com/imrd4R83
TV Shows.yml: https://pastebin.com/nDLBq3yp
Anime.yml: https://pastebin.com/tpqpHfgY

**Comment by meisnate12** [comment]
i highly recommend the cache it will save you a ton of execution time but it seems there isn't a proper check for if its been turned off. Ill add it in

**Comment by meisnate12** [comment]
ok fix is in dev

**Comment by GsMumbo** [comment]
> i highly recommend the cache it will save you a ton of execution time but it seems there isn't a proper check for if its been turned off. Ill add it in

Oh I plan on using the cache, I just had it disabled to rule it out as a potential issue.

**Comment by GsMumbo** [comment]
> ok fix is in dev

Updated to the latest dev, it works! Also reenabled cache and everything looks good. Thank you!
