### ISSUE TITLE
[Feature]: Split config.yml into two files to separate secrets from the config

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#900]
### Is your feature request related to a problem? Please elaborate.

Wishing I could more easily share my config.yml, but it has lots of information that should not be shared.

### Describe the solution you'd like

secrets.conf should contain all the secrets that you should not share with anyone
config.yml should contain the rest

**Comment by bakerboy448** [comment]
Alt possibility: add a run flag to output a cleansed config

**Comment by meisnate12** [comment]
i dont have plans on doing this
