### ISSUE TITLE
[Docs]: Using sort_by with plex_all and filters. This might be a bug, or a wiki request. Not sure

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#902]
### What is the improvement or update to the Wiki you wish to see?

So I've been trying to figure out how to use sort_by with a collection created using only  ```plex_all: true``` and
 ```
collectionName:
  filters:
    filepath: ____
```
  
  Haven't been able to find a wiki example. Maybe there's a way already though, and the documentation just doesn't show it?

**Comment by meisnate12** [comment]
`collection_order` can be used to sort the final collection 

https://metamanager.wiki/en/latest/metadata/details/metadata.html
