### ISSUE TITLE
[Feature]: More complete Metadata_backup operator

### ISSUE THREAD

**Issue by Sdub76** [Kometa-Team/Kometa#903]
NOTE: This is related to issue https://github.com/meisnate12/Plex-Meta-Manager/issues/904. I split the issue into two different feature requests.

### Is your feature request related to a problem? Please elaborate.

I have a Plex library of historic NFL games.  About 500 in all.   Over the years (pre-PMM) I've added custom posters and metadata to all of the items and put them into collections with custom posters.  I don't have any particular naming scheme for the files... I have the agent in plex set to "personal media", and I manually fix everything up once it's in Plex.  If the library ever gets corrupted, I'm out a TON of work.

Item metadata is already taken care of with the "metadata_backup" operator, but it does not back up collection metadata, does not download posters, and doesn't have any way of mapping items without a TMDb match.  

I would like to be able to perform a one-time full backup of this library's metadata... item metadata, collection metadata, posters, and file path+name/title mappings.  From that point forward, I would manage it all through these extracted YML files.

### Describe the solution you'd like

I have 2 requests... one for a more complete metadata_backup and one for a new builder that handles non-TMDb items.  I'll create 2 different Feature Requests since they're fairly independent.  

This one is for **a more complete "metadata_backup" operator**.  It would:

1. Download the current poster to the assets folder and add a file_poster mapping to the metadata_backup file
2. Saves the unmanaged collection metadata (summary, collection mode, etc.) to the metadata_backup file.... essentially allowing you to convert unmanaged collections into PMM managed collections.  

My end goal is to NEVER update metadata in Plex again.  This is where PMM really shines.  

### Additional Information

I think these features have broad applicability beyond sports.  I would use this for home movies, and potentially any TV shows that don't fit neatly into TMDb entries like concerts or special events.

**Comment by Sdub76** [comment]
Some of this functionality may be leverageable from these scripts that extract collection info and posters.  

https://github.com/chazlarson/Media-Scripts/tree/main/Plex-Meta-Manager

**Comment by meisnate12** [comment]
these are not features i want directly in pmm they function better as a one off script from chaz as these are not something to be done regually 

also p.s. you dont need to specify file_poster if the asset is named correctly
