### ISSUE TITLE
[Feature]: PMM builder for items not found in TMDb

### ISSUE THREAD

**Issue by Sdub76** [Kometa-Team/Kometa#904]
NOTE: This is related to issue #903.  I split the issue into two different feature requests.

### Is your feature request related to a problem? Please elaborate.

I have a Plex library of historic NFL games. About 500 in all. Over the years (pre-PMM) I've added custom posters and metadata to all of the items and put them into collections with custom posters. I don't have any particular naming scheme for the files... I have the agent in plex set to "personal media", and I manually fix everything up once it's in Plex. If the library ever gets corrupted, I'm out a TON of work.

Item metadata is already taken care of with the "metadata_backup" operation, but it does not back up collection metadata, does not download posters, and doesn't have any way of mapping items without a TMDb match.

I would like to be able to perform a one-time full backup of this library's metadata... item metadata, collection metadata, posters, and file path+name/title mappings. From that point forward, I would manage it all through these extracted YML files.

### Describe the solution you'd like

I have 2 requests... one for a more complete metadata_backup and one for a new builder that handles non-TMDb items. I'll create 2 different Feature Requests since they're fairly independent.

This specific request is for **handling of non-TMDb matched items.**  It would:

1.  Provide a new "builder" for "personal_media" that uses a YML listing of "/path/to/file" as the key to match metadata entries to titles where no TMDb ID is available. 
2. The metadata_backup operation should be able to create this YML listing for existing items so unmanaged Plex personal media libraries can become managed.  

### Additional Information

I think these features have broad applicability beyond sports. I would use this for home movies, and potentially any TV shows that don't fit neatly into TMDb entries like concerts or special events.

Custom solutions like the "Formula 1 Metadata Guide" could take advantage of this also... right now that relies on very specific file/folder naming so that files get ingested in Plex in a very specific way.  A builder like I described makes it way more flexible.

**Comment by meisnate12** [comment]
Plex Builders work with items not mapped by tmdb or tvdb and metadata items are matched by item title no tmdb id (although you can also map with ID)
