### ISSUE TITLE
[Feature]: Listrr.Pro Builder

### ISSUE THREAD

**Issue by owine** [Kometa-Team/Kometa#906]
### Is your feature request related to a problem? Please elaborate.

With Trakt limits incoming, [Listrr.Pro](https://listrr.pro) is an alternative to MDBList and others for list building. The dev is working on v2 which will have support for Radarr-style Custom Lists. The ability to use a Listrr.Pro list as a builder in PMM would be nice to diversify more list providers.

### Describe the solution you'd like

Builder for Listrr.Pro similar to MDBList.

**Comment by TheUltimateC0der** [comment]
Hey! Dev of listrr.pro here. The endpoint used for the radarr custom list feature outputs only an array of TMDb Ids. If you need more data, I could extend the radarr custom list endpoint, or I can create a completely new one with the data you need for you script to work.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/listrrpro-builder)
