### ISSUE TITLE
[Feature]: Import ignore_id list of movies to exclude from Radarr if Radarr is configured

### ISSUE THREAD

**Issue by DeftNerd** [Kometa-Team/Kometa#920]
### Is your feature request related to a problem? Please elaborate.

Being able to add TMDB ID's to the ignore_id field is handy, but if they also use Radarr to exclude movies, they need to keep both lists in sync. 

### Describe the solution you'd like

Radarr's API allows us to retrieve the list of movies excluded in Radarr from import from a URL such as 
`http://[host]:[port]/api/v3/exclusions?apikey=[apikey]`
It returns a JSON array similar to:

```
[
  {
    "tmdbId": 15102,
    "movieTitle": "Endgame",
    "movieYear": 2009,
    "id": 1
  },
  {
    "tmdbId": 15338,
    "movieTitle": "Ace Ventura Jr: Pet Detective",
    "movieYear": 2010,
    "id": 2
  }
]
```

I would like to see a configuration setting similar to `ignore_id` titled `ignore_import` or `ignore_radarr_import`. The results of the import could be merged with any items in the `ignore_id` array. 

A similar principal would likely apply to Sonarr too, but that should probably be tracked as a separate feature request if/when this feature request gets any traction. 

### Additional Information

There are a few other Import Exclusion options as part of the Radarr API. If some thought is put into the configuration in PMM, more opportunities open up like adding the manually specified ignore_id items TO Radarr. 

Reference:
* https://radarr.video/docs/api/#/ImportExclusions/get_api_v3_exclusions

**Comment by meisnate12** [comment]
so im wondering the use case because PMM already will not send IDs in your radarr exclusion list to radarr.

or do you want pmm to ignore the IDs that already dont exist in your plex which already would not have been sent to radarr.

Im just not seeing the need for this if you just exclude items in radarr you dont need to maintain a pmm ignore_ids

**Comment by dukejansen** [comment]
I thought PMM has its own list of excluded items which it won't import, but does it actually read Radarr's Import List Exclusions and exclude those as well? I think I've seen PMM add things to Plex which were on Plex's Import List Exclusions. I'll watch for a specific example.
