### ISSUE TITLE
[Docs]: 

### ISSUE THREAD

**Issue by SuperKafu** [Kometa-Team/Kometa#922]
### What is the improvement or update to the Wiki you wish to see?

Hi, 

Not an issue or request just asking to see if it is possbile.

So, I've installed and played around with the PMM config, collections and so on.
I've came across a screenshot of the Infuse Player's Home Screen(attached) and I kind of like it but I don't want to use a different player, run another server app for my media and so on.

Is there any way to replicate this type of layout and collection on Plex's Home Screen/Tab?
To be more precise:
1. How can one generate in Plex a fresh batch of movies every day in a collection similar to "Picks of the Day" (as seen in the screen grab)?
- I know about the PMM schedule and about adding the collection to the Home screen. What I haven't figured out is how to actually get the (random)"picks".
2.  How to get the Thumbnail on the home screen (as seen in Plex on the collection tab) instead of the individual items of the collection, while retaining the ability to post the collection on  other user's home screen?
Thanks
![Infuse](https://user-images.githubusercontent.com/35775512/173097216-a5b2898f-9910-4340-83ed-5adc92a9edcc.jpg)

**Comment by meisnate12** [comment]
i mean kinda you can have your collection show up on the home page like that although theres no way to have a random collection show up

**Comment by meisnate12** [comment]
mosst of this isnt possible in plex therefore pmm cant do it so im closing this
