### ISSUE TITLE
[Feature]: Method of determining PMM status for Docker healthchecks

### ISSUE THREAD

**Issue by DeftNerd** [Kometa-Team/Kometa#926]
### Is your feature request related to a problem? Please elaborate.

Man people run PMM within a docker container, but there is little visibility into its operations unless you set up notifications or analyze logs on a regular basis. Sometimes I'll do a "docker compose ps" and notice that PMM has crashed or stopped due to some kind of unrecoverable error. 

### Describe the solution you'd like

Some kind of hook for docker healthchecks to tie into that will allow docker to determine if the PMM process thinks that everything is working properly. 

There are multiple ways this can be done, but not all of them are suitable for the kind of monolithic application type that PMM seems to be. 

I see three methods of various difficulty:
* Implementing a lock file and the healthcheck checks for its existence
* Make the ghost logger available from within the container somehow
* Getting an early start on the HTTP interface by creating a /health/ping endpoint
* Creating some kind of healthcheck.py program that is able to find and communicate with the running plex_meta_manager.py process and determine how its doing. 

# Lock File
We could create a lock file that gets created on the program start and then removed as part of the error logging process before the application terminates. A docker healthcheck could just check for the existence of the file and if it's not found, the container would be restarted. 

# Ghost Logger
I'm a bit confused by the "Ghost Logger" so I apologize if I'm missing something obvious. 

I've been unable to figure out how to view the output like 
`Current Time: 12:34 | 3 Hours and 12 Minutes until the next run at 15:46 | Runs: 1`
referenced at 
https://github.com/meisnate12/Plex-Meta-Manager/blob/4e4c173e431a0f4cf7723350c3b8f8fdd7980090/plex_meta_manager.py#L892  
 
I think it's writing to the console, but I'm having difficulty finding out how to access that from within or even outside the container. If there is some way to monitor /dev/tty or /dev/stdout it would be helpful to document that, and maybe the ghost logger console output could be used for a docker healthcheck somehow?

# HTTP /health/ping endpoint
I know a local web GUI is in the plans for the future, and perhaps this is an opportunity to get started with that. 

My thought is to set up a web on http://localhost:port/ that just some static HTML with a link to `/health`, and then `/health` that has a link to `/health/ping`

The whole `/health` path would be reserved for very basic information ("OK", "WARNING", "ERROR", etc) messages so it wouldn't require authentication or API keys in the future, and it wouldn't leak any information that could ever be misused (even version numbers). A more detailed endpoint could eventually be made at `/status`

I propose for now, `/health/ping` just returns "OK". The existence of the reply means that PMM is running

In the future, additional endpoints could be created such as...

* `/health` might just show the links to the checks and descriptions 
* `/health/all` could eventually be some kind of "check everything" endpoint
* `/health/config` - Returns `OK` if the config files validate successfully
* `/health/plex` - Tests the connections to Plex, returns `OK` if no problems
* `/health/radarr` - Tests the connection to Radarr, returns `OK` connection tests OK. `WARNING` if problems are found but not critical or if the radarr module isn't configured, `ERROR` for critical problems
* `/health/tmdb` - Tests the TMDB API keys, etc
* `/health/permissions` - Tests various file ownerships and permissions. `ERROR` if problems are found but not critical. `WARNING` if critical problems are found. 

You'll likely want to split off the test routines from the config.py file into their own testing module and make it so config.py and health.py just call the same functions. 

It's worthy of consideration to pick a API friendly format. Is YAML common for API's? I don't know offhand. 

# Currently Working (but pointless)

Currently I'm running "pidof python3" to just validate that python3 is running in the container. If it isn't, it restarts the container... but that doesn't really do much since you use `tini` and `python3 plex_meta_manager.py` exiting just shuts the container down.

**Comment by meisnate12** [comment]
something like this will be added with a UI and for now you can set up webhooks to any url and have that notify you notifiarr works really well with pmm for just this purpose
