### ISSUE TITLE
Add to Radarr per collection

### ISSUE THREAD

**Issue by sacredshapes** [Kometa-Team/Kometa#93]
I couldn't find it in the wiki but is there an option to only add movies to Radarr for specific collections? It would seem as though it's only a global variable unless I'm missing something.

For example, I have an IMDB Top 250 collection that I don't want to add to Radarr, however I would like some other collections to add to Radarr if the results are missing.

**Comment by GsMumbo** [comment]
You can use the `add_to_arr` attribute to override whatever you have set globally:

https://github.com/meisnate12/Plex-Meta-Manager/wiki/Collection-Details

**Comment by meisnate12** [comment]
added the text below to the Radarr and Sonarr pages

* You can set `add` and `tag` per collection by using the `add_to_arr` and `arr_tag` [Collection Detail](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Collection-Details#settings-attributes)
