### ISSUE TITLE
[Feature]: Episode Text Overlay

### ISSUE THREAD

**Issue by elit3ge** [Kometa-Team/Kometa#932]
### Is your feature request related to a problem? Please elaborate.

Not an issue, not sure if it has been completed already.

Would it be possible to write the episode name on the episode poster

### Describe the solution you'd like

![Carnival Row S01E01](https://user-images.githubusercontent.com/1644699/174912617-97b6a6bb-4201-4d05-b295-8884c95e2877.jpg)

**Comment by Wdvh** [comment]
have you seen this [project](https://github.com/CollinHeist/TitleCardMaker) should solve your issue

**Comment by YozoraXCII** [comment]
As @Wdvh has pointed out, that image was created using TitleCardMaker.

I believe there are plans to introduce a similar feature within PMM, but there's nothing to announce at this point in time.

**Comment by elit3ge** [comment]
@Wdvh Yeah, that is exactly where I create the image from.

@YozoraXCII I was just hoping for an all-in-one package that's all.

**Comment by meisnate12** [comment]
this can also now be done in pmm https://metamanager.wiki/en/latest/metadata/overlay.html#special-text-variables
