### ISSUE TITLE
why not playlists?

### ISSUE THREAD

**Issue by ookla-ariel-ride** [Kometa-Team/Kometa#94]
Curious why collections would be used over playlists.  Any chance you might add the ability to create a playlists instead of a collection for a future release?

**Comment by meisnate12** [comment]
Personally, I just like how collections look better than playlists and I don't have to bother syncing them to each user. I can look into adding playlists in a future release.

**Comment by ookla-ariel-ride** [comment]
@meisnate12 maybe a screenshot of how this looks would be useful.  For me, there is a bit of effort to get this going and I am unsure what the end result looks like.  This is clearly a popular project with many happy users, so don't take my comment as a knock.

**Comment by SerinitySW** [comment]
> @meisnate12 maybe a screenshot of how this looks would be useful. For me, there is a bit of effort to get this going and I am unsure what the end result looks like. This is clearly a popular project with many happy users, so don't take my comment as a knock.

They look the same as any other plex collections. Here are some example pics for you though of my library:
https://i.imgur.com/0ACmOKH.jpg
https://i.imgur.com/oVtBmrQ.jpg

Of course one of the biggest advantages is that they're available to all in-home and remote users.
