### ISSUE TITLE
[Bug]: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mattyteds** [Kometa-Team/Kometa#941]
### Version Number

1.17.0-develop68

### What branch are you on?

nightly

### Describe the Bug

Looks like 68 has interduce a bug which causes a failure when reading the config.yml on startup. Seen a few reports of it on the Discord so far. My gist includes a redacted config.yml and my meta.log

### Logs

https://gist.github.com/mattyteds/fcc74403e18c0eb45fe74fd007e57773

**Comment by elit3ge** [comment]
Same here.

**Comment by elit3ge** [comment]
That fixed the issue :)
