### ISSUE TITLE
[Bug]: Too many open files

### ISSUE THREAD

**Issue by JohnFawkes** [Kometa-Team/Kometa#944]
### Version Number

1.17.1-develop3

### What branch are you on?

nightly

### Describe the Bug

Not exactly sure whats happening. Multiple python errors about too many open files when building collections for 4k movie library. 1080p movie library works completly fine

### Relevant Collection/Overlay/Playlist Definition

```yml
Every collection
```

### Logs

https://gist.github.com/JohnFawkes/fff842dfb4787c89ee05adfa7c437bf8

**Comment by YozoraXCII** [comment]
Can you advise if you are running this in docker or local install?

Can you also upload the full log file please?

**Comment by JohnFawkes** [comment]
> Can you advise if you are running this in docker or local install?
> 
> Can you also upload the full log file please?

local

https://drive.google.com/file/d/1RvSrcFuSKnGFgW9nBHTCV8MYCSxf7mpY/view?usp=sharing

**Comment by JohnFawkes** [comment]
so after a quick google search, it looks like this may not be a bug. running ```ulimit -a``` shows a limit of 1024 open files. I set it to 10,000 using ```ulimit -Sn 10000``` Will test again and raise higher if needed. Will confirm if this fixes the issue

**Comment by JohnFawkes** [comment]
Confirmed running ```ulimit -Sn 10000``` has let me run the command ```python plex_meta_manager.py -r``` further than before and the too many open files error has gone away. closing issue. thank you. It may also be helpful to add ulimit to the wiki. Im surprised this hasnt come up before as I dont have an exxcessively huge library and im sure theres others out there with bigger libraries that use pmm

**Comment by gitthangbaby** [comment]
why not fix this issue, if the default value is 1024. I've checked all Linux systems and all are set to this value.
i've counted this message, and it's present more than 10.000 times. makes logs unreadable & not confident if the script finished the job.
