### ISSUE TITLE
[Feature]: alt_title needs to defer to title  over mapping_name when using both in the same metadata update

### ISSUE THREAD

**Issue by cpt-kuesel** [Kometa-Team/Kometa#948]
### Is your feature request related to a problem? Please elaborate.

When using `alt_title` and `title` in the same metadata update PMM chooses to use the `mapping_name` for the item instead, thereby ignoring the functionality of `title`.

### Describe the solution you'd like

When using both for a metadata update `title` should win over the mapping name.

### Additional Information

Discord discussion of this with mattyteds: https://discord.com/channels/822460010649878528/992508369048973343/992540360893005834

**Comment by meisnate12** [comment]
fixed in 1.17.2
