### ISSUE TITLE
[Bug]: filesize of poster with overlay more than 10x than original

### ISSUE THREAD

**Issue by Iguana9999phil** [Kometa-Team/Kometa#956]
### Version Number

1.17.1

### What branch are you on?

master

### Describe the Bug

When using overlays I see the metadata directory growing in size. Upon checking the content the overlay posters are the cause. When I check the original poster (pulled by Plex on import) of a random movie it shows a file size of 117K. The one with overlay applied has ballooned to 1.2MB. This will add up depending on how much media is added into Plex. On top of that, it seems silly for it to be this big a file as it doesn't do much quality wise.

<img width="825" alt="Screenshot 2022-07-07 at 6 15 32 PM" src="https://user-images.githubusercontent.com/40793267/177751036-627ce1b3-533a-4828-a50c-a7ab1e69bfd6.png">
<img width="827" alt="Screenshot 2022-07-07 at 6 15 49 PM" src="https://user-images.githubusercontent.com/40793267/177751060-1dfb77b7-ae0c-4a75-9f90-0b1d02cc66ea.png">
.

### Relevant Collection/Overlay/Playlist Definition

```yml
N/A
```

### Logs

N/A

**Comment by YozoraXCII** [comment]
Whilst I'm not an expert, this isn't really a bug.

If I take a random image from the internet, scale it to 1000x1500 and save it as a 100% quality JPEG the file-size ranges from 900KB up to 1.5MB.

The "issue" here is that PMM has no idea about the quality of the source image, you could have an extremely low quality image that is a few kilobytes in size, PMM is going to scale that up to 1000x1500, apply the overlay and then save it - which is going to increase the size of the file. Even if the source image is LQ, you still want the overlay itself in "full quality" so that it doesn't have noticable compression/artefacts.

**Comment by Iguana9999phil** [comment]
I assume PMM just retrieve the original poster that was already pulled by Plex itself right? I've tested it with the same poster and overlay and while 100% jpg would make the file 700Kb exporting at around 80% jpg only doubles it. An option, if possible, to set it would be nice. Seems like a lot of wasted space especially for those on smaller NVMe drives.
EDIT: reviewing it again the files PMM creates are PNG and thus result in these bigger files. Is there a reason why PNG is used and not jpg?

**Comment by meisnate12** [comment]
It's a png because jpg can't handle transparency at all

**Comment by Iguana9999phil** [comment]
fair enough. Testing here with pngquant and I can shave off around 1Mb per file without any obvious quality loss when I preview both files. That would be good enough for me so I'll automated it on my end.

**Comment by xiaodoudou** [comment]
PNGQuant is a good approach; but the final output once all overlay are applied could be a JPG which would reduce the size.

**Comment by xiaodoudou** [comment]
Maybe we could change that line:
https://github.com/meisnate12/Plex-Meta-Manager/blob/510fb959b735bb6c9e7baefeb6505a3b164bb20d/modules/overlays.py#L270

To:
```
temp = os.path.join(self.library.overlay_folder, f"temp.jpg")
new_poster.save(temp, "JPEG", quality=95)
```

Could also be exposed as options.

@meisnate12 let me know if you want a PR to help over such an issue.
