### ISSUE TITLE
[Feature]: Configuration file for Letterboxd (to allow login)

### ISSUE THREAD

**Issue by markmarz** [Kometa-Team/Kometa#975]
### Is your feature request related to a problem? Please elaborate.

Letterboxd has the option to make a list Private, so only the creator can view it. Unfortunately the way they do it seems to involve blocking the URL for all but the logged in creator.

I surmise that because PMM errors out when trying to pull from a list marked Private:

Value: ['https://letterboxd.com/markmarz/list/classic-period-crossover-films-noir-westerns/', 'https://letterboxd.com/markmarz/list/classic-period-crossover-films-noir-westerns-1/'] |
| Traceback (most recent call last): |
| File "//plex_meta_manager.py", line 543, in run_collection |
| builder = CollectionBuilder(config, metadata, mapping_name, collection_attrs, library=library, extra=output_str) |
| File "/modules/builder.py", line 689, in init |
| self._letterboxd(method_name, method_data) |
| File "/modules/builder.py", line 1133, in _letterboxd |
| letterboxd_lists = self.config.Letterboxd.validate_letterboxd_lists(self.Type, method_data, self.language) |
| File "/modules/letterboxd.py", line 87, in validate_letterboxd_lists |
| raise Failed(f"{err_type} Error: {final['url']} failed to parse") |
| modules.util.Failed: Collection Error: https://letterboxd.com/markmarz/list/classic-period-crossover-films-noir-westerns-1/ failed to parse |
| |
| Collection Error: https://letterboxd.com/markmarz/list/classic-period-crossover-films-noir-westerns-1/ failed to parse |

But succeeds pulling from the same URL when the list is marked Public.

I'm thinking if there was a way to login to Letterboxd, this problem may be solved.

Thanks!

### Describe the solution you'd like

Add configuration file for Letterboxd to allow login, thus enabling fetch of Private Letterboxd lists.

**Comment by chazlarson** [comment]
API here:
https://api-docs.letterboxd.com/

BUT:
https://letterboxd.com/api-beta/
"The Letterboxd API is in private beta"

**Comment by markmarz** [comment]
> API here: https://api-docs.letterboxd.com/
> 
> BUT: https://letterboxd.com/api-beta/ "The Letterboxd API is in private beta"

Thanks! That's very helpful information. For meisnate12, I mean;  I hung up my developer's apron long ago.

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/letterboxd-private-lists)
