### ISSUE TITLE
[Feature]: allocine.fr

### ISSUE THREAD

**Issue by xiaodoudou** [Kometa-Team/Kometa#981]
### Is your feature request related to a problem? Please elaborate.

I would like to use critic/user review from allocine.fr

### Describe the solution you'd like

Having a module that can search and resolve by title to match the movie/tv show.

We could have configuration such as:
```
mass_audience_rating_update: allocine_audience
mass_critic_rating_update: allocine_critic
```

The search use the following URL: `https://www.allocine.fr/rechercher/?q={title}`
For movies:
```
$$("section.section.movies-results ul li")
// If result > 1 then conflict; we should avoid to resolve
$("section.section.movies-results ul li .meta-title a").href
```

For TV Shows:
```
$$("section.section.series-results ul li")
// If result > 1 then conflict; we should avoid to resolve
$("section.section.series-results ul li .meta-title a").href
```

ID parsing:
```
# URL Example: https://www.allocine.fr/series/ficheserie_gen_cserie=23080.html
def get_id_from_url(url):
    result = re.search('(.*?)(\d+)\.html',url)
    if result is not None:
        return result.group(2)
    else:
        return False
```

Ratings:
```
// On a page of movie/tv show
$$(".rating-holder .rating-item")
// First item will be the critics
// Critic value on 5
$(".rating-holder .rating-item:nth-child(1) .stareval-note")
// Number of critics reviews (first number found)
$(".rating-holder .rating-item:nth-child(1) .stareval-review")

// Second item will be the audience
// Audience value on 5
$(".rating-holder .rating-item:nth-child(2) .stareval-note")
// Number of audience reviews (first number found)
$(".rating-holder .rating-item:nth-child(2) .stareval-review")
```

### Additional Information

I am happy to help you to code such a module; however having a template/bootstrap over it will help to ensure it match your expectation regarding such a new module.

**Comment by meisnate12** [comment]
pmm doesnt query items by name for this i would recommend contacting the mdblist develop and get him to add the ratings on his site and then pmm can pull from there
