### ISSUE TITLE
[Feature]: Allow adding item to collection based on IMDB keyword (inverse of what exists today)

### ISSUE THREAD

**Issue by karan** [Kometa-Team/Kometa#983]
### Is your feature request related to a problem? Please elaborate.

Example scenario: I'm trying to build a collection of "Mini Series". I found https://www.imdb.com/search/keyword/?keywords=tv-mini-series which contains 45k+ results.

I could use that with `imdb_list` but parsing 44k+ items is inefficient especially if I want to create more collections with pretty generic keywords.

### Describe the solution you'd like

I should be able to define a collection with something like:

```
collections:
  Mini Series:
    imdb_keyword:
      - tv-mini-series
    sync_mode: sync
```

This would do a reverse look up: go through items in the library and add them to the collection if the keyword is attached to their imdb page.

**Comment by karan** [comment]
@meisnate12 hey any thoughts?

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/imdb-keyword-filter)
