### ISSUE TITLE
Better memory management

### ISSUE THREAD

**Issue by 2fst4u** [Kometa-Team/Kometa#985]
### Is your feature request related to a problem? Please elaborate.

As PMM configs get bigger and more complex, PMM appears to use more and more memory each time it needs to run until the script has completely finished.

### Describe the solution you'd like

It would be good if PMM could chunk this requirement for memory and write or flush what it needs to at certain checkpoints rather than letting this balloon bigger and bigger.

**Comment by VxDlH** [comment]
Hi, 

What's the news on this subject ?

In my case the memory size increases with the number of media in plex

![image](https://user-images.githubusercontent.com/5277569/232306878-6f80486a-bc7e-4d1f-8f93-541fe4c1db61.png)

**Comment by YozoraXCII** [comment]
Are you running 1.19?

We have made some changes to try optimise memory usage

**Comment by VxDlH** [comment]
Okay, 

I'm using version 1.18.3

That's great news, I'll try this new version  1.19.0

Thx

**Comment by VxDlH** [comment]
Awesome

I used version 1.19.0  and i also removed the environment variable PMM_CACHE_LIBRARIES but the processing took longer than before

![image](https://user-images.githubusercontent.com/5277569/232349973-fcf653bc-aaed-47d9-9ed7-71174b8a1330.png)

I will restart with the variable PMM_CACHE_LIBRARIES  to see the difference

**Comment by VxDlH** [comment]
Thank you for this memory management

![image](https://user-images.githubusercontent.com/5277569/232458643-36727854-f5ed-421d-a5b9-718d1b4a6493.png)

**Comment by VxDlH** [comment]
Hi, 

The memory management is excellent, nothing to say about it you did a great job on it.

But now my task takes more than 11 hours and it's not finished yet, while before it took 7 hours.
![image](https://user-images.githubusercontent.com/5277569/232534488-275436e7-ffba-49e5-b31b-3a9b03aac550.png)

I was wondering if there is a way to parallelize actions to reduce the processing time.

 I saw in the logs that PMM processes each element sequentially
![image](https://user-images.githubusercontent.com/5277569/232536944-bb93fe9b-ccf5-4c86-9dcc-41afbd35c309.png)

On the CPU side PMM consumes almost nothing
![image](https://user-images.githubusercontent.com/5277569/232537976-87926ed2-bf38-4dae-b3d3-d88dff815bf4.png)


Maybe I should talk about this in another issue.


Thx
