### ISSUE TITLE
[Feature]: delete_managed_collections operation

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#999]
### Is your feature request related to a problem? Please elaborate.

This has previously been discussed, but in case it was forgotten about - the ability to only delete managed collections would make sense and allow users to preserve their manually-generated collections,

### Describe the solution you'd like

delete_managed_collections operation

**Comment by meisnate12** [comment]
Feature Requests have been moved to https://features.metamanager.wiki. 

[This Request](https://features.metamanager.wiki/features/p/deletemanagedcollections-operation)
